TuttleOFX: tuttle::plugin::interact::ParamRectangleFromTwoCorners< TFrame, coord > Class Template Reference
tuttle::plugin::interact::ParamRectangleFromTwoCorners< TFrame, coord > Class Template Reference
#include <ParamRectangleFromTwoCorners.hpp>
Public Member Functions
ParamRectangleFromTwoCorners (const InteractInfos &infos, OFX::Double2DParam *paramA, OFX::Double2DParam *paramB, const TFrame &relativeClip)
~ParamRectangleFromTwoCorners ()
bool draw (const OFX::DrawArgs &args) const
the function called to draw in the interact
ESelectType selectType (const OFX::PenArgs &args) const
MotionType intersect (const OFX::PenArgs &args)
bool isIn (const OfxRectD &)
Point2 getPoint () const
void setPoint (const Scalar x, const Scalar y)
Private Types
enum ESelectType {
eSelectTypeNone, eSelectTypeT, eSelectTypeL, eSelectTypeR,
eSelectTypeB, eSelectTypeTL, eSelectTypeTR, eSelectTypeBL,
eSelectTypeBR, eSelectTypeC
}
Private Attributes
OFX::Double2DParam * _paramA
same as TL (min)
OFX::Double2DParam * _paramB
same as BR (max)
TFrame _relativeFrame
ESelectType _selectType
Detailed Description
template<class TFrame, ECoordinateSystem coord>
class tuttle::plugin::interact::ParamRectangleFromTwoCorners< TFrame, coord >
Definition at line 18 of file ParamRectangleFromTwoCorners.hpp.
Member Enumeration Documentation
template<class TFrame , ECoordinateSystem coord> enum tuttle::plugin::interact::ParamRectangleFromTwoCorners::ESelectType [private]
T TL___________ TR | | L | C | R | | |_________| BL BR B
Enumerator:
eSelectTypeNone
eSelectTypeT
eSelectTypeL
eSelectTypeR
eSelectTypeB
eSelectTypeTL
eSelectTypeTR
eSelectTypeBL
eSelectTypeBR
eSelectTypeC
Definition at line 39 of file ParamRectangleFromTwoCorners.hpp.
Constructor & Destructor Documentation
template<class TFrame , ECoordinateSystem coord> tuttle::plugin::interact::ParamRectangleFromTwoCorners< TFrame, coord >::ParamRectangleFromTwoCorners (const InteractInfos & infos, OFX::Double2DParam * paramA, OFX::Double2DParam * paramB, const TFrame & relativeClip)
Definition at line 143 of file ParamRectangleFromTwoCorners.hpp.
template<class TFrame , ECoordinateSystem coord> tuttle::plugin::interact::ParamRectangleFromTwoCorners< TFrame, coord >::~ParamRectangleFromTwoCorners ()
Definition at line 151 of file ParamRectangleFromTwoCorners.hpp.
Member Function Documentation
template<class TFrame , ECoordinateSystem coord> bool tuttle::plugin::interact::ParamRectangleFromTwoCorners< TFrame, coord >::draw (const OFX::DrawArgs & args) const [virtual]
the function called to draw in the interact
Reimplemented from tuttle::plugin::interact::PointInteract.
Definition at line 154 of file ParamRectangleFromTwoCorners.hpp.
References tuttle::plugin::overlay::displayRect(), tuttle::plugin::interact::PointInteract::draw(), tuttle::plugin::ofxToGil(), and tuttle::plugin::pointNormalizedXXcToCanonicalXY().
template<class TFrame , ECoordinateSystem coord> Point2 tuttle::plugin::interact::ParamRectangleFromTwoCorners< TFrame, coord >::getPoint () const [inline, virtual]
Implements tuttle::plugin::interact::PointInteract.
Definition at line 62 of file ParamRectangleFromTwoCorners.hpp.
References tuttle::plugin::interact::ParamRectangleFromTwoCorners< TFrame, coord >::_paramA, tuttle::plugin::interact::ParamRectangleFromTwoCorners< TFrame, coord >::_paramB, tuttle::plugin::interact::ParamRectangleFromTwoCorners< TFrame, coord >::_relativeFrame, tuttle::plugin::interact::PointInteract::getTime(), tuttle::plugin::ofxToGil(), and tuttle::plugin::pointNormalizedXXcToCanonicalXY().
Referenced by tuttle::plugin::interact::ParamRectangleFromTwoCorners< TFrame, coord >::setPoint().
template<class TFrame , ECoordinateSystem coord> MotionType tuttle::plugin::interact::ParamRectangleFromTwoCorners< TFrame, coord >::intersect (const OFX::PenArgs & args) [virtual]
Reimplemented from tuttle::plugin::interact::PointInteract.
Definition at line 208 of file ParamRectangleFromTwoCorners.hpp.
References tuttle::plugin::interact::MotionType::_axis, tuttle::plugin::interact::MotionType::_mode, tuttle::plugin::interact::eAxisNone, tuttle::plugin::interact::eAxisXY, tuttle::plugin::interact::eMotionTranslate, and tuttle::plugin::interact::PointInteract::intersect().
template<class TFrame , ECoordinateSystem coord> bool tuttle::plugin::interact::ParamRectangleFromTwoCorners< TFrame, coord >::isIn (const OfxRectD & rect) [virtual]
Reimplemented from tuttle::plugin::interact::PointInteract.
Definition at line 227 of file ParamRectangleFromTwoCorners.hpp.
References tuttle::max(), tuttle::min(), tuttle::plugin::ofxToGil(), and tuttle::plugin::pointNormalizedXXcToCanonicalXY().
template<class TFrame , ECoordinateSystem coord> ParamRectangleFromTwoCorners< TFrame, coord >::ESelectType tuttle::plugin::interact::ParamRectangleFromTwoCorners< TFrame, coord >::selectType (const OFX::PenArgs & args) const
Definition at line 166 of file ParamRectangleFromTwoCorners.hpp.
References tuttle::max(), tuttle::min(), tuttle::plugin::ofxToGil(), and tuttle::plugin::pointNormalizedXXcToCanonicalXY().
template<class TFrame , ECoordinateSystem coord> void tuttle::plugin::interact::ParamRectangleFromTwoCorners< TFrame, coord >::setPoint (const Scalar x, const Scalar y) [inline, virtual]
Implements tuttle::plugin::interact::PointInteract.
Definition at line 71 of file ParamRectangleFromTwoCorners.hpp.
References tuttle::plugin::interact::ParamRectangleFromTwoCorners< TFrame, coord >::_paramA, tuttle::plugin::interact::ParamRectangleFromTwoCorners< TFrame, coord >::_paramB, tuttle::plugin::interact::ParamRectangleFromTwoCorners< TFrame, coord >::_relativeFrame, tuttle::plugin::interact::ParamRectangleFromTwoCorners< TFrame, coord >::_selectType, tuttle::plugin::interact::ParamRectangleFromTwoCorners< TFrame, coord >::eSelectTypeB, tuttle::plugin::interact::ParamRectangleFromTwoCorners< TFrame, coord >::eSelectTypeBL, tuttle::plugin::interact::ParamRectangleFromTwoCorners< TFrame, coord >::eSelectTypeBR, tuttle::plugin::interact::ParamRectangleFromTwoCorners< TFrame, coord >::eSelectTypeC, tuttle::plugin::interact::ParamRectangleFromTwoCorners< TFrame, coord >::eSelectTypeL, tuttle::plugin::interact::ParamRectangleFromTwoCorners< TFrame, coord >::eSelectTypeNone, tuttle::plugin::interact::ParamRectangleFromTwoCorners< TFrame, coord >::eSelectTypeR, tuttle::plugin::interact::ParamRectangleFromTwoCorners< TFrame, coord >::eSelectTypeT, tuttle::plugin::interact::ParamRectangleFromTwoCorners< TFrame, coord >::eSelectTypeTL, tuttle::plugin::interact::ParamRectangleFromTwoCorners< TFrame, coord >::eSelectTypeTR, tuttle::plugin::interact::ParamRectangleFromTwoCorners< TFrame, coord >::getPoint(), tuttle::plugin::interact::PointInteract::getTime(), and tuttle::plugin::pointCanonicalXYToNormalizedXXc().
Field Documentation
template<class TFrame , ECoordinateSystem coord> OFX::Double2DParam* tuttle::plugin::interact::ParamRectangleFromTwoCorners< TFrame, coord >::_paramA [private]
same as TL (min)
Definition at line 25 of file ParamRectangleFromTwoCorners.hpp.
Referenced by tuttle::plugin::interact::ParamRectangleFromTwoCorners< TFrame, coord >::getPoint(), and tuttle::plugin::interact::ParamRectangleFromTwoCorners< TFrame, coord >::setPoint().
template<class TFrame , ECoordinateSystem coord> OFX::Double2DParam* tuttle::plugin::interact::ParamRectangleFromTwoCorners< TFrame, coord >::_paramB [private]
same as BR (max)
Definition at line 26 of file ParamRectangleFromTwoCorners.hpp.
Referenced by tuttle::plugin::interact::ParamRectangleFromTwoCorners< TFrame, coord >::getPoint(), and tuttle::plugin::interact::ParamRectangleFromTwoCorners< TFrame, coord >::setPoint().
template<class TFrame , ECoordinateSystem coord> TFrame tuttle::plugin::interact::ParamRectangleFromTwoCorners< TFrame, coord >::_relativeFrame [private]
Definition at line 27 of file ParamRectangleFromTwoCorners.hpp.
Referenced by tuttle::plugin::interact::ParamRectangleFromTwoCorners< TFrame, coord >::getPoint(), and tuttle::plugin::interact::ParamRectangleFromTwoCorners< TFrame, coord >::setPoint().
template<class TFrame , ECoordinateSystem coord> ESelectType tuttle::plugin::interact::ParamRectangleFromTwoCorners< TFrame, coord >::_selectType [private]
Definition at line 52 of file ParamRectangleFromTwoCorners.hpp.
Referenced by tuttle::plugin::interact::ParamRectangleFromTwoCorners< TFrame, coord >::setPoint().
The documentation for this class was generated from the following file:
TuttleOFX/libraries/tuttle/src/tuttle/plugin/interact/ParamRectangleFromTwoCorners.hpp