TuttleOFX: TuttleOFX/libraries/tuttle/tests/time/main.cpp File Reference
TuttleOFX/libraries/tuttle/tests/time/main.cpp File Reference
#include <tuttle/host/Graph.hpp>
#include <iostream>
#include <tuttle/test/unit_test.hpp>
Defines
#define BOOST_TEST_MODULE tuttle_time
Functions
BOOST_AUTO_TEST_CASE (preload)
BOOST_AUTO_TEST_CASE (time_shift_offset_null)
BOOST_AUTO_TEST_CASE (time_shift_positive_offset)
BOOST_AUTO_TEST_CASE (time_shift_negative_offset)
BOOST_AUTO_TEST_CASE (time_shift_negative_offset_forceIdentity)
Define Documentation
#define BOOST_TEST_MODULE tuttle_time
Definition at line 5 of file main.cpp.
Function Documentation
BOOST_AUTO_TEST_CASE (preload)
Definition at line 15 of file main.cpp.
References tuttle::host::ofx::OfxhPluginCache::addDirectoryToPath(), tuttle::host::core(), tuttle::host::Core::getPluginCache(), tuttle::host::Core::preload(), and TUTTLE_LOG_INFO.
BOOST_AUTO_TEST_CASE (time_shift_offset_null)
Definition at line 24 of file main.cpp.
References tuttle::host::Graph::compute(), tuttle::host::Graph::connect(), tuttle::host::Graph::createNode(), tuttle::host::INode::getName(), tuttle::host::INode::getParam(), tuttle::host::ofx::attribute::OfxhParam::setValue(), and TUTTLE_LOG_INFO.
BOOST_AUTO_TEST_CASE (time_shift_positive_offset)
Definition at line 60 of file main.cpp.
References tuttle::host::Graph::compute(), tuttle::host::Graph::connect(), tuttle::host::Graph::createNode(), tuttle::host::INode::getName(), tuttle::host::INode::getParam(), tuttle::host::ofx::attribute::OfxhParam::setValue(), and TUTTLE_LOG_INFO.
BOOST_AUTO_TEST_CASE (time_shift_negative_offset)
Definition at line 95 of file main.cpp.
References tuttle::host::Graph::compute(), tuttle::host::Graph::connect(), tuttle::host::Graph::createNode(), tuttle::host::INode::getName(), tuttle::host::INode::getParam(), tuttle::host::ofx::attribute::OfxhParam::setValue(), and TUTTLE_LOG_INFO.
BOOST_AUTO_TEST_CASE (time_shift_negative_offset_forceIdentity)
Definition at line 131 of file main.cpp.
References tuttle::host::Graph::compute(), tuttle::host::Graph::connect(), tuttle::host::Graph::createNode(), tuttle::host::INode::getName(), tuttle::host::INode::getParam(), tuttle::host::ofx::attribute::OfxhParam::setValue(), and TUTTLE_LOG_INFO.