TuttleOFX: tuttle::plugin::interact Namespace Reference
tuttle::plugin::interact Namespace Reference
Data Structures
struct IColor
struct Color
struct ColorRGBAParam
struct ColorRGBParam
struct IFrame
struct FrameClip
struct FrameOptionalClip
struct MotionType
class InteractInfos
class InteractObject
A base class for all object to use in interact or overlay. All sub classes needs to implement virtual functions from OFX::InteractI.
class InteractScene
To create a group of overlay/interact objects. Inherit from InteractObject, because a group of overlay/interact objects is itself an overlay/interact object.
struct IsActiveFunctor
struct AlwaysActiveFunctor
class IsEnableParamFunctor
class IsNotSecretParamFunctor
class IsActiveBooleanParamFunctor
class IsActiveChoiceParamFunctor
class AndActiveFunctor
class OrActiveFunctor
class ParamPoint
class ParamPointRelativePoint
struct CoordinateSystemNotCentered
struct CoordinateSystemNotCentered< eCoordinateSystemXXcn >
struct CoordinateSystemNotCentered< eCoordinateSystemXYc >
class ParamRectangleFromCenterSize
class ParamRectangleFromTwoCorners
class ParamTangent
class PointInteract
class SelectionManipulator
Typedefs
typedef double Scalar
typedef boost::gil::point2
< Scalar > Point2
Enumerations
enum EMotion { eMotionNone, eMotionTranslate, eMotionRotate, eMotionScale }
enum EAxis { eAxisNone, eAxisXY, eAxisX, eAxisY }
Functions
template<class Point >
EAxis clicPoint (const Point &point, const Point &mouse, const double marge)
EAxis clicDouble2D (const OFX::Double2DParam &point, const OfxPointD &mouse, const double marge)
check if the mouse clic intersect a point
EAxis clicDouble2D (const OFX::Double2DParam *point, const OfxPointD &mouse, const double marge)
IsActiveFunctor * new_clone (const IsActiveFunctor &a)
Typedef Documentation
typedef boost::gil::point2<Scalar> tuttle::plugin::interact::Point2
Definition at line 15 of file InteractObject.hpp.
typedef double tuttle::plugin::interact::Scalar
Definition at line 14 of file InteractObject.hpp.
Enumeration Type Documentation
enum tuttle::plugin::interact::EAxis
Enumerator:
eAxisNone
eAxisXY
eAxisX
eAxisY
Definition at line 22 of file interact.hpp.
enum tuttle::plugin::interact::EMotion
Enumerator:
eMotionNone
eMotionTranslate
eMotionRotate
eMotionScale
Definition at line 14 of file interact.hpp.
Function Documentation
EAxis tuttle::plugin::interact::clicDouble2D (const OFX::Double2DParam & point, const OfxPointD & mouse, const double marge) [inline]
check if the mouse clic intersect a point
Returns:
the type of intersection (None, XY, X, Y)
Parameters:
point the ofx parameter (in normalized space)
mouse the mouse clic
Definition at line 71 of file interact.hpp.
Referenced by clicDouble2D().
EAxis tuttle::plugin::interact::clicDouble2D (const OFX::Double2DParam * point, const OfxPointD & mouse, const double marge) [inline]
Definition at line 78 of file interact.hpp.
References clicDouble2D().
template<class Point > EAxis tuttle::plugin::interact::clicPoint (const Point & point, const Point & mouse, const double marge) [inline]
Definition at line 42 of file interact.hpp.
References eAxisNone, eAxisX, eAxisXY, and eAxisY.
Referenced by tuttle::plugin::interact::SelectionManipulator::intersect(), and tuttle::plugin::interact::PointInteract::intersect().
IsActiveFunctor* tuttle::plugin::interact::new_clone (const IsActiveFunctor & a) [inline]
Definition at line 24 of file IsActiveFunctor.hpp.
References tuttle::plugin::interact::IsActiveFunctor::clone().