TuttleOFX: tuttle::host::attribute::ParamDouble2D Class Reference
tuttle::host::attribute::ParamDouble2D Class Reference
#include <ParamDouble2D.hpp>
Public Member Functions
ParamDouble2D (INode &effect, const std::string &name, const ofx::attribute::OfxhParamDescriptor &descriptor)
ParamDouble2D * clone () const
clone this parameter
OfxPointD getDefault () const
void getValue (double &x, double &y) const OFX_EXCEPTION_SPEC
void getValueAtTime (const OfxTime time, double &x, double &y) const OFX_EXCEPTION_SPEC
void setValue (const double &x, const double &y, const ofx::attribute::EChange change) OFX_EXCEPTION_SPEC
void setValueAtTime (const OfxTime time, const double &x, const double &y, const ofx::attribute::EChange change) OFX_EXCEPTION_SPEC
void setValue (const int &x, const int &y, const ofx::attribute::EChange change) OFX_EXCEPTION_SPEC
void setValueAtTime (const OfxTime time, const int &x, const int &y, const ofx::attribute::EChange change) OFX_EXCEPTION_SPEC
Detailed Description
Definition at line 11 of file ParamDouble2D.hpp.
Constructor & Destructor Documentation
tuttle::host::attribute::ParamDouble2D::ParamDouble2D (INode & effect, const std::string & name, const ofx::attribute::OfxhParamDescriptor & descriptor)
Definition at line 9 of file ParamDouble2D.cpp.
References tuttle::host::ofx::attribute::OfxhMultiDimParam< ParamDouble, DIM >::_controls.
Referenced by clone().
Member Function Documentation
ParamDouble2D* tuttle::host::attribute::ParamDouble2D::clone () const [inline, virtual]
clone this parameter
Implements tuttle::host::ofx::attribute::OfxhParam.
Definition at line 16 of file ParamDouble2D.hpp.
References ParamDouble2D().
OfxPointD tuttle::host::attribute::ParamDouble2D::getDefault () const
Definition at line 19 of file ParamDouble2D.cpp.
References tuttle::host::ofx::attribute::OfxhMultiDimParam< ParamDouble, DIM >::_controls.
void tuttle::host::attribute::ParamDouble2D::getValue (double & x, double & y) const
Definition at line 28 of file ParamDouble2D.cpp.
void tuttle::host::attribute::ParamDouble2D::getValueAtTime (const OfxTime time, double & x, double & y) const
Definition at line 34 of file ParamDouble2D.cpp.
void tuttle::host::attribute::ParamDouble2D::setValue (const double & x, const double & y, const ofx::attribute::EChange change)
Definition at line 40 of file ParamDouble2D.cpp.
Referenced by setValue().
void tuttle::host::attribute::ParamDouble2D::setValue (const int & x, const int & y, const ofx::attribute::EChange change) [inline]
Definition at line 27 of file ParamDouble2D.hpp.
References setValue().
void tuttle::host::attribute::ParamDouble2D::setValueAtTime (const OfxTime time, const double & x, const double & y, const ofx::attribute::EChange change)
Definition at line 47 of file ParamDouble2D.cpp.
Referenced by setValueAtTime().
void tuttle::host::attribute::ParamDouble2D::setValueAtTime (const OfxTime time, const int & x, const int & y, const ofx::attribute::EChange change) [inline]
Definition at line 31 of file ParamDouble2D.hpp.
References setValueAtTime().
The documentation for this class was generated from the following files:
TuttleOFX/libraries/tuttle/src/tuttle/host/attribute/ParamDouble2D.hpp
TuttleOFX/libraries/tuttle/src/tuttle/host/attribute/ParamDouble2D.cpp