TuttleOFX: tuttle::host::ofx::attribute::OfxhParamInteger Class Reference
tuttle::host::ofx::attribute::OfxhParamInteger Class Reference
#include <OfxhParamInteger.hpp>
Public Types
typedef int BaseType
Public Member Functions
OfxhParamInteger (const OfxhParamDescriptor &descriptor, const std::string &name, OfxhParamSet &setInstance, const std::size_t index=0)
virtual void getValue (int &) const OFX_EXCEPTION_SPEC=0
virtual void getValueAtTime (const OfxTime time, int &) const OFX_EXCEPTION_SPEC=0
virtual void setValue (const int &, const EChange change) OFX_EXCEPTION_SPEC=0
virtual void setValueAtTime (const OfxTime time, const int &, const EChange change) OFX_EXCEPTION_SPEC=0
virtual void setValue (const bool &v, const EChange change) OFX_EXCEPTION_SPEC
virtual void setValueAtTime (const OfxTime time, const bool &v, const EChange change) OFX_EXCEPTION_SPEC
virtual void derive (const OfxTime time, int &) const OFX_EXCEPTION_SPEC
virtual void integrate (const OfxTime time1, const OfxTime time2, int &) const OFX_EXCEPTION_SPEC
virtual void getV (va_list arg) const OFX_EXCEPTION_SPEC
implementation of var args function
virtual void getV (const OfxTime time, va_list arg) const OFX_EXCEPTION_SPEC
implementation of var args function
virtual void setV (va_list arg, const EChange change) OFX_EXCEPTION_SPEC
implementation of var args function
virtual void setV (const OfxTime time, va_list arg, const EChange change) OFX_EXCEPTION_SPEC
implementation of var args function
virtual void deriveV (const OfxTime time, va_list arg) const OFX_EXCEPTION_SPEC
implementation of var args function
virtual void integrateV (const OfxTime time1, const OfxTime time2, va_list arg) const OFX_EXCEPTION_SPEC
implementation of var args function
std::ostream & displayValues (std::ostream &os) const
Protected Attributes
std::size_t _index
Detailed Description
Definition at line 14 of file OfxhParamInteger.hpp.
Member Typedef Documentation
typedef int tuttle::host::ofx::attribute::OfxhParamInteger::BaseType
Definition at line 22 of file OfxhParamInteger.hpp.
Constructor & Destructor Documentation
tuttle::host::ofx::attribute::OfxhParamInteger::OfxhParamInteger (const OfxhParamDescriptor & descriptor, const std::string & name, OfxhParamSet & setInstance, const std::size_t index = 0) [inline]
Definition at line 23 of file OfxhParamInteger.hpp.
References tuttle::host::ofx::property::OfxhSet::addNotifyHook(), and tuttle::host::ofx::attribute::OfxhAttribute::getEditableProperties().
Member Function Documentation
void tuttle::host::ofx::attribute::OfxhParamInteger::derive (const OfxTime time, int &) const [virtual]
Definition at line 8 of file OfxhParamInteger.cpp.
void tuttle::host::ofx::attribute::OfxhParamInteger::deriveV (const OfxTime time, va_list arg) const [virtual]
implementation of var args function
Reimplemented from tuttle::host::ofx::attribute::OfxhParam.
Definition at line 61 of file OfxhParamInteger.cpp.
std::ostream& tuttle::host::ofx::attribute::OfxhParamInteger::displayValues (std::ostream & os) const [inline, virtual]
Reimplemented from tuttle::host::ofx::attribute::OfxhParam.
Definition at line 71 of file OfxhParamInteger.hpp.
void tuttle::host::ofx::attribute::OfxhParamInteger::getV (va_list arg) const [virtual]
implementation of var args function
Reimplemented from tuttle::host::ofx::attribute::OfxhParam.
Definition at line 21 of file OfxhParamInteger.cpp.
void tuttle::host::ofx::attribute::OfxhParamInteger::getV (const OfxTime time, va_list arg) const [virtual]
implementation of var args function
Reimplemented from tuttle::host::ofx::attribute::OfxhParam.
Definition at line 31 of file OfxhParamInteger.cpp.
virtual void tuttle::host::ofx::attribute::OfxhParamInteger::getValue (int &) const [pure virtual]
virtual void tuttle::host::ofx::attribute::OfxhParamInteger::getValueAtTime (const OfxTime time, int &) const [pure virtual]
void tuttle::host::ofx::attribute::OfxhParamInteger::integrate (const OfxTime time1, const OfxTime time2, int &) const [virtual]
Definition at line 13 of file OfxhParamInteger.cpp.
void tuttle::host::ofx::attribute::OfxhParamInteger::integrateV (const OfxTime time1, const OfxTime time2, va_list arg) const [virtual]
implementation of var args function
Reimplemented from tuttle::host::ofx::attribute::OfxhParam.
Definition at line 71 of file OfxhParamInteger.cpp.
void tuttle::host::ofx::attribute::OfxhParamInteger::setV (va_list arg, const EChange change) [virtual]
implementation of var args function
Reimplemented from tuttle::host::ofx::attribute::OfxhParam.
Definition at line 41 of file OfxhParamInteger.cpp.
void tuttle::host::ofx::attribute::OfxhParamInteger::setV (const OfxTime time, va_list arg, const EChange change) [virtual]
implementation of var args function
Reimplemented from tuttle::host::ofx::attribute::OfxhParam.
Definition at line 51 of file OfxhParamInteger.cpp.
virtual void tuttle::host::ofx::attribute::OfxhParamInteger::setValue (const int & , const EChange change) [pure virtual]
Referenced by setValue().
virtual void tuttle::host::ofx::attribute::OfxhParamInteger::setValue (const bool & v, const EChange change) [inline, virtual]
Definition at line 37 of file OfxhParamInteger.hpp.
References setValue().
virtual void tuttle::host::ofx::attribute::OfxhParamInteger::setValueAtTime (const OfxTime time, const int & , const EChange change) [pure virtual]
Referenced by setValueAtTime().
virtual void tuttle::host::ofx::attribute::OfxhParamInteger::setValueAtTime (const OfxTime time, const bool & v, const EChange change) [inline, virtual]
Definition at line 42 of file OfxhParamInteger.hpp.
References setValueAtTime().
Field Documentation
std::size_t tuttle::host::ofx::attribute::OfxhParamInteger::_index [protected]
Definition at line 19 of file OfxhParamInteger.hpp.
The documentation for this class was generated from the following files:
TuttleOFX/libraries/tuttle/src/tuttle/host/ofx/attribute/OfxhParamInteger.hpp
TuttleOFX/libraries/tuttle/src/tuttle/host/ofx/attribute/OfxhParamInteger.cpp