TuttleOFX: tuttle::host::ofx::OfxhPluginDesc Class Reference
tuttle::host::ofx::OfxhPluginDesc Class Reference
#include <OfxhPluginDesc.hpp>
Public Types
typedef OfxhPluginDesc This
Public Member Functions
OfxhPluginDesc ()
OfxhPluginDesc (const std::string &api, int apiVersion, const std::string &identifier, const std::string &rawIdentifier, int versionMajor, int versionMinor)
OfxhPluginDesc (OfxPlugin &ofxPlugin)
virtual ~OfxhPluginDesc ()
bool operator== (const This &other) const
bool operator!= (const This &other) const
const std::string & getPluginApi () const
int getApiVersion () const
const OfxhPluginIdent & getIdentity () const
OfxhPluginIdent & getIdentity ()
const std::string & getIdentifier () const
const std::string & getRawIdentifier () const
int getVersionMajor () const
int getVersionMinor () const
std::size_t getHash () const
Protected Attributes
std::string _pluginApi
the API I implement
int _apiVersion
the version of the API
OfxhPluginIdent _ident
The plugin identity.
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Friends
class boost::serialization::access
Detailed Description
C++ version of the information kept inside an OfxPlugin struct
Definition at line 51 of file OfxhPluginDesc.hpp.
Member Typedef Documentation
typedef OfxhPluginDesc tuttle::host::ofx::OfxhPluginDesc::This
Reimplemented in tuttle::host::ofx::imageEffect::OfxhImageEffectPlugin, and tuttle::host::ofx::OfxhPlugin.
Definition at line 54 of file OfxhPluginDesc.hpp.
Constructor & Destructor Documentation
tuttle::host::ofx::OfxhPluginDesc::OfxhPluginDesc ()
Definition at line 9 of file OfxhPluginDesc.cpp.
tuttle::host::ofx::OfxhPluginDesc::OfxhPluginDesc (const std::string & api, int apiVersion, const std::string & identifier, const std::string & rawIdentifier, int versionMajor, int versionMinor)
Definition at line 13 of file OfxhPluginDesc.cpp.
tuttle::host::ofx::OfxhPluginDesc::OfxhPluginDesc (OfxPlugin & ofxPlugin)
constructor for the case where we have already loaded the plugin binary and are populating this object from it
Definition at line 31 of file OfxhPluginDesc.cpp.
References _ident, and tuttle::host::ofx::OfxhPluginIdent::_identifier.
tuttle::host::ofx::OfxhPluginDesc::~OfxhPluginDesc () [virtual]
Definition at line 24 of file OfxhPluginDesc.cpp.
Member Function Documentation
int tuttle::host::ofx::OfxhPluginDesc::getApiVersion () const [inline]
Definition at line 89 of file OfxhPluginDesc.hpp.
References _apiVersion.
Referenced by tuttle::host::ofx::OfxhPluginCache::serialize().
std::size_t tuttle::host::ofx::OfxhPluginDesc::getHash () const
Definition at line 48 of file OfxhPluginDesc.cpp.
References getIdentifier(), and getVersionMajor().
Referenced by tuttle::host::ImageEffectNode::getLocalHashAtTime().
const std::string& tuttle::host::ofx::OfxhPluginDesc::getIdentifier () const [inline]
Definition at line 104 of file OfxhPluginDesc.hpp.
References _ident, and tuttle::host::ofx::OfxhPluginIdent::_identifier.
Referenced by tuttle::host::ofx::OfxhPluginCache::addPlugin(), tuttle::host::ofx::imageEffect::OfxhImageEffectPluginCache::confirmPlugin(), tuttle::host::ofx::imageEffect::OfxhImageEffectPlugin::getDescriptorInContext(), getHash(), tuttle::host::Graph::getNodesByPlugin(), tuttle::host::ofx::imageEffect::OfxhImageEffectPluginCache::getPluginById(), tuttle::host::ofx::OfxhPluginCache::getPluginById(), tuttle::host::ofx::imageEffect::OfxhImageEffectPlugin::loadAndDescribeActions(), tuttle::host::ofx::imageEffect::OfxhImageEffectPluginCache::loadFromPlugin(), tuttle::host::ofx::OfxhPluginCache::scanDirectory(), and tuttle::host::ofx::OfxhPluginCache::scanPluginFiles().
const OfxhPluginIdent& tuttle::host::ofx::OfxhPluginDesc::getIdentity () const [inline]
Definition at line 94 of file OfxhPluginDesc.hpp.
References _ident.
Referenced by tuttle::host::ofx::OfxhPluginCache::addPlugin().
OfxhPluginIdent& tuttle::host::ofx::OfxhPluginDesc::getIdentity () [inline]
Definition at line 99 of file OfxhPluginDesc.hpp.
References _ident.
const std::string& tuttle::host::ofx::OfxhPluginDesc::getPluginApi () const [inline]
Definition at line 84 of file OfxhPluginDesc.hpp.
References _pluginApi.
Referenced by tuttle::host::ofx::OfxhPluginCache::serialize().
const std::string& tuttle::host::ofx::OfxhPluginDesc::getRawIdentifier () const [inline]
Definition at line 109 of file OfxhPluginDesc.hpp.
References _ident, and tuttle::host::ofx::OfxhPluginIdent::_rawIdentifier.
Referenced by tuttle::host::ofx::OfxhPluginCache::addPlugin(), and tuttle::host::ofx::imageEffect::OfxhImageEffectPluginCache::loadFromPlugin().
int tuttle::host::ofx::OfxhPluginDesc::getVersionMajor () const [inline]
Definition at line 114 of file OfxhPluginDesc.hpp.
References _ident, and tuttle::host::ofx::OfxhPluginIdent::_versionMajor.
Referenced by tuttle::host::ofx::imageEffect::OfxhImageEffectPluginCache::confirmPlugin(), getHash(), tuttle::host::ofx::imageEffect::OfxhImageEffectPluginCache::getPluginById(), tuttle::host::ofx::OfxhPluginCache::getPluginById(), tuttle::host::ofx::imageEffect::OfxhImageEffectPluginCache::getPluginByLabel(), tuttle::host::ofx::OfxhPluginCache::scanDirectory(), and tuttle::host::ofx::OfxhPlugin::trumps().
int tuttle::host::ofx::OfxhPluginDesc::getVersionMinor () const [inline]
Definition at line 119 of file OfxhPluginDesc.hpp.
References _ident, and tuttle::host::ofx::OfxhPluginIdent::_versionMinor.
Referenced by tuttle::host::ofx::imageEffect::OfxhImageEffectPluginCache::getPluginById(), tuttle::host::ofx::OfxhPluginCache::getPluginById(), tuttle::host::ofx::imageEffect::OfxhImageEffectPluginCache::getPluginByLabel(), tuttle::host::ofx::OfxhPluginCache::scanDirectory(), and tuttle::host::ofx::OfxhPlugin::trumps().
bool tuttle::host::ofx::OfxhPluginDesc::operator!= (const This & other) const [inline]
Definition at line 81 of file OfxhPluginDesc.hpp.
References operator==().
bool tuttle::host::ofx::OfxhPluginDesc::operator== (const This & other) const
Definition at line 39 of file OfxhPluginDesc.cpp.
References _apiVersion, _ident, and _pluginApi.
Referenced by operator!=().
template<class Archive > void tuttle::host::ofx::OfxhPluginDesc::serialize (Archive & ar, const unsigned int version) [inline, private]
Reimplemented in tuttle::host::ofx::imageEffect::OfxhImageEffectPlugin, and tuttle::host::ofx::OfxhPlugin.
Definition at line 129 of file OfxhPluginDesc.hpp.
References _apiVersion, _ident, tuttle::host::ofx::OfxhPluginIdent::_identifier, _pluginApi, tuttle::host::ofx::OfxhPluginIdent::_rawIdentifier, tuttle::host::ofx::OfxhPluginIdent::_versionMajor, and tuttle::host::ofx::OfxhPluginIdent::_versionMinor.
Friends And Related Function Documentation
friend class boost::serialization::access [friend]
Reimplemented in tuttle::host::ofx::imageEffect::OfxhImageEffectPlugin, and tuttle::host::ofx::OfxhPlugin.
Definition at line 127 of file OfxhPluginDesc.hpp.
Field Documentation
int tuttle::host::ofx::OfxhPluginDesc::_apiVersion [protected]
the version of the API
Definition at line 58 of file OfxhPluginDesc.hpp.
Referenced by getApiVersion(), operator==(), and serialize().
OfxhPluginIdent tuttle::host::ofx::OfxhPluginDesc::_ident [protected]
The plugin identity.
Definition at line 60 of file OfxhPluginDesc.hpp.
Referenced by getIdentifier(), getIdentity(), getRawIdentifier(), getVersionMajor(), getVersionMinor(), OfxhPluginDesc(), operator==(), and serialize().
std::string tuttle::host::ofx::OfxhPluginDesc::_pluginApi [protected]
the API I implement
Definition at line 57 of file OfxhPluginDesc.hpp.
Referenced by getPluginApi(), operator==(), and serialize().
The documentation for this class was generated from the following files:
TuttleOFX/libraries/tuttle/src/tuttle/host/ofx/OfxhPluginDesc.hpp
TuttleOFX/libraries/tuttle/src/tuttle/host/ofx/OfxhPluginDesc.cpp