TuttleOFX: tuttle::host Namespace Reference
tuttle::host Namespace Reference
Library for host.
Namespaces
namespace attribute
namespace core
All main class of the host.
namespace exception
namespace graph
graph work
namespace io
namespace memory
namespace ofx
OpenFX wrapping to communicate with C API.
Data Structures
class Callback
class IProgressHandle
struct TimeRange
class ComputeOptions
class Core
class DiskCacheTranslator
An helper to cache any kind of files on your HDD. It allows to:
class Graph
A user graph to manipulate OpenFX nodes.
class Host
class ImageEffectNode
class INode
class InputBufferWrapper
class NodeInit
Node initializer class.
class NodeAtTimeKey
class NodeHashContainer
class NodeListArg
An utility class to use as function argument. It allows to create a list of nodes from multiple inputs.
class OutputBufferWrapper
class OverlayInteract
class Preferences
struct PreloadPlugins
class ThreadEnv
class ThumbnailDiskCache
An helper to cache image thumbnails on your HDD.
Enumerations
enum EVerboseLevel {
eVerboseLevelTrace = boost::log::trivial::trace, eVerboseLevelDebug = boost::log::trivial::debug, eVerboseLevelInfo = boost::log::trivial::info, eVerboseLevelWarning = boost::log::trivial::warning,
eVerboseLevelError = boost::log::trivial::error, eVerboseLevelFatal = boost::log::trivial::fatal
}
Functions
std::ostream & operator<< (std::ostream &os, const Core &v)
Core & core ()
std::ostream & operator<< (std::ostream &os, const Graph &g)
std::ostream & operator<< (std::ostream &os, const ImageEffectNode &v)
std::ostream & operator<< (std::ostream &os, const INode &v)
INode * new_clone (const INode &a)
to make clonable for use in boost::ptr_container.
std::string mapNodeTypeEnumToString (const INode::ENodeType e)
INode * createNode (const std::string &pluginName)
bool compute (const std::vector< NodeInit > &nodes, const ComputeOptions &options)
bool compute (memory::IMemoryCache &memoryCache, const std::vector< NodeInit > &nodes, const ComputeOptions &options)
bool compute (memory::IMemoryCache &memoryCache, const std::vector< NodeInit > &nodes, const ComputeOptions &options, memory::IMemoryCache &internMemoryCache)
std::ostream & operator<< (std::ostream &os, const NodeAtTimeKey &k)
std::ostream & operator<< (std::ostream &os, const NodeHashContainer &c)
::boost::shared_ptr
< attribute::Image > loadImage (const std::string &imagePath)
::boost::shared_ptr
< attribute::Image > loadAndGenerateThumbnail (const std::string &imagePath, const std::string &thumbnailToCreate, const int thumbnailMaxSize)
Detailed Description
Library for host.
Enumeration Type Documentation
enum tuttle::host::EVerboseLevel
Enumerator:
eVerboseLevelTrace
eVerboseLevelDebug
eVerboseLevelInfo
eVerboseLevelWarning
eVerboseLevelError
eVerboseLevelFatal
Definition at line 56 of file ComputeOptions.hpp.
Function Documentation
bool tuttle::host::compute (const std::vector< NodeInit > & nodes, const ComputeOptions & options)
Definition at line 66 of file Node.cpp.
Referenced by BOOST_AUTO_TEST_CASE(), compute(), and loadImage().
bool tuttle::host::compute (memory::IMemoryCache & memoryCache, const std::vector< NodeInit > & nodes, const ComputeOptions & options)
Definition at line 74 of file Node.cpp.
References compute(), and core().
bool tuttle::host::compute (memory::IMemoryCache & memoryCache, const std::vector< NodeInit > & nodes, const ComputeOptions & options, memory::IMemoryCache & internMemoryCache)
Definition at line 79 of file Node.cpp.
References tuttle::host::Graph::addConnectedNodes(), and tuttle::host::Graph::compute().
Core& tuttle::host::core () [inline]
Definition at line 81 of file Core.hpp.
References Singleton< T >::instance().
Referenced by tuttle::host::memory::MemoryPool::allocate(), BOOST_AUTO_TEST_CASE(), tuttle::host::ofx::imageEffect::OfxhImageEffectNode::canCurrentlyHandleMultipleClipDepths(), compute(), tuttle::host::Graph::compute(), tuttle::host::Graph::computeGlobalHashAtTime(), tuttle::host::ofx::imageEffect::OfxhImageEffectPlugin::createInstance(), createNode(), tuttle::host::ofx::imageEffect::OfxhImageEffectPlugin::describeInContextAction(), tuttle::host::io::getIOPluginsForExtension(), tuttle::host::ofx::imageEffect::OfxhImageEffectNodeDescriptor::OfxhImageEffectNodeDescriptor(), tuttle::host::ofx::imageEffect::OfxhImageEffectPluginCache::pluginSupported(), tuttle::host::PreloadPlugins::PreloadPlugins(), tuttle::host::ImageEffectNode::process(), tuttle::host::ThreadEnv::runProcessFunc(), tuttle::host::Graph::setup(), and tuttle::host::Graph::setupAtTime().
INode * tuttle::host::createNode (const std::string & pluginName)
Definition at line 10 of file Node.cpp.
References core(), tuttle::host::ofx::imageEffect::OfxhImageEffectPlugin::createInstance(), tuttle::host::Core::getImageEffectPluginById(), tuttle::host::ofx::imageEffect::OfxhImageEffectPlugin::loadAndDescribeActions(), and tuttle::host::ofx::imageEffect::OfxhImageEffectPlugin::supportsContext().
Referenced by tuttle::host::NodeInit::NodeInit().
::boost::shared_ptr<attribute::Image> tuttle::host::loadAndGenerateThumbnail (const std::string & imagePath, const std::string & thumbnailToCreate, const int thumbnailMaxSize)
Definition at line 31 of file ThumbnailDiskCache.cpp.
References tuttle::host::Graph::addConnectedNodes(), tuttle::host::Graph::compute(), eVerboseLevelTrace, tuttle::host::memory::MemoryCache::get(), tuttle::host::io::getBestReader(), tuttle::host::io::getBestWriter(), tuttle::host::NodeInit::setParam(), tuttle::host::ComputeOptions::setTimeRange(), tuttle::host::Graph::setup(), and tuttle::host::ComputeOptions::setVerboseLevel().
Referenced by tuttle::host::ThumbnailDiskCache::create().
boost::shared_ptr< attribute::Image > tuttle::host::loadImage (const std::string & imagePath)
Definition at line 17 of file ThumbnailDiskCache.cpp.
References compute(), tuttle::host::memory::MemoryCache::get(), and tuttle::host::io::getBestReader().
Referenced by tuttle::host::ThumbnailDiskCache::getThumbnail(), and tuttle::host::ThumbnailDiskCache::retrieveThumbnail().
std::string tuttle::host::mapNodeTypeEnumToString (const INode::ENodeType e) [inline]
Definition at line 259 of file INode.hpp.
References tuttle::host::INode::eNodeTypeBuffer, tuttle::host::INode::eNodeTypeGraph, tuttle::host::INode::eNodeTypeImageEffect, tuttle::host::INode::eNodeTypeParam, and tuttle::host::INode::eNodeTypeUnknown.
Referenced by tuttle::host::attribute::ClipImage::fetchRegionOfDefinition().
INode* tuttle::host::new_clone (const INode & a) [inline]
to make clonable for use in boost::ptr_container.
Definition at line 252 of file INode.hpp.
References tuttle::host::INode::clone().
std::ostream& tuttle::host::operator<< (std::ostream & os, const NodeHashContainer & c)
Definition at line 8 of file NodeHashContainer.cpp.
References tuttle::host::NodeHashContainer::_hashes.
std::ostream& tuttle::host::operator<< (std::ostream & os, const NodeAtTimeKey & k)
Definition at line 32 of file NodeAtTimeKey.cpp.
References tuttle::host::NodeAtTimeKey::_name, and tuttle::host::NodeAtTimeKey::_time.
std::ostream& tuttle::host::operator<< (std::ostream & os, const Core & v)
Definition at line 149 of file Core.cpp.
References tuttle::host::Core::getImageEffectPluginCache().
std::ostream& tuttle::host::operator<< (std::ostream & os, const INode & v)
Definition at line 156 of file INode.cpp.
References tuttle::host::INode::print().
std::ostream& tuttle::host::operator<< (std::ostream & os, const Graph & g)
Definition at line 490 of file Graph.cpp.
References tuttle::host::Graph::getGraph().
std::ostream& tuttle::host::operator<< (std::ostream & os, const ImageEffectNode & v)
Definition at line 1035 of file ImageEffectNode.cpp.
References tuttle::host::ImageEffectNode::print().