TuttleOFX: tuttle::host::ofx::attribute::OfxhClipAccessor Class Reference
tuttle::host::ofx::attribute::OfxhClipAccessor Class Reference
#include <OfxhClipAccessor.hpp>
Public Member Functions
OfxhClipAccessor ()
base ctor, for a descriptor
virtual ~OfxhClipAccessor ()=0
bool isOptional () const
is the clip optional
const bool isConnected () const
void setConnected (const bool isConnected=true)
Connected Says whether the clip is currently connected.
virtual bool verifyMagic ()
Detailed Description
Base to both descriptor and instance it is used to basically fetch common properties by function name
Definition at line 16 of file OfxhClipAccessor.hpp.
Constructor & Destructor Documentation
tuttle::host::ofx::attribute::OfxhClipAccessor::OfxhClipAccessor ()
base ctor, for a descriptor
Definition at line 8 of file OfxhClipAccessor.cpp.
tuttle::host::ofx::attribute::OfxhClipAccessor::~OfxhClipAccessor () [pure virtual]
Definition at line 11 of file OfxhClipAccessor.cpp.
Member Function Documentation
const bool tuttle::host::ofx::attribute::OfxhClipAccessor::isConnected () const
Definition at line 23 of file OfxhClipAccessor.cpp.
References tuttle::host::ofx::property::OfxhSet::getIntProperty(), and tuttle::host::ofx::attribute::OfxhAttributeAccessor::getProperties().
Referenced by tuttle::host::ofx::imageEffect::OfxhImageEffectNode::calcDefaultRegionOfDefinition(), tuttle::host::ImageEffectNode::checkClipsConnected(), tuttle::host::ImageEffectNode::computeTimeDomain(), tuttle::host::ImageEffectNode::coutBitDepthConnections(), tuttle::host::attribute::ClipImage::fetchRegionOfDefinition(), tuttle::host::attribute::ClipImage::getClipIdentifier(), tuttle::host::attribute::ClipImage::getConnectedClipFullName(), tuttle::host::ImageEffectNode::getDefaultTimeDomain(), tuttle::host::ImageEffectNode::initComponents(), tuttle::host::ImageEffectNode::initInputClipsFps(), tuttle::host::ImageEffectNode::initInputClipsPixelAspectRatio(), tuttle::host::ofx::imageEffect::OfxhImageEffectNode::isLeafNode(), tuttle::host::ImageEffectNode::maximizeBitDepthFromReadsToWrites(), tuttle::host::ImageEffectNode::maximizeBitDepthFromWritesToReads(), tuttle::host::ImageEffectNode::process(), tuttle::host::ofx::imageEffect::OfxhImageEffectNode::setDefaultClipPreferences(), and tuttle::host::ImageEffectNode::validInputClipsConnections().
bool tuttle::host::ofx::attribute::OfxhClipAccessor::isOptional () const
is the clip optional
Definition at line 17 of file OfxhClipAccessor.cpp.
References tuttle::host::ofx::property::OfxhSet::getIntProperty(), and tuttle::host::ofx::attribute::OfxhAttributeAccessor::getProperties().
Referenced by tuttle::host::ImageEffectNode::checkClipsConnected().
void tuttle::host::ofx::attribute::OfxhClipAccessor::setConnected (const bool isConnected = true)
Connected Says whether the clip is currently connected.
Definition at line 32 of file OfxhClipAccessor.cpp.
References tuttle::host::ofx::attribute::OfxhAttributeAccessor::getEditableProperties(), and tuttle::host::ofx::property::OfxhSet::setIntProperty().
Referenced by tuttle::host::attribute::ClipImage::setConnectedClip(), and tuttle::host::attribute::ClipImage::setUnconnected().
virtual bool tuttle::host::ofx::attribute::OfxhClipAccessor::verifyMagic () [inline, virtual]
Definition at line 36 of file OfxhClipAccessor.hpp.
The documentation for this class was generated from the following files:
TuttleOFX/libraries/tuttle/src/tuttle/host/ofx/attribute/OfxhClipAccessor.hpp
TuttleOFX/libraries/tuttle/src/tuttle/host/ofx/attribute/OfxhClipAccessor.cpp