TuttleOFX: tuttle::host::ofx::APICache::OfxhPluginAPICacheI Class Reference
tuttle::host::ofx::APICache::OfxhPluginAPICacheI Class Reference
this acts as an interface for the Plugin Cache, handling api-specific cacheing
#include <OfxhPluginAPICache.hpp>
Public Member Functions
OfxhPluginAPICacheI (std::string apiName, int verMin, int verMax)
virtual ~OfxhPluginAPICacheI ()
virtual void loadFromPlugin (OfxhPlugin &)=0
virtual OfxhPlugin * newPlugin (OfxhPluginBinary &, int pi, OfxPlugin &plug)=0
factory method, to create a new plugin (from binary)
virtual OfxhPlugin * newPlugin (OfxhPluginBinary &pb, int pi, const std::string &api, int apiVersion, const std::string &pluginId, const std::string &rawId, int pluginMajorVersion, int pluginMinorVersion)=0
factory method, to create a new plugin (from the
virtual OfxhHost & getHost ()=0
virtual void confirmPlugin (OfxhPlugin &)=0
virtual bool pluginSupported (const OfxhPlugin &, std::string &reason) const =0
Data Fields
std::string _apiName
int _apiVersionMin
int _apiVersionMax
Detailed Description
this acts as an interface for the Plugin Cache, handling api-specific cacheing
Definition at line 46 of file OfxhPluginAPICache.hpp.
Constructor & Destructor Documentation
tuttle::host::ofx::APICache::OfxhPluginAPICacheI::OfxhPluginAPICacheI (std::string apiName, int verMin, int verMax) [inline]
Definition at line 53 of file OfxhPluginAPICache.hpp.
virtual tuttle::host::ofx::APICache::OfxhPluginAPICacheI::~OfxhPluginAPICacheI () [inline, virtual]
Definition at line 59 of file OfxhPluginAPICache.hpp.
Member Function Documentation
virtual void tuttle::host::ofx::APICache::OfxhPluginAPICacheI::confirmPlugin (OfxhPlugin &) [pure virtual]
Implemented in tuttle::host::ofx::imageEffect::OfxhImageEffectPluginCache.
Referenced by tuttle::host::ofx::OfxhPluginCache::scanPluginFiles().
virtual OfxhHost& tuttle::host::ofx::APICache::OfxhPluginAPICacheI::getHost () [pure virtual]
Implemented in tuttle::host::ofx::imageEffect::OfxhImageEffectPluginCache.
virtual void tuttle::host::ofx::APICache::OfxhPluginAPICacheI::loadFromPlugin (OfxhPlugin &) [pure virtual]
Implemented in tuttle::host::ofx::imageEffect::OfxhImageEffectPluginCache.
Referenced by tuttle::host::ofx::OfxhPluginCache::scanDirectory(), and tuttle::host::ofx::OfxhPluginCache::scanPluginFiles().
virtual OfxhPlugin* tuttle::host::ofx::APICache::OfxhPluginAPICacheI::newPlugin (OfxhPluginBinary & , int pi, OfxPlugin & plug) [pure virtual]
factory method, to create a new plugin (from binary)
Implemented in tuttle::host::ofx::imageEffect::OfxhImageEffectPluginCache.
virtual OfxhPlugin* tuttle::host::ofx::APICache::OfxhPluginAPICacheI::newPlugin (OfxhPluginBinary & pb, int pi, const std::string & api, int apiVersion, const std::string & pluginId, const std::string & rawId, int pluginMajorVersion, int pluginMinorVersion) [pure virtual]
factory method, to create a new plugin (from the
Implemented in tuttle::host::ofx::imageEffect::OfxhImageEffectPluginCache.
virtual bool tuttle::host::ofx::APICache::OfxhPluginAPICacheI::pluginSupported (const OfxhPlugin & , std::string & reason) const [pure virtual]
Implemented in tuttle::host::ofx::imageEffect::OfxhImageEffectPluginCache.
Referenced by tuttle::host::ofx::OfxhPluginCache::scanPluginFiles().
Field Documentation
std::string tuttle::host::ofx::APICache::OfxhPluginAPICacheI::_apiName
Definition at line 49 of file OfxhPluginAPICache.hpp.
Referenced by tuttle::host::ofx::PluginCacheSupportedApi::matches().
int tuttle::host::ofx::APICache::OfxhPluginAPICacheI::_apiVersionMax
Definition at line 50 of file OfxhPluginAPICache.hpp.
int tuttle::host::ofx::APICache::OfxhPluginAPICacheI::_apiVersionMin
Definition at line 50 of file OfxhPluginAPICache.hpp.
Referenced by tuttle::host::ofx::PluginCacheSupportedApi::matches().
The documentation for this class was generated from the following file:
TuttleOFX/libraries/tuttle/src/tuttle/host/ofx/OfxhPluginAPICache.hpp