TuttleOFX: tuttle::host::attribute::ParamRGBA Class Reference
tuttle::host::attribute::ParamRGBA Class Reference
#include <ParamRGBA.hpp>
Public Member Functions
ParamRGBA (INode &effect, const std::string &name, const ofx::attribute::OfxhParamDescriptor &descriptor)
ParamRGBA * clone () const
clone this parameter
OfxRGBAColourD getDefault () const
void getValue (double &r, double &g, double &b, double &a) const OFX_EXCEPTION_SPEC
void getValueAtTime (const OfxTime time, double &r, double &g, double &b, double &a) const OFX_EXCEPTION_SPEC
void setValue (const int &r, const int &g, const int &b, const int &a, const ofx::attribute::EChange change) OFX_EXCEPTION_SPEC
void setValue (const double &r, const double &g, const double &b, const double &a, const ofx::attribute::EChange change) OFX_EXCEPTION_SPEC
void setValueAtTime (const OfxTime time, const int &r, const int &g, const int &b, const int &a, const ofx::attribute::EChange change) OFX_EXCEPTION_SPEC
void setValueAtTime (const OfxTime time, const double &r, const double &g, const double &b, const ofx::attribute::EChange change) OFX_EXCEPTION_SPEC
void setValueAtTime (const OfxTime time, const int &r, const int &g, const int &b, const ofx::attribute::EChange change) OFX_EXCEPTION_SPEC
void setValueAtTime (const OfxTime time, const double &r, const double &g, const double &b, const double &a, const ofx::attribute::EChange change) OFX_EXCEPTION_SPEC
Detailed Description
Definition at line 14 of file ParamRGBA.hpp.
Constructor & Destructor Documentation
tuttle::host::attribute::ParamRGBA::ParamRGBA (INode & effect, const std::string & name, const ofx::attribute::OfxhParamDescriptor & descriptor)
Definition at line 9 of file ParamRGBA.cpp.
References tuttle::host::ofx::attribute::OfxhMultiDimParam< ParamDouble, DIM >::_controls.
Referenced by clone().
Member Function Documentation
ParamRGBA* tuttle::host::attribute::ParamRGBA::clone () const [inline, virtual]
clone this parameter
Implements tuttle::host::ofx::attribute::OfxhParam.
Definition at line 19 of file ParamRGBA.hpp.
References ParamRGBA().
OfxRGBAColourD tuttle::host::attribute::ParamRGBA::getDefault () const
Definition at line 21 of file ParamRGBA.cpp.
References tuttle::host::ofx::attribute::OfxhMultiDimParam< ParamDouble, DIM >::_controls.
void tuttle::host::attribute::ParamRGBA::getValue (double & r, double & g, double & b, double & a) const
Definition at line 32 of file ParamRGBA.cpp.
void tuttle::host::attribute::ParamRGBA::getValueAtTime (const OfxTime time, double & r, double & g, double & b, double & a) const
Definition at line 40 of file ParamRGBA.cpp.
void tuttle::host::attribute::ParamRGBA::setValue (const int & r, const int & g, const int & b, const int & a, const ofx::attribute::EChange change) [inline]
Definition at line 26 of file ParamRGBA.hpp.
void tuttle::host::attribute::ParamRGBA::setValue (const double & r, const double & g, const double & b, const double & a, const ofx::attribute::EChange change)
Definition at line 48 of file ParamRGBA.cpp.
void tuttle::host::attribute::ParamRGBA::setValueAtTime (const OfxTime time, const int & r, const int & g, const int & b, const int & a, const ofx::attribute::EChange change) [inline]
Definition at line 33 of file ParamRGBA.hpp.
Referenced by setValueAtTime().
void tuttle::host::attribute::ParamRGBA::setValueAtTime (const OfxTime time, const double & r, const double & g, const double & b, const ofx::attribute::EChange change) [inline]
Definition at line 37 of file ParamRGBA.hpp.
References setValueAtTime().
void tuttle::host::attribute::ParamRGBA::setValueAtTime (const OfxTime time, const int & r, const int & g, const int & b, const ofx::attribute::EChange change) [inline]
Definition at line 41 of file ParamRGBA.hpp.
References setValueAtTime().
void tuttle::host::attribute::ParamRGBA::setValueAtTime (const OfxTime time, const double & r, const double & g, const double & b, const double & a, const ofx::attribute::EChange change)
Definition at line 57 of file ParamRGBA.cpp.
The documentation for this class was generated from the following files:
TuttleOFX/libraries/tuttle/src/tuttle/host/attribute/ParamRGBA.hpp
TuttleOFX/libraries/tuttle/src/tuttle/host/attribute/ParamRGBA.cpp