TuttleOFX: tuttle::plugin::interact::ParamTangent< TFrame, coord > Class Template Reference
tuttle::plugin::interact::ParamTangent< TFrame, coord > Class Template Reference
#include <ParamTangent.hpp>
Public Types
typedef ParamPoint< TFrame, coord > PPoint
typedef PPoint Parent
Public Member Functions
ParamTangent (const InteractInfos &infos, OFX::Double2DParam *pCenter, OFX::Double2DParam *pTanA, OFX::Double2DParam *pTanB, const TFrame &frame)
virtual ~ParamTangent ()
bool draw (const OFX::DrawArgs &args) const
the function called to draw in the interact
MotionType intersect (const OFX::PenArgs &args)
virtual void translate (const Point2 &previous, const Point2 &vec)
Protected Types
enum ESelectType { eSelectTypeNone, eSelectTypeTanA, eSelectTypeTanB, eSelectTypeCenter }
Protected Attributes
PPoint _paramTanA
PPoint _paramTanB
Point2 _previousTanVec
ESelectType _selectType
Detailed Description
template<class TFrame, ECoordinateSystem coord>
class tuttle::plugin::interact::ParamTangent< TFrame, coord >
Definition at line 20 of file ParamTangent.hpp.
Member Typedef Documentation
template<class TFrame , ECoordinateSystem coord> typedef PPoint tuttle::plugin::interact::ParamTangent< TFrame, coord >::Parent
Definition at line 25 of file ParamTangent.hpp.
template<class TFrame , ECoordinateSystem coord> typedef ParamPoint<TFrame, coord> tuttle::plugin::interact::ParamTangent< TFrame, coord >::PPoint
Definition at line 24 of file ParamTangent.hpp.
Member Enumeration Documentation
template<class TFrame , ECoordinateSystem coord> enum tuttle::plugin::interact::ParamTangent::ESelectType [protected]
Enumerator:
eSelectTypeNone
eSelectTypeTanA
eSelectTypeTanB
eSelectTypeCenter
Definition at line 46 of file ParamTangent.hpp.
Constructor & Destructor Documentation
template<class TFrame , ECoordinateSystem coord> tuttle::plugin::interact::ParamTangent< TFrame, coord >::ParamTangent (const InteractInfos & infos, OFX::Double2DParam * pCenter, OFX::Double2DParam * pTanA, OFX::Double2DParam * pTanB, const TFrame & frame) [inline]
Definition at line 27 of file ParamTangent.hpp.
template<class TFrame , ECoordinateSystem coord> virtual tuttle::plugin::interact::ParamTangent< TFrame, coord >::~ParamTangent () [inline, virtual]
Definition at line 39 of file ParamTangent.hpp.
Member Function Documentation
template<class TFrame , ECoordinateSystem coord> bool tuttle::plugin::interact::ParamTangent< TFrame, coord >::draw (const OFX::DrawArgs & args) const [virtual]
the function called to draw in the interact
Reimplemented from tuttle::plugin::interact::PointInteract.
Definition at line 97 of file ParamTangent.hpp.
template<class TFrame , ECoordinateSystem coord> MotionType tuttle::plugin::interact::ParamTangent< TFrame, coord >::intersect (const OFX::PenArgs & args) [virtual]
Reimplemented from tuttle::plugin::interact::PointInteract.
Definition at line 115 of file ParamTangent.hpp.
References tuttle::plugin::interact::MotionType::_axis, tuttle::plugin::interact::MotionType::_mode, tuttle::plugin::interact::eAxisNone, tuttle::plugin::interact::eAxisXY, tuttle::plugin::interact::eMotionNone, and tuttle::plugin::interact::eMotionTranslate.
template<class TFrame , ECoordinateSystem coord> virtual void tuttle::plugin::interact::ParamTangent< TFrame, coord >::translate (const Point2 & previous, const Point2 & vec) [inline, virtual]
Reimplemented from tuttle::plugin::interact::InteractObject.
Definition at line 60 of file ParamTangent.hpp.
References tuttle::plugin::interact::ParamTangent< TFrame, coord >::_paramTanA, tuttle::plugin::interact::ParamTangent< TFrame, coord >::_paramTanB, tuttle::plugin::interact::ParamTangent< TFrame, coord >::_previousTanVec, tuttle::plugin::interact::ParamTangent< TFrame, coord >::_selectType, tuttle::plugin::interact::ParamTangent< TFrame, coord >::eSelectTypeCenter, tuttle::plugin::interact::ParamTangent< TFrame, coord >::eSelectTypeNone, tuttle::plugin::interact::ParamTangent< TFrame, coord >::eSelectTypeTanA, tuttle::plugin::interact::ParamTangent< TFrame, coord >::eSelectTypeTanB, tuttle::plugin::interact::ParamPoint< TFrame, coord >::getPoint(), tuttle::plugin::interact::PointInteract::getPosition(), and tuttle::plugin::interact::PointInteract::setPosition().
Field Documentation
template<class TFrame , ECoordinateSystem coord> PPoint tuttle::plugin::interact::ParamTangent< TFrame, coord >::_paramTanA [protected]
Definition at line 42 of file ParamTangent.hpp.
Referenced by tuttle::plugin::interact::ParamTangent< TFrame, coord >::translate().
template<class TFrame , ECoordinateSystem coord> PPoint tuttle::plugin::interact::ParamTangent< TFrame, coord >::_paramTanB [protected]
Definition at line 43 of file ParamTangent.hpp.
Referenced by tuttle::plugin::interact::ParamTangent< TFrame, coord >::translate().
template<class TFrame , ECoordinateSystem coord> Point2 tuttle::plugin::interact::ParamTangent< TFrame, coord >::_previousTanVec [protected]
Definition at line 44 of file ParamTangent.hpp.
Referenced by tuttle::plugin::interact::ParamTangent< TFrame, coord >::translate().
template<class TFrame , ECoordinateSystem coord> ESelectType tuttle::plugin::interact::ParamTangent< TFrame, coord >::_selectType [protected]
Definition at line 53 of file ParamTangent.hpp.
Referenced by tuttle::plugin::interact::ParamTangent< TFrame, coord >::translate().
The documentation for this class was generated from the following file:
TuttleOFX/libraries/tuttle/src/tuttle/plugin/interact/ParamTangent.hpp