TuttleOFX: tuttle::host::attribute::ParamInteger Class Reference
tuttle::host::attribute::ParamInteger Class Reference
#include <ParamInteger.hpp>
Public Member Functions
ParamInteger (INode &effect, const std::string &name, const ofx::attribute::OfxhParamDescriptor &descriptor, const std::size_t index=0)
int getDefault () const
Detailed Description
Definition at line 11 of file ParamInteger.hpp.
Constructor & Destructor Documentation
tuttle::host::attribute::ParamInteger::ParamInteger (INode & effect, const std::string & name, const ofx::attribute::OfxhParamDescriptor & descriptor, const std::size_t index = 0)
Definition at line 9 of file ParamInteger.cpp.
References tuttle::host::attribute::AnimatedParam< T, OFX_PARAM >::_value, and getDefault().
Member Function Documentation
int tuttle::host::attribute::ParamInteger::getDefault () const
Definition at line 18 of file ParamInteger.cpp.
References _index, and tuttle::host::ofx::attribute::OfxhAttributeAccessor::getProperties().
Referenced by ParamInteger().
The documentation for this class was generated from the following files:
TuttleOFX/libraries/tuttle/src/tuttle/host/attribute/ParamInteger.hpp
TuttleOFX/libraries/tuttle/src/tuttle/host/attribute/ParamInteger.cpp