TuttleOFX: tuttle::plugin::ImageGilProcessor< View > Class Template Reference
tuttle::plugin::ImageGilProcessor< View > Class Template Reference
Base class that can be used to process images of any type using boost::gil library view to access images.
#include <ImageGilProcessor.hpp>
Public Types
typedef View::value_type Pixel
typedef terry::image_from_view
< View >::type Image
Public Member Functions
ImageGilProcessor (OFX::ImageEffect &effect, const EImageOrientation imageOrientation)
virtual ~ImageGilProcessor ()
virtual void setup (const OFX::RenderArguments &args)
View getView (OFX::Image *img, const OfxRectI &pixelRod) const
Return a full gil view of an image.
template<typename CustomView >
CustomView getCustomView (OFX::Image *img, const OfxRectI &pixelRod) const
Protected Attributes
View _dstView
image to process into
Detailed Description
template<class View>
class tuttle::plugin::ImageGilProcessor< View >
Base class that can be used to process images of any type using boost::gil library view to access images.
Definition at line 16 of file ImageGilProcessor.hpp.
Member Typedef Documentation
template<class View> typedef terry::image_from_view<View>::type tuttle::plugin::ImageGilProcessor< View >::Image
Definition at line 20 of file ImageGilProcessor.hpp.
template<class View> typedef View::value_type tuttle::plugin::ImageGilProcessor< View >::Pixel
Definition at line 19 of file ImageGilProcessor.hpp.
Constructor & Destructor Documentation
template<class View> tuttle::plugin::ImageGilProcessor< View >::ImageGilProcessor (OFX::ImageEffect & effect, const EImageOrientation imageOrientation) [inline]
Definition at line 26 of file ImageGilProcessor.hpp.
template<class View> virtual tuttle::plugin::ImageGilProcessor< View >::~ImageGilProcessor () [inline, virtual]
Definition at line 29 of file ImageGilProcessor.hpp.
Member Function Documentation
template<class View> template<typename CustomView > CustomView tuttle::plugin::ImageGilProcessor< View >::getCustomView (OFX::Image * img, const OfxRectI & pixelRod) const [inline]
Definition at line 54 of file ImageGilProcessor.hpp.
template<class View> View tuttle::plugin::ImageGilProcessor< View >::getView (OFX::Image * img, const OfxRectI & pixelRod) const [inline]
Return a full gil view of an image.
Definition at line 49 of file ImageGilProcessor.hpp.
Referenced by tuttle::plugin::ImageGilProcessor< DView >::setup().
template<class View> virtual void tuttle::plugin::ImageGilProcessor< View >::setup (const OFX::RenderArguments & args) [inline, virtual]
Reimplemented from tuttle::plugin::ImageProcessor.
Reimplemented in tuttle::plugin::ImageGilFilterProcessor< SView, DView >.
Definition at line 31 of file ImageGilProcessor.hpp.
Referenced by tuttle::plugin::ImageGilFilterProcessor< SView, DView >::setup(), and tuttle::plugin::ImageGilProcessor< DView >::setup().
Field Documentation
template<class View> View tuttle::plugin::ImageGilProcessor< View >::_dstView [protected]
image to process into
Definition at line 23 of file ImageGilProcessor.hpp.
Referenced by tuttle::plugin::ImageGilProcessor< DView >::setup().
The documentation for this class was generated from the following file:
TuttleOFX/libraries/tuttle/src/tuttle/plugin/ImageGilProcessor.hpp