TuttleOFX: tuttle::plugin::interact::IsActiveFunctor Struct Reference
tuttle::plugin::interact::IsActiveFunctor Struct Reference
#include <IsActiveFunctor.hpp>
Public Types
typedef IsActiveFunctor This
Public Member Functions
virtual ~IsActiveFunctor ()=0
virtual bool active () const =0
virtual This * clone () const =0
Detailed Description
Definition at line 15 of file IsActiveFunctor.hpp.
Member Typedef Documentation
typedef IsActiveFunctor tuttle::plugin::interact::IsActiveFunctor::This
Reimplemented in tuttle::plugin::interact::OrActiveFunctor< negate >, tuttle::plugin::interact::AndActiveFunctor< negate >, tuttle::plugin::interact::IsActiveChoiceParamFunctor< negate >, tuttle::plugin::interact::IsActiveBooleanParamFunctor< negate >, tuttle::plugin::interact::IsNotSecretParamFunctor< negate >, tuttle::plugin::interact::IsEnableParamFunctor< negate >, and tuttle::plugin::interact::AlwaysActiveFunctor< negate >.
Definition at line 17 of file IsActiveFunctor.hpp.
Constructor & Destructor Documentation
tuttle::plugin::interact::IsActiveFunctor::~IsActiveFunctor () [pure virtual]
Definition at line 7 of file IsActiveFunctor.cpp.
Member Function Documentation
virtual bool tuttle::plugin::interact::IsActiveFunctor::active () const [pure virtual]
Implemented in tuttle::plugin::interact::OrActiveFunctor< negate >, tuttle::plugin::interact::AndActiveFunctor< negate >, tuttle::plugin::interact::IsActiveChoiceParamFunctor< negate >, tuttle::plugin::interact::IsActiveBooleanParamFunctor< negate >, tuttle::plugin::interact::IsNotSecretParamFunctor< negate >, tuttle::plugin::interact::IsEnableParamFunctor< negate >, and tuttle::plugin::interact::AlwaysActiveFunctor< negate >.
Referenced by tuttle::plugin::interact::AndActiveFunctor< negate >::active(), and tuttle::plugin::interact::OrActiveFunctor< negate >::active().
virtual This* tuttle::plugin::interact::IsActiveFunctor::clone () const [pure virtual]
Implemented in tuttle::plugin::interact::OrActiveFunctor< negate >, tuttle::plugin::interact::AndActiveFunctor< negate >, tuttle::plugin::interact::IsActiveChoiceParamFunctor< negate >, tuttle::plugin::interact::IsActiveBooleanParamFunctor< negate >, tuttle::plugin::interact::IsNotSecretParamFunctor< negate >, tuttle::plugin::interact::IsEnableParamFunctor< negate >, and tuttle::plugin::interact::AlwaysActiveFunctor< negate >.
Referenced by tuttle::plugin::interact::new_clone().
The documentation for this struct was generated from the following files:
TuttleOFX/libraries/tuttle/src/tuttle/plugin/interact/IsActiveFunctor.hpp
TuttleOFX/libraries/tuttle/src/tuttle/plugin/interact/IsActiveFunctor.cpp