TuttleOFX: tuttle::host::ofx Namespace Reference
tuttle::host::ofx Namespace Reference
OpenFX wrapping to communicate with C API.
Namespaces
namespace APICache
namespace attribute
namespace imageEffect
namespace interact
namespace property
Data Structures
class OfxhBinary
class representing a DLL/Shared Object/etc
class OfxhException
class OfxhHost
class OfxhIObject
All openfx objects that can be send to the plugin need to inherit this class. So all these objects can be seen as OfxhIObject (reinterpret_cast) and then properly dynamic_cast to the desired class.
class OfxhMajorPlugin
class OfxhMemory
class OfxhIMessage
class OfxhPlugin
class OfxhPluginBinary
struct PluginCacheSupportedApi
class OfxhPluginCache
struct OfxhPluginIdent
class OfxhPluginDesc
class OfxhPluginLoadGuard
class OfxhIProgress
class OfxhITimeline
Typedefs
typedef int(* OfxGetNumberOfPluginsType)(void)
typedef OfxPlugin *(* OfxGetPluginType)(int)
Functions
static void * fetchSuite (OfxPropertySetHandle hostProps, const char *suiteName, int suiteVersion)
void * getMemorySuite (const int version)
void * getMessageSuite (const int version)
void * getMultithreadSuite (const int version)
std::string OFXGetEnv (const char *e)
std::ostream & operator<< (std::ostream &os, const OfxhPluginCache &v)
void * getProgressSuite (const int version)
void * getTimelineSuite (const int version)
Variables
static property::OfxhPropSpec hostStuffs []
Detailed Description
OpenFX wrapping to communicate with C API.
Typedef Documentation
typedef int(* tuttle::host::ofx::OfxGetNumberOfPluginsType)(void)
Definition at line 10 of file OfxhPluginBinary.cpp.
typedef OfxPlugin *(* tuttle::host::ofx::OfxGetPluginType)(int)
Definition at line 11 of file OfxhPluginBinary.cpp.
Function Documentation
static void* tuttle::host::ofx::fetchSuite (OfxPropertySetHandle hostProps, const char * suiteName, int suiteVersion) [static]
Definition at line 61 of file OfxhHost.cpp.
References tuttle::host::ofx::OfxhHost::fetchSuite(), tuttle::host::ofx::property::OfxhSet::getPointerProperty(), and kOfxHostSupportHostPointer.
void * tuttle::host::ofx::getMemorySuite (const int version)
Definition at line 39 of file OfxhMemorySuite.cpp.
Referenced by tuttle::host::ofx::OfxhHost::fetchSuite().
void * tuttle::host::ofx::getMessageSuite (const int version)
Definition at line 43 of file OfxhMessageSuite.cpp.
Referenced by tuttle::host::ofx::imageEffect::OfxhImageEffectHost::fetchSuite().
void * tuttle::host::ofx::getMultithreadSuite (const int version)
Definition at line 144 of file OfxhMultiThreadSuite.cpp.
Referenced by tuttle::host::ofx::imageEffect::OfxhImageEffectHost::fetchSuite().
void * tuttle::host::ofx::getProgressSuite (const int version)
Definition at line 98 of file OfxhProgressSuite.cpp.
Referenced by tuttle::host::ofx::imageEffect::OfxhImageEffectHost::fetchSuite().
void * tuttle::host::ofx::getTimelineSuite (const int version)
Definition at line 99 of file OfxhTimelineSuite.cpp.
Referenced by tuttle::host::ofx::imageEffect::OfxhImageEffectHost::fetchSuite().
std::string tuttle::host::ofx::OFXGetEnv (const char * e)
Definition at line 140 of file OfxhPluginCache.cpp.
Referenced by tuttle::host::ofx::OfxhPluginCache::OfxhPluginCache().
std::ostream& tuttle::host::ofx::operator<< (std::ostream & os, const OfxhPluginCache & v)
Definition at line 537 of file OfxhPluginCache.cpp.
References tuttle::host::ofx::OfxhPluginCache::_pluginsByID.
Variable Documentation
property::OfxhPropSpec tuttle::host::ofx::hostStuffs[] [static]
Initial value:
 {
        { kOfxPropType, property::ePropTypeString, 1, false, "Host" },
        { kOfxPropName, property::ePropTypeString, 1, false, "UNKNOWN" },
        { kOfxPropLabel, property::ePropTypeString, 1, false, "UNKNOWN" },
        { kOfxHostSupportHostPointer,    property::ePropTypePointer,    0,    false,    NULL },
        { 0 },
}
Definition at line 53 of file OfxhHost.cpp.