TuttleOFX: tuttle::ofx::imageEffect Namespace Reference
tuttle::ofx::imageEffect Namespace Reference
Enumerations
enum EContext {
eContextNone, eContextGenerator, eContextFilter, eContextTransition,
eContextPaint, eContextGeneral, eContextRetimer, eContextReader,
eContextWriter
}
Enumerates the contexts a plugin can be used in.
enum EBitDepth {
eBitDepthNone = -1, eBitDepthCustom = 0, eBitDepthUByte = 1, eBitDepthUShort = 2,
eBitDepthFloat = 4
}
Enumerates the pixel depths supported.
enum EPixelComponent {
ePixelComponentNone, ePixelComponentRGBA, ePixelComponentRGB, ePixelComponentAlpha,
ePixelComponentCustom
}
Enumerates the component types supported.
Functions
EContext mapContextStringToEnum (const std::string &s)
map a std::string to a context
const std::string mapContextEnumToString (const EContext s)
map a std::string to a context
EBitDepth mapBitDepthStringToEnum (const std::string &str)
map a std::string to a context
const std::string mapBitDepthEnumToString (const EBitDepth e)
EPixelComponent mapPixelComponentStringToEnum (const std::string &str)
turns a pixel component string into and enum
std::string mapPixelComponentEnumToString (const EPixelComponent e)
std::string findDeepestBitDepth (const std::string &s1, const std::string &s2)
turns a premultiplication string into and enum
std::size_t bitDepthMemorySize (const EBitDepth e)
std::size_t numberOfComponents (const EPixelComponent c)
Enumeration Type Documentation
enum tuttle::ofx::imageEffect::EBitDepth
Enumerates the pixel depths supported.
Enumerator:
eBitDepthNone
bit depth that indicates no data is present
eBitDepthCustom
some non standard bit depth
eBitDepthUByte
eBitDepthUShort
eBitDepthFloat
Definition at line 31 of file imageEffect.hpp.
enum tuttle::ofx::imageEffect::EContext
Enumerates the contexts a plugin can be used in.
Enumerator:
eContextNone
eContextGenerator
eContextFilter
eContextTransition
eContextPaint
eContextGeneral
eContextRetimer
eContextReader
eContextWriter
Definition at line 15 of file imageEffect.hpp.
enum tuttle::ofx::imageEffect::EPixelComponent
Enumerates the component types supported.
Enumerator:
ePixelComponentNone
ePixelComponentRGBA
ePixelComponentRGB
ePixelComponentAlpha
ePixelComponentCustom
some non standard pixel type
Definition at line 62 of file imageEffect.hpp.
Function Documentation
std::size_t tuttle::ofx::imageEffect::bitDepthMemorySize (const EBitDepth e) [inline]
Definition at line 43 of file imageEffect.hpp.
References eBitDepthCustom, eBitDepthFloat, eBitDepthNone, eBitDepthUByte, and eBitDepthUShort.
Referenced by tuttle::host::ofx::attribute::OfxhClipImage::getBitDepthMemorySize(), and tuttle::host::ofx::imageEffect::OfxhImage::getBitDepthMemorySize().
std::string tuttle::ofx::imageEffect::findDeepestBitDepth (const std::string & s1, const std::string & s2)
turns a premultiplication string into and enum
get me deepest bit depth
turns a field string into and enum get me deepest bit depth
Definition at line 298 of file imageEffect.cpp.
References tuttle::quotes().
Referenced by tuttle::host::ImageEffectNode::maximizeBitDepthFromReadsToWrites(), and tuttle::host::ofx::imageEffect::OfxhImageEffectNode::setDefaultClipPreferences().
const std::string tuttle::ofx::imageEffect::mapBitDepthEnumToString (const EBitDepth e)
Definition at line 155 of file imageEffect.cpp.
References eBitDepthCustom, eBitDepthFloat, eBitDepthNone, eBitDepthUByte, and eBitDepthUShort.
Referenced by tuttle::plugin::doGilRender(), tuttle::plugin::doGilRender2(), and tuttle::host::ofx::attribute::OfxhClipImage::setBitDepth().
EBitDepth tuttle::ofx::imageEffect::mapBitDepthStringToEnum (const std::string & str)
map a std::string to a context
turns a bit depth string into and enum
Definition at line 131 of file imageEffect.cpp.
References eBitDepthCustom, eBitDepthFloat, eBitDepthNone, eBitDepthUByte, and eBitDepthUShort.
Referenced by tuttle::host::ofx::attribute::OfxhClipImage::getBitDepth(), tuttle::host::ofx::attribute::OfxhClipImage::setBitDepthStringIfUpper(), and tuttle::host::ofx::attribute::OfxhClipImage::setBitDepthStringIfUpperAndNotModifiedByPlugin().
const std::string tuttle::ofx::imageEffect::mapContextEnumToString (const EContext s)
map a std::string to a context
Definition at line 38 of file imageEffect.cpp.
References eContextFilter, eContextGeneral, eContextGenerator, eContextNone, eContextPaint, eContextReader, eContextRetimer, eContextTransition, and eContextWriter.
EContext tuttle::ofx::imageEffect::mapContextStringToEnum (const std::string & s)
map a std::string to a context
Definition at line 14 of file imageEffect.cpp.
References eContextFilter, eContextGeneral, eContextGenerator, eContextPaint, eContextReader, eContextRetimer, eContextTransition, and eContextWriter.
std::string tuttle::ofx::imageEffect::mapPixelComponentEnumToString (const EPixelComponent e)
Definition at line 200 of file imageEffect.cpp.
References ePixelComponentAlpha, ePixelComponentCustom, ePixelComponentNone, ePixelComponentRGB, and ePixelComponentRGBA.
Referenced by tuttle::plugin::doGilRender(), tuttle::plugin::doGilRender2(), and tuttle::host::ofx::attribute::OfxhClipImage::setComponents().
EPixelComponent tuttle::ofx::imageEffect::mapPixelComponentStringToEnum (const std::string & str)
turns a pixel component string into and enum
Definition at line 176 of file imageEffect.cpp.
References ePixelComponentAlpha, ePixelComponentCustom, ePixelComponentNone, ePixelComponentRGB, and ePixelComponentRGBA.
Referenced by tuttle::host::ofx::attribute::OfxhClipImage::getComponents().
std::size_t tuttle::ofx::imageEffect::numberOfComponents (const EPixelComponent c) [inline]
Definition at line 74 of file imageEffect.hpp.
References ePixelComponentAlpha, ePixelComponentCustom, ePixelComponentNone, ePixelComponentRGB, and ePixelComponentRGBA.
Referenced by tuttle::host::attribute::Image::getNbComponents(), and tuttle::host::ofx::attribute::OfxhClipImage::getNbComponents().