TuttleOFX: tuttle::host::ofx::attribute::OfxhClipImageSet Class Reference
tuttle::host::ofx::attribute::OfxhClipImageSet Class Reference
#include <OfxhClipImageSet.hpp>
Public Types
typedef OfxhClipImageSet This
typedef std::map< std::string,
OfxhClipImage * > ClipImageMap
typedef boost::ptr_vector
< OfxhClipImage > ClipImageVector
Public Member Functions
OfxhClipImageSet ()
OfxhClipImageSet (const OfxhClipImageSet &other)
virtual ~OfxhClipImageSet ()=0
bool operator== (const This &other) const
bool operator!= (const This &other) const
void copyClipsValues (const OfxhClipImageSet &other)
void populateClips (const imageEffect::OfxhImageEffectNodeDescriptor &descriptor) OFX_EXCEPTION_SPEC
const ClipImageMap & getClipsByName () const
ClipImageMap & getClipsByName ()
const ClipImageVector & getClipsByOrder () const
ClipImageVector & getClipsByOrder ()
OfxhClipImage & getClip (const std::string &name, const bool acceptPartialName=false)
const OfxhClipImage & getClip (const std::string &name, const bool acceptPartialName=false) const
const OfxhClipImage * getClipPtr (const std::string &name, const bool acceptPartialName=false) const
OfxhClipImage * getClipPtr (const std::string &name, const bool acceptPartialName=false)
void addClip (const std::string &name, OfxhClipImage *instance) OFX_EXCEPTION_SPEC
virtual OfxhClipImage * newClipImage (const OfxhClipImageDescriptor &descriptor)=0
OfxhClipImage & getNthClip (int index)
int getNbClips () const
bool areClipPrefsDirty () const
Protected Attributes
ClipImageVector _clipsByOrder
clips list (data owner)
ClipImageMap _clipImages
clips by name (link to datas)
bool _clipPrefsDirty
do we need to re-run the clip prefs action
Private Member Functions
void initMapFromList ()
Detailed Description
Definition at line 20 of file OfxhClipImageSet.hpp.
Member Typedef Documentation
typedef std::map<std::string, OfxhClipImage*> tuttle::host::ofx::attribute::OfxhClipImageSet::ClipImageMap
Definition at line 26 of file OfxhClipImageSet.hpp.
typedef boost::ptr_vector<OfxhClipImage> tuttle::host::ofx::attribute::OfxhClipImageSet::ClipImageVector
Definition at line 27 of file OfxhClipImageSet.hpp.
typedef OfxhClipImageSet tuttle::host::ofx::attribute::OfxhClipImageSet::This
Reimplemented in tuttle::host::ofx::imageEffect::OfxhImageEffectNode, and tuttle::host::ImageEffectNode.
Definition at line 25 of file OfxhClipImageSet.hpp.
Constructor & Destructor Documentation
tuttle::host::ofx::attribute::OfxhClipImageSet::OfxhClipImageSet () [explicit]
The propery set being passed in belongs to the owning plugin instance.
Definition at line 13 of file OfxhClipImageSet.cpp.
tuttle::host::ofx::attribute::OfxhClipImageSet::OfxhClipImageSet (const OfxhClipImageSet & other) [explicit]
Definition at line 17 of file OfxhClipImageSet.cpp.
References initMapFromList().
tuttle::host::ofx::attribute::OfxhClipImageSet::~OfxhClipImageSet () [pure virtual]
Definition at line 34 of file OfxhClipImageSet.cpp.
Member Function Documentation
void tuttle::host::ofx::attribute::OfxhClipImageSet::addClip (const std::string & name, OfxhClipImage * instance) [inline]
add a clip
Definition at line 89 of file OfxhClipImageSet.hpp.
References _clipImages, and _clipsByOrder.
bool tuttle::host::ofx::attribute::OfxhClipImageSet::areClipPrefsDirty () const [inline]
are the clip preferences currently dirty
Definition at line 124 of file OfxhClipImageSet.hpp.
References _clipPrefsDirty.
Referenced by tuttle::host::ofx::imageEffect::OfxhImageEffectNode::runGetClipPrefsConditionally().
void tuttle::host::ofx::attribute::OfxhClipImageSet::copyClipsValues (const OfxhClipImageSet & other)
Definition at line 42 of file OfxhClipImageSet.cpp.
References _clipsByOrder, tuttle::host::ofx::attribute::OfxhAttribute::copyValues(), and tuttle::host::ofx::attribute::OfxhAttributeAccessor::getName().
Referenced by tuttle::host::ofx::imageEffect::OfxhImageEffectNode::copyAttributesValues().
OfxhClipImage & tuttle::host::ofx::attribute::OfxhClipImageSet::getClip (const std::string & name, const bool acceptPartialName = false)
get the clip
Reimplemented in tuttle::host::ImageEffectNode.
Definition at line 88 of file OfxhClipImageSet.cpp.
References _clipImages.
Referenced by tuttle::host::ofx::imageEffect::OfxhImageEffectNode::calcDefaultRegionOfDefinition(), getClip(), getClipPtr(), and tuttle::host::ofx::imageEffect::OfxhImageEffectNode::getOutputOfxhClip().
const OfxhClipImage& tuttle::host::ofx::attribute::OfxhClipImageSet::getClip (const std::string & name, const bool acceptPartialName = false) const [inline]
Reimplemented in tuttle::host::ImageEffectNode.
Definition at line 75 of file OfxhClipImageSet.hpp.
References getClip().
const OfxhClipImage * tuttle::host::ofx::attribute::OfxhClipImageSet::getClipPtr (const std::string & name, const bool acceptPartialName = false) const
Definition at line 142 of file OfxhClipImageSet.cpp.
References getClip().
OfxhClipImage * tuttle::host::ofx::attribute::OfxhClipImageSet::getClipPtr (const std::string & name, const bool acceptPartialName = false)
Definition at line 130 of file OfxhClipImageSet.cpp.
References getClip().
const ClipImageMap& tuttle::host::ofx::attribute::OfxhClipImageSet::getClipsByName () const [inline]
Definition at line 50 of file OfxhClipImageSet.hpp.
References _clipImages.
Referenced by tuttle::host::ImageEffectNode::getSingleInputAttribute().
ClipImageMap& tuttle::host::ofx::attribute::OfxhClipImageSet::getClipsByName () [inline]
Definition at line 55 of file OfxhClipImageSet.hpp.
References _clipImages.
const ClipImageVector& tuttle::host::ofx::attribute::OfxhClipImageSet::getClipsByOrder () const [inline]
Definition at line 60 of file OfxhClipImageSet.hpp.
References _clipsByOrder.
Referenced by tuttle::host::ImageEffectNode::getSingleInputAttribute().
ClipImageVector& tuttle::host::ofx::attribute::OfxhClipImageSet::getClipsByOrder () [inline]
Definition at line 65 of file OfxhClipImageSet.hpp.
References _clipsByOrder.
int tuttle::host::ofx::attribute::OfxhClipImageSet::getNbClips () const [inline]
get the number of clips
Definition at line 116 of file OfxhClipImageSet.hpp.
References _clipImages.
Referenced by tuttle::host::ImageEffectNode::initInputClipsPixelAspectRatio().
OfxhClipImage& tuttle::host::ofx::attribute::OfxhClipImageSet::getNthClip (int index) [inline]
get the nth clip, in order of declaration
Definition at line 108 of file OfxhClipImageSet.hpp.
References _clipsByOrder.
void tuttle::host::ofx::attribute::OfxhClipImageSet::initMapFromList () [private]
Definition at line 24 of file OfxhClipImageSet.cpp.
References _clipImages, and _clipsByOrder.
Referenced by OfxhClipImageSet().
virtual OfxhClipImage* tuttle::host::ofx::attribute::OfxhClipImageSet::newClipImage (const OfxhClipImageDescriptor & descriptor) [pure virtual]
make a clip instance
Client host code needs to implement this
Implemented in tuttle::host::ImageEffectNode.
bool tuttle::host::ofx::attribute::OfxhClipImageSet::operator!= (const This & other) const [inline]
Reimplemented in tuttle::host::ofx::imageEffect::OfxhImageEffectNode.
Definition at line 44 of file OfxhClipImageSet.hpp.
References operator==().
bool tuttle::host::ofx::attribute::OfxhClipImageSet::operator== (const This & other) const
Reimplemented in tuttle::host::ofx::imageEffect::OfxhImageEffectNode.
Definition at line 37 of file OfxhClipImageSet.cpp.
References _clipsByOrder.
Referenced by operator!=().
void tuttle::host::ofx::attribute::OfxhClipImageSet::populateClips (const imageEffect::OfxhImageEffectNodeDescriptor & descriptor)
Todo:
tuttle don't manipulate clip here, delegate to ClipInstanceSet
Definition at line 66 of file OfxhClipImageSet.cpp.
Referenced by tuttle::host::ofx::imageEffect::OfxhImageEffectNode::populate().
Field Documentation
ClipImageMap tuttle::host::ofx::attribute::OfxhClipImageSet::_clipImages [protected]
clips by name (link to datas)
Definition at line 31 of file OfxhClipImageSet.hpp.
Referenced by addClip(), tuttle::host::ofx::imageEffect::OfxhImageEffectNode::calcDefaultRegionOfDefinition(), tuttle::host::ofx::imageEffect::OfxhImageEffectNode::checkClipConnectionStatus(), tuttle::host::ImageEffectNode::checkClipsConnected(), tuttle::host::ImageEffectNode::computeTimeDomain(), tuttle::host::ImageEffectNode::coutBitDepthConnections(), tuttle::host::ImageEffectNode::debugOutputImage(), getClip(), getClipsByName(), tuttle::host::ImageEffectNode::getDefaultTimeDomain(), getNbClips(), tuttle::host::ImageEffectNode::initComponents(), tuttle::host::ImageEffectNode::initInputClipsFps(), tuttle::host::ImageEffectNode::initInputClipsPixelAspectRatio(), initMapFromList(), tuttle::host::ofx::imageEffect::OfxhImageEffectNode::isLeafNode(), tuttle::host::ImageEffectNode::maximizeBitDepthFromReadsToWrites(), tuttle::host::ImageEffectNode::maximizeBitDepthFromWritesToReads(), tuttle::host::ImageEffectNode::print(), tuttle::host::ImageEffectNode::process(), tuttle::host::ofx::imageEffect::OfxhImageEffectNode::setDefaultClipPreferences(), tuttle::host::ofx::imageEffect::OfxhImageEffectNode::setupClipInstancePreferences(), tuttle::host::ofx::imageEffect::OfxhImageEffectNode::setupClipPreferencesArgs(), and tuttle::host::ImageEffectNode::validInputClipsConnections().
bool tuttle::host::ofx::attribute::OfxhClipImageSet::_clipPrefsDirty [protected]
do we need to re-run the clip prefs action
Definition at line 32 of file OfxhClipImageSet.hpp.
Referenced by areClipPrefsDirty(), and tuttle::host::ofx::imageEffect::OfxhImageEffectNode::getClipPreferencesAction().
ClipImageVector tuttle::host::ofx::attribute::OfxhClipImageSet::_clipsByOrder [protected]
clips list (data owner)
Definition at line 30 of file OfxhClipImageSet.hpp.
Referenced by addClip(), copyClipsValues(), getClipsByOrder(), tuttle::host::ofx::imageEffect::OfxhImageEffectNode::getFramesNeeded(), getNthClip(), initMapFromList(), and operator==().
The documentation for this class was generated from the following files:
TuttleOFX/libraries/tuttle/src/tuttle/host/ofx/attribute/OfxhClipImageSet.hpp
TuttleOFX/libraries/tuttle/src/tuttle/host/ofx/attribute/OfxhClipImageSet.cpp