TuttleOFX: tuttle::host::Core Class Reference
tuttle::host::Core Class Reference
#include <Core.hpp>
Public Types
typedef Core This
Public Member Functions
ofx::OfxhPluginCache & getPluginCache ()
const ofx::OfxhPluginCache & getPluginCache () const
const std::list
< ofx::OfxhPlugin * > & getPlugins () const
const Host & getHost () const
tuttle::common::Formatter & getFormatter ()
Preferences & getPreferences ()
const Preferences & getPreferences () const
const
ofx::imageEffect::OfxhImageEffectPluginCache & getImageEffectPluginCache () const
memory::IMemoryPool & getMemoryPool ()
const memory::IMemoryPool & getMemoryPool () const
memory::IMemoryCache & getMemoryCache ()
const memory::IMemoryCache & getMemoryCache () const
ofx::imageEffect::OfxhImageEffectPlugin * getImageEffectPluginById (const std::string &id, int vermaj=-1, int vermin=-1)
void preload (const bool useCache=true)
const ofx::OfxhPlugin & operator[] (const std::string &name) const
Private Member Functions
Core ()
~Core ()
Private Attributes
Host _host
ofx::imageEffect::OfxhImageEffectPluginCache _imageEffectPluginCache
ofx::OfxhPluginCache _pluginCache
memory::IMemoryPool & _memoryPool
memory::IMemoryCache & _memoryCache
bool _isPreloaded
boost::shared_ptr
< tuttle::common::Formatter > _formatter
Preferences _preferences
Friends
class Singleton< Core >
std::ostream & operator<< (std::ostream &os, const This &v)
Detailed Description
Definition at line 21 of file Core.hpp.
Member Typedef Documentation
typedef Core tuttle::host::Core::This
Definition at line 24 of file Core.hpp.
Constructor & Destructor Documentation
tuttle::host::Core::Core () [private]
Definition at line 44 of file Core.cpp.
References _imageEffectPluginCache, _memoryPool, _pluginCache, tuttle::host::ofx::OfxhPluginCache::registerAPICache(), tuttle::host::ofx::OfxhPluginCache::setCacheVersion(), and tuttle::host::memory::IMemoryPool::updateMemoryAuthorizedWithRAM().
tuttle::host::Core::~Core () [private]
Definition at line 63 of file Core.cpp.
Member Function Documentation
tuttle::common::Formatter& tuttle::host::Core::getFormatter () [inline]
Definition at line 50 of file Core.hpp.
References _formatter.
const Host& tuttle::host::Core::getHost () const [inline]
Definition at line 48 of file Core.hpp.
References _host.
Referenced by tuttle::host::ofx::imageEffect::OfxhImageEffectNode::canCurrentlyHandleMultipleClipDepths(), tuttle::host::ofx::imageEffect::OfxhImageEffectPlugin::createInstance(), tuttle::host::ofx::imageEffect::OfxhImageEffectNodeDescriptor::OfxhImageEffectNodeDescriptor(), and tuttle::host::ofx::imageEffect::OfxhImageEffectPluginCache::pluginSupported().
ofx::imageEffect::OfxhImageEffectPlugin* tuttle::host::Core::getImageEffectPluginById (const std::string & id, int vermaj = -1, int vermin = -1) [inline]
Definition at line 64 of file Core.hpp.
References _imageEffectPluginCache, and tuttle::host::ofx::imageEffect::OfxhImageEffectPluginCache::getPluginById().
Referenced by BOOST_AUTO_TEST_CASE(), and tuttle::host::createNode().
const ofx::imageEffect::OfxhImageEffectPluginCache& tuttle::host::Core::getImageEffectPluginCache () const [inline]
Definition at line 56 of file Core.hpp.
References _imageEffectPluginCache.
Referenced by tuttle::host::io::getIOPluginsForExtension(), and tuttle::host::operator<<().
memory::IMemoryCache& tuttle::host::Core::getMemoryCache () [inline]
Definition at line 60 of file Core.hpp.
References _memoryCache.
Referenced by tuttle::host::memory::MemoryPool::allocate(), tuttle::host::Graph::computeGlobalHashAtTime(), tuttle::host::ThreadEnv::runProcessFunc(), and tuttle::host::Graph::setupAtTime().
const memory::IMemoryCache& tuttle::host::Core::getMemoryCache () const [inline]
Definition at line 61 of file Core.hpp.
References _memoryCache.
memory::IMemoryPool& tuttle::host::Core::getMemoryPool () [inline]
Definition at line 58 of file Core.hpp.
References _memoryPool.
const memory::IMemoryPool& tuttle::host::Core::getMemoryPool () const [inline]
Definition at line 59 of file Core.hpp.
References _memoryPool.
ofx::OfxhPluginCache& tuttle::host::Core::getPluginCache () [inline]
Definition at line 43 of file Core.hpp.
References _pluginCache.
Referenced by BOOST_AUTO_TEST_CASE(), getPlugins(), operator[](), and tuttle::host::PreloadPlugins::PreloadPlugins().
const ofx::OfxhPluginCache& tuttle::host::Core::getPluginCache () const [inline]
Definition at line 44 of file Core.hpp.
References _pluginCache.
const std::list<ofx::OfxhPlugin*>& tuttle::host::Core::getPlugins () const [inline]
Definition at line 46 of file Core.hpp.
References getPluginCache(), and tuttle::host::ofx::OfxhPluginCache::getPlugins().
Preferences& tuttle::host::Core::getPreferences () [inline]
Definition at line 52 of file Core.hpp.
References _preferences.
Referenced by BOOST_AUTO_TEST_CASE(), and preload().
const Preferences& tuttle::host::Core::getPreferences () const [inline]
Definition at line 53 of file Core.hpp.
References _preferences.
const ofx::OfxhPlugin& tuttle::host::Core::operator[] (const std::string & name) const [inline]
Definition at line 73 of file Core.hpp.
References tuttle::host::ofx::OfxhPluginCache::getPluginById(), and getPluginCache().
void tuttle::host::Core::preload (const bool useCache = true)
Definition at line 66 of file Core.cpp.
References _isPreloaded, _pluginCache, tuttle::host::ofx::OfxhPluginCache::clearPluginFiles(), getPreferences(), tuttle::host::Preferences::getTuttleHomePath(), tuttle::host::ofx::OfxhPluginCache::isDirty(), tuttle::host::ofx::OfxhPluginCache::scanPluginFiles(), OFX::to_string(), TUTTLE_INFO, TUTTLE_LOG_DEBUG, and TUTTLE_LOG_WARNING.
Referenced by BOOST_AUTO_TEST_CASE(), and tuttle::host::PreloadPlugins::PreloadPlugins().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const This & v) [friend]
Definition at line 149 of file Core.cpp.
friend class Singleton< Core > [friend]
Definition at line 25 of file Core.hpp.
Field Documentation
boost::shared_ptr<tuttle::common::Formatter> tuttle::host::Core::_formatter [private]
Definition at line 38 of file Core.hpp.
Referenced by getFormatter().
Host tuttle::host::Core::_host [private]
Definition at line 32 of file Core.hpp.
Referenced by getHost().
ofx::imageEffect::OfxhImageEffectPluginCache tuttle::host::Core::_imageEffectPluginCache [private]
Definition at line 33 of file Core.hpp.
Referenced by Core(), getImageEffectPluginById(), and getImageEffectPluginCache().
bool tuttle::host::Core::_isPreloaded [private]
Definition at line 37 of file Core.hpp.
Referenced by preload().
memory::IMemoryCache& tuttle::host::Core::_memoryCache [private]
Definition at line 36 of file Core.hpp.
Referenced by getMemoryCache().
memory::IMemoryPool& tuttle::host::Core::_memoryPool [private]
Definition at line 35 of file Core.hpp.
Referenced by Core(), and getMemoryPool().
ofx::OfxhPluginCache tuttle::host::Core::_pluginCache [private]
Definition at line 34 of file Core.hpp.
Referenced by Core(), getPluginCache(), and preload().
Preferences tuttle::host::Core::_preferences [private]
Definition at line 40 of file Core.hpp.
Referenced by getPreferences().
The documentation for this class was generated from the following files:
TuttleOFX/libraries/tuttle/src/tuttle/host/Core.hpp
TuttleOFX/libraries/tuttle/src/tuttle/host/Core.cpp