TuttleOFX: tuttle::plugin::interact::ParamPointRelativePoint< TFrame, coord > Class Template Reference
tuttle::plugin::interact::ParamPointRelativePoint< TFrame, coord > Class Template Reference
#include <ParamPointRelativePoint.hpp>
Public Member Functions
ParamPointRelativePoint (const InteractInfos &infos, OFX::Double2DParam *param, const TFrame &relativeFrame, const PointInteract *relativePoint)
~ParamPointRelativePoint ()
Point2 getPoint () const
void setPoint (const Scalar x, const Scalar y)
Private Attributes
const PointInteract & _relativePoint
Static Private Attributes
static const ECoordinateSystem notCenteredCoord = CoordinateSystemAxisXY<NotCenteredCoodinate<coord>::value>::value
Detailed Description
template<class TFrame, ECoordinateSystem coord>
class tuttle::plugin::interact::ParamPointRelativePoint< TFrame, coord >
Definition at line 15 of file ParamPointRelativePoint.hpp.
Constructor & Destructor Documentation
template<class TFrame , ECoordinateSystem coord> tuttle::plugin::interact::ParamPointRelativePoint< TFrame, coord >::ParamPointRelativePoint (const InteractInfos & infos, OFX::Double2DParam * param, const TFrame & relativeFrame, const PointInteract * relativePoint) [inline]
Definition at line 19 of file ParamPointRelativePoint.hpp.
template<class TFrame , ECoordinateSystem coord> tuttle::plugin::interact::ParamPointRelativePoint< TFrame, coord >::~ParamPointRelativePoint () [inline]
Definition at line 24 of file ParamPointRelativePoint.hpp.
Member Function Documentation
template<class TFrame , ECoordinateSystem coord> Point2 tuttle::plugin::interact::ParamPointRelativePoint< TFrame, coord >::getPoint () const [inline, virtual]
Reimplemented from tuttle::plugin::interact::ParamPoint< TFrame, coord >.
Definition at line 30 of file ParamPointRelativePoint.hpp.
References tuttle::plugin::interact::ParamPoint< TFrame, coord >::_frame, tuttle::plugin::interact::ParamPoint< TFrame, coord >::_param, tuttle::plugin::interact::ParamPointRelativePoint< TFrame, coord >::_relativePoint, tuttle::plugin::interact::PointInteract::getPoint(), tuttle::plugin::interact::PointInteract::getTime(), and tuttle::plugin::ofxToGil().
template<class TFrame , ECoordinateSystem coord> void tuttle::plugin::interact::ParamPointRelativePoint< TFrame, coord >::setPoint (const Scalar x, const Scalar y) [inline, virtual]
Reimplemented from tuttle::plugin::interact::ParamPoint< TFrame, coord >.
Definition at line 42 of file ParamPointRelativePoint.hpp.
References tuttle::plugin::interact::ParamPoint< TFrame, coord >::_frame, tuttle::plugin::interact::ParamPoint< TFrame, coord >::_param, tuttle::plugin::interact::ParamPointRelativePoint< TFrame, coord >::_relativePoint, tuttle::plugin::interact::PointInteract::getPoint(), tuttle::plugin::interact::InteractObject::getSelected(), and tuttle::plugin::interact::PointInteract::getTime().
Field Documentation
template<class TFrame , ECoordinateSystem coord> const PointInteract& tuttle::plugin::interact::ParamPointRelativePoint< TFrame, coord >::_relativePoint [private]
Definition at line 27 of file ParamPointRelativePoint.hpp.
Referenced by tuttle::plugin::interact::ParamPointRelativePoint< TFrame, coord >::getPoint(), and tuttle::plugin::interact::ParamPointRelativePoint< TFrame, coord >::setPoint().
template<class TFrame , ECoordinateSystem coord> const ECoordinateSystem tuttle::plugin::interact::ParamPointRelativePoint< TFrame, coord >::notCenteredCoord = CoordinateSystemAxisXY<NotCenteredCoodinate<coord>::value>::value [static, private]
Definition at line 17 of file ParamPointRelativePoint.hpp.
The documentation for this class was generated from the following file:
TuttleOFX/libraries/tuttle/src/tuttle/plugin/interact/ParamPointRelativePoint.hpp