TuttleOFX: tuttle::host::ofx::imageEffect::OfxhImageEffectNodeBase Class Reference
tuttle::host::ofx::imageEffect::OfxhImageEffectNodeBase Class Reference
#include <OfxhImageEffectNodeBase.hpp>
Public Member Functions
OfxhImageEffectNodeBase (const property::OfxhSet &set)
OfxhImageEffectNodeBase (const property::OfxhPropSpec *propSpec)
virtual ~OfxhImageEffectNodeBase ()
bool operator== (const OfxhImageEffectNodeBase &other) const
bool operator!= (const OfxhImageEffectNodeBase &other) const
virtual bool verifyMagic ()
is my magic number valid?
OfxImageEffectHandle getHandle () const
obtain a handle on this for passing to the C api
const property::OfxhSet & getProperties () const
property::OfxhSet & getEditableProperties ()
const std::string & getShortLabel () const
name of the Node
const std::string & getLabel () const
name of the Node
const std::string & getName () const
name of the Node
void setName (const std::string &name)
name of the Node
const std::string & getLongLabel () const
Description of the Node.
bool isContextSupported (const std::string &s) const
is the given context supported
const std::string & getPluginGrouping () const
what is the name of the group the plug-in belongs to
bool isSingleInstance () const
is the effect single instance
const std::string & getRenderThreadSafety () const
what is the thread safety on this effect
bool getHostFrameThreading () const
OfxPluginEntryPoint * getOverlayInteractMainEntry () const
get the overlay interact main entry if it exists
bool supportsMultiResolution () const
does the effect support images of differing sizes
bool supportsTiles () const
does the effect support tiled rendering
bool temporalAccess () const
does this effect need random temporal access
bool isBitDepthSupported (const std::string &s) const
is the given bit depth supported by the effect
bool fieldRenderTwiceAlways () const
bool supportsMultipleClipDepths () const
does the effect support multiple clip depths
bool supportsMultipleClipPARs () const
does the effect support multiple clip pixel aspect ratios
bool isClipPreferencesSlaveParam (const std::string &s) const
does changing the named param re-tigger a clip preferences action
Protected Attributes
property::OfxhSet _properties
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Friends
class boost::serialization::access
Detailed Description
base class to both effect descriptors and instances
Definition at line 28 of file OfxhImageEffectNodeBase.hpp.
Constructor & Destructor Documentation
tuttle::host::ofx::imageEffect::OfxhImageEffectNodeBase::OfxhImageEffectNodeBase (const property::OfxhSet & set)
Definition at line 11 of file OfxhImageEffectNodeBase.cpp.
tuttle::host::ofx::imageEffect::OfxhImageEffectNodeBase::OfxhImageEffectNodeBase (const property::OfxhPropSpec * propSpec)
Definition at line 15 of file OfxhImageEffectNodeBase.cpp.
tuttle::host::ofx::imageEffect::OfxhImageEffectNodeBase::~OfxhImageEffectNodeBase () [virtual]
Definition at line 19 of file OfxhImageEffectNodeBase.cpp.
Member Function Documentation
bool tuttle::host::ofx::imageEffect::OfxhImageEffectNodeBase::fieldRenderTwiceAlways () const
when field rendering, does the effect need to be called twice to render a frame in all circumstances (with different fields)
when field rendering, does the effect need to be called twice to render a frame in all Base::circumstances (with different fields)
Definition at line 163 of file OfxhImageEffectNodeBase.cpp.
References _properties, and tuttle::host::ofx::property::OfxhSet::getIntProperty().
property::OfxhSet& tuttle::host::ofx::imageEffect::OfxhImageEffectNodeBase::getEditableProperties () [inline]
Reimplemented in tuttle::host::ImageEffectNode.
Definition at line 48 of file OfxhImageEffectNodeBase.hpp.
References _properties.
OfxImageEffectHandle tuttle::host::ofx::imageEffect::OfxhImageEffectNodeBase::getHandle () const
obtain a handle on this for passing to the C api
Definition at line 29 of file OfxhImageEffectNodeBase.cpp.
Referenced by tuttle::host::ofx::imageEffect::OfxhImageEffectNode::beginInstanceEditAction(), tuttle::host::ofx::imageEffect::OfxhImageEffectNode::createInstanceAction(), tuttle::host::ofx::imageEffect::OfxhImageEffectNode::endInstanceEditAction(), tuttle::host::ofx::imageEffect::OfxhImageEffectNode::getClipPreferencesAction(), tuttle::host::ofx::imageEffect::OfxhImageEffectPluginCache::loadFromPlugin(), tuttle::host::ofx::imageEffect::OfxhImageEffectNode::purgeCachesAction(), tuttle::host::ofx::imageEffect::OfxhImageEffectNode::syncPrivateDataAction(), and tuttle::host::ofx::imageEffect::OfxhImageEffectNode::~OfxhImageEffectNode().
bool tuttle::host::ofx::imageEffect::OfxhImageEffectNodeBase::getHostFrameThreading () const
should the host attempt to managed multi-threaded rendering if it can via tiling or some such
Definition at line 120 of file OfxhImageEffectNodeBase.cpp.
References _properties, and tuttle::host::ofx::property::OfxhSet::getIntProperty().
const std::string & tuttle::host::ofx::imageEffect::OfxhImageEffectNodeBase::getLabel () const
name of the Node
name of the imageEffect
Reimplemented in tuttle::host::ImageEffectNode.
Definition at line 51 of file OfxhImageEffectNodeBase.cpp.
References _properties, getName(), and tuttle::host::ofx::property::OfxhSet::getStringProperty().
Referenced by getLongLabel(), and getShortLabel().
const std::string & tuttle::host::ofx::imageEffect::OfxhImageEffectNodeBase::getLongLabel () const
Description of the Node.
Definition at line 74 of file OfxhImageEffectNodeBase.cpp.
References _properties, getLabel(), getName(), and tuttle::host::ofx::property::OfxhSet::getStringProperty().
Referenced by tuttle::host::ImageEffectNode::print().
const std::string & tuttle::host::ofx::imageEffect::OfxhImageEffectNodeBase::getName () const
name of the Node
name of the imageEffect
Reimplemented in tuttle::host::ImageEffectNode.
Definition at line 63 of file OfxhImageEffectNodeBase.cpp.
References _properties, and tuttle::host::ofx::property::OfxhSet::getStringProperty().
Referenced by tuttle::host::ofx::imageEffect::OfxhImageEffectNode::createInstanceAction(), getLabel(), getLongLabel(), and getShortLabel().
OfxPluginEntryPoint * tuttle::host::ofx::imageEffect::OfxhImageEffectNodeBase::getOverlayInteractMainEntry () const
get the overlay interact main entry if it exists
Definition at line 127 of file OfxhImageEffectNodeBase.cpp.
References _properties, and tuttle::host::ofx::property::OfxhSet::getPointerProperty().
Referenced by tuttle::host::ofx::imageEffect::OfxhImageEffectNodeDescriptor::initOverlayDescriptor().
const std::string & tuttle::host::ofx::imageEffect::OfxhImageEffectNodeBase::getPluginGrouping () const
what is the name of the group the plug-in belongs to
Definition at line 98 of file OfxhImageEffectNodeBase.cpp.
References _properties, and tuttle::host::ofx::property::OfxhSet::getStringProperty().
const property::OfxhSet& tuttle::host::ofx::imageEffect::OfxhImageEffectNodeBase::getProperties () const [inline]
Reimplemented in tuttle::host::ImageEffectNode.
Definition at line 47 of file OfxhImageEffectNodeBase.hpp.
References _properties.
Referenced by tuttle::host::ofx::imageEffect::OfxhImageEffectNode::getFramesNeeded(), tuttle::host::io::getIOPluginsForExtension(), tuttle::host::ofx::imageEffect::OfxhImageEffectPluginCache::getPluginByLabel(), tuttle::host::ofx::imageEffect::OfxhImageEffectPlugin::initContexts(), tuttle::host::ofx::imageEffect::OfxhImageEffectNode::isSupportedBitDepth(), tuttle::host::ofx::imageEffect::OfxhImageEffectPluginCache::loadFromPlugin(), and tuttle::host::ofx::imageEffect::OfxhImageEffectNode::OfxhImageEffectNode().
const std::string & tuttle::host::ofx::imageEffect::OfxhImageEffectNodeBase::getRenderThreadSafety () const
what is the thread safety on this effect
Definition at line 112 of file OfxhImageEffectNodeBase.cpp.
References _properties, and tuttle::host::ofx::property::OfxhSet::getStringProperty().
const std::string & tuttle::host::ofx::imageEffect::OfxhImageEffectNodeBase::getShortLabel () const
name of the Node
name of the imageEffect
Definition at line 35 of file OfxhImageEffectNodeBase.cpp.
References _properties, getLabel(), getName(), and tuttle::host::ofx::property::OfxhSet::getStringProperty().
bool tuttle::host::ofx::imageEffect::OfxhImageEffectNodeBase::isBitDepthSupported (const std::string & s) const
is the given bit depth supported by the effect
is the given RGBA/A pixel depth supported by the effect
Definition at line 155 of file OfxhImageEffectNodeBase.cpp.
References _properties, and tuttle::host::ofx::property::OfxhSet::findStringPropValueIndex().
Referenced by tuttle::host::ofx::imageEffect::OfxhImageEffectNode::bestSupportedBitDepth().
bool tuttle::host::ofx::imageEffect::OfxhImageEffectNodeBase::isClipPreferencesSlaveParam (const std::string & s) const
does changing the named param re-tigger a clip preferences action
Definition at line 184 of file OfxhImageEffectNodeBase.cpp.
References _properties, and tuttle::host::ofx::property::OfxhSet::findStringPropValueIndex().
bool tuttle::host::ofx::imageEffect::OfxhImageEffectNodeBase::isContextSupported (const std::string & s) const
is the given context supported
Definition at line 91 of file OfxhImageEffectNodeBase.cpp.
References _properties, and tuttle::host::ofx::property::OfxhSet::findStringPropValueIndex().
bool tuttle::host::ofx::imageEffect::OfxhImageEffectNodeBase::isSingleInstance () const
is the effect single instance
Definition at line 105 of file OfxhImageEffectNodeBase.cpp.
References _properties, and tuttle::host::ofx::property::OfxhSet::getIntProperty().
bool tuttle::host::ofx::imageEffect::OfxhImageEffectNodeBase::operator!= (const OfxhImageEffectNodeBase & other) const [inline]
Definition at line 39 of file OfxhImageEffectNodeBase.hpp.
References operator==().
bool tuttle::host::ofx::imageEffect::OfxhImageEffectNodeBase::operator== (const OfxhImageEffectNodeBase & other) const
Definition at line 21 of file OfxhImageEffectNodeBase.cpp.
References _properties.
Referenced by operator!=().
template<class Archive > void tuttle::host::ofx::imageEffect::OfxhImageEffectNodeBase::serialize (Archive & ar, const unsigned int version) [inline, private]
Reimplemented in tuttle::host::ofx::imageEffect::OfxhImageEffectNode, and tuttle::host::ofx::imageEffect::OfxhImageEffectNodeDescriptor.
Definition at line 114 of file OfxhImageEffectNodeBase.hpp.
References _properties.
void tuttle::host::ofx::imageEffect::OfxhImageEffectNodeBase::setName (const std::string & name)
name of the Node
name of the imageEffect
Reimplemented in tuttle::host::ImageEffectNode.
Definition at line 69 of file OfxhImageEffectNodeBase.cpp.
References _properties, and tuttle::host::ofx::property::OfxhSet::setStringProperty().
bool tuttle::host::ofx::imageEffect::OfxhImageEffectNodeBase::supportsMultipleClipDepths () const
does the effect support multiple clip depths
Definition at line 170 of file OfxhImageEffectNodeBase.cpp.
References _properties, and tuttle::host::ofx::property::OfxhSet::getIntProperty().
Referenced by tuttle::host::ofx::imageEffect::OfxhImageEffectNode::canCurrentlyHandleMultipleClipDepths(), tuttle::host::ImageEffectNode::maximizeBitDepthFromReadsToWrites(), and tuttle::host::ImageEffectNode::maximizeBitDepthFromWritesToReads().
bool tuttle::host::ofx::imageEffect::OfxhImageEffectNodeBase::supportsMultipleClipPARs () const
does the effect support multiple clip pixel aspect ratios
Definition at line 177 of file OfxhImageEffectNodeBase.cpp.
References _properties, and tuttle::host::ofx::property::OfxhSet::getIntProperty().
Referenced by tuttle::host::ImageEffectNode::initInputClipsPixelAspectRatio().
bool tuttle::host::ofx::imageEffect::OfxhImageEffectNodeBase::supportsMultiResolution () const
does the effect support images of differing sizes
Definition at line 134 of file OfxhImageEffectNodeBase.cpp.
References _properties, and tuttle::host::ofx::property::OfxhSet::getIntProperty().
bool tuttle::host::ofx::imageEffect::OfxhImageEffectNodeBase::supportsTiles () const
does the effect support tiled rendering
Definition at line 141 of file OfxhImageEffectNodeBase.cpp.
References _properties, and tuttle::host::ofx::property::OfxhSet::getIntProperty().
bool tuttle::host::ofx::imageEffect::OfxhImageEffectNodeBase::temporalAccess () const
does this effect need random temporal access
Definition at line 148 of file OfxhImageEffectNodeBase.cpp.
References _properties, and tuttle::host::ofx::property::OfxhSet::getIntProperty().
virtual bool tuttle::host::ofx::imageEffect::OfxhImageEffectNodeBase::verifyMagic () [inline, virtual]
is my magic number valid?
Definition at line 42 of file OfxhImageEffectNodeBase.hpp.
Friends And Related Function Documentation
friend class boost::serialization::access [friend]
Reimplemented in tuttle::host::ofx::imageEffect::OfxhImageEffectNode, and tuttle::host::ofx::imageEffect::OfxhImageEffectNodeDescriptor.
Definition at line 112 of file OfxhImageEffectNodeBase.hpp.
Field Documentation
property::OfxhSet tuttle::host::ofx::imageEffect::OfxhImageEffectNodeBase::_properties [protected]
Definition at line 31 of file OfxhImageEffectNodeBase.hpp.
Referenced by fieldRenderTwiceAlways(), getEditableProperties(), getHostFrameThreading(), getLabel(), getLongLabel(), getName(), getOverlayInteractMainEntry(), tuttle::host::ofx::imageEffect::OfxhImageEffectNodeDescriptor::getParamSetProps(), tuttle::host::ofx::imageEffect::OfxhImageEffectNode::getParamSetProps(), getPluginGrouping(), getProperties(), getRenderThreadSafety(), getShortLabel(), tuttle::host::ofx::imageEffect::OfxhImageEffectNode::initHook(), isBitDepthSupported(), isClipPreferencesSlaveParam(), isContextSupported(), isSingleInstance(), tuttle::host::ofx::imageEffect::OfxhImageEffectNode::OfxhImageEffectNode(), tuttle::host::ofx::imageEffect::OfxhImageEffectNodeDescriptor::OfxhImageEffectNodeDescriptor(), operator==(), serialize(), setName(), supportsMultipleClipDepths(), supportsMultipleClipPARs(), supportsMultiResolution(), supportsTiles(), temporalAccess(), and tuttle::host::ofx::imageEffect::OfxhImageEffectNode::upperGetDimension().
The documentation for this class was generated from the following files:
TuttleOFX/libraries/tuttle/src/tuttle/host/ofx/OfxhImageEffectNodeBase.hpp
TuttleOFX/libraries/tuttle/src/tuttle/host/ofx/OfxhImageEffectNodeBase.cpp