TuttleOFX: boost::backtrace Class Reference
boost::backtrace Class Reference
#include <backtrace.hpp>
Public Member Functions
backtrace (size_t frames_no=default_stack_size)
virtual ~backtrace () throw ()
size_t stack_size () const
void * return_address (unsigned frame_no) const
void trace_line (unsigned frame_no, std::ostream &out) const
std::string trace_line (unsigned frame_no) const
std::string trace () const
void trace (std::ostream &out) const
Static Public Attributes
static size_t const default_stack_size = 32
Private Attributes
std::vector< void * > frames_
Detailed Description
Definition at line 28 of file backtrace.hpp.
Constructor & Destructor Documentation
boost::backtrace::backtrace (size_t frames_no = default_stack_size) [inline]
Definition at line 33 of file backtrace.hpp.
References frames_, and trace().
virtual boost::backtrace::~backtrace () throw () [inline, virtual]
Definition at line 42 of file backtrace.hpp.
Member Function Documentation
void* boost::backtrace::return_address (unsigned frame_no) const [inline]
Definition at line 51 of file backtrace.hpp.
References frames_, and stack_size().
size_t boost::backtrace::stack_size () const [inline]
Definition at line 46 of file backtrace.hpp.
References frames_.
Referenced by return_address().
std::string boost::backtrace::trace () const [inline]
Definition at line 71 of file backtrace.hpp.
References frames_, and boost::stack_trace::get_symbols().
Referenced by backtrace(), and boost::details::trace_manip::write().
void boost::backtrace::trace (std::ostream & out) const [inline]
Definition at line 78 of file backtrace.hpp.
References frames_, and boost::stack_trace::write_symbols().
void boost::backtrace::trace_line (unsigned frame_no, std::ostream & out) const [inline]
Definition at line 58 of file backtrace.hpp.
References frames_, and boost::stack_trace::write_symbols().
std::string boost::backtrace::trace_line (unsigned frame_no) const [inline]
Definition at line 64 of file backtrace.hpp.
References frames_, and boost::stack_trace::get_symbol().
Field Documentation
size_t const boost::backtrace::default_stack_size = 32 [static]
Definition at line 31 of file backtrace.hpp.
std::vector<void *> boost::backtrace::frames_ [private]
Definition at line 86 of file backtrace.hpp.
Referenced by backtrace(), return_address(), stack_size(), trace(), and trace_line().
The documentation for this class was generated from the following file:
TuttleOFX/libraries/tuttle/src/tuttle/common/utils/backtrace.hpp