TuttleOFX: tuttle::host::OverlayInteract Class Reference
tuttle::host::OverlayInteract Class Reference
#include <OverlayInteract.hpp>
Public Member Functions
OverlayInteract (Graph &userGraph, ImageEffectNode &effect, int bitDepthPerComponent=8, bool hasAlpha=false)
void setupGraph ()
void draw (const OfxPointD &renderScale)
Protected Attributes
ImageEffectNode & _instance
our image effect instance
int _bitDepthPerComponent
bool _hasAlpha
OfxTime _time
graph::ProcessGraph _procGraph
Detailed Description
An overlay interact for image effects, derived from one of these to be an overlay interact
Definition at line 19 of file OverlayInteract.hpp.
Constructor & Destructor Documentation
tuttle::host::OverlayInteract::OverlayInteract (Graph & userGraph, ImageEffectNode & effect, int bitDepthPerComponent = 8, bool hasAlpha = false)
Definition at line 6 of file OverlayInteract.cpp.
References tuttle::host::ofx::interact::OfxhInteract::createInstanceAction(), and tuttle::host::ofx::imageEffect::OfxhImageEffectNode::initOverlayDescriptor().
Member Function Documentation
void tuttle::host::OverlayInteract::draw (const OfxPointD & renderScale)
Definition at line 18 of file OverlayInteract.cpp.
References _time, and tuttle::host::ofx::interact::OfxhInteract::drawAction().
void tuttle::host::OverlayInteract::setupGraph () [inline]
Definition at line 32 of file OverlayInteract.hpp.
References _procGraph, _time, tuttle::host::graph::ProcessGraph::setup(), and tuttle::host::graph::ProcessGraph::setupAtTime().
Field Documentation
int tuttle::host::OverlayInteract::_bitDepthPerComponent [protected]
Definition at line 24 of file OverlayInteract.hpp.
bool tuttle::host::OverlayInteract::_hasAlpha [protected]
Definition at line 25 of file OverlayInteract.hpp.
ImageEffectNode& tuttle::host::OverlayInteract::_instance [protected]
our image effect instance
Definition at line 23 of file OverlayInteract.hpp.
graph::ProcessGraph tuttle::host::OverlayInteract::_procGraph [protected]
Definition at line 27 of file OverlayInteract.hpp.
Referenced by setupGraph().
OfxTime tuttle::host::OverlayInteract::_time [protected]
Definition at line 26 of file OverlayInteract.hpp.
Referenced by draw(), and setupGraph().
The documentation for this class was generated from the following files:
TuttleOFX/libraries/tuttle/src/tuttle/host/OverlayInteract.hpp
TuttleOFX/libraries/tuttle/src/tuttle/host/OverlayInteract.cpp