TuttleOFX: tuttle::host::attribute::ClipImage Class Reference
tuttle::host::attribute::ClipImage Class Reference
#include <ClipImage.hpp>
Public Member Functions
ClipImage (INode &effect, const ofx::attribute::OfxhClipImageDescriptor &desc)
ClipImage (const ClipImage &other)
~ClipImage ()
ClipImage * clone () const
clone this clip
const std::string & getName () const
void setConnectedClip (const ClipImage &other)
void setUnconnected ()
std::string getFullName () const
OfxTime getRemappedTime (const OfxTime time) const
std::string getConnectedClipFullName () const
std::string getClipIdentifier () const
ClipImage & getConnectedClip ()
const ClipImage & getConnectedClip () const
const std::string & getUnmappedBitDepth () const
Get the Raw Unmapped Pixel Depth from the host.
const std::string & getUnmappedComponents () const
Get the Raw Unmapped Components from the host.
double getFrameRate () const
Frame Rate The frame rate of a clip or instance's project.
void setFrameRate (const double fps)
void setFrameRange (const double startFrame, const double endFrame)
Frame Range (startFrame, endFrame) The frame range over which a clip has images.
const double getUnmappedFrameRate () const
Unmapped Frame Rate.
void setUnmappedFrameRange (const double unmappedStartFrame, const double unmappedEndFrame)
Unmapped Frame Range - The unmaped frame range over which an output clip has images.
tuttle::host::ofx::imageEffect::OfxhImage * getImage (const OfxTime time, const OfxRectD *optionalBounds=NULL)
override this to fill in the image at the given time. The bounds of the image on the image plane should be appropriate', typically the value returned in getRegionsOfInterest on the effect instance. Outside a render call, the optionalBounds should be 'appropriate' for the. If bounds is not null, fetch the indicated section of the canonical image plane.
OfxRectD fetchRegionOfDefinition (const OfxTime time) const
override this to return the rod on the clip
Protected Attributes
std::string _name
bool _isConnected
bool _continuousSamples
const ClipImage * _connectedClip
Private Member Functions
ClipImage & operator= (const ClipImage &other)
Friends
class INode
Detailed Description
Definition at line 23 of file ClipImage.hpp.
Constructor & Destructor Documentation
tuttle::host::attribute::ClipImage::ClipImage (INode & effect, const ofx::attribute::OfxhClipImageDescriptor & desc)
Definition at line 34 of file ClipImage.cpp.
References tuttle::host::ofx::attribute::OfxhAttribute::getEditableProperties(), and getFullName().
Referenced by clone().
tuttle::host::attribute::ClipImage::ClipImage (const ClipImage & other)
Definition at line 45 of file ClipImage.cpp.
References _connectedClip, _continuousSamples, _isConnected, and _name.
tuttle::host::attribute::ClipImage::~ClipImage ()
Definition at line 55 of file ClipImage.cpp.
Member Function Documentation
ClipImage* tuttle::host::attribute::ClipImage::clone () const [inline, virtual]
clone this clip
Implements tuttle::host::ofx::attribute::OfxhClipImage.
Definition at line 46 of file ClipImage.hpp.
References ClipImage().
OfxRectD tuttle::host::attribute::ClipImage::fetchRegionOfDefinition (const OfxTime time) const [virtual]
override this to return the rod on the clip
Return the rod on the clip canonical coords!
Todo:
tuttle: renderscale, time, ?
Implements tuttle::host::ofx::attribute::OfxhClipImage.
Definition at line 79 of file ClipImage.cpp.
References _connectedClip, tuttle::host::INode::asImageEffectNode(), tuttle::host::INode::eNodeTypeImageEffect, fetchRegionOfDefinition(), getFullName(), tuttle::host::attribute::Attribute::getNode(), tuttle::host::ImageEffectNode::getRegionOfDefinition(), getRemappedTime(), tuttle::host::ofx::attribute::OfxhClipAccessor::isConnected(), tuttle::host::ofx::attribute::OfxhAttributeAccessor::isOutput(), and tuttle::host::mapNodeTypeEnumToString().
Referenced by tuttle::host::graph::ProcessVertexAtTime::exportDotDebug(), fetchRegionOfDefinition(), and getImage().
std::string tuttle::host::attribute::ClipImage::getClipIdentifier () const [inline, virtual]
Implements tuttle::host::ofx::attribute::OfxhClipImage.
Definition at line 91 of file ClipImage.hpp.
References getConnectedClipFullName(), getFullName(), tuttle::host::ofx::attribute::OfxhClipAccessor::isConnected(), and tuttle::host::ofx::attribute::OfxhAttributeAccessor::isOutput().
Referenced by getImage(), tuttle::host::ImageEffectNode::process(), and setConnectedClip().
ClipImage& tuttle::host::attribute::ClipImage::getConnectedClip () [inline]
Todo:
tuttle: this is really bad...
Definition at line 100 of file ClipImage.hpp.
Referenced by tuttle::host::ImageEffectNode::computeTimeDomain(), tuttle::host::ImageEffectNode::coutBitDepthConnections(), tuttle::host::ImageEffectNode::getDefaultTimeDomain(), tuttle::host::ImageEffectNode::initComponents(), tuttle::host::ImageEffectNode::initInputClipsFps(), tuttle::host::ImageEffectNode::initInputClipsPixelAspectRatio(), tuttle::host::ImageEffectNode::maximizeBitDepthFromReadsToWrites(), tuttle::host::ImageEffectNode::maximizeBitDepthFromWritesToReads(), and tuttle::host::ImageEffectNode::validInputClipsConnections().
const ClipImage& tuttle::host::attribute::ClipImage::getConnectedClip () const [inline]
Definition at line 105 of file ClipImage.hpp.
References _connectedClip.
std::string tuttle::host::attribute::ClipImage::getConnectedClipFullName () const [inline, virtual]
Todo:
tuttle: remove this!
Implements tuttle::host::ofx::attribute::OfxhClipImage.
Definition at line 81 of file ClipImage.hpp.
References _connectedClip, getFullName(), tuttle::host::ofx::attribute::OfxhClipAccessor::isConnected(), and tuttle::host::ofx::attribute::OfxhAttributeAccessor::isOutput().
Referenced by getClipIdentifier().
double tuttle::host::attribute::ClipImage::getFrameRate () const [virtual]
Frame Rate The frame rate of a clip or instance's project.
Reimplemented from tuttle::host::ofx::attribute::OfxhClipImage.
Definition at line 120 of file ClipImage.cpp.
References tuttle::host::ofx::attribute::OfxhAttribute::getProperties().
Referenced by tuttle::host::graph::ProcessVertex::exportDotDebug(), tuttle::host::graph::ProcessVertexAtTime::exportDotDebug(), and tuttle::host::ImageEffectNode::initInputClipsFps().
std::string tuttle::host::attribute::ClipImage::getFullName () const [virtual]
Implements tuttle::host::ofx::attribute::OfxhClip.
Definition at line 58 of file ClipImage.cpp.
References getName(), tuttle::host::INode::getName(), and tuttle::host::attribute::Attribute::getNode().
Referenced by tuttle::host::ImageEffectNode::checkClipsConnected(), ClipImage(), tuttle::host::ImageEffectNode::coutBitDepthConnections(), fetchRegionOfDefinition(), getClipIdentifier(), getConnectedClipFullName(), tuttle::host::ImageEffectNode::process(), setConnectedClip(), and tuttle::host::ImageEffectNode::validInputClipsConnections().
tuttle::host::ofx::imageEffect::OfxhImage * tuttle::host::attribute::ClipImage::getImage (const OfxTime time, const OfxRectD * optionalBounds = NULL) [virtual]
override this to fill in the image at the given time. The bounds of the image on the image plane should be appropriate', typically the value returned in getRegionsOfInterest on the effect instance. Outside a render call, the optionalBounds should be 'appropriate' for the. If bounds is not null, fetch the indicated section of the canonical image plane.
override this to fill in the image at the given time. The bounds of the image on the image plane should be 'appropriate', typically the value returned in getRegionsOfInterest on the effect instance. Outside a render call, the optionalBounds should be 'appropriate' for the. If bounds is not null, fetch the indicated section of the canonical image plane.
Todo:
tuttle do something with bounds... if bounds != cache buffer bounds: bounds < cache buffer: use rowSize to adjust, and modify pointer bounds > cache buffer: recompute / exception ?
Implements tuttle::host::ofx::attribute::OfxhClipImage.
Definition at line 164 of file ClipImage.cpp.
References fetchRegionOfDefinition(), getClipIdentifier(), tuttle::host::INode::getData(), tuttle::host::attribute::Attribute::getNode(), and getRemappedTime().
const std::string& tuttle::host::attribute::ClipImage::getName () const [inline, virtual]
Implements tuttle::host::attribute::Attribute.
Definition at line 48 of file ClipImage.hpp.
Referenced by getFullName(), getRemappedTime(), and tuttle::host::ImageEffectNode::initInputClipsPixelAspectRatio().
OfxTime tuttle::host::attribute::ClipImage::getRemappedTime (const OfxTime time) const
Maybe we are not inside a compute (eg. overlay)... so datas are not initialized, etc.
Definition at line 63 of file ClipImage.cpp.
References tuttle::host::INode::getData(), getName(), tuttle::host::attribute::Attribute::getNode(), and tuttle::host::ofx::attribute::OfxhAttributeAccessor::isOutput().
Referenced by fetchRegionOfDefinition(), and getImage().
const std::string & tuttle::host::attribute::ClipImage::getUnmappedBitDepth () const [virtual]
Get the Raw Unmapped Pixel Depth from the host.
Get the Raw Unmapped Pixel Depth.
Returns:
kOfxBitDepthNone (implying a clip is unconnected image)
kOfxBitDepthByte
kOfxBitDepthShort
kOfxBitDepthFloat
Reimplemented from tuttle::host::ofx::attribute::OfxhClipImage.
Definition at line 104 of file ClipImage.cpp.
References tuttle::host::ofx::attribute::OfxhAttribute::getProperties().
const std::string & tuttle::host::attribute::ClipImage::getUnmappedComponents () const [virtual]
Get the Raw Unmapped Components from the host.
Returns:
kOfxImageComponentNone (implying a clip is unconnected, not valid for an image)
kOfxImageComponentRGBA
kOfxImageComponentRGB
kOfxImageComponentAlpha
Reimplemented from tuttle::host::ofx::attribute::OfxhClipImage.
Definition at line 111 of file ClipImage.cpp.
References tuttle::host::ofx::attribute::OfxhAttribute::getProperties().
const double tuttle::host::attribute::ClipImage::getUnmappedFrameRate () const [virtual]
Unmapped Frame Rate.
Unmapped Frame Rate The unmaped frame range over which an output clip has images.
Reimplemented from tuttle::host::ofx::attribute::OfxhClipImage.
Definition at line 143 of file ClipImage.cpp.
References tuttle::host::INode::asImageEffectNode(), tuttle::host::attribute::Attribute::getNode(), and tuttle::host::ofx::imageEffect::OfxhImageEffectNode::getOutputFrameRate().
ClipImage& tuttle::host::attribute::ClipImage::operator= (const ClipImage & other) [private]
void tuttle::host::attribute::ClipImage::setConnectedClip (const ClipImage & other) [inline]
Warning:
HACK ! to keep the connection
Todo:
remove this !!!!
Definition at line 52 of file ClipImage.hpp.
References _connectedClip, getClipIdentifier(), tuttle::host::ofx::attribute::OfxhAttribute::getEditableProperties(), getFullName(), tuttle::host::ofx::attribute::OfxhAttributeAccessor::isOutput(), and tuttle::host::ofx::attribute::OfxhClipAccessor::setConnected().
Referenced by tuttle::host::ImageEffectNode::connect().
void tuttle::host::attribute::ClipImage::setFrameRange (const double startFrame, const double endFrame)
Frame Range (startFrame, endFrame) The frame range over which a clip has images.
Definition at line 133 of file ClipImage.cpp.
References tuttle::host::ofx::attribute::OfxhAttribute::getEditableProperties().
Referenced by tuttle::host::ImageEffectNode::computeTimeDomain().
void tuttle::host::attribute::ClipImage::setFrameRate (const double fps)
Definition at line 125 of file ClipImage.cpp.
References tuttle::host::ofx::attribute::OfxhAttribute::getEditableProperties().
Referenced by tuttle::host::ImageEffectNode::initFps(), and tuttle::host::ImageEffectNode::initInputClipsFps().
void tuttle::host::attribute::ClipImage::setUnconnected () [inline]
Definition at line 75 of file ClipImage.hpp.
References _connectedClip, and tuttle::host::ofx::attribute::OfxhClipAccessor::setConnected().
void tuttle::host::attribute::ClipImage::setUnmappedFrameRange (const double unmappedStartFrame, const double unmappedEndFrame)
Unmapped Frame Range - The unmaped frame range over which an output clip has images.
Definition at line 152 of file ClipImage.cpp.
References tuttle::host::ofx::attribute::OfxhAttribute::getEditableProperties().
Referenced by tuttle::host::ImageEffectNode::computeTimeDomain().
Friends And Related Function Documentation
friend class INode [friend]
Definition at line 26 of file ClipImage.hpp.
Field Documentation
const ClipImage* tuttle::host::attribute::ClipImage::_connectedClip [protected]
Warning:
HACK ! to keep the connection
Todo:
remove this !!!!
Definition at line 33 of file ClipImage.hpp.
Referenced by ClipImage(), fetchRegionOfDefinition(), getConnectedClip(), getConnectedClipFullName(), setConnectedClip(), and setUnconnected().
bool tuttle::host::attribute::ClipImage::_continuousSamples [protected]
Definition at line 31 of file ClipImage.hpp.
Referenced by ClipImage().
bool tuttle::host::attribute::ClipImage::_isConnected [protected]
Definition at line 30 of file ClipImage.hpp.
Referenced by ClipImage().
std::string tuttle::host::attribute::ClipImage::_name [protected]
Definition at line 29 of file ClipImage.hpp.
Referenced by ClipImage().
The documentation for this class was generated from the following files:
TuttleOFX/libraries/tuttle/src/tuttle/host/attribute/ClipImage.hpp
TuttleOFX/libraries/tuttle/src/tuttle/host/attribute/ClipImage.cpp