TuttleOFX: tuttle::host::graph::IEdge Class Reference
tuttle::host::graph::IEdge Class Reference
#include <IEdge.hpp>
Public Member Functions
IEdge ()
IEdge (const std::string &out, const std::string &in, const std::string &inAttrName)
IEdge (const IEdge &e)
virtual ~IEdge ()=0
IEdge & operator= (const IEdge &e)
const std::string & getOut () const
const std::string & getIn () const
const std::string & getInAttrName () const
const std::string & getName () const
virtual std::ostream & exportDotDebug (std::ostream &os) const
Data Fields
std::string _out
std::string _in
std::string _inAttrName
std::string _name
std::size_t _localId
Friends
std::ostream & operator<< (std::ostream &os, const IEdge &v)
Detailed Description
Definition at line 17 of file IEdge.hpp.
Constructor & Destructor Documentation
tuttle::host::graph::IEdge::IEdge ()
Definition at line 8 of file IEdge.cpp.
tuttle::host::graph::IEdge::IEdge (const std::string & out, const std::string & in, const std::string & inAttrName)
Definition at line 13 of file IEdge.cpp.
tuttle::host::graph::IEdge::IEdge (const IEdge & e)
Definition at line 22 of file IEdge.cpp.
References operator=().
tuttle::host::graph::IEdge::~IEdge () [pure virtual]
Definition at line 28 of file IEdge.cpp.
Member Function Documentation
std::ostream & tuttle::host::graph::IEdge::exportDotDebug (std::ostream & os) const [virtual]
Reimplemented in tuttle::host::graph::ProcessEdge, and tuttle::host::graph::ProcessEdgeAtTime.
Definition at line 33 of file IEdge.cpp.
References _localId, tuttle::host::graph::dotEntry(), getName(), and tuttle::host::graph::subDotEntry().
const std::string& tuttle::host::graph::IEdge::getIn () const [inline]
Definition at line 38 of file IEdge.hpp.
References _in.
Referenced by tuttle::host::ImageEffectNode::process().
const std::string& tuttle::host::graph::IEdge::getInAttrName () const [inline]
Definition at line 39 of file IEdge.hpp.
References _inAttrName.
Referenced by tuttle::host::graph::ProcessGraph::bakeGraphInformationToNodes(), tuttle::host::ImageEffectNode::process(), and tuttle::host::graph::ProcessGraph::setupAtTime().
const std::string& tuttle::host::graph::IEdge::getName () const [inline]
Definition at line 40 of file IEdge.hpp.
References _name.
Referenced by tuttle::host::graph::ProcessEdgeAtTime::exportDotDebug(), tuttle::host::graph::ProcessEdge::exportDotDebug(), exportDotDebug(), and tuttle::host::graph::operator<<().
const std::string& tuttle::host::graph::IEdge::getOut () const [inline]
Definition at line 37 of file IEdge.hpp.
References _out.
Referenced by tuttle::host::ImageEffectNode::process().
IEdge& tuttle::host::graph::IEdge::operator= (const IEdge & e) [inline]
Definition at line 25 of file IEdge.hpp.
References _in, _inAttrName, _localId, _name, and _out.
Referenced by IEdge().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const IEdge & v) [friend]
Definition at line 46 of file IEdge.cpp.
Field Documentation
std::string tuttle::host::graph::IEdge::_in
Definition at line 47 of file IEdge.hpp.
Referenced by getIn(), and operator=().
std::string tuttle::host::graph::IEdge::_inAttrName
Definition at line 48 of file IEdge.hpp.
Referenced by getInAttrName(), and operator=().
std::size_t tuttle::host::graph::IEdge::_localId
Definition at line 50 of file IEdge.hpp.
Referenced by tuttle::host::graph::ProcessEdgeAtTime::exportDotDebug(), tuttle::host::graph::ProcessEdge::exportDotDebug(), exportDotDebug(), and operator=().
std::string tuttle::host::graph::IEdge::_name
Definition at line 49 of file IEdge.hpp.
Referenced by tuttle::host::graph::exportAsDOT(), tuttle::host::graph::exportSimple(), getName(), and operator=().
std::string tuttle::host::graph::IEdge::_out
Definition at line 46 of file IEdge.hpp.
Referenced by getOut(), and operator=().
The documentation for this class was generated from the following files:
TuttleOFX/libraries/tuttle/src/tuttle/host/graph/IEdge.hpp
TuttleOFX/libraries/tuttle/src/tuttle/host/graph/IEdge.cpp