TuttleOFX: tuttle::host::graph::ProcessEdgeAtTime Class Reference
tuttle::host::graph::ProcessEdgeAtTime Class Reference
#include <ProcessEdgeAtTime.hpp>
Public Member Functions
ProcessEdgeAtTime ()
ProcessEdgeAtTime (const ProcessVertexAtTime::Key &out, const ProcessVertexAtTime::Key &in, const std::string &inAttrName)
ProcessEdgeAtTime (const ProcessEdge &e)
ProcessEdgeAtTime (const ProcessEdgeAtTime &other)
virtual ~ProcessEdgeAtTime ()
std::ostream & exportDotDebug (std::ostream &os) const
ProcessEdgeAtTime & operator= (const ProcessEdge &e)
OfxTime getOutTime () const
OfxTime getInTime () const
Private Attributes
OfxTime _inTime
OfxTime _outTime
Detailed Description
Definition at line 12 of file ProcessEdgeAtTime.hpp.
Constructor & Destructor Documentation
tuttle::host::graph::ProcessEdgeAtTime::ProcessEdgeAtTime ()
Definition at line 8 of file ProcessEdgeAtTime.cpp.
tuttle::host::graph::ProcessEdgeAtTime::ProcessEdgeAtTime (const ProcessVertexAtTime::Key & out, const ProcessVertexAtTime::Key & in, const std::string & inAttrName)
Definition at line 14 of file ProcessEdgeAtTime.cpp.
tuttle::host::graph::ProcessEdgeAtTime::ProcessEdgeAtTime (const ProcessEdge & e)
Definition at line 21 of file ProcessEdgeAtTime.cpp.
tuttle::host::graph::ProcessEdgeAtTime::ProcessEdgeAtTime (const ProcessEdgeAtTime & other)
Definition at line 28 of file ProcessEdgeAtTime.cpp.
tuttle::host::graph::ProcessEdgeAtTime::~ProcessEdgeAtTime () [virtual]
Definition at line 35 of file ProcessEdgeAtTime.cpp.
Member Function Documentation
std::ostream & tuttle::host::graph::ProcessEdgeAtTime::exportDotDebug (std::ostream & os) const [virtual]
Reimplemented from tuttle::host::graph::IEdge.
Definition at line 39 of file ProcessEdgeAtTime.cpp.
References _inTime, tuttle::host::graph::IEdge::_localId, _outTime, tuttle::host::graph::dotEntry(), tuttle::host::graph::IEdge::getName(), and tuttle::host::graph::subDotEntry().
OfxTime tuttle::host::graph::ProcessEdgeAtTime::getInTime () const [inline]
Definition at line 30 of file ProcessEdgeAtTime.hpp.
References _inTime.
Referenced by tuttle::host::graph::ProcessGraph::bakeGraphInformationToNodes().
OfxTime tuttle::host::graph::ProcessEdgeAtTime::getOutTime () const [inline]
Definition at line 29 of file ProcessEdgeAtTime.hpp.
References _outTime.
Referenced by tuttle::host::ImageEffectNode::process().
ProcessEdgeAtTime& tuttle::host::graph::ProcessEdgeAtTime::operator= (const ProcessEdge & e) [inline]
Definition at line 23 of file ProcessEdgeAtTime.hpp.
Field Documentation
OfxTime tuttle::host::graph::ProcessEdgeAtTime::_inTime [private]
Definition at line 33 of file ProcessEdgeAtTime.hpp.
Referenced by exportDotDebug(), and getInTime().
OfxTime tuttle::host::graph::ProcessEdgeAtTime::_outTime [private]
Definition at line 34 of file ProcessEdgeAtTime.hpp.
Referenced by exportDotDebug(), and getOutTime().
The documentation for this class was generated from the following files:
TuttleOFX/libraries/tuttle/src/tuttle/host/graph/ProcessEdgeAtTime.hpp
TuttleOFX/libraries/tuttle/src/tuttle/host/graph/ProcessEdgeAtTime.cpp