TuttleOFX: tuttle::host::ofx::attribute::OfxhParamDescriptor Class Reference
tuttle::host::ofx::attribute::OfxhParamDescriptor Class Reference
the Descriptor of a plugin parameter
#include <OfxhParamDescriptor.hpp>
Public Types
typedef OfxhParamDescriptor This
Public Member Functions
OfxhParamDescriptor (const std::string &type, const std::string &name)
make a parameter, with the given type and name
~OfxhParamDescriptor ()
bool operator== (const This &other) const
bool operator!= (const This &other) const
OfxParamHandle getParamHandle () const
grab a handle on the parameter for passing to the C API
void initStandardParamProps (const std::string &type)
add standard param props, will call the below
Private Member Functions
OfxhParamDescriptor ()
void initInteractParamProps (const std::string &type)
add standard properties to a params that can take an interact
void initValueParamProps (const std::string &type, property::EPropType valueType, int dim)
add standard properties to a value holding param
void initNoValueParamProps ()
void initNumericParamProps (const std::string &type, property::EPropType valueType, int dim)
add standard properties to a value holding param
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Friends
class boost::serialization::access
Detailed Description
the Descriptor of a plugin parameter
Definition at line 18 of file OfxhParamDescriptor.hpp.
Member Typedef Documentation
typedef OfxhParamDescriptor tuttle::host::ofx::attribute::OfxhParamDescriptor::This
Reimplemented from tuttle::host::ofx::attribute::OfxhAttributeDescriptor.
Definition at line 23 of file OfxhParamDescriptor.hpp.
Constructor & Destructor Documentation
tuttle::host::ofx::attribute::OfxhParamDescriptor::OfxhParamDescriptor () [inline, private]
Definition at line 26 of file OfxhParamDescriptor.hpp.
tuttle::host::ofx::attribute::OfxhParamDescriptor::OfxhParamDescriptor (const std::string & type, const std::string & name)
make a parameter, with the given type and name
<
Todo:
TUTTLE_TODO : common property for all Attributes
Definition at line 91 of file OfxhParamDescriptor.cpp.
References tuttle::host::ofx::property::OfxhSet::addProperties(), tuttle::host::ofx::property::ePropTypeInt, tuttle::host::ofx::property::ePropTypePointer, tuttle::host::ofx::property::ePropTypeString, tuttle::host::ofx::attribute::OfxhAttributeDescriptor::getEditableProperties(), tuttle::host::ofx::attribute::OfxhAttributeAccessor::setAllNames(), and tuttle::host::ofx::property::OfxhSet::setStringProperty().
tuttle::host::ofx::attribute::OfxhParamDescriptor::~OfxhParamDescriptor () [inline]
Definition at line 31 of file OfxhParamDescriptor.hpp.
Member Function Documentation
OfxParamHandle tuttle::host::ofx::attribute::OfxhParamDescriptor::getParamHandle () const [inline, virtual]
grab a handle on the parameter for passing to the C API
Implements tuttle::host::ofx::attribute::OfxhParamAccessor.
Definition at line 43 of file OfxhParamDescriptor.hpp.
void tuttle::host::ofx::attribute::OfxhParamDescriptor::initInteractParamProps (const std::string & type) [private]
add standard properties to a params that can take an interact
Definition at line 200 of file OfxhParamDescriptor.cpp.
References tuttle::host::ofx::property::OfxhSet::addProperties(), tuttle::host::ofx::property::ePropTypeDouble, tuttle::host::ofx::property::ePropTypeInt, tuttle::host::ofx::property::ePropTypePointer, and tuttle::host::ofx::attribute::OfxhAttributeDescriptor::getEditableProperties().
Referenced by initStandardParamProps().
void tuttle::host::ofx::attribute::OfxhParamDescriptor::initNoValueParamProps () [private]
Definition at line 240 of file OfxhParamDescriptor.cpp.
References tuttle::host::ofx::property::OfxhSet::addProperties(), tuttle::host::ofx::property::ePropTypeInt, tuttle::host::ofx::property::ePropTypeString, and tuttle::host::ofx::attribute::OfxhAttributeDescriptor::getEditableProperties().
Referenced by initStandardParamProps().
void tuttle::host::ofx::attribute::OfxhParamDescriptor::initNumericParamProps (const std::string & type, property::EPropType valueType, int dim) [private]
add standard properties to a value holding param
if any double or a colour
if a double param type
if a multi dimensional param
if a multi dimensional param
Definition at line 260 of file OfxhParamDescriptor.cpp.
References tuttle::host::ofx::property::OfxhSet::addProperties(), tuttle::host::ofx::property::ePropTypeDouble, tuttle::host::ofx::property::ePropTypeInt, tuttle::host::ofx::property::ePropTypeString, tuttle::host::ofx::attribute::OfxhAttributeDescriptor::getEditableProperties(), tuttle::host::ofx::attribute::isColourParam(), tuttle::host::ofx::attribute::isDoubleParam(), tuttle::max(), tuttle::min(), and tuttle::host::ofx::property::OfxhSet::setStringProperty().
Referenced by initStandardParamProps().
void tuttle::host::ofx::attribute::OfxhParamDescriptor::initStandardParamProps (const std::string & type)
add standard param props, will call the below
make a parameter, with the given type and name
Definition at line 125 of file OfxhParamDescriptor.cpp.
References tuttle::host::ofx::property::OfxhSet::addProperties(), tuttle::host::ofx::property::ePropTypeInt, tuttle::host::ofx::property::ePropTypeNone, tuttle::host::ofx::property::ePropTypePointer, tuttle::host::ofx::property::ePropTypeString, tuttle::host::ofx::attribute::findType(), tuttle::host::ofx::attribute::OfxhAttributeDescriptor::getEditableProperties(), initInteractParamProps(), initNoValueParamProps(), initNumericParamProps(), initValueParamProps(), tuttle::host::ofx::attribute::isColourParam(), tuttle::host::ofx::attribute::isDoubleParam(), and tuttle::host::ofx::attribute::isIntParam().
Referenced by tuttle::host::ofx::attribute::OfxhParamSetDescriptor::paramDefine().
void tuttle::host::ofx::attribute::OfxhParamDescriptor::initValueParamProps (const std::string & type, property::EPropType valueType, int dim) [private]
add standard properties to a value holding param
Definition at line 217 of file OfxhParamDescriptor.cpp.
References tuttle::host::ofx::property::OfxhSet::addProperties(), tuttle::host::ofx::property::ePropTypeInt, tuttle::host::ofx::property::ePropTypeString, and tuttle::host::ofx::attribute::OfxhAttributeDescriptor::getEditableProperties().
Referenced by initStandardParamProps().
bool tuttle::host::ofx::attribute::OfxhParamDescriptor::operator!= (const This & other) const [inline]
Reimplemented from tuttle::host::ofx::attribute::OfxhAttributeDescriptor.
Definition at line 40 of file OfxhParamDescriptor.hpp.
References operator==().
bool tuttle::host::ofx::attribute::OfxhParamDescriptor::operator== (const This & other) const [inline]
Reimplemented from tuttle::host::ofx::attribute::OfxhAttributeDescriptor.
Definition at line 33 of file OfxhParamDescriptor.hpp.
Referenced by operator!=().
template<class Archive > void tuttle::host::ofx::attribute::OfxhParamDescriptor::serialize (Archive & ar, const unsigned int version) [inline, private]
Reimplemented from tuttle::host::ofx::attribute::OfxhAttributeDescriptor.
Definition at line 65 of file OfxhParamDescriptor.hpp.
Friends And Related Function Documentation
friend class boost::serialization::access [friend]
Reimplemented from tuttle::host::ofx::attribute::OfxhAttributeDescriptor.
Definition at line 63 of file OfxhParamDescriptor.hpp.
The documentation for this class was generated from the following files:
TuttleOFX/libraries/tuttle/src/tuttle/host/ofx/attribute/OfxhParamDescriptor.hpp
TuttleOFX/libraries/tuttle/src/tuttle/host/ofx/attribute/OfxhParamDescriptor.cpp