TuttleOFX: tuttle::test::DummyEdge Class Reference
tuttle::test::DummyEdge Class Reference
#include <DummyEdge.hpp>
Public Member Functions
DummyEdge ()
DummyEdge (const std::string &name)
DummyEdge (const DummyEdge &e)
virtual ~DummyEdge ()
DummyEdge & operator= (const DummyEdge &e)
const std::string & getName () const
const std::string & getInAttrName () const
void setName (const std::string s)
Private Attributes
std::string _name
std::string _inAttrName
Friends
std::ostream & operator<< (std::ostream &os, const DummyEdge &v)
Detailed Description
Definition at line 9 of file DummyEdge.hpp.
Constructor & Destructor Documentation
tuttle::test::DummyEdge::DummyEdge () [inline]
Definition at line 12 of file DummyEdge.hpp.
tuttle::test::DummyEdge::DummyEdge (const std::string & name) [inline]
Definition at line 14 of file DummyEdge.hpp.
tuttle::test::DummyEdge::DummyEdge (const DummyEdge & e) [inline]
Definition at line 17 of file DummyEdge.hpp.
virtual tuttle::test::DummyEdge::~DummyEdge () [inline, virtual]
Definition at line 20 of file DummyEdge.hpp.
Member Function Documentation
const std::string& tuttle::test::DummyEdge::getInAttrName () const [inline]
Definition at line 33 of file DummyEdge.hpp.
References _inAttrName.
const std::string& tuttle::test::DummyEdge::getName () const [inline]
Definition at line 32 of file DummyEdge.hpp.
References _name.
Referenced by tuttle::test::operator<<(), and operator=().
DummyEdge& tuttle::test::DummyEdge::operator= (const DummyEdge & e) [inline]
Definition at line 24 of file DummyEdge.hpp.
References _name, and getName().
void tuttle::test::DummyEdge::setName (const std::string s) [inline]
Definition at line 34 of file DummyEdge.hpp.
References _name.
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const DummyEdge & v) [friend]
Definition at line 6 of file DummyEdge.cpp.
Field Documentation
std::string tuttle::test::DummyEdge::_inAttrName [private]
Definition at line 40 of file DummyEdge.hpp.
Referenced by getInAttrName().
std::string tuttle::test::DummyEdge::_name [private]
Definition at line 39 of file DummyEdge.hpp.
Referenced by getName(), operator=(), and setName().
The documentation for this class was generated from the following file:
TuttleOFX/libraries/tuttle/tests/internalGraph/dummy/DummyEdge.hpp