TuttleOFX: tuttle::host::ofx::imageEffect::OfxhImageEffectPlugin Class Reference
tuttle::host::ofx::imageEffect::OfxhImageEffectPlugin Class Reference
#include <OfxhImageEffectPlugin.hpp>
Public Types
typedef OfxhImageEffectPlugin This
typedef boost::ptr_map
< std::string,
OfxhImageEffectNodeDescriptor > ContextMap
typedef std::set< std::string > ContextSet
Public Member Functions
OfxhImageEffectPlugin (OfxhImageEffectPluginCache &imageEffectPluginCache, OfxhPluginBinary &pluginBinary, int pluginIndex, OfxPlugin &plugin)
OfxhImageEffectPlugin (OfxhImageEffectPluginCache &imageEffectPluginCache, OfxhPluginBinary &pluginBinary, int pluginIndex, const std::string &api, int apiVersion, const std::string &pluginId, const std::string &rawId, int pluginMajorVersion, int pluginMinorVersion)
~OfxhImageEffectPlugin ()
bool operator== (const OfxhImageEffectPlugin &other) const
bool operator!= (const OfxhImageEffectPlugin &other) const
void setApiHandler (OfxhImageEffectPluginCache &api)
void setApiHandler (APICache::OfxhPluginAPICacheI &api)
APICache::OfxhPluginAPICacheI & getApiHandler ()
const
APICache::OfxhPluginAPICacheI & getApiHandler () const
OfxhImageEffectNodeDescriptor & getDescriptor ()
get the base image effect descriptor
const
OfxhImageEffectNodeDescriptor & getDescriptor () const
get the base image effect descriptor, const version
OfxhImageEffectNodeDescriptor & getDescriptorInContext (const std::string &context)
get the image effect descriptor for the context
void addContext (const std::string &context)
void addContext (const std::string &context, OfxhImageEffectNodeDescriptor *ied)
void initContexts ()
const ContextSet & getContexts () const
bool supportsContext (const std::string &context) const
OfxhPluginLoadGuard * getPluginLoadGuardPtr ()
const OfxhPluginLoadGuard * getPluginLoadGuardPtr () const
void loadAndDescribeActions ()
void unloadAction ()
imageEffect::OfxhImageEffectNode * createInstance (const std::string &context)
this is called to make an instance of the effect the client data ptr is what is passed back to the client creation function
Private Member Functions
OfxhImageEffectPlugin ()
OfxhImageEffectNodeDescriptor & describeInContextAction (const std::string &context)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
OfxhImageEffectPluginCache * _imageEffectPluginCache
ContextMap _contexts
map to store contexts in
ContextSet _knownContexts
boost::scoped_ptr
< OfxhPluginLoadGuard > _pluginLoadGuard
boost::scoped_ptr
< OfxhImageEffectNodeDescriptor > _baseDescriptor
NEEDS TO BE MADE WITH A FACTORY FUNCTION ON THE HOST!!!!!!
Friends
class boost::serialization::access
Detailed Description
subclass of Plugin representing an ImageEffect plugin. used to store API-specific data
Definition at line 66 of file OfxhImageEffectPlugin.hpp.
Member Typedef Documentation
typedef boost::ptr_map<std::string, OfxhImageEffectNodeDescriptor> tuttle::host::ofx::imageEffect::OfxhImageEffectPlugin::ContextMap
Definition at line 70 of file OfxhImageEffectPlugin.hpp.
typedef std::set<std::string> tuttle::host::ofx::imageEffect::OfxhImageEffectPlugin::ContextSet
Definition at line 71 of file OfxhImageEffectPlugin.hpp.
typedef OfxhImageEffectPlugin tuttle::host::ofx::imageEffect::OfxhImageEffectPlugin::This
Reimplemented from tuttle::host::ofx::OfxhPlugin.
Definition at line 69 of file OfxhImageEffectPlugin.hpp.
Constructor & Destructor Documentation
tuttle::host::ofx::imageEffect::OfxhImageEffectPlugin::OfxhImageEffectPlugin () [private]
Todo:
tuttle
Definition at line 64 of file OfxhImageEffectPlugin.cpp.
tuttle::host::ofx::imageEffect::OfxhImageEffectPlugin::OfxhImageEffectPlugin (OfxhImageEffectPluginCache & imageEffectPluginCache, OfxhPluginBinary & pluginBinary, int pluginIndex, OfxPlugin & plugin)
Definition at line 73 of file OfxhImageEffectPlugin.cpp.
tuttle::host::ofx::imageEffect::OfxhImageEffectPlugin::OfxhImageEffectPlugin (OfxhImageEffectPluginCache & imageEffectPluginCache, OfxhPluginBinary & pluginBinary, int pluginIndex, const std::string & api, int apiVersion, const std::string & pluginId, const std::string & rawId, int pluginMajorVersion, int pluginMinorVersion)
Definition at line 82 of file OfxhImageEffectPlugin.cpp.
tuttle::host::ofx::imageEffect::OfxhImageEffectPlugin::~OfxhImageEffectPlugin ()
Definition at line 103 of file OfxhImageEffectPlugin.cpp.
References _pluginLoadGuard.
Member Function Documentation
void tuttle::host::ofx::imageEffect::OfxhImageEffectPlugin::addContext (const std::string & context)
Definition at line 154 of file OfxhImageEffectPlugin.cpp.
References _knownContexts.
Referenced by initContexts(), and tuttle::host::ofx::imageEffect::OfxhImageEffectPluginCache::loadFromPlugin().
void tuttle::host::ofx::imageEffect::OfxhImageEffectPlugin::addContext (const std::string & context, OfxhImageEffectNodeDescriptor * ied)
Definition at line 146 of file OfxhImageEffectPlugin.cpp.
References _contexts, and _knownContexts.
imageEffect::OfxhImageEffectNode * tuttle::host::ofx::imageEffect::OfxhImageEffectPlugin::createInstance (const std::string & context)
this is called to make an instance of the effect the client data ptr is what is passed back to the client creation function
Todo:
we need to make sure action:load is called, then action:describe again (not because we are expecting the results to change, but because plugin might get confused otherwise), then a describe_in_context
Todo:
tuttle: don't use singleton here.
Definition at line 277 of file OfxhImageEffectPlugin.cpp.
References tuttle::host::core(), tuttle::host::ofx::imageEffect::OfxhImageEffectNode::createInstanceAction(), getDescriptorInContext(), tuttle::host::Core::getHost(), loadAndDescribeActions(), and tuttle::host::Host::newInstance().
Referenced by tuttle::host::createNode().
OfxhImageEffectNodeDescriptor & tuttle::host::ofx::imageEffect::OfxhImageEffectPlugin::describeInContextAction (const std::string & context) [private]
Definition at line 254 of file OfxhImageEffectPlugin.cpp.
References _contexts, _pluginLoadGuard, tuttle::host::core(), tuttle::host::ofx::property::ePropTypeString, getDescriptor(), and tuttle::host::ofx::property::OfxhSet::getHandle().
Referenced by getDescriptorInContext().
APICache::OfxhPluginAPICacheI & tuttle::host::ofx::imageEffect::OfxhImageEffectPlugin::getApiHandler () [virtual]
Returns:
the API handler this plugin was constructed by
Implements tuttle::host::ofx::OfxhPlugin.
Definition at line 124 of file OfxhImageEffectPlugin.cpp.
References _imageEffectPluginCache.
Referenced by loadAndDescribeActions().
const APICache::OfxhPluginAPICacheI & tuttle::host::ofx::imageEffect::OfxhImageEffectPlugin::getApiHandler () const [virtual]
Implements tuttle::host::ofx::OfxhPlugin.
Definition at line 129 of file OfxhImageEffectPlugin.cpp.
References _imageEffectPluginCache.
const std::set< std::string > & tuttle::host::ofx::imageEffect::OfxhImageEffectPlugin::getContexts () const
Definition at line 160 of file OfxhImageEffectPlugin.cpp.
References _knownContexts.
OfxhImageEffectNodeDescriptor & tuttle::host::ofx::imageEffect::OfxhImageEffectPlugin::getDescriptor ()
get the base image effect descriptor
get the image effect descriptor
Definition at line 135 of file OfxhImageEffectPlugin.cpp.
References _baseDescriptor.
Referenced by describeInContextAction(), tuttle::host::ofx::imageEffect::OfxhImageEffectPluginCache::getPluginByLabel(), initContexts(), loadAndDescribeActions(), and tuttle::host::ofx::imageEffect::OfxhImageEffectPluginCache::loadFromPlugin().
const OfxhImageEffectNodeDescriptor & tuttle::host::ofx::imageEffect::OfxhImageEffectPlugin::getDescriptor () const
get the base image effect descriptor, const version
get the image effect descriptor const version
Definition at line 141 of file OfxhImageEffectPlugin.cpp.
References _baseDescriptor.
OfxhImageEffectNodeDescriptor & tuttle::host::ofx::imageEffect::OfxhImageEffectPlugin::getDescriptorInContext (const std::string & context)
get the image effect descriptor for the context
Definition at line 233 of file OfxhImageEffectPlugin.cpp.
References _contexts, _knownContexts, describeInContextAction(), and tuttle::host::ofx::OfxhPluginDesc::getIdentifier().
Referenced by createInstance().
OfxhPluginLoadGuard* tuttle::host::ofx::imageEffect::OfxhImageEffectPlugin::getPluginLoadGuardPtr () [inline]
Definition at line 132 of file OfxhImageEffectPlugin.hpp.
References _pluginLoadGuard.
Referenced by tuttle::host::ofx::imageEffect::OfxhImageEffectNode::mainEntry(), and tuttle::host::ofx::imageEffect::OfxhImageEffectNode::OfxhImageEffectNode().
const OfxhPluginLoadGuard* tuttle::host::ofx::imageEffect::OfxhImageEffectPlugin::getPluginLoadGuardPtr () const [inline]
Definition at line 133 of file OfxhImageEffectPlugin.hpp.
References _pluginLoadGuard.
void tuttle::host::ofx::imageEffect::OfxhImageEffectPlugin::initContexts ()
Definition at line 177 of file OfxhImageEffectPlugin.cpp.
References addContext(), getDescriptor(), tuttle::host::ofx::property::OfxhSet::getDimension(), tuttle::host::ofx::imageEffect::OfxhImageEffectNodeBase::getProperties(), and tuttle::host::ofx::property::OfxhSet::getStringProperty().
Referenced by loadAndDescribeActions().
void tuttle::host::ofx::imageEffect::OfxhImageEffectPlugin::loadAndDescribeActions ()
Definition at line 189 of file OfxhImageEffectPlugin.cpp.
References _pluginLoadGuard, getApiHandler(), getDescriptor(), tuttle::host::ofx::OfxhPluginDesc::getIdentifier(), and initContexts().
Referenced by createInstance(), and tuttle::host::createNode().
bool tuttle::host::ofx::imageEffect::OfxhImageEffectPlugin::operator!= (const OfxhImageEffectPlugin & other) const [inline]
Definition at line 105 of file OfxhImageEffectPlugin.hpp.
References operator==().
bool tuttle::host::ofx::imageEffect::OfxhImageEffectPlugin::operator== (const OfxhImageEffectPlugin & other) const
Definition at line 111 of file OfxhImageEffectPlugin.cpp.
References _baseDescriptor.
Referenced by operator!=().
template<class Archive > void tuttle::host::ofx::imageEffect::OfxhImageEffectPlugin::serialize (Archive & ar, const unsigned int version) [inline, private]
Reimplemented from tuttle::host::ofx::OfxhPlugin.
Definition at line 151 of file OfxhImageEffectPlugin.hpp.
References _baseDescriptor, and _contexts.
void tuttle::host::ofx::imageEffect::OfxhImageEffectPlugin::setApiHandler (OfxhImageEffectPluginCache & api) [inline]
Definition at line 107 of file OfxhImageEffectPlugin.hpp.
References _imageEffectPluginCache.
void tuttle::host::ofx::imageEffect::OfxhImageEffectPlugin::setApiHandler (APICache::OfxhPluginAPICacheI & api) [virtual]
Implements tuttle::host::ofx::OfxhPlugin.
Definition at line 119 of file OfxhImageEffectPlugin.cpp.
References _imageEffectPluginCache.
bool tuttle::host::ofx::imageEffect::OfxhImageEffectPlugin::supportsContext (const std::string & context) const
Definition at line 165 of file OfxhImageEffectPlugin.cpp.
References _knownContexts.
Referenced by tuttle::host::createNode().
void tuttle::host::ofx::imageEffect::OfxhImageEffectPlugin::unloadAction ()
Definition at line 292 of file OfxhImageEffectPlugin.cpp.
References _pluginLoadGuard.
Friends And Related Function Documentation
friend class boost::serialization::access [friend]
Reimplemented from tuttle::host::ofx::OfxhPlugin.
Definition at line 149 of file OfxhImageEffectPlugin.hpp.
Field Documentation
boost::scoped_ptr<OfxhImageEffectNodeDescriptor> tuttle::host::ofx::imageEffect::OfxhImageEffectPlugin::_baseDescriptor [private]
NEEDS TO BE MADE WITH A FACTORY FUNCTION ON THE HOST!!!!!!
Todo:
tuttle: ???
Definition at line 84 of file OfxhImageEffectPlugin.hpp.
Referenced by getDescriptor(), operator==(), and serialize().
ContextMap tuttle::host::ofx::imageEffect::OfxhImageEffectPlugin::_contexts [private]
map to store contexts in
Definition at line 77 of file OfxhImageEffectPlugin.hpp.
Referenced by addContext(), describeInContextAction(), getDescriptorInContext(), and serialize().
OfxhImageEffectPluginCache* tuttle::host::ofx::imageEffect::OfxhImageEffectPlugin::_imageEffectPluginCache [private]
Definition at line 74 of file OfxhImageEffectPlugin.hpp.
Referenced by getApiHandler(), and setApiHandler().
ContextSet tuttle::host::ofx::imageEffect::OfxhImageEffectPlugin::_knownContexts [private]
Definition at line 78 of file OfxhImageEffectPlugin.hpp.
Referenced by addContext(), getContexts(), getDescriptorInContext(), and supportsContext().
boost::scoped_ptr<OfxhPluginLoadGuard> tuttle::host::ofx::imageEffect::OfxhImageEffectPlugin::_pluginLoadGuard [private]
Definition at line 79 of file OfxhImageEffectPlugin.hpp.
Referenced by describeInContextAction(), getPluginLoadGuardPtr(), loadAndDescribeActions(), unloadAction(), and ~OfxhImageEffectPlugin().
The documentation for this class was generated from the following files:
TuttleOFX/libraries/tuttle/src/tuttle/host/ofx/OfxhImageEffectPlugin.hpp
TuttleOFX/libraries/tuttle/src/tuttle/host/ofx/OfxhImageEffectPlugin.cpp