TuttleOFX: tuttle::host::attribute::ParamDouble Class Reference
tuttle::host::attribute::ParamDouble Class Reference
#include <ParamDouble.hpp>
Public Member Functions
ParamDouble (INode &effect, const std::string &name, const ofx::attribute::OfxhParamDescriptor &descriptor, const std::size_t index=0)
double getDefault () const
void setValue (const double &v, const ofx::attribute::EChange change) OFX_EXCEPTION_SPEC
We reimplement some functions of AnimatedParamDouble, because without them, the integer version takes the priority.
void setValueAtTime (const OfxTime time, const double &v, const ofx::attribute::EChange change) OFX_EXCEPTION_SPEC
void setValueAtIndex (const std::size_t index, const double &v, const ofx::attribute::EChange change) OFX_EXCEPTION_SPEC
void setValueAtTimeAndIndex (const OfxTime time, const std::size_t index, const double &v, const ofx::attribute::EChange change) OFX_EXCEPTION_SPEC
void setValue (const int &v, const ofx::attribute::EChange change) OFX_EXCEPTION_SPEC
Re-implementation for Int, to allows an implicit conversion from Int to Double.
void setValueAtTime (const OfxTime time, const int &v, const ofx::attribute::EChange change) OFX_EXCEPTION_SPEC
void setValueAtIndex (const std::size_t index, const int &v, const ofx::attribute::EChange change) OFX_EXCEPTION_SPEC
void setValueAtTimeAndIndex (const OfxTime time, const std::size_t index, const int &v, const ofx::attribute::EChange change) OFX_EXCEPTION_SPEC
Detailed Description
Definition at line 11 of file ParamDouble.hpp.
Constructor & Destructor Documentation
tuttle::host::attribute::ParamDouble::ParamDouble (INode & effect, const std::string & name, const ofx::attribute::OfxhParamDescriptor & descriptor, const std::size_t index = 0)
Definition at line 9 of file ParamDouble.cpp.
References tuttle::host::attribute::AnimatedParam< double, ofx::attribute::OfxhParamDouble >::_value, and getDefault().
Member Function Documentation
double tuttle::host::attribute::ParamDouble::getDefault () const
Definition at line 18 of file ParamDouble.cpp.
References tuttle::host::ofx::attribute::OfxhParamDouble::_index, and tuttle::host::ofx::attribute::OfxhAttribute::getProperties().
Referenced by ParamDouble().
void tuttle::host::attribute::ParamDouble::setValue (const double & v, const ofx::attribute::EChange change) [inline, virtual]
We reimplement some functions of AnimatedParamDouble, because without them, the integer version takes the priority.
Reimplemented from tuttle::host::attribute::AnimatedParamDouble.
Definition at line 21 of file ParamDouble.hpp.
Referenced by setValue().
void tuttle::host::attribute::ParamDouble::setValue (const int & v, const ofx::attribute::EChange change) [inline, virtual]
Re-implementation for Int, to allows an implicit conversion from Int to Double.
Reimplemented from tuttle::host::attribute::AnimatedParamDouble.
Definition at line 45 of file ParamDouble.hpp.
References setValue().
void tuttle::host::attribute::ParamDouble::setValueAtIndex (const std::size_t index, const double & v, const ofx::attribute::EChange change) [inline]
Definition at line 31 of file ParamDouble.hpp.
Referenced by setValueAtIndex().
void tuttle::host::attribute::ParamDouble::setValueAtIndex (const std::size_t index, const int & v, const ofx::attribute::EChange change) [inline]
Definition at line 55 of file ParamDouble.hpp.
References setValueAtIndex().
void tuttle::host::attribute::ParamDouble::setValueAtTime (const OfxTime time, const double & v, const ofx::attribute::EChange change) [inline, virtual]
Reimplemented from tuttle::host::attribute::AnimatedParamDouble.
Definition at line 26 of file ParamDouble.hpp.
Referenced by setValueAtTime().
void tuttle::host::attribute::ParamDouble::setValueAtTime (const OfxTime time, const int & v, const ofx::attribute::EChange change) [inline, virtual]
Reimplemented from tuttle::host::attribute::AnimatedParamDouble.
Definition at line 50 of file ParamDouble.hpp.
References setValueAtTime().
void tuttle::host::attribute::ParamDouble::setValueAtTimeAndIndex (const OfxTime time, const std::size_t index, const double & v, const ofx::attribute::EChange change) [inline]
Definition at line 36 of file ParamDouble.hpp.
Referenced by setValueAtTimeAndIndex().
void tuttle::host::attribute::ParamDouble::setValueAtTimeAndIndex (const OfxTime time, const std::size_t index, const int & v, const ofx::attribute::EChange change) [inline]
Definition at line 60 of file ParamDouble.hpp.
References setValueAtTimeAndIndex().
The documentation for this class was generated from the following files:
TuttleOFX/libraries/tuttle/src/tuttle/host/attribute/ParamDouble.hpp
TuttleOFX/libraries/tuttle/src/tuttle/host/attribute/ParamDouble.cpp