TuttleOFX: tuttle::host::ofx::OfxhPlugin Class Reference
tuttle::host::ofx::OfxhPlugin Class Reference
#include <OfxhPlugin.hpp>
Public Types
typedef OfxhPlugin This
Public Member Functions
OfxhPlugin ()
OfxhPlugin (OfxhPluginBinary &bin, int idx, OfxPlugin &o)
OfxhPlugin (OfxhPluginBinary &bin, int idx, const std::string &api, int apiVersion, const std::string &identifier, const std::string &rawIdentifier, int majorVersion, int minorVersion)
virtual ~OfxhPlugin ()=0
bool operator== (const This &other) const
bool operator!= (const This &other) const
void setBinary (OfxhPluginBinary &binary)
OfxhPluginBinary & getBinary ()
const OfxhPluginBinary & getBinary () const
void setIsSupported (bool isSupported)
bool isSupported () const
int getIndex () const
bool trumps (OfxhPlugin &other)
virtual void setApiHandler (APICache::OfxhPluginAPICacheI &)=0
virtual
APICache::OfxhPluginAPICacheI & getApiHandler ()=0
virtual const
APICache::OfxhPluginAPICacheI & getApiHandler () const =0
Protected Attributes
OfxhPluginBinary * _binary
the file I live inside
int _index
where I live inside that file
bool _isSupported
Indicates if the plugin can be loaded (actions: Load and Describe)
Private Member Functions
OfxhPlugin (const This &)
hidden
OfxhPlugin & operator= (const This &)
hidden
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Friends
class boost::serialization::access
Detailed Description
class that we use to manipulate a plugin.
Owned by the PluginBinary it lives inside. Plugins can only be pass about either by pointer or reference.
Definition at line 19 of file OfxhPlugin.hpp.
Member Typedef Documentation
typedef OfxhPlugin tuttle::host::ofx::OfxhPlugin::This
Reimplemented from tuttle::host::ofx::OfxhPluginDesc.
Reimplemented in tuttle::host::ofx::imageEffect::OfxhImageEffectPlugin.
Definition at line 22 of file OfxhPlugin.hpp.
Constructor & Destructor Documentation
tuttle::host::ofx::OfxhPlugin::OfxhPlugin (const This &) [private]
hidden
tuttle::host::ofx::OfxhPlugin::OfxhPlugin () [inline]
Definition at line 34 of file OfxhPlugin.hpp.
tuttle::host::ofx::OfxhPlugin::OfxhPlugin (OfxhPluginBinary & bin, int idx, OfxPlugin & o) [inline]
construct this based on the struct returned by the getNthPlugin() in the binary
Definition at line 43 of file OfxhPlugin.hpp.
tuttle::host::ofx::OfxhPlugin::OfxhPlugin (OfxhPluginBinary & bin, int idx, const std::string & api, int apiVersion, const std::string & identifier, const std::string & rawIdentifier, int majorVersion, int minorVersion) [inline]
construct me from the cache
Definition at line 52 of file OfxhPlugin.hpp.
tuttle::host::ofx::OfxhPlugin::~OfxhPlugin () [pure virtual]
Definition at line 7 of file OfxhPlugin.cpp.
Member Function Documentation
virtual APICache::OfxhPluginAPICacheI& tuttle::host::ofx::OfxhPlugin::getApiHandler () [pure virtual]
Implemented in tuttle::host::ofx::imageEffect::OfxhImageEffectPlugin.
Referenced by tuttle::host::ofx::OfxhPluginCache::scanDirectory(), and tuttle::host::ofx::OfxhPluginCache::scanPluginFiles().
virtual const APICache::OfxhPluginAPICacheI& tuttle::host::ofx::OfxhPlugin::getApiHandler () const [pure virtual]
Implemented in tuttle::host::ofx::imageEffect::OfxhImageEffectPlugin.
OfxhPluginBinary& tuttle::host::ofx::OfxhPlugin::getBinary () [inline]
Definition at line 68 of file OfxhPlugin.hpp.
References _binary.
Referenced by tuttle::host::ofx::OfxhPluginCache::addPlugin(), and tuttle::host::ofx::imageEffect::OfxhImageEffectNodeDescriptor::OfxhImageEffectNodeDescriptor().
const OfxhPluginBinary& tuttle::host::ofx::OfxhPlugin::getBinary () const [inline]
Definition at line 69 of file OfxhPlugin.hpp.
References _binary.
int tuttle::host::ofx::OfxhPlugin::getIndex () const [inline]
Definition at line 80 of file OfxhPlugin.hpp.
References _index.
Referenced by tuttle::host::ofx::OfxhPluginLoadGuard::OfxhPluginLoadGuard().
bool tuttle::host::ofx::OfxhPlugin::isSupported () const [inline]
Definition at line 75 of file OfxhPlugin.hpp.
References _isSupported.
Referenced by setIsSupported().
bool tuttle::host::ofx::OfxhPlugin::operator!= (const This & other) const [inline]
Definition at line 65 of file OfxhPlugin.hpp.
References operator==().
OfxhPlugin& tuttle::host::ofx::OfxhPlugin::operator= (const This &) [private]
hidden
bool tuttle::host::ofx::OfxhPlugin::operator== (const This & other) const
Definition at line 9 of file OfxhPlugin.cpp.
References _index.
Referenced by operator!=().
template<class Archive > void tuttle::host::ofx::OfxhPlugin::serialize (Archive & ar, const unsigned int version) [inline, private]
Reimplemented from tuttle::host::ofx::OfxhPluginDesc.
Reimplemented in tuttle::host::ofx::imageEffect::OfxhImageEffectPlugin.
Definition at line 114 of file OfxhPlugin.hpp.
References _index, and _isSupported.
virtual void tuttle::host::ofx::OfxhPlugin::setApiHandler (APICache::OfxhPluginAPICacheI &) [pure virtual]
Implemented in tuttle::host::ofx::imageEffect::OfxhImageEffectPlugin.
Referenced by tuttle::host::ofx::OfxhPluginCache::serialize().
void tuttle::host::ofx::OfxhPlugin::setBinary (OfxhPluginBinary & binary) [inline]
Definition at line 67 of file OfxhPlugin.hpp.
References _binary.
void tuttle::host::ofx::OfxhPlugin::setIsSupported (bool isSupported) [inline]
Definition at line 71 of file OfxhPlugin.hpp.
References _isSupported, and isSupported().
Referenced by tuttle::host::ofx::imageEffect::OfxhImageEffectPluginCache::loadFromPlugin().
bool tuttle::host::ofx::OfxhPlugin::trumps (OfxhPlugin & other) [inline]
Definition at line 85 of file OfxhPlugin.hpp.
References tuttle::host::ofx::OfxhPluginDesc::getVersionMajor(), and tuttle::host::ofx::OfxhPluginDesc::getVersionMinor().
Referenced by tuttle::host::ofx::OfxhPluginCache::addPlugin(), tuttle::host::ofx::imageEffect::OfxhImageEffectPluginCache::confirmPlugin(), tuttle::host::ofx::imageEffect::OfxhImageEffectPluginCache::getPluginById(), tuttle::host::ofx::OfxhPluginCache::getPluginById(), and tuttle::host::ofx::imageEffect::OfxhImageEffectPluginCache::getPluginByLabel().
Friends And Related Function Documentation
friend class boost::serialization::access [friend]
Reimplemented from tuttle::host::ofx::OfxhPluginDesc.
Reimplemented in tuttle::host::ofx::imageEffect::OfxhImageEffectPlugin.
Definition at line 112 of file OfxhPlugin.hpp.
Field Documentation
OfxhPluginBinary* tuttle::host::ofx::OfxhPlugin::_binary [protected]
the file I live inside
Definition at line 29 of file OfxhPlugin.hpp.
Referenced by getBinary(), and setBinary().
int tuttle::host::ofx::OfxhPlugin::_index [protected]
where I live inside that file
Definition at line 30 of file OfxhPlugin.hpp.
Referenced by getIndex(), operator==(), and serialize().
bool tuttle::host::ofx::OfxhPlugin::_isSupported [protected]
Indicates if the plugin can be loaded (actions: Load and Describe)
Definition at line 31 of file OfxhPlugin.hpp.
Referenced by isSupported(), serialize(), and setIsSupported().
The documentation for this class was generated from the following files:
TuttleOFX/libraries/tuttle/src/tuttle/host/ofx/OfxhPlugin.hpp
TuttleOFX/libraries/tuttle/src/tuttle/host/ofx/OfxhPlugin.cpp