TuttleOFX: tuttle::host::attribute::Attribute Class Reference
tuttle::host::attribute::Attribute Class Reference
#include <Attribute.hpp>
Public Member Functions
Attribute (INode &effect)
Attribute (const Attribute &other)
virtual ~Attribute ()=0
Attribute & operator= (const Attribute &other)
virtual const std::string & getName () const =0
const INode & getNode () const
Protected Attributes
INode & _effect
Detailed Description
Definition at line 13 of file Attribute.hpp.
Constructor & Destructor Documentation
tuttle::host::attribute::Attribute::Attribute (INode & effect)
Definition at line 9 of file Attribute.cpp.
tuttle::host::attribute::Attribute::Attribute (const Attribute & other)
Definition at line 13 of file Attribute.cpp.
tuttle::host::attribute::Attribute::~Attribute () [pure virtual]
Definition at line 17 of file Attribute.cpp.
Member Function Documentation
virtual const std::string& tuttle::host::attribute::Attribute::getName () const [pure virtual]
Implemented in tuttle::host::attribute::ClipImage, and tuttle::host::attribute::Param.
Referenced by tuttle::host::Graph::connect(), and tuttle::host::Graph::unconnect().
const INode & tuttle::host::attribute::Attribute::getNode () const
Definition at line 24 of file Attribute.cpp.
References _effect.
Referenced by tuttle::host::Graph::connect(), tuttle::host::ImageEffectNode::debugOutputImage(), tuttle::host::attribute::ClipImage::fetchRegionOfDefinition(), tuttle::host::ImageEffectNode::getDefaultTimeDomain(), tuttle::host::attribute::ClipImage::getFullName(), tuttle::host::attribute::ClipImage::getImage(), tuttle::host::attribute::ClipImage::getRemappedTime(), tuttle::host::attribute::ClipImage::getUnmappedFrameRate(), tuttle::host::ImageEffectNode::maximizeBitDepthFromReadsToWrites(), tuttle::host::ImageEffectNode::maximizeBitDepthFromWritesToReads(), and tuttle::host::Graph::unconnect().
Attribute & tuttle::host::attribute::Attribute::operator= (const Attribute & other)
Definition at line 19 of file Attribute.cpp.
Field Documentation
INode& tuttle::host::attribute::Attribute::_effect [protected]
Definition at line 16 of file Attribute.hpp.
Referenced by getNode().
The documentation for this class was generated from the following files:
TuttleOFX/libraries/tuttle/src/tuttle/host/attribute/Attribute.hpp
TuttleOFX/libraries/tuttle/src/tuttle/host/attribute/Attribute.cpp