TuttleOFX: TuttleOFX/libraries/tuttle/tests/ofx/properties/serialization.cpp File Reference
TuttleOFX/libraries/tuttle/tests/ofx/properties/serialization.cpp File Reference
#include <tuttle/test/unit_test.hpp>
#include <tuttle/common/utils/global.hpp>
#include <tuttle/host/Core.hpp>
#include <boost/archive/xml_oarchive.hpp>
#include <boost/archive/binary_oarchive.hpp>
#include <boost/archive/text_oarchive.hpp>
#include <boost/archive/xml_iarchive.hpp>
#include <boost/archive/binary_iarchive.hpp>
#include <boost/archive/text_iarchive.hpp>
#include <boost/serialization/serialization.hpp>
#include <boost/serialization/export.hpp>
#include <boost/serialization/extended_type_info.hpp>
#include <fstream>
#include <iostream>
Defines
#define testString_1_ro "testString_1_ro"
#define testString_2_rw "testString_2_rw"
#define testPointer_1_rw "testPointer_1_rw"
#define testDouble_2_ro "testDouble_2_ro"
#define testDouble_1_rw "testDouble_1_rw"
#define testInt_1_rw "testInt_1_rw"
#define testInt_2_rw "testInt_2_rw"
#define testInt_4_ro "testInt_4_ro"
Functions
BOOST_AUTO_TEST_CASE (properties_serialization)
Define Documentation
#define testDouble_1_rw "testDouble_1_rw"
#define testDouble_2_ro "testDouble_2_ro"
#define testInt_1_rw "testInt_1_rw"
#define testInt_2_rw "testInt_2_rw"
#define testInt_4_ro "testInt_4_ro"
#define testPointer_1_rw "testPointer_1_rw"
#define testString_1_ro "testString_1_ro"
#define testString_2_rw "testString_2_rw"
Function Documentation
BOOST_AUTO_TEST_CASE (properties_serialization)
Definition at line 24 of file serialization.cpp.
References tuttle::host::ofx::property::ePropTypeDouble, tuttle::host::ofx::property::ePropTypeInt, tuttle::host::ofx::property::ePropTypePointer, tuttle::host::ofx::property::ePropTypeString, tuttle::host::ofx::property::OfxhSet::setDoublePropertyN(), tuttle::host::ofx::property::OfxhSet::setIntProperty(), tuttle::host::ofx::property::OfxhSet::setStringProperty(), testDouble_1_rw, testDouble_2_ro, testInt_1_rw, testInt_2_rw, testInt_4_ro, testPointer_1_rw, testString_1_ro, and testString_2_rw.