TuttleOFX: tuttle::common::Color Class Reference
tuttle::common::Color Class Reference
#include <color.hpp>
Public Member Functions
~Color ()
void disable ()
void enable ()
Static Public Member Functions
static boost::shared_ptr< Color > get ()
Data Fields
std::string _blue
std::string _green
std::string _yellow
std::string _red
std::string _folder
std::string _file
std::string _std
std::string _error
Static Public Attributes
static boost::shared_ptr< Color > color
Private Member Functions
Color ()
Detailed Description
Definition at line 48 of file color.hpp.
Constructor & Destructor Documentation
tuttle::common::Color::Color () [inline, private]
Definition at line 51 of file color.hpp.
tuttle::common::Color::~Color () [inline]
Definition at line 57 of file color.hpp.
Member Function Documentation
void tuttle::common::Color::disable () [inline]
Definition at line 70 of file color.hpp.
References _blue, _error, _file, _folder, _green, _red, _std, and _yellow.
void tuttle::common::Color::enable () [inline]
Definition at line 83 of file color.hpp.
References _blue, _error, _file, _folder, _green, _red, _std, _yellow, tuttle::common::details::kColorBlue(), tuttle::common::details::kColorError(), tuttle::common::details::kColorFile(), tuttle::common::details::kColorFolder(), tuttle::common::details::kColorGreen(), tuttle::common::details::kColorRed(), tuttle::common::details::kColorStd(), and tuttle::common::details::kColorYellow().
boost::shared_ptr< Color > tuttle::common::Color::get () [static]
Definition at line 6 of file color.cpp.
References color.
Referenced by tuttle::host::ImageEffectNode::progressStart(), and tuttle::host::ComputeOptions::setColorEnable().
Field Documentation
std::string tuttle::common::Color::_blue
Definition at line 59 of file color.hpp.
Referenced by disable(), and enable().
std::string tuttle::common::Color::_error
Definition at line 68 of file color.hpp.
Referenced by disable(), and enable().
std::string tuttle::common::Color::_file
Definition at line 65 of file color.hpp.
Referenced by disable(), and enable().
std::string tuttle::common::Color::_folder
Definition at line 64 of file color.hpp.
Referenced by disable(), and enable().
std::string tuttle::common::Color::_green
Definition at line 60 of file color.hpp.
Referenced by disable(), and enable().
std::string tuttle::common::Color::_red
Definition at line 62 of file color.hpp.
Referenced by disable(), and enable().
std::string tuttle::common::Color::_std
Definition at line 67 of file color.hpp.
Referenced by disable(), and enable().
std::string tuttle::common::Color::_yellow
Definition at line 61 of file color.hpp.
Referenced by disable(), and enable().
boost::shared_ptr< Color > tuttle::common::Color::color [static]
Definition at line 99 of file color.hpp.
Referenced by get().
The documentation for this class was generated from the following files:
TuttleOFX/libraries/tuttle/src/tuttle/common/utils/color.hpp
TuttleOFX/libraries/tuttle/src/tuttle/common/utils/color.cpp