TuttleOFX: tuttle::host::ofx::attribute::OfxhParamDouble Class Reference
tuttle::host::ofx::attribute::OfxhParamDouble Class Reference
#include <OfxhParamDouble.hpp>
Public Types
typedef double BaseType
Public Member Functions
OfxhParamDouble (const OfxhParamDescriptor &descriptor, const std::string &name, OfxhParamSet &setInstance, const std::size_t index=0)
virtual void getValue (double &) const OFX_EXCEPTION_SPEC=0
virtual void getValueAtTime (const OfxTime time, double &) const OFX_EXCEPTION_SPEC=0
virtual void setValue (const double &, const EChange change) OFX_EXCEPTION_SPEC=0
virtual void setValueAtTime (const OfxTime time, const double &, const EChange change) OFX_EXCEPTION_SPEC=0
virtual void setValue (const int &v, const EChange change) OFX_EXCEPTION_SPEC
virtual void setValueAtTime (const OfxTime time, const int &v, const EChange change) OFX_EXCEPTION_SPEC
virtual void derive (const OfxTime time, double &) const OFX_EXCEPTION_SPEC=0
virtual void integrate (const OfxTime time1, const OfxTime time2, double &) const OFX_EXCEPTION_SPEC=0
virtual void getV (va_list arg) const OFX_EXCEPTION_SPEC
implementation of var args function
virtual void getV (const OfxTime time, va_list arg) const OFX_EXCEPTION_SPEC
implementation of var args function
virtual void setV (va_list arg, const EChange change) OFX_EXCEPTION_SPEC
implementation of var args function
virtual void setV (const OfxTime time, va_list arg, const EChange change) OFX_EXCEPTION_SPEC
implementation of var args function
virtual void deriveV (const OfxTime time, va_list arg) const OFX_EXCEPTION_SPEC
implementation of var args function
virtual void integrateV (const OfxTime time1, const OfxTime time2, va_list arg) const OFX_EXCEPTION_SPEC
implementation of var args function
std::ostream & displayValues (std::ostream &os) const
Protected Attributes
std::size_t _index
Detailed Description
Definition at line 14 of file OfxhParamDouble.hpp.
Member Typedef Documentation
typedef double tuttle::host::ofx::attribute::OfxhParamDouble::BaseType
Definition at line 22 of file OfxhParamDouble.hpp.
Constructor & Destructor Documentation
tuttle::host::ofx::attribute::OfxhParamDouble::OfxhParamDouble (const OfxhParamDescriptor & descriptor, const std::string & name, OfxhParamSet & setInstance, const std::size_t index = 0) [inline]
Definition at line 23 of file OfxhParamDouble.hpp.
References tuttle::host::ofx::property::OfxhSet::addNotifyHook(), and tuttle::host::ofx::attribute::OfxhAttribute::getEditableProperties().
Member Function Documentation
virtual void tuttle::host::ofx::attribute::OfxhParamDouble::derive (const OfxTime time, double &) const [pure virtual]
Implemented in tuttle::host::attribute::AnimatedParam< double, ofx::attribute::OfxhParamDouble >.
void tuttle::host::ofx::attribute::OfxhParamDouble::deriveV (const OfxTime time, va_list arg) const [virtual]
implementation of var args function
Reimplemented from tuttle::host::ofx::attribute::OfxhParam.
Definition at line 51 of file OfxhParamDouble.cpp.
std::ostream& tuttle::host::ofx::attribute::OfxhParamDouble::displayValues (std::ostream & os) const [inline, virtual]
Reimplemented from tuttle::host::ofx::attribute::OfxhParam.
Definition at line 70 of file OfxhParamDouble.hpp.
void tuttle::host::ofx::attribute::OfxhParamDouble::getV (va_list arg) const [virtual]
implementation of var args function
Reimplemented from tuttle::host::ofx::attribute::OfxhParam.
Definition at line 11 of file OfxhParamDouble.cpp.
void tuttle::host::ofx::attribute::OfxhParamDouble::getV (const OfxTime time, va_list arg) const [virtual]
implementation of var args function
Reimplemented from tuttle::host::ofx::attribute::OfxhParam.
Definition at line 21 of file OfxhParamDouble.cpp.
virtual void tuttle::host::ofx::attribute::OfxhParamDouble::getValue (double &) const [pure virtual]
Implemented in tuttle::host::attribute::AnimatedParam< double, ofx::attribute::OfxhParamDouble >.
virtual void tuttle::host::ofx::attribute::OfxhParamDouble::getValueAtTime (const OfxTime time, double &) const [pure virtual]
Implemented in tuttle::host::attribute::AnimatedParam< double, ofx::attribute::OfxhParamDouble >.
virtual void tuttle::host::ofx::attribute::OfxhParamDouble::integrate (const OfxTime time1, const OfxTime time2, double &) const [pure virtual]
Implemented in tuttle::host::attribute::AnimatedParam< double, ofx::attribute::OfxhParamDouble >.
void tuttle::host::ofx::attribute::OfxhParamDouble::integrateV (const OfxTime time1, const OfxTime time2, va_list arg) const [virtual]
implementation of var args function
Reimplemented from tuttle::host::ofx::attribute::OfxhParam.
Definition at line 61 of file OfxhParamDouble.cpp.
void tuttle::host::ofx::attribute::OfxhParamDouble::setV (va_list arg, const EChange change) [virtual]
implementation of var args function
Reimplemented from tuttle::host::ofx::attribute::OfxhParam.
Definition at line 31 of file OfxhParamDouble.cpp.
void tuttle::host::ofx::attribute::OfxhParamDouble::setV (const OfxTime time, va_list arg, const EChange change) [virtual]
implementation of var args function
Reimplemented from tuttle::host::ofx::attribute::OfxhParam.
Definition at line 41 of file OfxhParamDouble.cpp.
virtual void tuttle::host::ofx::attribute::OfxhParamDouble::setValue (const double & , const EChange change) [pure virtual]
Implemented in tuttle::host::attribute::AnimatedParam< double, ofx::attribute::OfxhParamDouble >, tuttle::host::attribute::AnimatedParamDouble, and tuttle::host::attribute::ParamDouble.
Referenced by setValue().
virtual void tuttle::host::ofx::attribute::OfxhParamDouble::setValue (const int & v, const EChange change) [inline, virtual]
Reimplemented in tuttle::host::attribute::ParamDouble, and tuttle::host::attribute::AnimatedParamDouble.
Definition at line 37 of file OfxhParamDouble.hpp.
References setValue().
virtual void tuttle::host::ofx::attribute::OfxhParamDouble::setValueAtTime (const OfxTime time, const double & , const EChange change) [pure virtual]
Implemented in tuttle::host::attribute::AnimatedParam< double, ofx::attribute::OfxhParamDouble >, tuttle::host::attribute::AnimatedParamDouble, and tuttle::host::attribute::ParamDouble.
Referenced by setValueAtTime().
virtual void tuttle::host::ofx::attribute::OfxhParamDouble::setValueAtTime (const OfxTime time, const int & v, const EChange change) [inline, virtual]
Reimplemented in tuttle::host::attribute::ParamDouble, and tuttle::host::attribute::AnimatedParamDouble.
Definition at line 42 of file OfxhParamDouble.hpp.
References setValueAtTime().
Field Documentation
std::size_t tuttle::host::ofx::attribute::OfxhParamDouble::_index [protected]
Definition at line 19 of file OfxhParamDouble.hpp.
Referenced by tuttle::host::attribute::ParamDouble::getDefault().
The documentation for this class was generated from the following files:
TuttleOFX/libraries/tuttle/src/tuttle/host/ofx/attribute/OfxhParamDouble.hpp
TuttleOFX/libraries/tuttle/src/tuttle/host/ofx/attribute/OfxhParamDouble.cpp