TuttleOFX: tuttle::host::PreloadPlugins Struct Reference
tuttle::host::PreloadPlugins Struct Reference
#include <PreloadPlugins.hpp>
Public Member Functions
PreloadPlugins (bool usingCache=false)
~PreloadPlugins ()
Detailed Description
Definition at line 11 of file PreloadPlugins.hpp.
Constructor & Destructor Documentation
tuttle::host::PreloadPlugins::PreloadPlugins (bool usingCache = false) [inline]
Definition at line 13 of file PreloadPlugins.hpp.
References tuttle::host::ofx::OfxhPluginCache::addDirectoryToPath(), tuttle::host::core(), tuttle::host::Core::getPluginCache(), tuttle::host::Core::preload(), and TUTTLE_LOG_TRACE.
tuttle::host::PreloadPlugins::~PreloadPlugins () [inline]
Definition at line 24 of file PreloadPlugins.hpp.
The documentation for this struct was generated from the following file:
TuttleOFX/libraries/tuttle/src/tuttle/host/PreloadPlugins.hpp