TuttleOFX: tuttle::host::ComputeOptions Class Reference
tuttle::host::ComputeOptions Class Reference
#include <ComputeOptions.hpp>
Public Types
typedef ComputeOptions This
Public Member Functions
ComputeOptions ()
ComputeOptions (const int frame)
ComputeOptions (const int begin, const int end, const int step=1)
ComputeOptions (const ComputeOptions &options)
ComputeOptions & operator= (const ComputeOptions &other)
const std::list< TimeRange > & getTimeRanges () const
int getBegin () const
int getEnd () const
This & setTimeRange (const int begin, const int end, const int step=1)
This & setTimeRange (const TimeRange &timeRange)
This & addTimeRange (const int begin, const int end, const int step=1)
This & addTimeRange (const TimeRange &timeRange)
This & setBegin (const int &beginTime)
This & setEnd (const int &endTime)
This & setRenderScale (const double x, const double y)
To get a preview of the result, you could set a renderscale.
const OfxPointD & getRenderScale () const
This & setContinueOnError (const bool v=true)
Continue as much as possible after an error. If an image file inside an image sequence failed to be loaded, we continue to process other images of the sequence.
bool getContinueOnError () const
This & setContinueOnMissingFile (const bool v=true)
Continue as much as possible after an error. If an image file inside an image sequence failed to be loaded, we continue to process other images of the sequence.
bool getContinueOnMissingFile () const
This & setReturnBuffers (const bool v=true)
To get output buffer of all output nodes.
bool getReturnBuffers () const
This & setVerboseLevel (const EVerboseLevel level)
Set the verbose level of the process.
This & setColorEnable (const bool enable=true)
Set the output color enabled or not.
This & setIsInteractive (const bool v=true)
Inform plugins about the kind of process: batch or interactive.
bool getIsInteractive () const
This & setForceIdentityNodesProcess (const bool v=true)
For debug puposes only, you could force to call the process on all identity nodes. This case should never happens to the plugin, so it may fail to do it.
bool getForceIdentityNodesProcess () const
void abort ()
The application would like to abort the process (from another thread).
bool getAbort () const
Has someone asked to abort the process?
void setProgressHandle (boost::shared_ptr< IProgressHandle > progressHandle)
A handle to follow the progress (start, end...) of the compute.
bool isProgressHandleSet () const
void beginSequenceHandle () const
void beginFrameHandle () const
void setupAtTimeHandle () const
void processAtTimeHandle () const
void endFrameHandle () const
void endSequenceHandle () const
Private Member Functions
void init ()
Private Attributes
std::list< TimeRange > _timeRanges
OfxPointD _renderScale
int _begin
int _end
bool _continueOnError
bool _continueOnMissingFile
bool _forceIdentityNodesProcess
bool _returnBuffers
bool _isInteractive
boost::atomic_bool _abort
boost::shared_ptr
< IProgressHandle > _progressHandle
Detailed Description
Definition at line 66 of file ComputeOptions.hpp.
Member Typedef Documentation
typedef ComputeOptions tuttle::host::ComputeOptions::This
Definition at line 69 of file ComputeOptions.hpp.
Constructor & Destructor Documentation
tuttle::host::ComputeOptions::ComputeOptions () [inline]
Definition at line 71 of file ComputeOptions.hpp.
References init().
tuttle::host::ComputeOptions::ComputeOptions (const int frame) [inline, explicit]
Definition at line 80 of file ComputeOptions.hpp.
References _timeRanges, and init().
tuttle::host::ComputeOptions::ComputeOptions (const int begin, const int end, const int step = 1) [inline]
Definition at line 89 of file ComputeOptions.hpp.
References _timeRanges, and init().
tuttle::host::ComputeOptions::ComputeOptions (const ComputeOptions & options) [inline]
Definition at line 98 of file ComputeOptions.hpp.
Member Function Documentation
void tuttle::host::ComputeOptions::abort () [inline]
The application would like to abort the process (from another thread).
Definition at line 266 of file ComputeOptions.hpp.
References _abort.
Referenced by tuttle::host::ThreadEnv::abort().
This& tuttle::host::ComputeOptions::addTimeRange (const int begin, const int end, const int step = 1) [inline]
Definition at line 156 of file ComputeOptions.hpp.
Referenced by setTimeRange().
This& tuttle::host::ComputeOptions::addTimeRange (const TimeRange & timeRange) [inline]
Definition at line 161 of file ComputeOptions.hpp.
References _timeRanges.
void tuttle::host::ComputeOptions::beginFrameHandle () const [inline]
Definition at line 291 of file ComputeOptions.hpp.
References _progressHandle, and isProgressHandleSet().
Referenced by tuttle::host::graph::ProcessGraph::process().
void tuttle::host::ComputeOptions::beginSequenceHandle () const [inline]
Definition at line 286 of file ComputeOptions.hpp.
References _progressHandle, and isProgressHandleSet().
Referenced by tuttle::host::graph::ProcessGraph::beginSequence().
void tuttle::host::ComputeOptions::endFrameHandle () const [inline]
Definition at line 306 of file ComputeOptions.hpp.
References _progressHandle, and isProgressHandleSet().
Referenced by tuttle::host::graph::ProcessGraph::process().
void tuttle::host::ComputeOptions::endSequenceHandle () const [inline]
Definition at line 311 of file ComputeOptions.hpp.
References _progressHandle, and isProgressHandleSet().
Referenced by tuttle::host::graph::ProcessGraph::endSequence().
bool tuttle::host::ComputeOptions::getAbort () const [inline]
Has someone asked to abort the process?
Definition at line 273 of file ComputeOptions.hpp.
References _abort.
Referenced by tuttle::host::graph::ProcessGraph::process().
int tuttle::host::ComputeOptions::getBegin () const [inline]
Definition at line 141 of file ComputeOptions.hpp.
References _begin.
Referenced by tuttle::host::graph::ProcessGraph::computeTimeRange().
bool tuttle::host::ComputeOptions::getContinueOnError () const [inline]
Definition at line 199 of file ComputeOptions.hpp.
References _continueOnError.
Referenced by tuttle::host::graph::ProcessGraph::process().
bool tuttle::host::ComputeOptions::getContinueOnMissingFile () const [inline]
Definition at line 210 of file ComputeOptions.hpp.
References _continueOnMissingFile.
Referenced by tuttle::host::graph::ProcessGraph::process().
int tuttle::host::ComputeOptions::getEnd () const [inline]
Definition at line 142 of file ComputeOptions.hpp.
References _end.
Referenced by tuttle::host::graph::ProcessGraph::computeTimeRange().
bool tuttle::host::ComputeOptions::getForceIdentityNodesProcess () const [inline]
Definition at line 261 of file ComputeOptions.hpp.
References _forceIdentityNodesProcess.
Referenced by tuttle::host::graph::ProcessGraph::setupAtTime().
bool tuttle::host::ComputeOptions::getIsInteractive () const [inline]
Definition at line 250 of file ComputeOptions.hpp.
References _isInteractive.
Referenced by tuttle::host::graph::ProcessGraph::ProcessGraph().
const OfxPointD& tuttle::host::ComputeOptions::getRenderScale () const [inline]
Definition at line 188 of file ComputeOptions.hpp.
References _renderScale.
Referenced by tuttle::host::graph::ProcessGraph::ProcessGraph().
bool tuttle::host::ComputeOptions::getReturnBuffers () const [inline]
Definition at line 220 of file ComputeOptions.hpp.
References _returnBuffers.
Referenced by tuttle::host::graph::ProcessGraph::processAtTime().
const std::list<TimeRange>& tuttle::host::ComputeOptions::getTimeRanges () const [inline]
Definition at line 139 of file ComputeOptions.hpp.
References _timeRanges.
Referenced by tuttle::host::graph::ProcessGraph::computeTimeRange().
void tuttle::host::ComputeOptions::init () [inline, private]
Definition at line 126 of file ComputeOptions.hpp.
References tuttle::host::eVerboseLevelWarning, setColorEnable(), setContinueOnError(), setContinueOnMissingFile(), setForceIdentityNodesProcess(), setIsInteractive(), setRenderScale(), setReturnBuffers(), and setVerboseLevel().
Referenced by ComputeOptions().
bool tuttle::host::ComputeOptions::isProgressHandleSet () const [inline]
Definition at line 282 of file ComputeOptions.hpp.
References _progressHandle.
Referenced by beginFrameHandle(), beginSequenceHandle(), endFrameHandle(), endSequenceHandle(), processAtTimeHandle(), and setupAtTimeHandle().
ComputeOptions& tuttle::host::ComputeOptions::operator= (const ComputeOptions & other) [inline]
Definition at line 106 of file ComputeOptions.hpp.
References _begin, _continueOnError, _continueOnMissingFile, _end, _forceIdentityNodesProcess, _isInteractive, _renderScale, _returnBuffers, and _timeRanges.
void tuttle::host::ComputeOptions::processAtTimeHandle () const [inline]
Definition at line 301 of file ComputeOptions.hpp.
References _progressHandle, and isProgressHandleSet().
Referenced by tuttle::host::graph::ProcessGraph::processAtTime().
This& tuttle::host::ComputeOptions::setBegin (const int & beginTime) [inline]
Definition at line 167 of file ComputeOptions.hpp.
References _begin.
This& tuttle::host::ComputeOptions::setColorEnable (const bool enable = true) [inline]
Set the output color enabled or not.
Definition at line 234 of file ComputeOptions.hpp.
References tuttle::common::Color::get().
Referenced by init().
This& tuttle::host::ComputeOptions::setContinueOnError (const bool v = true) [inline]
Continue as much as possible after an error. If an image file inside an image sequence failed to be loaded, we continue to process other images of the sequence.
Definition at line 194 of file ComputeOptions.hpp.
References _continueOnError.
Referenced by init().
This& tuttle::host::ComputeOptions::setContinueOnMissingFile (const bool v = true) [inline]
Continue as much as possible after an error. If an image file inside an image sequence failed to be loaded, we continue to process other images of the sequence.
Definition at line 205 of file ComputeOptions.hpp.
References _continueOnMissingFile.
Referenced by init().
This& tuttle::host::ComputeOptions::setEnd (const int & endTime) [inline]
Definition at line 173 of file ComputeOptions.hpp.
References _end.
This& tuttle::host::ComputeOptions::setForceIdentityNodesProcess (const bool v = true) [inline]
For debug puposes only, you could force to call the process on all identity nodes. This case should never happens to the plugin, so it may fail to do it.
Definition at line 256 of file ComputeOptions.hpp.
References _forceIdentityNodesProcess.
Referenced by init().
This& tuttle::host::ComputeOptions::setIsInteractive (const bool v = true) [inline]
Inform plugins about the kind of process: batch or interactive.
Definition at line 245 of file ComputeOptions.hpp.
References _isInteractive.
Referenced by init().
void tuttle::host::ComputeOptions::setProgressHandle (boost::shared_ptr< IProgressHandle > progressHandle) [inline]
A handle to follow the progress (start, end...) of the compute.
Definition at line 278 of file ComputeOptions.hpp.
References _progressHandle.
This& tuttle::host::ComputeOptions::setRenderScale (const double x, const double y) [inline]
To get a preview of the result, you could set a renderscale.
Definition at line 182 of file ComputeOptions.hpp.
References _renderScale.
Referenced by init().
This& tuttle::host::ComputeOptions::setReturnBuffers (const bool v = true) [inline]
To get output buffer of all output nodes.
Definition at line 215 of file ComputeOptions.hpp.
References _returnBuffers.
Referenced by init(), and tuttle::host::ThreadEnv::ThreadEnv().
This& tuttle::host::ComputeOptions::setTimeRange (const int begin, const int end, const int step = 1) [inline]
Definition at line 144 of file ComputeOptions.hpp.
References _timeRanges, and addTimeRange().
Referenced by BOOST_AUTO_TEST_CASE(), and tuttle::host::loadAndGenerateThumbnail().
This& tuttle::host::ComputeOptions::setTimeRange (const TimeRange & timeRange) [inline]
Definition at line 150 of file ComputeOptions.hpp.
References _timeRanges.
void tuttle::host::ComputeOptions::setupAtTimeHandle () const [inline]
Definition at line 296 of file ComputeOptions.hpp.
References _progressHandle, and isProgressHandleSet().
Referenced by tuttle::host::graph::ProcessGraph::setupAtTime().
This& tuttle::host::ComputeOptions::setVerboseLevel (const EVerboseLevel level) [inline]
Set the verbose level of the process.
Definition at line 225 of file ComputeOptions.hpp.
References tuttle::common::Formatter::get().
Referenced by init(), and tuttle::host::loadAndGenerateThumbnail().
Field Documentation
boost::atomic_bool tuttle::host::ComputeOptions::_abort [private]
Definition at line 331 of file ComputeOptions.hpp.
Referenced by abort(), and getAbort().
int tuttle::host::ComputeOptions::_begin [private]
Definition at line 322 of file ComputeOptions.hpp.
Referenced by getBegin(), operator=(), and setBegin().
bool tuttle::host::ComputeOptions::_continueOnError [private]
Definition at line 325 of file ComputeOptions.hpp.
Referenced by getContinueOnError(), operator=(), and setContinueOnError().
bool tuttle::host::ComputeOptions::_continueOnMissingFile [private]
Definition at line 326 of file ComputeOptions.hpp.
Referenced by getContinueOnMissingFile(), operator=(), and setContinueOnMissingFile().
int tuttle::host::ComputeOptions::_end [private]
Definition at line 323 of file ComputeOptions.hpp.
Referenced by getEnd(), operator=(), and setEnd().
bool tuttle::host::ComputeOptions::_forceIdentityNodesProcess [private]
Definition at line 327 of file ComputeOptions.hpp.
Referenced by getForceIdentityNodesProcess(), operator=(), and setForceIdentityNodesProcess().
bool tuttle::host::ComputeOptions::_isInteractive [private]
Definition at line 329 of file ComputeOptions.hpp.
Referenced by getIsInteractive(), operator=(), and setIsInteractive().
boost::shared_ptr<IProgressHandle> tuttle::host::ComputeOptions::_progressHandle [private]
Definition at line 333 of file ComputeOptions.hpp.
Referenced by beginFrameHandle(), beginSequenceHandle(), endFrameHandle(), endSequenceHandle(), isProgressHandleSet(), processAtTimeHandle(), setProgressHandle(), and setupAtTimeHandle().
OfxPointD tuttle::host::ComputeOptions::_renderScale [private]
Definition at line 320 of file ComputeOptions.hpp.
Referenced by getRenderScale(), operator=(), and setRenderScale().
bool tuttle::host::ComputeOptions::_returnBuffers [private]
Definition at line 328 of file ComputeOptions.hpp.
Referenced by getReturnBuffers(), operator=(), and setReturnBuffers().
std::list<TimeRange> tuttle::host::ComputeOptions::_timeRanges [private]
Definition at line 318 of file ComputeOptions.hpp.
Referenced by addTimeRange(), ComputeOptions(), getTimeRanges(), operator=(), and setTimeRange().
The documentation for this class was generated from the following file:
TuttleOFX/libraries/tuttle/src/tuttle/host/ComputeOptions.hpp