TuttleOFX: tuttle::host::ofx::property Namespace Reference
tuttle::host::ofx::property Namespace Reference
Data Structures
class OfxhGetHook
class OfxhNotifyHook
class OfxhProperty
base class for all properties
struct OfxhIntValue
type holder, for integers, used to template up int properties
struct OfxhDoubleValue
type holder, for doubles, used to template up double properties
struct OfxhPointerValue
type holder, for pointers, used to template up pointer properties
struct OfxhStringValue
type holder, for strings, used to template up string properties
class OfxhPropertyTemplate
struct OfxhPropSpec
class OfxhSet
Typedefs
typedef OfxhPropertyTemplate
< OfxhIntValue > Int
typedef OfxhPropertyTemplate
< OfxhDoubleValue > Double
Our int property.
typedef OfxhPropertyTemplate
< OfxhStringValue > String
Our double property.
typedef OfxhPropertyTemplate
< OfxhPointerValue > Pointer
Our string property.
typedef boost::ptr_map
< std::string, OfxhProperty > PropertyMap
A std::map of properties by name.
Enumerations
enum EPropType {
ePropTypeNone = -1, ePropTypeInt = 0, ePropTypeDouble = 1, ePropTypeString = 2,
ePropTypePointer = 3
}
type of a property
enum EModifiedBy { eModifiedByHost = 0, eModifiedByPlugin }
Functions
void * getPropertySuite (const int version)
return the OFX function suite that manages properties
std::string mapTypeEnumToString (const EPropType &e)
OfxhProperty * new_clone (const OfxhProperty &p)
int castToAPIType (int i)
void * castToAPIType (void *v)
double castToAPIType (double d)
const char * castToAPIType (const std::string &s)
std::ostream & operator<< (std::ostream &os, const OfxhSet &v)
Typedef Documentation
typedef OfxhPropertyTemplate<OfxhDoubleValue> tuttle::host::ofx::property::Double
Our int property.
Definition at line 241 of file OfxhPropertyTemplate.hpp.
typedef OfxhPropertyTemplate<OfxhIntValue> tuttle::host::ofx::property::Int
Definition at line 240 of file OfxhPropertyTemplate.hpp.
typedef OfxhPropertyTemplate<OfxhPointerValue> tuttle::host::ofx::property::Pointer
Our string property.
Definition at line 243 of file OfxhPropertyTemplate.hpp.
typedef boost::ptr_map<std::string, OfxhProperty> tuttle::host::ofx::property::PropertyMap
A std::map of properties by name.
Definition at line 54 of file OfxhSet.hpp.
typedef OfxhPropertyTemplate<OfxhStringValue> tuttle::host::ofx::property::String
Our double property.
Definition at line 242 of file OfxhPropertyTemplate.hpp.
Enumeration Type Documentation
enum tuttle::host::ofx::property::EModifiedBy
Enumerator:
eModifiedByHost
eModifiedByPlugin
Definition at line 91 of file OfxhProperty.hpp.
enum tuttle::host::ofx::property::EPropType
type of a property
Enumerator:
ePropTypeNone
ePropTypeInt
ePropTypeDouble
ePropTypeString
ePropTypePointer
Definition at line 63 of file OfxhProperty.hpp.
Function Documentation
int tuttle::host::ofx::property::castToAPIType (int i) [inline]
Definition at line 59 of file OfxhPropertyTemplate.cpp.
Referenced by tuttle::host::ofx::property::OfxhPropertyTemplate< T >::getValueN(), and tuttle::host::ofx::property::OfxhPropertyTemplate< T >::getValueNRaw().
void* tuttle::host::ofx::property::castToAPIType (void * v) [inline]
Definition at line 64 of file OfxhPropertyTemplate.cpp.
double tuttle::host::ofx::property::castToAPIType (double d) [inline]
Definition at line 69 of file OfxhPropertyTemplate.cpp.
const char* tuttle::host::ofx::property::castToAPIType (const std::string & s) [inline]
Definition at line 74 of file OfxhPropertyTemplate.cpp.
void * tuttle::host::ofx::property::getPropertySuite (const int version)
return the OFX function suite that manages properties
Definition at line 267 of file OfxhPropertySuite.cpp.
Referenced by tuttle::host::ofx::OfxhHost::fetchSuite().
std::string tuttle::host::ofx::property::mapTypeEnumToString (const EPropType & e) [inline]
Definition at line 72 of file OfxhProperty.hpp.
References ePropTypeDouble, ePropTypeInt, ePropTypeNone, ePropTypePointer, and ePropTypeString.
Referenced by tuttle::host::ofx::property::OfxhSet::createProperty(), and operator<<().
OfxhProperty* tuttle::host::ofx::property::new_clone (const OfxhProperty & p) [inline]
Definition at line 232 of file OfxhProperty.hpp.
References tuttle::host::ofx::property::OfxhProperty::clone().
std::ostream& tuttle::host::ofx::property::operator<< (std::ostream & os, const OfxhSet & v)
Definition at line 372 of file OfxhSet.cpp.
References tuttle::host::ofx::property::OfxhSet::_props, eModifiedByHost, tuttle::host::ofx::property::OfxhProperty::getDimension(), tuttle::host::ofx::property::OfxhProperty::getModifiedBy(), tuttle::host::ofx::property::OfxhProperty::getPluginReadOnly(), tuttle::host::ofx::property::OfxhProperty::getStringValueAt(), tuttle::host::ofx::property::OfxhProperty::getType(), and mapTypeEnumToString().