TuttleOFX: tuttle::host::InputBufferWrapper Class Reference
tuttle::host::InputBufferWrapper Class Reference
#include <InputBufferWrapper.hpp>
Public Types
enum EMode { eModeBuffer, eModeCallback }
enum EPixelComponent { ePixelComponentRGBA, ePixelComponentRGB, ePixelComponentAlpha }
enum EBitDepth { eBitDepthUByte, eBitDepthUShort, eBitDepthFloat }
enum EImageOrientation { eImageOrientationFromTopToBottom, eImageOrientationFromBottomToTop }
enum EField { eFieldBoth, eFieldLower, eFieldUpper }
typedef void * CustomDataPtr
typedef void(* CallbackInputImagePtr)(OfxTime time, CustomDataPtr outputCustomData, void **rawdata, int *width, int *height, int *rowSizeBytes)
typedef void(* CallbackDestroyCustomDataPtr)(CustomDataPtr outputCustomData)
Public Member Functions
InputBufferWrapper (INode &node)
InputBufferWrapper ()
~InputBufferWrapper ()
INode & getNode ()
void setMode (const EMode mode)
void setBuffer (void *rawBuffer)
void set2DArrayBuffer (unsigned char *rawBuffer, int height, int width)
void set3DArrayBuffer (unsigned char *rawBuffer, int height, int width, int nbComponents)
void set2DArrayBuffer (unsigned short *rawBuffer, int height, int width)
void set3DArrayBuffer (unsigned short *rawBuffer, int height, int width, int nbComponents)
void set2DArrayBuffer (float *rawBuffer, int height, int width)
void set3DArrayBuffer (float *rawBuffer, int height, int width, int nbComponents)
void setSize (const int width, const int height)
void setComponents (const EPixelComponent components)
void setBitDepth (const EBitDepth bitDepth)
void setRowDistanceSize (const int rowDistanceBytes)
void setOrientation (const EImageOrientation orientation)
void setRawImageBuffer (void *rawBuffer, const int width, const int height, const EPixelComponent components, const EBitDepth bitDepth, const int rowDistanceBytes=0, const EImageOrientation orientation=eImageOrientationFromBottomToTop)
void setRawImageBuffer (unsigned char *rawBuffer, const int width, const int height, const EPixelComponent components, const int rowDistanceBytes=0, const EImageOrientation orientation=eImageOrientationFromBottomToTop)
void setRawImageBuffer (unsigned short *rawBuffer, const int width, const int height, const EPixelComponent components, const int rowDistanceBytes=0, const EImageOrientation orientation=eImageOrientationFromBottomToTop)
void setRawImageBuffer (float *rawBuffer, const int width, const int height, const EPixelComponent components, const int rowDistanceBytes=0, const EImageOrientation orientation=eImageOrientationFromBottomToTop)
void setCallback (CallbackInputImagePtr callback, CustomDataPtr customData=NULL, CallbackDestroyCustomDataPtr destroyCustomData=NULL)
Private Member Functions
void set2DArrayBuffer (void *rawBuffer, const int width, const int height)
void set3DArrayBuffer (void *rawBuffer, const int width, const int height, const int nbComponents)
Private Attributes
INode * _node
Detailed Description
Definition at line 15 of file InputBufferWrapper.hpp.
Member Typedef Documentation
typedef void(* tuttle::host::InputBufferWrapper::CallbackDestroyCustomDataPtr)(CustomDataPtr outputCustomData)
Definition at line 49 of file InputBufferWrapper.hpp.
typedef void(* tuttle::host::InputBufferWrapper::CallbackInputImagePtr)(OfxTime time, CustomDataPtr outputCustomData, void **rawdata, int *width, int *height, int *rowSizeBytes)
Definition at line 48 of file InputBufferWrapper.hpp.
typedef void* tuttle::host::InputBufferWrapper::CustomDataPtr
Definition at line 47 of file InputBufferWrapper.hpp.
Member Enumeration Documentation
enum tuttle::host::InputBufferWrapper::EBitDepth
Enumerator:
eBitDepthUByte
eBitDepthUShort
eBitDepthFloat
Definition at line 29 of file InputBufferWrapper.hpp.
enum tuttle::host::InputBufferWrapper::EField
Enumerator:
eFieldBoth
eFieldLower
eFieldUpper
Definition at line 40 of file InputBufferWrapper.hpp.
enum tuttle::host::InputBufferWrapper::EImageOrientation
Enumerator:
eImageOrientationFromTopToBottom
eImageOrientationFromBottomToTop
Definition at line 35 of file InputBufferWrapper.hpp.
enum tuttle::host::InputBufferWrapper::EMode
Enumerator:
eModeBuffer
eModeCallback
Definition at line 18 of file InputBufferWrapper.hpp.
enum tuttle::host::InputBufferWrapper::EPixelComponent
Enumerator:
ePixelComponentRGBA
ePixelComponentRGB
ePixelComponentAlpha
Definition at line 23 of file InputBufferWrapper.hpp.
Constructor & Destructor Documentation
tuttle::host::InputBufferWrapper::InputBufferWrapper (INode & node) [inline]
Definition at line 55 of file InputBufferWrapper.hpp.
tuttle::host::InputBufferWrapper::InputBufferWrapper () [inline]
Definition at line 58 of file InputBufferWrapper.hpp.
tuttle::host::InputBufferWrapper::~InputBufferWrapper () [inline]
Definition at line 61 of file InputBufferWrapper.hpp.
Member Function Documentation
INode& tuttle::host::InputBufferWrapper::getNode () [inline]
Definition at line 64 of file InputBufferWrapper.hpp.
References _node.
void tuttle::host::InputBufferWrapper::set2DArrayBuffer (void * rawBuffer, const int width, const int height) [private]
Definition at line 35 of file InputBufferWrapper.cpp.
References tuttle::ofx::imageEffect::ePixelComponentAlpha.
Referenced by set2DArrayBuffer().
void tuttle::host::InputBufferWrapper::set2DArrayBuffer (unsigned char * rawBuffer, int height, int width) [inline]
Definition at line 73 of file InputBufferWrapper.hpp.
References eBitDepthUByte, set2DArrayBuffer(), and setBitDepth().
void tuttle::host::InputBufferWrapper::set2DArrayBuffer (unsigned short * rawBuffer, int height, int width) [inline]
Definition at line 84 of file InputBufferWrapper.hpp.
References eBitDepthUShort, set2DArrayBuffer(), and setBitDepth().
void tuttle::host::InputBufferWrapper::set2DArrayBuffer (float * rawBuffer, int height, int width) [inline]
Definition at line 95 of file InputBufferWrapper.hpp.
References eBitDepthUShort, set2DArrayBuffer(), and setBitDepth().
void tuttle::host::InputBufferWrapper::set3DArrayBuffer (void * rawBuffer, const int width, const int height, const int nbComponents) [private]
Definition at line 42 of file InputBufferWrapper.cpp.
References tuttle::ofx::imageEffect::ePixelComponentAlpha, tuttle::ofx::imageEffect::ePixelComponentRGB, tuttle::ofx::imageEffect::ePixelComponentRGBA, TUTTLE_INFO, TUTTLE_TLOG, and TUTTLE_TLOG_INFOS.
Referenced by set3DArrayBuffer().
void tuttle::host::InputBufferWrapper::set3DArrayBuffer (unsigned char * rawBuffer, int height, int width, int nbComponents) [inline]
Definition at line 78 of file InputBufferWrapper.hpp.
References eBitDepthUByte, set3DArrayBuffer(), and setBitDepth().
void tuttle::host::InputBufferWrapper::set3DArrayBuffer (unsigned short * rawBuffer, int height, int width, int nbComponents) [inline]
Definition at line 89 of file InputBufferWrapper.hpp.
References eBitDepthUShort, set3DArrayBuffer(), and setBitDepth().
void tuttle::host::InputBufferWrapper::set3DArrayBuffer (float * rawBuffer, int height, int width, int nbComponents) [inline]
Definition at line 100 of file InputBufferWrapper.hpp.
References eBitDepthUShort, set3DArrayBuffer(), and setBitDepth().
void tuttle::host::InputBufferWrapper::setBitDepth (const EBitDepth bitDepth)
Definition at line 81 of file InputBufferWrapper.cpp.
References tuttle::ofx::imageEffect::eBitDepthFloat, tuttle::ofx::imageEffect::eBitDepthUByte, and tuttle::ofx::imageEffect::eBitDepthUShort.
Referenced by set2DArrayBuffer(), and set3DArrayBuffer().
void tuttle::host::InputBufferWrapper::setBuffer (void * rawBuffer)
Definition at line 28 of file InputBufferWrapper.cpp.
void tuttle::host::InputBufferWrapper::setCallback (CallbackInputImagePtr callback, CustomDataPtr customData = NULL, CallbackDestroyCustomDataPtr destroyCustomData = NULL)
Definition at line 144 of file InputBufferWrapper.cpp.
void tuttle::host::InputBufferWrapper::setComponents (const EPixelComponent components)
Definition at line 71 of file InputBufferWrapper.cpp.
References tuttle::ofx::imageEffect::ePixelComponentAlpha, tuttle::ofx::imageEffect::ePixelComponentRGB, and tuttle::ofx::imageEffect::ePixelComponentRGBA.
void tuttle::host::InputBufferWrapper::setMode (const EMode mode)
Definition at line 19 of file InputBufferWrapper.cpp.
void tuttle::host::InputBufferWrapper::setOrientation (const EImageOrientation orientation)
Definition at line 96 of file InputBufferWrapper.cpp.
References tuttle::plugin::eImageOrientationFromBottomToTop, and tuttle::plugin::eImageOrientationFromTopToBottom.
void tuttle::host::InputBufferWrapper::setRawImageBuffer (void * rawBuffer, const int width, const int height, const EPixelComponent components, const EBitDepth bitDepth, const int rowDistanceBytes = 0, const EImageOrientation orientation = eImageOrientationFromBottomToTop)
Definition at line 105 of file InputBufferWrapper.cpp.
Referenced by setRawImageBuffer().
void tuttle::host::InputBufferWrapper::setRawImageBuffer (unsigned char * rawBuffer, const int width, const int height, const EPixelComponent components, const int rowDistanceBytes = 0, const EImageOrientation orientation = eImageOrientationFromBottomToTop) [inline]
Definition at line 120 of file InputBufferWrapper.hpp.
References eBitDepthUByte, and setRawImageBuffer().
void tuttle::host::InputBufferWrapper::setRawImageBuffer (unsigned short * rawBuffer, const int width, const int height, const EPixelComponent components, const int rowDistanceBytes = 0, const EImageOrientation orientation = eImageOrientationFromBottomToTop) [inline]
Definition at line 135 of file InputBufferWrapper.hpp.
References eBitDepthUShort, and setRawImageBuffer().
void tuttle::host::InputBufferWrapper::setRawImageBuffer (float * rawBuffer, const int width, const int height, const EPixelComponent components, const int rowDistanceBytes = 0, const EImageOrientation orientation = eImageOrientationFromBottomToTop) [inline]
Definition at line 150 of file InputBufferWrapper.hpp.
References eBitDepthFloat, and setRawImageBuffer().
void tuttle::host::InputBufferWrapper::setRowDistanceSize (const int rowDistanceBytes)
Definition at line 91 of file InputBufferWrapper.cpp.
void tuttle::host::InputBufferWrapper::setSize (const int width, const int height)
Definition at line 66 of file InputBufferWrapper.cpp.
Field Documentation
INode* tuttle::host::InputBufferWrapper::_node [private]
Definition at line 52 of file InputBufferWrapper.hpp.
Referenced by getNode().
The documentation for this class was generated from the following files:
TuttleOFX/libraries/tuttle/src/tuttle/host/InputBufferWrapper.hpp
TuttleOFX/libraries/tuttle/src/tuttle/host/InputBufferWrapper.cpp