TuttleOFX: tuttle::host::ofx::interact::OfxhInteractDescriptor Class Reference
tuttle::host::ofx::interact::OfxhInteractDescriptor Class Reference
Descriptor for an interact. Interacts all share a single description.
#include <OfxhInteract.hpp>
Public Member Functions
OfxhInteractDescriptor ()
CTOR.
virtual ~OfxhInteractDescriptor ()
dtor
void setEntryPoint (OfxPluginEntryPoint *entryPoint)
set the main entry points
bool describe (int bitDepthPerComponent, bool hasAlpha)
call describe on this descriptor, returns true if all went well
OfxPropertySetHandle getPropHandle ()
grab a handle on the properties of this parameter for the C api
const property::OfxhSet & getProperties () const
get prop set
property::OfxhSet & getProperties ()
get a non const prop set
OfxStatus callEntry (const char *action, void *handle, OfxPropertySetHandle inArgs, OfxPropertySetHandle outArgs) const
call the entry point with action and the given args
State getState () const
what is it's state?
Protected Attributes
property::OfxhSet _properties
its props
State _state
how is it feeling today
OfxPluginEntryPoint * _entryPoint
the entry point for this overlay
Detailed Description
Descriptor for an interact. Interacts all share a single description.
Definition at line 79 of file OfxhInteract.hpp.
Constructor & Destructor Documentation
tuttle::host::ofx::interact::OfxhInteractDescriptor::OfxhInteractDescriptor ()
CTOR.
Definition at line 64 of file OfxhInteract.cpp.
tuttle::host::ofx::interact::OfxhInteractDescriptor::~OfxhInteractDescriptor () [virtual]
dtor
Definition at line 70 of file OfxhInteract.cpp.
Member Function Documentation
OfxStatus tuttle::host::ofx::interact::OfxhInteractDescriptor::callEntry (const char * action, void * handle, OfxPropertySetHandle inArgs, OfxPropertySetHandle outArgs) const
call the entry point with action and the given args
Definition at line 95 of file OfxhInteract.cpp.
References _entryPoint, _state, and tuttle::host::ofx::interact::eFailed.
Referenced by tuttle::host::ofx::interact::OfxhInteract::callEntry(), and describe().
bool tuttle::host::ofx::interact::OfxhInteractDescriptor::describe (int bitDepthPerComponent, bool hasAlpha)
call describe on this descriptor, returns true if all went well
call describe on this descriptor
Definition at line 74 of file OfxhInteract.cpp.
References _properties, _state, callEntry(), tuttle::host::ofx::interact::eDescribed, tuttle::host::ofx::interact::eFailed, tuttle::host::ofx::interact::eUninitialised, tuttle::host::ofx::interact::OfxhInteractBase::getHandle(), and tuttle::host::ofx::property::OfxhSet::setIntProperty().
Referenced by tuttle::host::ofx::imageEffect::OfxhImageEffectNodeDescriptor::initOverlayDescriptor().
const property::OfxhSet& tuttle::host::ofx::interact::OfxhInteractDescriptor::getProperties () const [inline]
get prop set
Definition at line 103 of file OfxhInteract.hpp.
References _properties.
Referenced by tuttle::host::ofx::interact::OfxhInteract::OfxhInteract().
property::OfxhSet& tuttle::host::ofx::interact::OfxhInteractDescriptor::getProperties () [inline]
get a non const prop set
Definition at line 106 of file OfxhInteract.hpp.
References _properties.
OfxPropertySetHandle tuttle::host::ofx::interact::OfxhInteractDescriptor::getPropHandle () [inline, virtual]
grab a handle on the properties of this parameter for the C api
Implements tuttle::host::ofx::interact::OfxhInteractBase.
Definition at line 100 of file OfxhInteract.hpp.
References _properties, and tuttle::host::ofx::property::OfxhSet::getHandle().
State tuttle::host::ofx::interact::OfxhInteractDescriptor::getState () const [inline]
what is it's state?
Definition at line 115 of file OfxhInteract.hpp.
References _state.
Referenced by tuttle::host::ofx::imageEffect::OfxhImageEffectNodeDescriptor::initOverlayDescriptor().
void tuttle::host::ofx::interact::OfxhInteractDescriptor::setEntryPoint (OfxPluginEntryPoint * entryPoint) [inline]
set the main entry points
Definition at line 94 of file OfxhInteract.hpp.
References _entryPoint.
Referenced by tuttle::host::ofx::imageEffect::OfxhImageEffectNodeDescriptor::initOverlayDescriptor().
Field Documentation
OfxPluginEntryPoint* tuttle::host::ofx::interact::OfxhInteractDescriptor::_entryPoint [protected]
the entry point for this overlay
Definition at line 84 of file OfxhInteract.hpp.
Referenced by callEntry(), and setEntryPoint().
property::OfxhSet tuttle::host::ofx::interact::OfxhInteractDescriptor::_properties [protected]
its props
Definition at line 82 of file OfxhInteract.hpp.
Referenced by describe(), getProperties(), and getPropHandle().
State tuttle::host::ofx::interact::OfxhInteractDescriptor::_state [protected]
how is it feeling today
Definition at line 83 of file OfxhInteract.hpp.
Referenced by callEntry(), describe(), and getState().
The documentation for this class was generated from the following files:
TuttleOFX/libraries/tuttle/src/tuttle/host/ofx/OfxhInteract.hpp
TuttleOFX/libraries/tuttle/src/tuttle/host/ofx/OfxhInteract.cpp