TuttleOFX: TuttleOFX/libraries/tuttle/tests/graph/graph.cpp File Reference
TuttleOFX/libraries/tuttle/tests/graph/graph.cpp File Reference
#include <tuttle/test/unit_test.hpp>
#include <tuttle/host/Graph.hpp>
#include <tuttle/host/Node.hpp>
#include <iostream>
Functions
BOOST_AUTO_TEST_CASE (create_node)
BOOST_AUTO_TEST_CASE (graph_copy)
BOOST_AUTO_TEST_CASE (graph_NodeInit)
BOOST_AUTO_TEST_CASE (graph_unconnect)
BOOST_AUTO_TEST_CASE (graph_replaceNodeConnections)
BOOST_AUTO_TEST_CASE (create_processGraph)
BOOST_AUTO_TEST_CASE (graph_compute)
Function Documentation
BOOST_AUTO_TEST_CASE (create_node)
Definition at line 13 of file graph.cpp.
References tuttle::host::Graph::createNode(), and TUTTLE_LOG_INFO.
BOOST_AUTO_TEST_CASE (graph_copy)
Definition at line 21 of file graph.cpp.
References tuttle::host::Graph::connect(), tuttle::host::Graph::createNode(), tuttle::host::INode::getName(), tuttle::host::Graph::getNode(), and TUTTLE_LOG_INFO.
BOOST_AUTO_TEST_CASE (graph_NodeInit)
Definition at line 43 of file graph.cpp.
References tuttle::host::compute(), and TUTTLE_LOG_INFO.
BOOST_AUTO_TEST_CASE (graph_unconnect)
Definition at line 60 of file graph.cpp.
References tuttle::host::Graph::addConnectedNodes(), tuttle::host::Graph::getNbInputConnections(), tuttle::host::Graph::getNbOutputConnections(), tuttle::host::Graph::getNodesByPlugin(), TUTTLE_LOG_INFO, and tuttle::host::Graph::unconnect().
BOOST_AUTO_TEST_CASE (graph_replaceNodeConnections)
Definition at line 97 of file graph.cpp.
References tuttle::host::Graph::addConnectedNodes(), tuttle::host::Graph::addNode(), tuttle::host::Graph::compute(), tuttle::host::Graph::getNbInputConnections(), tuttle::host::Graph::getNbOutputConnections(), tuttle::host::Graph::getNodesByPlugin(), tuttle::host::INode::getParam(), tuttle::host::Graph::replaceNodeConnections(), and TUTTLE_LOG_INFO.
BOOST_AUTO_TEST_CASE (create_processGraph)
Definition at line 136 of file graph.cpp.
References tuttle::host::Graph::connect(), tuttle::host::Graph::createNode(), tuttle::host::INode::getAttribute(), tuttle::host::INode::getName(), tuttle::host::INode::getParam(), tuttle::host::ofx::attribute::OfxhParam::setValue(), TUTTLE_LOG_INFO, TUTTLE_TLOG, and TUTTLE_TRACE.
BOOST_AUTO_TEST_CASE (graph_compute)
Definition at line 202 of file graph.cpp.
References tuttle::host::Graph::connect(), tuttle::host::Graph::createNode(), tuttle::host::INode::getClip(), tuttle::host::INode::getParam(), tuttle::host::ofx::attribute::OfxhParam::setValue(), and TUTTLE_LOG_INFO.