TuttleOFX: TuttleOFX/libraries/tuttle/tests/ofx/clone/main.cpp File Reference
TuttleOFX/libraries/tuttle/tests/ofx/clone/main.cpp File Reference
#include <tuttle/common/utils/global.hpp>
#include <tuttle/host/exceptions.hpp>
#include <tuttle/host/Core.hpp>
#include <tuttle/host/ImageEffectNode.hpp>
#include <iostream>
#include <tuttle/test/unit_test.hpp>
#include <boost/smart_ptr/scoped_ptr.hpp>
Defines
#define BOOST_TEST_MODULE properties_tests
Functions
BOOST_AUTO_TEST_CASE (ofx_imageEffect_clones)
Define Documentation
#define BOOST_TEST_MODULE properties_tests
Definition at line 8 of file main.cpp.
Function Documentation
BOOST_AUTO_TEST_CASE (ofx_imageEffect_clones)
Definition at line 16 of file main.cpp.
References tuttle::host::ofx::OfxhPluginCache::addDirectoryToPath(), tuttle::host::core(), tuttle::host::Core::getImageEffectPluginById(), tuttle::host::Core::getPluginCache(), and tuttle::host::Core::preload().