TuttleOFX: tuttle::host::ofx::attribute::OfxhClipImageDescriptor Class Reference
tuttle::host::ofx::attribute::OfxhClipImageDescriptor Class Reference
#include <OfxhClipImageDescriptor.hpp>
Public Types
typedef OfxhClipImageDescriptor This
Public Member Functions
OfxhClipImageDescriptor (const std::string &name)
constructor
virtual ~OfxhClipImageDescriptor ()
bool operator== (const This &other) const
bool operator!= (const This &other) const
OfxImageClipHandle getOfxImageClipHandle () const
Private Member Functions
OfxhClipImageDescriptor ()
void init (const std::string &name)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Friends
class boost::serialization::access
Detailed Description
a clip image descriptor
Definition at line 15 of file OfxhClipImageDescriptor.hpp.
Member Typedef Documentation
typedef OfxhClipImageDescriptor tuttle::host::ofx::attribute::OfxhClipImageDescriptor::This
Reimplemented from tuttle::host::ofx::attribute::OfxhClipDescriptor.
Definition at line 20 of file OfxhClipImageDescriptor.hpp.
Constructor & Destructor Documentation
tuttle::host::ofx::attribute::OfxhClipImageDescriptor::OfxhClipImageDescriptor () [private]
Definition at line 8 of file OfxhClipImageDescriptor.cpp.
References init().
tuttle::host::ofx::attribute::OfxhClipImageDescriptor::OfxhClipImageDescriptor (const std::string & name)
constructor
descriptor
Definition at line 17 of file OfxhClipImageDescriptor.cpp.
References init().
virtual tuttle::host::ofx::attribute::OfxhClipImageDescriptor::~OfxhClipImageDescriptor () [inline, virtual]
Definition at line 30 of file OfxhClipImageDescriptor.hpp.
Member Function Documentation
OfxImageClipHandle tuttle::host::ofx::attribute::OfxhClipImageDescriptor::getOfxImageClipHandle () const [inline, virtual]
get a handle on the clip descriptor for the C api
Implements tuttle::host::ofx::attribute::OfxhClipImageAccessor.
Definition at line 43 of file OfxhClipImageDescriptor.hpp.
void tuttle::host::ofx::attribute::OfxhClipImageDescriptor::init (const std::string & name) [private]
descriptor
properties common to the desciptor and instance the desc and set them, the instance cannot
Definition at line 26 of file OfxhClipImageDescriptor.cpp.
References tuttle::host::ofx::attribute::OfxhAttributeDescriptor::_properties, tuttle::host::ofx::property::OfxhSet::addProperties(), tuttle::host::ofx::property::ePropTypeInt, tuttle::host::ofx::property::ePropTypeString, and tuttle::host::ofx::property::OfxhSet::setStringProperty().
Referenced by OfxhClipImageDescriptor().
bool tuttle::host::ofx::attribute::OfxhClipImageDescriptor::operator!= (const This & other) const [inline]
Reimplemented from tuttle::host::ofx::attribute::OfxhClipDescriptor.
Definition at line 39 of file OfxhClipImageDescriptor.hpp.
References operator==().
bool tuttle::host::ofx::attribute::OfxhClipImageDescriptor::operator== (const This & other) const [inline]
Reimplemented from tuttle::host::ofx::attribute::OfxhClipDescriptor.
Definition at line 32 of file OfxhClipImageDescriptor.hpp.
Referenced by operator!=().
template<class Archive > void tuttle::host::ofx::attribute::OfxhClipImageDescriptor::serialize (Archive & ar, const unsigned int version) [inline, private]
Reimplemented from tuttle::host::ofx::attribute::OfxhClipDescriptor.
Definition at line 51 of file OfxhClipImageDescriptor.hpp.
Friends And Related Function Documentation
friend class boost::serialization::access [friend]
Reimplemented from tuttle::host::ofx::attribute::OfxhClipDescriptor.
Definition at line 49 of file OfxhClipImageDescriptor.hpp.
The documentation for this class was generated from the following files:
TuttleOFX/libraries/tuttle/src/tuttle/host/ofx/attribute/OfxhClipImageDescriptor.hpp
TuttleOFX/libraries/tuttle/src/tuttle/host/ofx/attribute/OfxhClipImageDescriptor.cpp