TuttleOFX: tuttle::common::Formatter Class Reference
tuttle::common::Formatter Class Reference
#include <Formatter.hpp>
Public Member Functions
~Formatter ()
void setLogLevel (const boost::log::trivial::severity_level level)
void setLogLevel_int (const int level)
void setLogLevel_string (const std::string &level)
void displayLogLevel (bool display)
Static Public Member Functions
static boost::shared_ptr
< Formatter > get ()
Data Fields
boost::shared_ptr< sink_t > _sink
Static Public Attributes
static boost::shared_ptr
< Formatter > _formatter
Private Types
typedef
boost::log::sinks::synchronous_sink
< boost::log::sinks::text_ostream_backend > sink_t
Private Member Functions
Formatter ()
void init_logging ()
Detailed Description
Definition at line 49 of file Formatter.hpp.
Member Typedef Documentation
typedef boost::log::sinks::synchronous_sink< boost::log::sinks::text_ostream_backend > tuttle::common::Formatter::sink_t [private]
Definition at line 53 of file Formatter.hpp.
Constructor & Destructor Documentation
tuttle::common::Formatter::Formatter () [private]
Definition at line 24 of file Formatter.cpp.
References init_logging(), setLogLevel(), and setLogLevel_string().
tuttle::common::Formatter::~Formatter () [inline]
Definition at line 62 of file Formatter.hpp.
Member Function Documentation
void tuttle::common::Formatter::displayLogLevel (bool display)
Definition at line 126 of file Formatter.cpp.
References _sink.
Referenced by init_logging().
boost::shared_ptr< Formatter > tuttle::common::Formatter::get () [static]
Definition at line 14 of file Formatter.cpp.
References _formatter.
Referenced by init_logging(), setLogLevel(), and tuttle::host::ComputeOptions::setVerboseLevel().
void tuttle::common::Formatter::init_logging () [private]
Definition at line 39 of file Formatter.cpp.
References _sink, displayLogLevel(), and get().
Referenced by Formatter().
void tuttle::common::Formatter::setLogLevel (const boost::log::trivial::severity_level level)
Definition at line 119 of file Formatter.cpp.
References get().
Referenced by Formatter(), and setLogLevel_int().
void tuttle::common::Formatter::setLogLevel_int (const int level)
Definition at line 63 of file Formatter.cpp.
References setLogLevel(), boost::stack_trace::trace(), and TUTTLE_LOG_WARNING.
Referenced by setLogLevel_string().
void tuttle::common::Formatter::setLogLevel_string (const std::string & level)
Definition at line 102 of file Formatter.cpp.
References tuttle::common::logLevel_stringToInt(), and setLogLevel_int().
Referenced by Formatter().
Field Documentation
boost::shared_ptr< Formatter > tuttle::common::Formatter::_formatter [static]
Definition at line 76 of file Formatter.hpp.
Referenced by get().
boost::shared_ptr< sink_t > tuttle::common::Formatter::_sink
Definition at line 79 of file Formatter.hpp.
Referenced by displayLogLevel(), and init_logging().
The documentation for this class was generated from the following files:
TuttleOFX/libraries/tuttle/src/tuttle/common/utils/Formatter.hpp
TuttleOFX/libraries/tuttle/src/tuttle/common/utils/Formatter.cpp