TuttleOFX: tuttle::host::ofx::attribute::OfxhParamChoice Class Reference
tuttle::host::ofx::attribute::OfxhParamChoice Class Reference
#include <OfxhParamChoice.hpp>
Public Member Functions
OfxhParamChoice (const OfxhParamDescriptor &descriptor, const std::string &name, OfxhParamSet &setInstance)
virtual ~OfxhParamChoice ()
int getIndexFor (const std::string &key) const
const std::string & getChoiceKeyAt (const int index) const
const std::vector< std::string > & getChoiceKeys () const
virtual void getValue (int &) const OFX_EXCEPTION_SPEC=0
virtual void getValueAtTime (const OfxTime time, int &) const OFX_EXCEPTION_SPEC=0
virtual void setValue (const int &, const EChange change) OFX_EXCEPTION_SPEC=0
virtual void setValueAtTime (const OfxTime time, const int &, const EChange change) OFX_EXCEPTION_SPEC=0
void getValue (std::string &outKey) const OFX_EXCEPTION_SPEC
void getValueAtTime (const OfxTime time, std::string &outKey) const OFX_EXCEPTION_SPEC
void setValue (const std::string &key, const EChange change) OFX_EXCEPTION_SPEC
void setValueAtTime (const OfxTime time, const std::string &key, const EChange change) OFX_EXCEPTION_SPEC
virtual void getV (va_list arg) const OFX_EXCEPTION_SPEC
implementation of var args function
virtual void getV (const OfxTime time, va_list arg) const OFX_EXCEPTION_SPEC
implementation of var args function
virtual void setV (va_list arg, const EChange change) OFX_EXCEPTION_SPEC
implementation of var args function
virtual void setV (const OfxTime time, va_list arg, const EChange change) OFX_EXCEPTION_SPEC
implementation of var args function
bool paramTypeHasData () const
std::size_t getHashAtTime (const OfxTime time) const
Detailed Description
Definition at line 12 of file OfxhParamChoice.hpp.
Constructor & Destructor Documentation
tuttle::host::ofx::attribute::OfxhParamChoice::OfxhParamChoice (const OfxhParamDescriptor & descriptor, const std::string & name, OfxhParamSet & setInstance) [inline]
Definition at line 17 of file OfxhParamChoice.hpp.
virtual tuttle::host::ofx::attribute::OfxhParamChoice::~OfxhParamChoice () [inline, virtual]
Definition at line 18 of file OfxhParamChoice.hpp.
Member Function Documentation
const std::string & tuttle::host::ofx::attribute::OfxhParamChoice::getChoiceKeyAt (const int index) const
Definition at line 77 of file OfxhParamChoice.cpp.
References getChoiceKeys().
const std::vector<std::string>& tuttle::host::ofx::attribute::OfxhParamChoice::getChoiceKeys () const [inline]
Definition at line 23 of file OfxhParamChoice.hpp.
References tuttle::host::ofx::property::OfxhSet::fetchStringProperty(), and tuttle::host::ofx::attribute::OfxhAttribute::getProperties().
Referenced by getChoiceKeyAt(), and getIndexFor().
std::size_t tuttle::host::ofx::attribute::OfxhParamChoice::getHashAtTime (const OfxTime time) const [virtual]
Implements tuttle::host::ofx::attribute::OfxhParam.
Definition at line 144 of file OfxhParamChoice.cpp.
References getValueAtTime(), and boost::hash_value().
int tuttle::host::ofx::attribute::OfxhParamChoice::getIndexFor (const std::string & key) const
Definition at line 12 of file OfxhParamChoice.cpp.
References getChoiceKeys(), and tuttle::host::ofx::attribute::OfxhAttributeAccessor::getName().
Referenced by setValue(), and setValueAtTime().
void tuttle::host::ofx::attribute::OfxhParamChoice::getV (va_list arg) const [virtual]
implementation of var args function
Reimplemented from tuttle::host::ofx::attribute::OfxhParam.
Definition at line 107 of file OfxhParamChoice.cpp.
void tuttle::host::ofx::attribute::OfxhParamChoice::getV (const OfxTime time, va_list arg) const [virtual]
implementation of var args function
Reimplemented from tuttle::host::ofx::attribute::OfxhParam.
Definition at line 117 of file OfxhParamChoice.cpp.
virtual void tuttle::host::ofx::attribute::OfxhParamChoice::getValue (int &) const [pure virtual]
Implemented in tuttle::host::attribute::ParamChoice.
void tuttle::host::ofx::attribute::OfxhParamChoice::getValue (std::string & outKey) const
Definition at line 90 of file OfxhParamChoice.cpp.
virtual void tuttle::host::ofx::attribute::OfxhParamChoice::getValueAtTime (const OfxTime time, int &) const [pure virtual]
Implemented in tuttle::host::attribute::ParamChoice.
Referenced by getHashAtTime().
void tuttle::host::ofx::attribute::OfxhParamChoice::getValueAtTime (const OfxTime time, std::string & outKey) const
Definition at line 97 of file OfxhParamChoice.cpp.
bool tuttle::host::ofx::attribute::OfxhParamChoice::paramTypeHasData () const [inline, virtual]
Implements tuttle::host::ofx::attribute::OfxhParam.
Definition at line 61 of file OfxhParamChoice.hpp.
void tuttle::host::ofx::attribute::OfxhParamChoice::setV (va_list arg, const EChange change) [virtual]
implementation of var args function
Reimplemented from tuttle::host::ofx::attribute::OfxhParam.
Definition at line 127 of file OfxhParamChoice.cpp.
void tuttle::host::ofx::attribute::OfxhParamChoice::setV (const OfxTime time, va_list arg, const EChange change) [virtual]
implementation of var args function
Reimplemented from tuttle::host::ofx::attribute::OfxhParam.
Definition at line 137 of file OfxhParamChoice.cpp.
virtual void tuttle::host::ofx::attribute::OfxhParamChoice::setValue (const int & , const EChange change) [pure virtual]
Implemented in tuttle::host::attribute::ParamChoice.
Referenced by setValue().
void tuttle::host::ofx::attribute::OfxhParamChoice::setValue (const std::string & key, const EChange change) [inline]
Definition at line 37 of file OfxhParamChoice.hpp.
References getIndexFor(), and setValue().
virtual void tuttle::host::ofx::attribute::OfxhParamChoice::setValueAtTime (const OfxTime time, const int & , const EChange change) [pure virtual]
Implemented in tuttle::host::attribute::ParamChoice.
Referenced by setValueAtTime().
void tuttle::host::ofx::attribute::OfxhParamChoice::setValueAtTime (const OfxTime time, const std::string & key, const EChange change) [inline]
Definition at line 42 of file OfxhParamChoice.hpp.
References getIndexFor(), and setValueAtTime().
The documentation for this class was generated from the following files:
TuttleOFX/libraries/tuttle/src/tuttle/host/ofx/attribute/OfxhParamChoice.hpp
TuttleOFX/libraries/tuttle/src/tuttle/host/ofx/attribute/OfxhParamChoice.cpp