TuttleOFX: tuttle::ofx Namespace Reference
tuttle::ofx Namespace Reference
Namespaces
namespace imageEffect
Typedefs
typedef std::vector< std::string > StringVec
class that is a std::vector of std::strings
Functions
std::string mapStatusToString (const OfxStatus stat)
maps status to a string
void setStringVecValue (StringVec &sv, const std::string &value, size_t index=0)
template<class T >
T minimum (const T &a, const T &b)
get the min value
template<class T >
T maximum (const T &a, const T &b)
get the max value
template<class T >
T clamp (const T &v, const T &min, const T &max)
clamp the value
OfxRectD clamp (const OfxRectD &v, const OfxRectD &bounds)
clamp the rect in v to the given bounds
OfxRectI clamp (const OfxRectI &v, const OfxRectI &bounds)
clamp the rect in v to the given bounds
OfxRectD rectUnion (const OfxRectD &a, const OfxRectD &b)
get the union of the two rects
bool isEmpty (const OfxRectD &r)
bool isEmpty (const OfxRectI &r)
OfxRectD infiniteRectD ()
create an infinite rectangle
OfxRectI rectDToRectI (const OfxRectD &rectD)
Convert OfxRectD to OfxRectI.
Typedef Documentation
typedef std::vector<std::string> tuttle::ofx::StringVec
class that is a std::vector of std::strings
Definition at line 18 of file utilities.hpp.
Function Documentation
template<class T > T tuttle::ofx::clamp (const T & v, const T & min, const T & max) [inline]
clamp the value
Definition at line 53 of file utilities.hpp.
References tuttle::max(), and tuttle::min().
Referenced by clamp(), and tuttle::host::ofx::imageEffect::OfxhImageEffectNode::getRegionOfInterestAction().
OfxRectD tuttle::ofx::clamp (const OfxRectD & v, const OfxRectD & bounds) [inline]
clamp the rect in v to the given bounds
Definition at line 63 of file utilities.hpp.
References clamp().
OfxRectI tuttle::ofx::clamp (const OfxRectI & v, const OfxRectI & bounds) [inline]
clamp the rect in v to the given bounds
Definition at line 76 of file utilities.hpp.
References clamp().
OfxRectD tuttle::ofx::infiniteRectD () [inline]
create an infinite rectangle
Definition at line 120 of file utilities.hpp.
bool tuttle::ofx::isEmpty (const OfxRectD & r) [inline]
Definition at line 101 of file utilities.hpp.
bool tuttle::ofx::isEmpty (const OfxRectI & r) [inline]
Definition at line 110 of file utilities.hpp.
std::string tuttle::ofx::mapStatusToString (const OfxStatus stat)
maps status to a string
Definition at line 10 of file core.cpp.
Referenced by tuttle::host::ofx::OfxhException::getStatusStr(), OFX::to_string(), tuttle::host::ofx::imageEffect::OfxhImageEffectNode::~OfxhImageEffectNode(), and tuttle::host::ofx::interact::OfxhInteract::~OfxhInteract().
template<class T > T tuttle::ofx::maximum (const T & a, const T & b) [inline]
get the max value
Definition at line 46 of file utilities.hpp.
Referenced by rectUnion(), and tuttle::host::ofx::imageEffect::OfxhImageEffectNode::setDefaultClipPreferences().
template<class T > T tuttle::ofx::minimum (const T & a, const T & b) [inline]
get the min value
Definition at line 39 of file utilities.hpp.
Referenced by rectUnion().
OfxRectI tuttle::ofx::rectDToRectI (const OfxRectD & rectD) [inline]
Convert OfxRectD to OfxRectI.
Definition at line 131 of file utilities.hpp.
OfxRectD tuttle::ofx::rectUnion (const OfxRectD & a, const OfxRectD & b) [inline]
get the union of the two rects
Definition at line 89 of file utilities.hpp.
References maximum(), and minimum().
Referenced by tuttle::host::ofx::imageEffect::OfxhImageEffectNode::calcDefaultRegionOfDefinition(), and tuttle::host::ofx::imageEffect::OfxhImageEffectNode::computeClipRodUnionAtTimes().
void tuttle::ofx::setStringVecValue (StringVec & sv, const std::string & value, size_t index = 0) [inline]
Definition at line 20 of file utilities.hpp.