TuttleOFX: tuttle::host::io Namespace Reference
tuttle::host::io Namespace Reference
Typedefs
typedef boost::tuples::tuple
< double, int, std::string > Tuple
Functions
std::vector< std::string > getIOPluginsForExtension (const std::string &extension, const std::string &context)
std::string getFileExtension (const std::string &filename)
std::vector< std::string > _getReaders (const std::string &extension)
std::vector< std::string > getReaders (const std::string &filename)
std::string getBestReader (const std::string &filename)
std::vector< std::string > _getWriters (const std::string &extension)
std::vector< std::string > getWriters (const std::string &filename)
std::string getBestWriter (const std::string &filename)
Typedef Documentation
typedef boost::tuples::tuple< double, int, std::string > tuttle::host::io::Tuple
Definition at line 25 of file io.cpp.
Function Documentation
std::vector< std::string > tuttle::host::io::_getReaders (const std::string & extension)
Parameters:
extension
Returns:
the reader nodes identifiers that support the given file extension
Definition at line 106 of file io.cpp.
References getIOPluginsForExtension().
Referenced by getBestReader(), and getReaders().
std::vector< std::string > tuttle::host::io::_getWriters (const std::string & extension)
Parameters:
extension
Returns:
the writer nodes identifiers that support the given file extension
Definition at line 161 of file io.cpp.
References getIOPluginsForExtension().
Referenced by getBestWriter(), and getWriters().
std::string tuttle::host::io::getBestReader (const std::string & filename)
Parameters:
filename can be a filename or an extension
Returns:
the reader node identifier that supports the extension of the given file
Definition at line 117 of file io.cpp.
References _getReaders(), tuttle::host::Graph::createNode(), getFileExtension(), tuttle::host::ImageEffectNode::getParam(), tuttle::host::ImageEffectNode::getRegionOfDefinition(), tuttle::host::ImageEffectNode::getTimeDomain(), tuttle::host::Graph::setup(), tuttle::host::Graph::setupAtTime(), and tuttle::host::ofx::attribute::OfxhParam::setValue().
Referenced by tuttle::host::loadAndGenerateThumbnail(), and tuttle::host::loadImage().
std::string tuttle::host::io::getBestWriter (const std::string & filename)
Parameters:
filename can be a filename or an extension
Returns:
the writer node identifier that supports the extension of the given file.
Definition at line 172 of file io.cpp.
References _getWriters(), and getFileExtension().
Referenced by tuttle::host::loadAndGenerateThumbnail().
std::string tuttle::host::io::getFileExtension (const std::string & filename)
Get a file extension of the given file name.
Returns:
the file extension
Definition at line 85 of file io.cpp.
Referenced by getBestReader(), getBestWriter(), getReaders(), and getWriters().
std::vector< std::string > tuttle::host::io::getIOPluginsForExtension (const std::string & extension, const std::string & context)
Choose a plugin which supports the given file extension. This plugin has the best evaluation among available plugins.
Returns:
the node identifier
Definition at line 27 of file io.cpp.
References tuttle::host::core(), tuttle::host::Core::getImageEffectPluginCache(), tuttle::host::ofx::imageEffect::OfxhImageEffectPluginCache::getPluginsByID(), and tuttle::host::ofx::imageEffect::OfxhImageEffectNodeBase::getProperties().
Referenced by _getReaders(), and _getWriters().
std::vector< std::string > tuttle::host::io::getReaders (const std::string & filename)
Parameters:
filename can be a filename or an extension
Returns:
the reader nodes identifiers that support the extension of the given file
Definition at line 112 of file io.cpp.
References _getReaders(), and getFileExtension().
std::vector< std::string > tuttle::host::io::getWriters (const std::string & filename)
Parameters:
filename can be a filename or an extension
Returns:
the writer nodes identifiers that support the extension of the given file.
Definition at line 167 of file io.cpp.
References _getWriters(), and getFileExtension().