TuttleOFX: tuttle::host::ofx::attribute::OfxhAttribute Class Reference
tuttle::host::ofx::attribute::OfxhAttribute Class Reference
#include <OfxhAttribute.hpp>
Public Types
typedef OfxhAttribute This
Public Member Functions
OfxhAttribute (const property::OfxhSet &properties)
OfxhAttribute (const OfxhAttributeDescriptor &desc)
virtual ~OfxhAttribute ()=0
virtual bool operator== (const This &other) const
bool operator!= (const This &other) const
const property::OfxhSet & getProperties () const
property::OfxhSet & getEditableProperties ()
virtual void copyValues (const This &other)
Protected Member Functions
OfxhAttribute ()
void setProperties (const property::OfxhSet &properties)
Protected Attributes
property::OfxhSet _properties
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Friends
class boost::serialization::access
Detailed Description
Definition at line 52 of file OfxhAttribute.hpp.
Member Typedef Documentation
typedef OfxhAttribute tuttle::host::ofx::attribute::OfxhAttribute::This
Reimplemented in tuttle::host::ofx::attribute::OfxhParam, tuttle::host::attribute::AnimatedParam< double, ofx::attribute::OfxhParamDouble >, tuttle::host::ofx::attribute::OfxhClipImage, and tuttle::host::ofx::attribute::OfxhClip.
Definition at line 55 of file OfxhAttribute.hpp.
Constructor & Destructor Documentation
tuttle::host::ofx::attribute::OfxhAttribute::OfxhAttribute () [inline, protected]
Definition at line 58 of file OfxhAttribute.hpp.
tuttle::host::ofx::attribute::OfxhAttribute::OfxhAttribute (const property::OfxhSet & properties)
Definition at line 8 of file OfxhAttribute.cpp.
References tuttle::host::ofx::attribute::OfxhAttributeAccessor::getAttributeType().
tuttle::host::ofx::attribute::OfxhAttribute::OfxhAttribute (const OfxhAttributeDescriptor & desc)
Definition at line 14 of file OfxhAttribute.cpp.
References tuttle::host::ofx::attribute::OfxhAttributeAccessor::getAttributeType().
tuttle::host::ofx::attribute::OfxhAttribute::~OfxhAttribute () [pure virtual]
Definition at line 20 of file OfxhAttribute.cpp.
Member Function Documentation
virtual void tuttle::host::ofx::attribute::OfxhAttribute::copyValues (const This & other) [inline, virtual]
Definition at line 95 of file OfxhAttribute.hpp.
References _properties, and tuttle::host::ofx::property::OfxhSet::copyValues().
Referenced by tuttle::host::ofx::attribute::OfxhClipImageSet::copyClipsValues().
property::OfxhSet& tuttle::host::ofx::attribute::OfxhAttribute::getEditableProperties () [inline, virtual]
Implements tuttle::host::ofx::attribute::OfxhAttributeAccessor.
Definition at line 90 of file OfxhAttribute.hpp.
References _properties.
Referenced by tuttle::host::attribute::ClipImage::ClipImage(), tuttle::host::ofx::attribute::OfxhClip::OfxhClip(), tuttle::host::ofx::attribute::OfxhParam::OfxhParam(), tuttle::host::ofx::attribute::OfxhParamDouble::OfxhParamDouble(), tuttle::host::ofx::attribute::OfxhParamInteger::OfxhParamInteger(), tuttle::host::ofx::attribute::OfxhClipImage::setBitDepthString(), tuttle::host::ofx::attribute::OfxhClipImage::setBitDepthStringIfUpper(), tuttle::host::ofx::attribute::OfxhClipImage::setBitDepthStringIfUpperAndNotModifiedByPlugin(), tuttle::host::ofx::attribute::OfxhClipImage::setComponentsString(), tuttle::host::ofx::attribute::OfxhClipImage::setComponentsStringIfNotModifiedByPlugin(), tuttle::host::attribute::ClipImage::setConnectedClip(), tuttle::host::attribute::ClipImage::setFrameRange(), tuttle::host::attribute::ClipImage::setFrameRate(), tuttle::host::ofx::attribute::OfxhClipImage::setPixelAspectRatio(), and tuttle::host::attribute::ClipImage::setUnmappedFrameRange().
const property::OfxhSet& tuttle::host::ofx::attribute::OfxhAttribute::getProperties () const [inline, virtual]
Implements tuttle::host::ofx::attribute::OfxhAttributeAccessor.
Definition at line 85 of file OfxhAttribute.hpp.
References _properties.
Referenced by tuttle::host::ofx::attribute::OfxhClipImage::getBitDepthString(), tuttle::host::ofx::attribute::OfxhParamPage::getChildren(), tuttle::host::ofx::attribute::OfxhParamChoice::getChoiceKeys(), tuttle::host::ofx::attribute::OfxhClipImage::getComponentsString(), tuttle::host::ofx::attribute::OfxhClipImage::getContinuousSamples(), tuttle::host::attribute::ParamDouble::getDefault(), tuttle::host::attribute::ParamChoice::getDefault(), tuttle::host::attribute::ParamBoolean::getDefault(), tuttle::host::attribute::ParamString::getDefault(), tuttle::host::ofx::attribute::OfxhClipImage::getFieldExtraction(), tuttle::host::ofx::attribute::OfxhClipImage::getFieldOrder(), tuttle::host::ofx::attribute::OfxhClipImage::getFrameRange(), tuttle::host::attribute::ClipImage::getFrameRate(), tuttle::host::ofx::attribute::OfxhClipImage::getFrameRate(), tuttle::host::ofx::attribute::OfxhClipImage::getPixelAspectRatio(), tuttle::host::ofx::attribute::OfxhClipImage::getPremult(), tuttle::host::ofx::attribute::OfxhParamString::getStringMode(), tuttle::host::attribute::ClipImage::getUnmappedBitDepth(), tuttle::host::ofx::attribute::OfxhClipImage::getUnmappedBitDepth(), tuttle::host::attribute::ClipImage::getUnmappedComponents(), tuttle::host::ofx::attribute::OfxhClipImage::getUnmappedComponents(), tuttle::host::ofx::attribute::OfxhClipImage::getUnmappedFrameRange(), tuttle::host::ofx::attribute::OfxhClipImage::getUnmappedFrameRate(), tuttle::host::ofx::imageEffect::OfxhImage::initClipBits(), tuttle::host::ofx::attribute::operator<<(), and operator==().
bool tuttle::host::ofx::attribute::OfxhAttribute::operator!= (const This & other) const [inline]
Reimplemented in tuttle::host::ofx::attribute::OfxhClipImage, and tuttle::host::ofx::attribute::OfxhClip.
Definition at line 72 of file OfxhAttribute.hpp.
References operator==().
virtual bool tuttle::host::ofx::attribute::OfxhAttribute::operator== (const This & other) const [inline, virtual]
Reimplemented in tuttle::host::ofx::attribute::OfxhClipImage, and tuttle::host::ofx::attribute::OfxhClip.
Definition at line 65 of file OfxhAttribute.hpp.
References getProperties().
Referenced by operator!=().
template<class Archive > void tuttle::host::ofx::attribute::OfxhAttribute::serialize (Archive & ar, const unsigned int version) [inline, private]
Reimplemented in tuttle::host::ofx::attribute::OfxhClip.
Definition at line 103 of file OfxhAttribute.hpp.
References _properties.
void tuttle::host::ofx::attribute::OfxhAttribute::setProperties (const property::OfxhSet & properties) [inline, protected, virtual]
Implements tuttle::host::ofx::attribute::OfxhAttributeAccessor.
Definition at line 78 of file OfxhAttribute.hpp.
References _properties, and tuttle::host::ofx::attribute::OfxhAttributeAccessor::getAttributeType().
Friends And Related Function Documentation
friend class boost::serialization::access [friend]
Reimplemented in tuttle::host::ofx::attribute::OfxhClip.
Definition at line 101 of file OfxhAttribute.hpp.
Field Documentation
property::OfxhSet tuttle::host::ofx::attribute::OfxhAttribute::_properties [protected]
Definition at line 75 of file OfxhAttribute.hpp.
Referenced by copyValues(), getEditableProperties(), getProperties(), tuttle::host::ofx::attribute::OfxhClipImage::OfxhClipImage(), serialize(), and setProperties().
The documentation for this class was generated from the following files:
TuttleOFX/libraries/tuttle/src/tuttle/host/ofx/attribute/OfxhAttribute.hpp
TuttleOFX/libraries/tuttle/src/tuttle/host/ofx/attribute/OfxhAttribute.cpp