TuttleOFX: tuttle::host::NodeListArg Class Reference
tuttle::host::NodeListArg Class Reference
An utility class to use as function argument. It allows to create a list of nodes from multiple inputs.
#include <NodeListArg.hpp>
Public Member Functions
NodeListArg ()
NodeListArg (const std::list< std::string > &nodes)
NodeListArg (const std::list< INode * > &nodes)
NodeListArg (const std::string &node)
NodeListArg (const INode &node)
const std::list< std::string > & getNodes () const
Private Attributes
std::list< std::string > _nodes
Detailed Description
An utility class to use as function argument. It allows to create a list of nodes from multiple inputs.
All constructors are not "explicit", so we could automatically convert the input inside when we use it as a function argument.
Definition at line 18 of file NodeListArg.hpp.
Constructor & Destructor Documentation
tuttle::host::NodeListArg::NodeListArg () [inline]
Definition at line 21 of file NodeListArg.hpp.
tuttle::host::NodeListArg::NodeListArg (const std::list< std::string > & nodes) [inline]
Definition at line 23 of file NodeListArg.hpp.
tuttle::host::NodeListArg::NodeListArg (const std::list< INode * > & nodes)
Definition at line 9 of file NodeListArg.cpp.
References _nodes, and tuttle::host::INode::getName().
tuttle::host::NodeListArg::NodeListArg (const std::string & node) [inline]
Definition at line 28 of file NodeListArg.hpp.
References _nodes.
tuttle::host::NodeListArg::NodeListArg (const INode & node)
Definition at line 17 of file NodeListArg.cpp.
References _nodes, and tuttle::host::INode::getName().
Member Function Documentation
const std::list<std::string>& tuttle::host::NodeListArg::getNodes () const [inline]
Definition at line 35 of file NodeListArg.hpp.
References _nodes.
Referenced by tuttle::host::ThreadEnv::compute(), tuttle::host::Graph::compute(), tuttle::host::Graph::computeGlobalHashAtTime(), and tuttle::host::Graph::setupAtTime().
Field Documentation
std::list<std::string> tuttle::host::NodeListArg::_nodes [private]
Definition at line 38 of file NodeListArg.hpp.
Referenced by getNodes(), and NodeListArg().
The documentation for this class was generated from the following files:
TuttleOFX/libraries/tuttle/src/tuttle/host/NodeListArg.hpp
TuttleOFX/libraries/tuttle/src/tuttle/host/NodeListArg.cpp