TuttleOFX: tuttle Namespace Reference
tuttle Namespace Reference
global namespace of the project
Namespaces
namespace common
namespace exception
namespace host
Library for host.
namespace ofx
namespace plugin
namespace plugins
Library for plugins.
namespace test
Functions
std::string quotes (const std::string &s)
template<typename T >
T min (const T &a, const T &b, const T &c)
template<typename T >
T max (const T &a, const T &b, const T &c)
template<typename T >
T min (const T &a, const T &b, const T &c, const T &d)
template<typename T >
T max (const T &a, const T &b, const T &c, const T &d)
template<class P >
OfxRectD pointsBoundingBox (const P &a, const P &b, const P &c, const P &d)
template<typename Point2 >
OfxRectD pointsBoundingBox (const std::vector< Point2 > &points)
template<class Point2 >
Point2 pointsMinXY (const std::vector< Point2 > &points)
template<class Point2 >
Point2 pointsMaxXY (const std::vector< Point2 > &points)
template<class Point , class Rect >
bool pointInRect (const Point &p, const Rect &rec)
template<class Rect >
Rect translateRegion (const Rect &windowRoW, const Rect &dependingTo)
template<class Rect , class Point >
Rect translateRegion (const Rect &windowRoW, const Point &move)
template<class R >
R rectanglesBoundingBox (const R &a, const R &b)
template<class R >
R rectanglesIntersection (const R &a, const R &b)
template<class R >
bool rectanglesIntersect (const R &a, const R &b)
template<class R >
bool rectangleAContainsB (const R &a, const R &b)
template<class R >
bool rectangleContainsAnother (const R &a, const R &b)
template<class R , class V >
R rectangleGrow (const R &rect, const V marge)
template<class R , class V >
R rectangleReduce (const R &rect, const V marge)
Detailed Description
global namespace of the project
This file provides a set of member function that are needed to manage algorithm progression.
<
: remove include dependencies to gil
Todo:
temporary solution..
Todo:
tuttle: custom parameter support...
Todo:
tuttle: please remove this ! (don't use as singleton)
Todo:
tuttle: remove this !
Todo:
tuttle: remove this!
Function Documentation
template<typename T > T tuttle::max (const T & a, const T & b, const T & c) [inline]
Definition at line 40 of file minmax.hpp.
Referenced by tuttle::ofx::clamp(), tuttle::host::graph::ProcessGraph::computeTimeRange(), tuttle::plugin::describeGeneratorParamsInContext(), tuttle::host::ImageEffectNode::getDefaultTimeDomain(), tuttle::host::ofx::imageEffect::OfxhImageEffectNode::getFramesNeededAction(), getMemoryInfo(), tuttle::host::ofx::attribute::OfxhParamDescriptor::initNumericParamProps(), tuttle::plugin::interact::ParamRectangleFromTwoCorners< TFrame, coord >::isIn(), tuttle::plugin::interact::ParamRectangleFromCenterSize< TFrame, coord >::isIn(), max(), tuttle::plugin::OfxAllocator< T >::max_size(), pointsBoundingBox(), rectanglesBoundingBox(), rectanglesIntersection(), tuttle::plugin::interact::ParamRectangleFromTwoCorners< TFrame, coord >::selectType(), tuttle::plugin::interact::ParamRectangleFromCenterSize< TFrame, coord >::selectType(), and tuttle::host::ofx::imageEffect::OfxhImageEffectNode::setDefaultClipPreferences().
template<typename T > T tuttle::max (const T & a, const T & b, const T & c, const T & d) [inline]
Definition at line 52 of file minmax.hpp.
References max().
template<typename T > T tuttle::min (const T & a, const T & b, const T & c) [inline]
Definition at line 34 of file minmax.hpp.
Referenced by tuttle::ofx::clamp(), tuttle::host::graph::ProcessGraph::computeTimeRange(), tuttle::host::ImageEffectNode::getDefaultTimeDomain(), tuttle::host::ofx::imageEffect::OfxhImageEffectNode::getFramesNeededAction(), tuttle::host::ofx::attribute::OfxhParamDescriptor::initNumericParamProps(), tuttle::plugin::interact::ParamRectangleFromTwoCorners< TFrame, coord >::isIn(), tuttle::plugin::interact::ParamRectangleFromCenterSize< TFrame, coord >::isIn(), min(), pointsBoundingBox(), rectanglesBoundingBox(), rectanglesIntersection(), tuttle::plugin::interact::ParamRectangleFromTwoCorners< TFrame, coord >::selectType(), and tuttle::plugin::interact::ParamRectangleFromCenterSize< TFrame, coord >::selectType().
template<typename T > T tuttle::min (const T & a, const T & b, const T & c, const T & d) [inline]
Definition at line 46 of file minmax.hpp.
References min().
template<class Point , class Rect > bool tuttle::pointInRect (const Point & p, const Rect & rec) [inline]
Definition at line 89 of file rectOp.hpp.
Referenced by tuttle::plugin::interact::PointInteract::isIn().
template<class P > OfxRectD tuttle::pointsBoundingBox (const P & a, const P & b, const P & c, const P & d) [inline]
Definition at line 15 of file rectOp.hpp.
References max(), and min().
template<typename Point2 > OfxRectD tuttle::pointsBoundingBox (const std::vector< Point2 > & points) [inline]
Definition at line 26 of file rectOp.hpp.
template<class Point2 > Point2 tuttle::pointsMaxXY (const std::vector< Point2 > & points) [inline]
Definition at line 70 of file rectOp.hpp.
template<class Point2 > Point2 tuttle::pointsMinXY (const std::vector< Point2 > & points) [inline]
Definition at line 51 of file rectOp.hpp.
std::string tuttle::quotes (const std::string & s) [inline]
Definition at line 69 of file exceptions.hpp.
Referenced by tuttle::host::ImageEffectNode::computeTimeDomain(), tuttle::host::graph::ProcessGraph::computeTimeRange(), tuttle::ofx::imageEffect::findDeepestBitDepth(), tuttle::host::ofx::OfxhBinary::findSymbol(), tuttle::host::graph::visitor::RemoveIdentityNodes< TGraph >::finish_vertex(), tuttle::host::graph::visitor::Process< TGraph >::finish_vertex(), tuttle::host::graph::ProcessVertexAtTimeData::getInputEdgeByClipName(), tuttle::host::ofx::OfxhBinary::load(), tuttle::common::logLevel_stringToInt(), tuttle::exception::MissingHostFeature::MissingHostFeature(), tuttle::host::ImageEffectNode::newParam(), tuttle::host::ofx::imageEffect::OfxhImageEffectNode::populateParams(), tuttle::host::ImageEffectNode::process(), tuttle::host::Graph::renameNode(), tuttle::host::ofx::OfxhPluginCache::scanDirectory(), tuttle::host::ofx::OfxhPluginCache::scanPluginFiles(), tuttle::plugin::ImageGilFilterProcessor< SView, DView >::setup(), tuttle::plugin::ImageFilterProcessor::setup(), tuttle::plugin::ImageProcessor::setup(), and tuttle::host::ofx::imageEffect::OfxhImage::~OfxhImage().
template<class R > bool tuttle::rectangleAContainsB (const R & a, const R & b) [inline]
Definition at line 171 of file rectOp.hpp.
Referenced by rectangleContainsAnother().
template<class R > bool tuttle::rectangleContainsAnother (const R & a, const R & b) [inline]
Definition at line 179 of file rectOp.hpp.
References rectangleAContainsB().
template<class R , class V > R tuttle::rectangleGrow (const R & rect, const V marge) [inline]
Definition at line 185 of file rectOp.hpp.
template<class R , class V > R tuttle::rectangleReduce (const R & rect, const V marge) [inline]
Definition at line 196 of file rectOp.hpp.
template<class R > R tuttle::rectanglesBoundingBox (const R & a, const R & b) [inline]
Definition at line 139 of file rectOp.hpp.
References max(), and min().
template<class R > bool tuttle::rectanglesIntersect (const R & a, const R & b) [inline]
Definition at line 161 of file rectOp.hpp.
template<class R > R tuttle::rectanglesIntersection (const R & a, const R & b) [inline]
Definition at line 150 of file rectOp.hpp.
References max(), and min().
template<class Rect > Rect tuttle::translateRegion (const Rect & windowRoW, const Rect & dependingTo) [inline]
Definition at line 117 of file rectOp.hpp.
Referenced by tuttle::plugin::ImageProcessor::translateRoWToOutputClipCoordinates().
template<class Rect , class Point > Rect tuttle::translateRegion (const Rect & windowRoW, const Point & move) [inline]
Definition at line 128 of file rectOp.hpp.