TuttleOFX: tuttle::host::graph::ProcessEdge Class Reference
tuttle::host::graph::ProcessEdge Class Reference
#include <ProcessEdge.hpp>
Public Types
typedef std::set< OfxTime > TimesSet
typedef std::map< OfxTime,
TimesSet > TimeMap
Public Member Functions
ProcessEdge ()
ProcessEdge (const ProcessVertex::Key &out, const ProcessVertex::Key &in, const std::string &inAttrName)
ProcessEdge (const ProcessEdge &e)
~ProcessEdge ()
ProcessEdge & operator= (const ProcessEdge &e)
ProcessEdge & operator= (const UEdge &e)
void clearTimeInfo ()
std::ostream & exportDotDebug (std::ostream &os) const
Data Fields
TimeMap _timesNeeded
Detailed Description
Definition at line 15 of file ProcessEdge.hpp.
Member Typedef Documentation
typedef std::map<OfxTime, TimesSet> tuttle::host::graph::ProcessEdge::TimeMap
Definition at line 42 of file ProcessEdge.hpp.
typedef std::set<OfxTime> tuttle::host::graph::ProcessEdge::TimesSet
Definition at line 41 of file ProcessEdge.hpp.
Constructor & Destructor Documentation
tuttle::host::graph::ProcessEdge::ProcessEdge ()
Definition at line 8 of file ProcessEdge.cpp.
tuttle::host::graph::ProcessEdge::ProcessEdge (const ProcessVertex::Key & out, const ProcessVertex::Key & in, const std::string & inAttrName)
Definition at line 11 of file ProcessEdge.cpp.
tuttle::host::graph::ProcessEdge::ProcessEdge (const ProcessEdge & e)
Definition at line 16 of file ProcessEdge.cpp.
tuttle::host::graph::ProcessEdge::~ProcessEdge ()
Definition at line 20 of file ProcessEdge.cpp.
Member Function Documentation
void tuttle::host::graph::ProcessEdge::clearTimeInfo () [inline]
Definition at line 36 of file ProcessEdge.hpp.
References _timesNeeded.
std::ostream & tuttle::host::graph::ProcessEdge::exportDotDebug (std::ostream & os) const [virtual]
Reimplemented from tuttle::host::graph::IEdge.
Definition at line 24 of file ProcessEdge.cpp.
References tuttle::host::graph::IEdge::_localId, _timesNeeded, tuttle::host::graph::dotEntry(), tuttle::host::graph::IEdge::getName(), and tuttle::host::graph::subDotEntry().
ProcessEdge& tuttle::host::graph::ProcessEdge::operator= (const ProcessEdge & e) [inline]
Definition at line 23 of file ProcessEdge.hpp.
References _timesNeeded.
Referenced by operator=().
ProcessEdge& tuttle::host::graph::ProcessEdge::operator= (const UEdge & e) [inline]
Definition at line 30 of file ProcessEdge.hpp.
References operator=().
Field Documentation
TimeMap tuttle::host::graph::ProcessEdge::_timesNeeded
Definition at line 43 of file ProcessEdge.hpp.
Referenced by clearTimeInfo(), exportDotDebug(), operator=(), and tuttle::host::graph::ProcessGraph::setupAtTime().
The documentation for this class was generated from the following files:
TuttleOFX/libraries/tuttle/src/tuttle/host/graph/ProcessEdge.hpp
TuttleOFX/libraries/tuttle/src/tuttle/host/graph/ProcessEdge.cpp