TuttleOFX: tuttle::host::ofx::OfxhHost Class Reference
tuttle::host::ofx::OfxhHost Class Reference
#include <OfxhHost.hpp>
Public Member Functions
OfxhHost ()
virtual ~OfxhHost ()=0
const property::OfxhSet & getProperties () const
get the props on this host
property::OfxhSet & getProperties ()
virtual void * fetchSuite (const char *suiteName, const int suiteVersion)
OfxHost * getHandle ()
get the C API handle that is passed across the API to represent this host
bool verifyMagic ()
is my magic number valid?
virtual void initDescriptor (attribute::OfxhParamDescriptor &) const
override this to handle do post-construction initialisation on a Param::Descriptor
virtual OfxStatus vmessage (const char *type, const char *id, const char *format, va_list args) const =0
vmessage
Protected Attributes
OfxHost _host
property::OfxhSet _properties
Detailed Description
Base class for all objects passed to a plugin by the 'setHost' function passed back by any plug-in.
Definition at line 56 of file OfxhHost.hpp.
Constructor & Destructor Documentation
tuttle::host::ofx::OfxhHost::OfxhHost ()
Definition at line 74 of file OfxhHost.cpp.
References _host, _properties, fetchSuite(), tuttle::host::ofx::property::OfxhSet::getHandle(), kOfxHostSupportHostPointer, and tuttle::host::ofx::property::OfxhSet::setPointerProperty().
tuttle::host::ofx::OfxhHost::~OfxhHost () [pure virtual]
Definition at line 83 of file OfxhHost.cpp.
Member Function Documentation
void * tuttle::host::ofx::OfxhHost::fetchSuite (const char * suiteName, const int suiteVersion) [virtual]
fetch a suite The base class returns the following suites PropertySuite MemorySuite
Reimplemented in tuttle::host::ofx::imageEffect::OfxhImageEffectHost.
Definition at line 90 of file OfxhHost.cpp.
References tuttle::host::ofx::getMemorySuite(), tuttle::host::ofx::property::getPropertySuite(), and TUTTLE_LOG_TRACE.
Referenced by tuttle::host::ofx::fetchSuite(), and OfxhHost().
OfxHost * tuttle::host::ofx::OfxhHost::getHandle ()
get the C API handle that is passed across the API to represent this host
Definition at line 85 of file OfxhHost.cpp.
References _host.
Referenced by tuttle::host::ofx::OfxhPluginLoadGuard::OfxhPluginLoadGuard().
const property::OfxhSet& tuttle::host::ofx::OfxhHost::getProperties () const [inline]
get the props on this host
Definition at line 67 of file OfxhHost.hpp.
References _properties.
Referenced by tuttle::host::ofx::imageEffect::OfxhImageEffectNode::canCurrentlyHandleMultipleClipDepths().
property::OfxhSet& tuttle::host::ofx::OfxhHost::getProperties () [inline]
Definition at line 68 of file OfxhHost.hpp.
References _properties.
virtual void tuttle::host::ofx::OfxhHost::initDescriptor (attribute::OfxhParamDescriptor &) const [inline, virtual]
override this to handle do post-construction initialisation on a Param::Descriptor
Definition at line 87 of file OfxhHost.hpp.
bool tuttle::host::ofx::OfxhHost::verifyMagic () [inline]
is my magic number valid?
Definition at line 82 of file OfxhHost.hpp.
virtual OfxStatus tuttle::host::ofx::OfxhHost::vmessage (const char * type, const char * id, const char * format, va_list args) const [pure virtual]
vmessage
Implemented in tuttle::host::Host.
Field Documentation
OfxHost tuttle::host::ofx::OfxhHost::_host [protected]
Definition at line 59 of file OfxhHost.hpp.
Referenced by getHandle(), and OfxhHost().
property::OfxhSet tuttle::host::ofx::OfxhHost::_properties [protected]
Definition at line 60 of file OfxhHost.hpp.
Referenced by getProperties(), tuttle::host::Host::Host(), OfxhHost(), and tuttle::host::ofx::imageEffect::OfxhImageEffectHost::OfxhImageEffectHost().
The documentation for this class was generated from the following files:
TuttleOFX/libraries/tuttle/src/tuttle/host/ofx/OfxhHost.hpp
TuttleOFX/libraries/tuttle/src/tuttle/host/ofx/OfxhHost.cpp