TuttleOFX: TuttleOFX/libraries/tuttle/tests/ofx/plugin/main.cpp File Reference
TuttleOFX/libraries/tuttle/tests/ofx/plugin/main.cpp File Reference
#include <tuttle/test/unit_test.hpp>
#include <tuttle/common/utils/global.hpp>
#include <tuttle/host/Core.hpp>
#include <tuttle/host/ofx/OfxhImageEffectPlugin.hpp>
#include <boost/archive/xml_oarchive.hpp>
#include <boost/archive/binary_oarchive.hpp>
#include <boost/archive/text_oarchive.hpp>
#include <boost/archive/xml_iarchive.hpp>
#include <boost/archive/binary_iarchive.hpp>
#include <boost/archive/text_iarchive.hpp>
#include <boost/serialization/serialization.hpp>
#include <boost/serialization/export.hpp>
#include <boost/serialization/extended_type_info.hpp>
#include <boost/filesystem/operations.hpp>
#include <fstream>
#include <iostream>
Defines
#define BOOST_TEST_MODULE imageeffectplugin_tests
Functions
BOOST_AUTO_TEST_CASE (imageeffectplugin_serialization)
Define Documentation
#define BOOST_TEST_MODULE imageeffectplugin_tests
Definition at line 1 of file main.cpp.
Function Documentation
BOOST_AUTO_TEST_CASE (imageeffectplugin_serialization)
Definition at line 26 of file main.cpp.
References tuttle::host::ofx::OfxhPluginCache::addDirectoryToPath(), tuttle::host::Preferences::buildTuttleTestPath(), tuttle::host::core(), tuttle::host::Core::getImageEffectPluginById(), tuttle::host::Core::getPluginCache(), tuttle::host::Core::getPreferences(), tuttle::host::Core::preload(), TUTTLE_TLOG_VAR, and TUTTLE_TRACE.