TuttleOFX: boost::stack_trace Namespace Reference
boost::stack_trace Namespace Reference
Functions
int trace (void **, int)
std::string get_symbol (void *ptr)
std::string get_symbols (void *const *ptrs, int size)
void write_symbols (void *const *addresses, int size, std::ostream &out)
Function Documentation
std::string boost::stack_trace::get_symbol (void * ptr)
Definition at line 281 of file backtrace.cpp.
Referenced by boost::backtrace::trace_line().
std::string boost::stack_trace::get_symbols (void *const * ptrs, int size)
Definition at line 291 of file backtrace.cpp.
References write_symbols().
Referenced by boost::backtrace::trace().
int boost::stack_trace::trace (void ** , int)
Definition at line 67 of file backtrace.cpp.
Referenced by tuttle::exception::format_exception_info(), and tuttle::common::Formatter::setLogLevel_int().
void boost::stack_trace::write_symbols (void *const * addresses, int size, std::ostream & out)
Definition at line 301 of file backtrace.cpp.
Referenced by get_symbols(), boost::backtrace::trace(), and boost::backtrace::trace_line().