TuttleOFX: tuttle::host::attribute::ParamRGB Class Reference
tuttle::host::attribute::ParamRGB Class Reference
#include <ParamRGB.hpp>
Public Member Functions
ParamRGB (INode &effect, const std::string &name, const ofx::attribute::OfxhParamDescriptor &descriptor)
ParamRGB * clone () const
clone this parameter
OfxRGBColourD getDefault () const
void getValue (double &r, double &g, double &b) const OFX_EXCEPTION_SPEC
void getValueAtTime (const OfxTime time, double &r, double &g, double &b) const OFX_EXCEPTION_SPEC
void setValue (const double &r, const double &g, const double &b, const ofx::attribute::EChange change) OFX_EXCEPTION_SPEC
void setValueAtTime (const OfxTime time, const double &r, const double &g, const double &b, const ofx::attribute::EChange change) OFX_EXCEPTION_SPEC
void setValue (const int &r, const int &g, const int &b, const ofx::attribute::EChange change) OFX_EXCEPTION_SPEC
void setValueAtTime (const OfxTime time, const int &r, const int &g, const int &b, const ofx::attribute::EChange change) OFX_EXCEPTION_SPEC
Detailed Description
Definition at line 14 of file ParamRGB.hpp.
Constructor & Destructor Documentation
tuttle::host::attribute::ParamRGB::ParamRGB (INode & effect, const std::string & name, const ofx::attribute::OfxhParamDescriptor & descriptor)
Definition at line 9 of file ParamRGB.cpp.
References tuttle::host::ofx::attribute::OfxhMultiDimParam< ParamDouble, DIM >::_controls.
Referenced by clone().
Member Function Documentation
ParamRGB* tuttle::host::attribute::ParamRGB::clone () const [inline, virtual]
clone this parameter
Implements tuttle::host::ofx::attribute::OfxhParam.
Definition at line 19 of file ParamRGB.hpp.
References ParamRGB().
OfxRGBColourD tuttle::host::attribute::ParamRGB::getDefault () const
Definition at line 20 of file ParamRGB.cpp.
References tuttle::host::ofx::attribute::OfxhMultiDimParam< ParamDouble, DIM >::_controls.
void tuttle::host::attribute::ParamRGB::getValue (double & r, double & g, double & b) const
Definition at line 30 of file ParamRGB.cpp.
void tuttle::host::attribute::ParamRGB::getValueAtTime (const OfxTime time, double & r, double & g, double & b) const
Definition at line 37 of file ParamRGB.cpp.
void tuttle::host::attribute::ParamRGB::setValue (const double & r, const double & g, const double & b, const ofx::attribute::EChange change)
Definition at line 44 of file ParamRGB.cpp.
Referenced by setValue().
void tuttle::host::attribute::ParamRGB::setValue (const int & r, const int & g, const int & b, const ofx::attribute::EChange change) [inline]
Definition at line 27 of file ParamRGB.hpp.
References setValue().
void tuttle::host::attribute::ParamRGB::setValueAtTime (const OfxTime time, const double & r, const double & g, const double & b, const ofx::attribute::EChange change)
Definition at line 52 of file ParamRGB.cpp.
Referenced by setValueAtTime().
void tuttle::host::attribute::ParamRGB::setValueAtTime (const OfxTime time, const int & r, const int & g, const int & b, const ofx::attribute::EChange change) [inline]
Definition at line 31 of file ParamRGB.hpp.
References setValueAtTime().
The documentation for this class was generated from the following files:
TuttleOFX/libraries/tuttle/src/tuttle/host/attribute/ParamRGB.hpp
TuttleOFX/libraries/tuttle/src/tuttle/host/attribute/ParamRGB.cpp