TuttleOFX: tuttle::host::ofx::attribute::OfxhMultiDimParam< T, DIM > Class Template Reference
tuttle::host::ofx::attribute::OfxhMultiDimParam< T, DIM > Class Template Reference
#include <OfxhMultiDimParam.hpp>
Public Types
typedef T Type
typedef T::BaseType BaseType
Public Member Functions
OfxhMultiDimParam (const OfxhParamDescriptor &descriptor, const std::string &name, OfxhParamSet &setInstance)
virtual ~OfxhMultiDimParam ()
std::size_t getSize () const
void setValueFromExpression (const std::string &value, const ofx::attribute::EChange change) OFX_EXCEPTION_SPEC
void copy (const OfxhMultiDimParam &p) OFX_EXCEPTION_SPEC
void copy (const OfxhParam &p) OFX_EXCEPTION_SPEC
void setValue (const BaseType &value, const ofx::attribute::EChange change) OFX_EXCEPTION_SPEC
void setValueAtTime (const OfxTime time, const BaseType &value, const ofx::attribute::EChange change) OFX_EXCEPTION_SPEC
virtual void setValueAtIndex (const std::size_t index, const BaseType &value, const EChange change) OFX_EXCEPTION_SPEC
virtual void setValueAtTimeAndIndex (const OfxTime time, const std::size_t index, const BaseType &value, const EChange change) OFX_EXCEPTION_SPEC
virtual void setValue (const std::vector< BaseType > &values, const EChange change) OFX_EXCEPTION_SPEC
virtual void setValueAtTime (const OfxTime time, const std::vector< BaseType > &values, const EChange change) OFX_EXCEPTION_SPEC
virtual void deriveAtIndex (const OfxTime time, const std::size_t index, BaseType &outDst) const OFX_EXCEPTION_SPEC
virtual void integrateAtIndex (const OfxTime time1, const OfxTime time2, const std::size_t index, BaseType &outDst) const OFX_EXCEPTION_SPEC
virtual void getV (va_list arg) const OFX_EXCEPTION_SPEC
implementation of var args function
virtual void getV (const OfxTime time, va_list arg) const OFX_EXCEPTION_SPEC
implementation of var args function
virtual void setV (va_list arg, const EChange change) OFX_EXCEPTION_SPEC
implementation of var args function
virtual void setV (const OfxTime time, va_list arg, const EChange change) OFX_EXCEPTION_SPEC
implementation of var args function
virtual void deriveV (const OfxTime time, va_list arg) const OFX_EXCEPTION_SPEC
implementation of var args function
virtual void integrateV (const OfxTime time1, const OfxTime time2, va_list arg) const OFX_EXCEPTION_SPEC
implementation of var args function
bool paramTypeHasData () const
std::size_t getHashAtTime (const OfxTime time) const
std::ostream & displayValues (std::ostream &os) const
Protected Member Functions
BOOST_STATIC_ASSERT (DIM!=0)
virtual void getValueAtIndex (const std::size_t index, BaseType &outDst) const OFX_EXCEPTION_SPEC
virtual void getValueAtTimeAndIndex (const OfxTime time, const std::size_t index, BaseType &outDst) const OFX_EXCEPTION_SPEC
Protected Attributes
boost::ptr_array< T, DIM > _controls
Detailed Description
template<class T, std::size_t DIM>
class tuttle::host::ofx::attribute::OfxhMultiDimParam< T, DIM >
Definition at line 22 of file OfxhMultiDimParam.hpp.
Member Typedef Documentation
template<class T, std::size_t DIM> typedef T::BaseType tuttle::host::ofx::attribute::OfxhMultiDimParam< T, DIM >::BaseType
Definition at line 27 of file OfxhMultiDimParam.hpp.
template<class T, std::size_t DIM> typedef T tuttle::host::ofx::attribute::OfxhMultiDimParam< T, DIM >::Type
Definition at line 26 of file OfxhMultiDimParam.hpp.
Constructor & Destructor Documentation
template<class T, std::size_t DIM> tuttle::host::ofx::attribute::OfxhMultiDimParam< T, DIM >::OfxhMultiDimParam (const OfxhParamDescriptor & descriptor, const std::string & name, OfxhParamSet & setInstance) [inline]
Definition at line 37 of file OfxhMultiDimParam.hpp.
template<class T, std::size_t DIM> virtual tuttle::host::ofx::attribute::OfxhMultiDimParam< T, DIM >::~OfxhMultiDimParam () [inline, virtual]
Definition at line 41 of file OfxhMultiDimParam.hpp.
Member Function Documentation
template<class T, std::size_t DIM> tuttle::host::ofx::attribute::OfxhMultiDimParam< T, DIM >::BOOST_STATIC_ASSERT (DIM! = 0) [protected]
template<class T, std::size_t DIM> void tuttle::host::ofx::attribute::OfxhMultiDimParam< T, DIM >::copy (const OfxhMultiDimParam< T, DIM > & p) [inline]
Definition at line 103 of file OfxhMultiDimParam.hpp.
Referenced by tuttle::host::ofx::attribute::OfxhMultiDimParam< ParamDouble, DIM >::copy().
template<class T, std::size_t DIM> void tuttle::host::ofx::attribute::OfxhMultiDimParam< T, DIM >::copy (const OfxhParam & p) [inline, virtual]
Implements tuttle::host::ofx::attribute::OfxhParam.
Definition at line 111 of file OfxhMultiDimParam.hpp.
template<class T, std::size_t DIM> virtual void tuttle::host::ofx::attribute::OfxhMultiDimParam< T, DIM >::deriveAtIndex (const OfxTime time, const std::size_t index, BaseType & outDst) const [inline, virtual]
Definition at line 192 of file OfxhMultiDimParam.hpp.
template<class T, std::size_t DIM> virtual void tuttle::host::ofx::attribute::OfxhMultiDimParam< T, DIM >::deriveV (const OfxTime time, va_list arg) const [inline, virtual]
implementation of var args function
Reimplemented from tuttle::host::ofx::attribute::OfxhParam.
Definition at line 259 of file OfxhMultiDimParam.hpp.
template<class T, std::size_t DIM> std::ostream& tuttle::host::ofx::attribute::OfxhMultiDimParam< T, DIM >::displayValues (std::ostream & os) const [inline, virtual]
Reimplemented from tuttle::host::ofx::attribute::OfxhParam.
Definition at line 294 of file OfxhMultiDimParam.hpp.
template<class T, std::size_t DIM> std::size_t tuttle::host::ofx::attribute::OfxhMultiDimParam< T, DIM >::getHashAtTime (const OfxTime time) const [inline, virtual]
Implements tuttle::host::ofx::attribute::OfxhParam.
Definition at line 282 of file OfxhMultiDimParam.hpp.
template<class T, std::size_t DIM> std::size_t tuttle::host::ofx::attribute::OfxhMultiDimParam< T, DIM >::getSize () const [inline, virtual]
Reimplemented from tuttle::host::ofx::attribute::OfxhParam.
Definition at line 44 of file OfxhMultiDimParam.hpp.
Referenced by tuttle::host::ofx::attribute::OfxhMultiDimParam< ParamDouble, DIM >::deriveAtIndex(), tuttle::host::ofx::attribute::OfxhMultiDimParam< ParamDouble, DIM >::getHashAtTime(), tuttle::host::ofx::attribute::OfxhMultiDimParam< ParamDouble, DIM >::getValueAtIndex(), tuttle::host::ofx::attribute::OfxhMultiDimParam< ParamDouble, DIM >::getValueAtTimeAndIndex(), tuttle::host::ofx::attribute::OfxhMultiDimParam< ParamDouble, DIM >::integrateAtIndex(), tuttle::host::ofx::attribute::OfxhMultiDimParam< ParamDouble, DIM >::setValue(), tuttle::host::ofx::attribute::OfxhMultiDimParam< ParamDouble, DIM >::setValueAtIndex(), tuttle::host::ofx::attribute::OfxhMultiDimParam< ParamDouble, DIM >::setValueAtTime(), tuttle::host::ofx::attribute::OfxhMultiDimParam< ParamDouble, DIM >::setValueAtTimeAndIndex(), and tuttle::host::ofx::attribute::OfxhMultiDimParam< ParamDouble, DIM >::setValueFromExpression().
template<class T, std::size_t DIM> virtual void tuttle::host::ofx::attribute::OfxhMultiDimParam< T, DIM >::getV (va_list arg) const [inline, virtual]
implementation of var args function
Reimplemented from tuttle::host::ofx::attribute::OfxhParam.
Definition at line 216 of file OfxhMultiDimParam.hpp.
template<class T, std::size_t DIM> virtual void tuttle::host::ofx::attribute::OfxhMultiDimParam< T, DIM >::getV (const OfxTime time, va_list arg) const [inline, virtual]
implementation of var args function
Reimplemented from tuttle::host::ofx::attribute::OfxhParam.
Definition at line 227 of file OfxhMultiDimParam.hpp.
template<class T, std::size_t DIM> virtual void tuttle::host::ofx::attribute::OfxhMultiDimParam< T, DIM >::getValueAtIndex (const std::size_t index, BaseType & outDst) const [inline, protected, virtual]
Definition at line 79 of file OfxhMultiDimParam.hpp.
template<class T, std::size_t DIM> virtual void tuttle::host::ofx::attribute::OfxhMultiDimParam< T, DIM >::getValueAtTimeAndIndex (const OfxTime time, const std::size_t index, BaseType & outDst) const [inline, protected, virtual]
Definition at line 90 of file OfxhMultiDimParam.hpp.
Referenced by tuttle::host::ofx::attribute::OfxhMultiDimParam< ParamDouble, DIM >::getHashAtTime().
template<class T, std::size_t DIM> virtual void tuttle::host::ofx::attribute::OfxhMultiDimParam< T, DIM >::integrateAtIndex (const OfxTime time1, const OfxTime time2, const std::size_t index, BaseType & outDst) const [inline, virtual]
Definition at line 203 of file OfxhMultiDimParam.hpp.
template<class T, std::size_t DIM> virtual void tuttle::host::ofx::attribute::OfxhMultiDimParam< T, DIM >::integrateV (const OfxTime time1, const OfxTime time2, va_list arg) const [inline, virtual]
implementation of var args function
Reimplemented from tuttle::host::ofx::attribute::OfxhParam.
Definition at line 269 of file OfxhMultiDimParam.hpp.
template<class T, std::size_t DIM> bool tuttle::host::ofx::attribute::OfxhMultiDimParam< T, DIM >::paramTypeHasData () const [inline, virtual]
Implements tuttle::host::ofx::attribute::OfxhParam.
Definition at line 280 of file OfxhMultiDimParam.hpp.
template<class T, std::size_t DIM> virtual void tuttle::host::ofx::attribute::OfxhMultiDimParam< T, DIM >::setV (va_list arg, const EChange change) [inline, virtual]
implementation of var args function
Reimplemented from tuttle::host::ofx::attribute::OfxhParam.
Definition at line 237 of file OfxhMultiDimParam.hpp.
template<class T, std::size_t DIM> virtual void tuttle::host::ofx::attribute::OfxhMultiDimParam< T, DIM >::setV (const OfxTime time, va_list arg, const EChange change) [inline, virtual]
implementation of var args function
Reimplemented from tuttle::host::ofx::attribute::OfxhParam.
Definition at line 248 of file OfxhMultiDimParam.hpp.
template<class T, std::size_t DIM> void tuttle::host::ofx::attribute::OfxhMultiDimParam< T, DIM >::setValue (const BaseType & value, const ofx::attribute::EChange change) [inline]
Definition at line 119 of file OfxhMultiDimParam.hpp.
template<class T, std::size_t DIM> virtual void tuttle::host::ofx::attribute::OfxhMultiDimParam< T, DIM >::setValue (const std::vector< BaseType > & values, const EChange change) [inline, virtual]
Definition at line 161 of file OfxhMultiDimParam.hpp.
template<class T, std::size_t DIM> virtual void tuttle::host::ofx::attribute::OfxhMultiDimParam< T, DIM >::setValueAtIndex (const std::size_t index, const BaseType & value, const EChange change) [inline, virtual]
Definition at line 137 of file OfxhMultiDimParam.hpp.
template<class T, std::size_t DIM> void tuttle::host::ofx::attribute::OfxhMultiDimParam< T, DIM >::setValueAtTime (const OfxTime time, const BaseType & value, const ofx::attribute::EChange change) [inline]
Definition at line 128 of file OfxhMultiDimParam.hpp.
template<class T, std::size_t DIM> virtual void tuttle::host::ofx::attribute::OfxhMultiDimParam< T, DIM >::setValueAtTime (const OfxTime time, const std::vector< BaseType > & values, const EChange change) [inline, virtual]
Definition at line 176 of file OfxhMultiDimParam.hpp.
template<class T, std::size_t DIM> virtual void tuttle::host::ofx::attribute::OfxhMultiDimParam< T, DIM >::setValueAtTimeAndIndex (const OfxTime time, const std::size_t index, const BaseType & value, const EChange change) [inline, virtual]
Definition at line 149 of file OfxhMultiDimParam.hpp.
template<class T, std::size_t DIM> void tuttle::host::ofx::attribute::OfxhMultiDimParam< T, DIM >::setValueFromExpression (const std::string & value, const ofx::attribute::EChange change) [inline, virtual]
Reimplemented from tuttle::host::ofx::attribute::OfxhParam.
Definition at line 49 of file OfxhMultiDimParam.hpp.
Field Documentation
template<class T, std::size_t DIM> boost::ptr_array<T, DIM> tuttle::host::ofx::attribute::OfxhMultiDimParam< T, DIM >::_controls [protected]
Definition at line 30 of file OfxhMultiDimParam.hpp.
Referenced by tuttle::host::ofx::attribute::OfxhMultiDimParam< ParamDouble, DIM >::copy(), tuttle::host::ofx::attribute::OfxhMultiDimParam< ParamDouble, DIM >::deriveAtIndex(), tuttle::host::ofx::attribute::OfxhMultiDimParam< ParamDouble, DIM >::deriveV(), tuttle::host::ofx::attribute::OfxhMultiDimParam< ParamDouble, DIM >::displayValues(), tuttle::host::ofx::attribute::OfxhMultiDimParam< ParamDouble, DIM >::getSize(), tuttle::host::ofx::attribute::OfxhMultiDimParam< ParamDouble, DIM >::getV(), tuttle::host::ofx::attribute::OfxhMultiDimParam< ParamDouble, DIM >::getValueAtIndex(), tuttle::host::ofx::attribute::OfxhMultiDimParam< ParamDouble, DIM >::getValueAtTimeAndIndex(), tuttle::host::ofx::attribute::OfxhMultiDimParam< ParamDouble, DIM >::integrateAtIndex(), tuttle::host::ofx::attribute::OfxhMultiDimParam< ParamDouble, DIM >::integrateV(), tuttle::host::ofx::attribute::OfxhMultiDimParam< ParamDouble, DIM >::setV(), tuttle::host::ofx::attribute::OfxhMultiDimParam< ParamDouble, DIM >::setValue(), tuttle::host::ofx::attribute::OfxhMultiDimParam< ParamDouble, DIM >::setValueAtIndex(), tuttle::host::ofx::attribute::OfxhMultiDimParam< ParamDouble, DIM >::setValueAtTime(), tuttle::host::ofx::attribute::OfxhMultiDimParam< ParamDouble, DIM >::setValueAtTimeAndIndex(), and tuttle::host::ofx::attribute::OfxhMultiDimParam< ParamDouble, DIM >::setValueFromExpression().
The documentation for this class was generated from the following file:
TuttleOFX/libraries/tuttle/src/tuttle/host/ofx/attribute/OfxhMultiDimParam.hpp