TuttleOFX: tuttle::host::attribute::ParamCustom Class Reference
tuttle::host::attribute::ParamCustom Class Reference
#include <ParamCustom.hpp>
Public Member Functions
ParamCustom (INode &effect, const std::string &name, const ofx::attribute::OfxhParamDescriptor &descriptor)
ParamCustom * clone () const
clone this parameter
const std::string & getDefault () const
void getValue (std::string &) const OFX_EXCEPTION_SPEC
void getValueAtTime (const OfxTime time, std::string &) const OFX_EXCEPTION_SPEC
void setValue (const std::string &value, const ofx::attribute::EChange change) OFX_EXCEPTION_SPEC
void setValueAtTime (const OfxTime time, const std::string &value, const ofx::attribute::EChange change) OFX_EXCEPTION_SPEC
void setValueFromExpression (const std::string &value, const ofx::attribute::EChange change) OFX_EXCEPTION_SPEC
void copy (const ParamCustom &p) OFX_EXCEPTION_SPEC
void copy (const OfxhParam &p) OFX_EXCEPTION_SPEC
Protected Attributes
std::string _value
Detailed Description
Definition at line 13 of file ParamCustom.hpp.
Constructor & Destructor Documentation
tuttle::host::attribute::ParamCustom::ParamCustom (INode & effect, const std::string & name, const ofx::attribute::OfxhParamDescriptor & descriptor)
Todo:
link de parametres
Definition at line 10 of file ParamCustom.cpp.
References _value, and getDefault().
Referenced by clone().
Member Function Documentation
ParamCustom* tuttle::host::attribute::ParamCustom::clone () const [inline, virtual]
clone this parameter
Implements tuttle::host::ofx::attribute::OfxhParam.
Definition at line 21 of file ParamCustom.hpp.
References ParamCustom().
void tuttle::host::attribute::ParamCustom::copy (const ParamCustom & p)
Definition at line 52 of file ParamCustom.cpp.
References _value.
void tuttle::host::attribute::ParamCustom::copy (const OfxhParam & p)
Definition at line 58 of file ParamCustom.cpp.
const std::string & tuttle::host::attribute::ParamCustom::getDefault () const
Definition at line 19 of file ParamCustom.cpp.
References tuttle::host::ofx::attribute::OfxhAttributeAccessor::getProperties().
Referenced by ParamCustom().
void tuttle::host::attribute::ParamCustom::getValue (std::string & v) const [virtual]
Implements tuttle::host::ofx::attribute::OfxhParamString.
Definition at line 24 of file ParamCustom.cpp.
References _value.
void tuttle::host::attribute::ParamCustom::getValueAtTime (const OfxTime time, std::string & v) const [virtual]
<
Todo:
: in time !
Implements tuttle::host::ofx::attribute::OfxhParamString.
Definition at line 29 of file ParamCustom.cpp.
References _value.
void tuttle::host::attribute::ParamCustom::setValue (const std::string & value, const ofx::attribute::EChange change) [virtual]
Implements tuttle::host::ofx::attribute::OfxhParamString.
Definition at line 34 of file ParamCustom.cpp.
References _value.
void tuttle::host::attribute::ParamCustom::setValueAtTime (const OfxTime time, const std::string & value, const ofx::attribute::EChange change) [virtual]
<
Todo:
: in time !
Implements tuttle::host::ofx::attribute::OfxhParamString.
Definition at line 40 of file ParamCustom.cpp.
References _value.
void tuttle::host::attribute::ParamCustom::setValueFromExpression (const std::string & value, const ofx::attribute::EChange change) [virtual]
Reimplemented from tuttle::host::ofx::attribute::OfxhParam.
Definition at line 46 of file ParamCustom.cpp.
References _value.
Field Documentation
std::string tuttle::host::attribute::ParamCustom::_value [protected]
Definition at line 17 of file ParamCustom.hpp.
Referenced by ParamCustom().
The documentation for this class was generated from the following files:
TuttleOFX/libraries/tuttle/src/tuttle/host/attribute/ParamCustom.hpp
TuttleOFX/libraries/tuttle/src/tuttle/host/attribute/ParamCustom.cpp