TuttleOFX: TuttleOFX/libraries/tuttle/tests/ofx/properties/main.cpp File Reference
TuttleOFX/libraries/tuttle/tests/ofx/properties/main.cpp File Reference
#include <tuttle/test/unit_test.hpp>
#include <tuttle/common/utils/global.hpp>
#include <tuttle/host/Core.hpp>
#include <iostream>
Defines
#define BOOST_TEST_MODULE properties_tests
#define testString_1_ro "testString_1_ro"
#define testString_2_rw "testString_2_rw"
#define testPointer_1_rw "testPointer_1_rw"
#define testDouble_2_ro "testDouble_2_ro"
#define testDouble_1_rw "testDouble_1_rw"
#define testInt_1_rw "testInt_1_rw"
#define testInt_2_rw "testInt_2_rw"
#define testInt_4_ro "testInt_4_ro"
Functions
BOOST_AUTO_TEST_CASE (properties_get_and_set)
Define Documentation
#define BOOST_TEST_MODULE properties_tests
Definition at line 1 of file main.cpp.
#define testDouble_1_rw "testDouble_1_rw"
Referenced by BOOST_AUTO_TEST_CASE().
#define testDouble_2_ro "testDouble_2_ro"
Referenced by BOOST_AUTO_TEST_CASE().
#define testInt_1_rw "testInt_1_rw"
Referenced by BOOST_AUTO_TEST_CASE().
#define testInt_2_rw "testInt_2_rw"
Referenced by BOOST_AUTO_TEST_CASE().
#define testInt_4_ro "testInt_4_ro"
Referenced by BOOST_AUTO_TEST_CASE().
#define testPointer_1_rw "testPointer_1_rw"
Referenced by BOOST_AUTO_TEST_CASE().
#define testString_1_ro "testString_1_ro"
Referenced by BOOST_AUTO_TEST_CASE().
#define testString_2_rw "testString_2_rw"
Referenced by BOOST_AUTO_TEST_CASE().
Function Documentation
BOOST_AUTO_TEST_CASE (properties_get_and_set)
Definition at line 13 of file main.cpp.
References tuttle::host::ofx::property::ePropTypeDouble, tuttle::host::ofx::property::ePropTypeInt, tuttle::host::ofx::property::ePropTypePointer, tuttle::host::ofx::property::ePropTypeString, tuttle::host::ofx::property::OfxhSet::getDoubleProperty(), tuttle::host::ofx::property::OfxhSet::getIntProperty(), tuttle::host::ofx::property::OfxhSet::getIntPropertyN(), tuttle::host::ofx::property::OfxhSet::getStringProperty(), tuttle::host::ofx::property::OfxhSet::setDoublePropertyN(), tuttle::host::ofx::property::OfxhSet::setIntProperty(), tuttle::host::ofx::property::OfxhSet::setStringProperty(), testDouble_1_rw, testDouble_2_ro, testInt_1_rw, testInt_2_rw, testInt_4_ro, testPointer_1_rw, testString_1_ro, and testString_2_rw.