TuttleOFX: tuttle::host::attribute::ParamChoice Class Reference
tuttle::host::attribute::ParamChoice Class Reference
#include <ParamChoice.hpp>
Public Member Functions
ParamChoice (INode &effect, const std::string &name, const ofx::attribute::OfxhParamDescriptor &descriptor)
ParamChoice * clone () const
clone this parameter
int getDefault () const
void getValue (int &) const OFX_EXCEPTION_SPEC
void getValueAtTime (const OfxTime time, int &) const OFX_EXCEPTION_SPEC
void setValue (const int &, const ofx::attribute::EChange change) OFX_EXCEPTION_SPEC
void setValueAtTime (const OfxTime time, const int &, const ofx::attribute::EChange change) OFX_EXCEPTION_SPEC
void setValueFromExpression (const std::string &value, const ofx::attribute::EChange change) OFX_EXCEPTION_SPEC
void copy (const ParamChoice &p) OFX_EXCEPTION_SPEC
void copy (const OfxhParam &p) OFX_EXCEPTION_SPEC
Protected Attributes
int _value
Detailed Description
Definition at line 12 of file ParamChoice.hpp.
Constructor & Destructor Documentation
tuttle::host::attribute::ParamChoice::ParamChoice (INode & effect, const std::string & name, const ofx::attribute::OfxhParamDescriptor & descriptor)
Definition at line 10 of file ParamChoice.cpp.
References _value, and getDefault().
Referenced by clone().
Member Function Documentation
ParamChoice* tuttle::host::attribute::ParamChoice::clone () const [inline, virtual]
clone this parameter
Implements tuttle::host::ofx::attribute::OfxhParam.
Definition at line 20 of file ParamChoice.hpp.
References ParamChoice().
void tuttle::host::attribute::ParamChoice::copy (const ParamChoice & p)
Definition at line 84 of file ParamChoice.cpp.
References _value.
void tuttle::host::attribute::ParamChoice::copy (const OfxhParam & p)
Definition at line 90 of file ParamChoice.cpp.
int tuttle::host::attribute::ParamChoice::getDefault () const
Definition at line 19 of file ParamChoice.cpp.
References tuttle::host::ofx::attribute::OfxhAttribute::getProperties().
Referenced by ParamChoice().
void tuttle::host::attribute::ParamChoice::getValue (int & v) const [virtual]
Implements tuttle::host::ofx::attribute::OfxhParamChoice.
Definition at line 24 of file ParamChoice.cpp.
References _value.
void tuttle::host::attribute::ParamChoice::getValueAtTime (const OfxTime time, int & v) const [virtual]
<
Todo:
: in time !
Implements tuttle::host::ofx::attribute::OfxhParamChoice.
Definition at line 29 of file ParamChoice.cpp.
References _value.
void tuttle::host::attribute::ParamChoice::setValue (const int & v, const ofx::attribute::EChange change) [virtual]
Implements tuttle::host::ofx::attribute::OfxhParamChoice.
Definition at line 34 of file ParamChoice.cpp.
References _value.
void tuttle::host::attribute::ParamChoice::setValueAtTime (const OfxTime time, const int & v, const ofx::attribute::EChange change) [virtual]
<
Todo:
: in time !
Implements tuttle::host::ofx::attribute::OfxhParamChoice.
Definition at line 48 of file ParamChoice.cpp.
References _value.
void tuttle::host::attribute::ParamChoice::setValueFromExpression (const std::string & value, const ofx::attribute::EChange change) [virtual]
Reimplemented from tuttle::host::ofx::attribute::OfxhParam.
Definition at line 62 of file ParamChoice.cpp.
Field Documentation
int tuttle::host::attribute::ParamChoice::_value [protected]
Definition at line 16 of file ParamChoice.hpp.
Referenced by ParamChoice().
The documentation for this class was generated from the following files:
TuttleOFX/libraries/tuttle/src/tuttle/host/attribute/ParamChoice.hpp
TuttleOFX/libraries/tuttle/src/tuttle/host/attribute/ParamChoice.cpp