TuttleOFX: tuttle::host::ofx::attribute::OfxhParamGroup Class Reference
tuttle::host::ofx::attribute::OfxhParamGroup Class Reference
#include <OfxhParamGroup.hpp>
Public Member Functions
OfxhParamGroup (const OfxhParamDescriptor &descriptor, const std::string &name, OfxhParamSet &setInstance)
virtual ~OfxhParamGroup ()
property::OfxhSet & getParamSetProps ()
virtual void paramChanged (const attribute::OfxhParam &param, const EChange change)
virtual void editBegin (const std::string &name) OFX_EXCEPTION_SPEC
Triggered when the plug-in calls OfxParameterSuiteV1::paramEditBegin.
virtual void editEnd () OFX_EXCEPTION_SPEC
Triggered when the plug-in calls OfxParameterSuiteV1::paramEditEnd.
bool paramTypeHasData () const
std::size_t getHashAtTime (const OfxTime time) const
Detailed Description
Definition at line 13 of file OfxhParamGroup.hpp.
Constructor & Destructor Documentation
tuttle::host::ofx::attribute::OfxhParamGroup::OfxhParamGroup (const OfxhParamDescriptor & descriptor, const std::string & name, OfxhParamSet & setInstance) [inline]
Definition at line 18 of file OfxhParamGroup.hpp.
virtual tuttle::host::ofx::attribute::OfxhParamGroup::~OfxhParamGroup () [inline, virtual]
Definition at line 21 of file OfxhParamGroup.hpp.
Member Function Documentation
virtual void tuttle::host::ofx::attribute::OfxhParamGroup::editBegin (const std::string & name) [inline, virtual]
Triggered when the plug-in calls OfxParameterSuiteV1::paramEditBegin.
Implements tuttle::host::ofx::attribute::OfxhParamSet.
Definition at line 36 of file OfxhParamGroup.hpp.
References tuttle::host::ofx::attribute::OfxhParam::_paramSetInstance, and tuttle::host::ofx::attribute::OfxhParamSet::editBegin().
virtual void tuttle::host::ofx::attribute::OfxhParamGroup::editEnd () [inline, virtual]
Triggered when the plug-in calls OfxParameterSuiteV1::paramEditEnd.
Implements tuttle::host::ofx::attribute::OfxhParamSet.
Definition at line 42 of file OfxhParamGroup.hpp.
References tuttle::host::ofx::attribute::OfxhParam::_paramSetInstance, and tuttle::host::ofx::attribute::OfxhParamSet::editEnd().
std::size_t tuttle::host::ofx::attribute::OfxhParamGroup::getHashAtTime (const OfxTime time) const [inline, virtual]
Implements tuttle::host::ofx::attribute::OfxhParam.
Definition at line 49 of file OfxhParamGroup.hpp.
property::OfxhSet& tuttle::host::ofx::attribute::OfxhParamGroup::getParamSetProps () [inline, virtual]
get the property handle that lives with the set The plugin descriptor/instance that derives from this will provide this.
Implements tuttle::host::ofx::attribute::OfxhParamSetAccessor.
Definition at line 23 of file OfxhParamGroup.hpp.
References tuttle::host::ofx::attribute::OfxhParam::_paramSetInstance, and tuttle::host::ofx::attribute::OfxhParamSetAccessor::getParamSetProps().
virtual void tuttle::host::ofx::attribute::OfxhParamGroup::paramChanged (const attribute::OfxhParam & param, const EChange change) [inline, virtual]
The inheriting plugin instance needs to set this up to deal with plug-ins changing their own values.
Implements tuttle::host::ofx::attribute::OfxhParamSet.
Definition at line 30 of file OfxhParamGroup.hpp.
References tuttle::host::ofx::attribute::OfxhParam::_paramSetInstance, and tuttle::host::ofx::attribute::OfxhParamSet::paramChanged().
bool tuttle::host::ofx::attribute::OfxhParamGroup::paramTypeHasData () const [inline, virtual]
Implements tuttle::host::ofx::attribute::OfxhParam.
Definition at line 47 of file OfxhParamGroup.hpp.
The documentation for this class was generated from the following file:
TuttleOFX/libraries/tuttle/src/tuttle/host/ofx/attribute/OfxhParamGroup.hpp