TuttleOFX: tuttle::host::ofx::attribute::OfxhClipImageAccessor Class Reference
tuttle::host::ofx::attribute::OfxhClipImageAccessor Class Reference
#include <OfxhClipImageAccessor.hpp>
Public Member Functions
OfxhClipImageAccessor ()
base ctor, for a descriptor
virtual ~OfxhClipImageAccessor ()=0
const std::vector< std::string > & getSupportedComponents () const
bool isSupportedComponent (const std::string &comp) const
is the given component supported
bool temporalAccess () const
does the clip do random temporal access
bool isMask () const
is the clip a nominal 'mask' clip
const std::string & getFieldExtraction () const
how does this clip like fielded images to be presented to it
bool supportsTiles () const
is the clip a nominal 'mask' clip
virtual OfxImageClipHandle getOfxImageClipHandle () const =0
get a handle on the clip descriptor/instance for the C api
Detailed Description
Base to both descriptor and instance it is used to basically fetch common properties by function name
Definition at line 16 of file OfxhClipImageAccessor.hpp.
Constructor & Destructor Documentation
tuttle::host::ofx::attribute::OfxhClipImageAccessor::OfxhClipImageAccessor ()
base ctor, for a descriptor
Definition at line 11 of file OfxhClipImageAccessor.cpp.
tuttle::host::ofx::attribute::OfxhClipImageAccessor::~OfxhClipImageAccessor () [pure virtual]
Definition at line 13 of file OfxhClipImageAccessor.cpp.
Member Function Documentation
const std::string & tuttle::host::ofx::attribute::OfxhClipImageAccessor::getFieldExtraction () const
how does this clip like fielded images to be presented to it
Reimplemented in tuttle::host::ofx::attribute::OfxhClipImage.
Definition at line 45 of file OfxhClipImageAccessor.cpp.
References tuttle::host::ofx::attribute::OfxhAttributeAccessor::getProperties(), and tuttle::host::ofx::property::OfxhSet::getStringProperty().
virtual OfxImageClipHandle tuttle::host::ofx::attribute::OfxhClipImageAccessor::getOfxImageClipHandle () const [pure virtual]
get a handle on the clip descriptor/instance for the C api
Implemented in tuttle::host::ofx::attribute::OfxhClipImage, and tuttle::host::ofx::attribute::OfxhClipImageDescriptor.
const std::vector< std::string > & tuttle::host::ofx::attribute::OfxhClipImageAccessor::getSupportedComponents () const
Returns:
a std::vector of supported comp
return a std::vector of supported comp
Definition at line 17 of file OfxhClipImageAccessor.cpp.
References tuttle::host::ofx::property::OfxhSet::fetchStringProperty(), and tuttle::host::ofx::attribute::OfxhAttributeAccessor::getProperties().
Referenced by tuttle::host::ofx::attribute::OfxhClipImage::findSupportedComp().
bool tuttle::host::ofx::attribute::OfxhClipImageAccessor::isMask () const
is the clip a nominal 'mask' clip
Definition at line 38 of file OfxhClipImageAccessor.cpp.
References tuttle::host::ofx::property::OfxhSet::getIntProperty(), and tuttle::host::ofx::attribute::OfxhAttributeAccessor::getProperties().
bool tuttle::host::ofx::attribute::OfxhClipImageAccessor::isSupportedComponent (const std::string & comp) const
is the given component supported
Definition at line 24 of file OfxhClipImageAccessor.cpp.
References tuttle::host::ofx::property::OfxhSet::findStringPropValueIndex(), and tuttle::host::ofx::attribute::OfxhAttributeAccessor::getProperties().
Referenced by tuttle::host::ofx::attribute::OfxhClipImage::findSupportedComp(), and tuttle::host::ImageEffectNode::initComponents().
bool tuttle::host::ofx::attribute::OfxhClipImageAccessor::supportsTiles () const
is the clip a nominal 'mask' clip
Definition at line 52 of file OfxhClipImageAccessor.cpp.
References tuttle::host::ofx::property::OfxhSet::getIntProperty(), and tuttle::host::ofx::attribute::OfxhAttributeAccessor::getProperties().
bool tuttle::host::ofx::attribute::OfxhClipImageAccessor::temporalAccess () const
does the clip do random temporal access
Definition at line 31 of file OfxhClipImageAccessor.cpp.
References tuttle::host::ofx::property::OfxhSet::getIntProperty(), and tuttle::host::ofx::attribute::OfxhAttributeAccessor::getProperties().
The documentation for this class was generated from the following files:
TuttleOFX/libraries/tuttle/src/tuttle/host/ofx/attribute/OfxhClipImageAccessor.hpp
TuttleOFX/libraries/tuttle/src/tuttle/host/ofx/attribute/OfxhClipImageAccessor.cpp