TuttleOFX: tuttle::plugin::overlay Namespace Reference
tuttle::plugin::overlay Namespace Reference
Functions
template<typename Point2 >
void displayCross (const Point2 &p, const double marge)
template<typename Point2 >
void displayPointRect (const Point2 &p, const Point2 &size)
template<typename Point2 >
void displayPointRect (const Point2 &p, const double marge)
template<typename Rect >
void displayRect (const Rect &r, const double marge=0)
template<typename Point2 >
void displayRect (const Point2 &a, const Point2 &b, const double marge=0)
template<typename Point2 >
void drawCurve (const std::vector< Point2 > &vec)
template<typename Point2 >
void drawCurves (const std::vector< std::vector< Point2 > > &vec)
Function Documentation
template<typename Point2 > void tuttle::plugin::overlay::displayCross (const Point2 & p, const double marge) [inline]
Definition at line 12 of file overlay.hpp.
Referenced by tuttle::plugin::interact::PointInteract::draw().
template<typename Point2 > void tuttle::plugin::overlay::displayPointRect (const Point2 & p, const Point2 & size) [inline]
Definition at line 23 of file overlay.hpp.
Referenced by tuttle::plugin::interact::PointInteract::draw(), and tuttle::plugin::interact::ParamRectangleFromCenterSize< TFrame, coord >::draw().
template<typename Point2 > void tuttle::plugin::overlay::displayPointRect (const Point2 & p, const double marge) [inline]
Definition at line 34 of file overlay.hpp.
template<typename Rect > void tuttle::plugin::overlay::displayRect (const Rect & r, const double marge = 0) [inline]
Definition at line 45 of file overlay.hpp.
Referenced by tuttle::plugin::interact::ParamRectangleFromTwoCorners< TFrame, coord >::draw(), and tuttle::plugin::interact::InteractScene::drawSelection().
template<typename Point2 > void tuttle::plugin::overlay::displayRect (const Point2 & a, const Point2 & b, const double marge = 0) [inline]
Definition at line 56 of file overlay.hpp.
template<typename Point2 > void tuttle::plugin::overlay::drawCurve (const std::vector< Point2 > & vec) [inline]
Definition at line 68 of file overlay.hpp.
Referenced by drawCurves().
template<typename Point2 > void tuttle::plugin::overlay::drawCurves (const std::vector< std::vector< Point2 > > & vec) [inline]
Definition at line 81 of file overlay.hpp.
References drawCurve().