TuttleOFX: tuttle::host::ofx::attribute::OfxhClip Class Reference
tuttle::host::ofx::attribute::OfxhClip Class Reference
#include <OfxhClip.hpp>
Public Types
typedef OfxhClip This
Public Member Functions
OfxhClip (const OfxhClipDescriptor &desc)
virtual ~OfxhClip ()=0
virtual OfxhClip * clone () const =0
clone this clip
virtual bool operator== (const This &other) const
bool operator!= (const This &other) const
virtual std::string getFullName () const =0
void initHook (const property::OfxhPropSpec *propSpec)
void notify (const std::string &name, bool isSingle, int indexOrN) OFX_EXCEPTION_SPEC
notify override properties
void reset (const std::string &name) OFX_EXCEPTION_SPEC
override this to handle a reset().
Protected Member Functions
OfxhClip (const OfxhClip &other)
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Friends
class boost::serialization::access
Detailed Description
a clip instance
Definition at line 22 of file OfxhClip.hpp.
Member Typedef Documentation
typedef OfxhClip tuttle::host::ofx::attribute::OfxhClip::This
Reimplemented from tuttle::host::ofx::attribute::OfxhAttribute.
Reimplemented in tuttle::host::ofx::attribute::OfxhClipImage.
Definition at line 30 of file OfxhClip.hpp.
Constructor & Destructor Documentation
tuttle::host::ofx::attribute::OfxhClip::OfxhClip (const OfxhClip & other) [inline, protected]
Definition at line 33 of file OfxhClip.hpp.
tuttle::host::ofx::attribute::OfxhClip::OfxhClip (const OfxhClipDescriptor & desc)
extra properties for the instance, these are fetched from the host via a get hook and some virtuals
we are an instance, we need to reset the props to read only
Definition at line 9 of file OfxhClip.cpp.
References tuttle::host::ofx::property::OfxhSet::addProperties(), tuttle::host::ofx::property::ePropTypeInt, tuttle::host::ofx::attribute::OfxhAttribute::getEditableProperties(), and initHook().
tuttle::host::ofx::attribute::OfxhClip::~OfxhClip () [pure virtual]
Definition at line 32 of file OfxhClip.cpp.
Member Function Documentation
virtual OfxhClip* tuttle::host::ofx::attribute::OfxhClip::clone () const [pure virtual]
clone this clip
Implemented in tuttle::host::ofx::attribute::OfxhClipImage, and tuttle::host::attribute::ClipImage.
Referenced by tuttle::host::ofx::attribute::new_clone().
virtual std::string tuttle::host::ofx::attribute::OfxhClip::getFullName () const [pure virtual]
Implemented in tuttle::host::attribute::ClipImage.
void tuttle::host::ofx::attribute::OfxhClip::initHook (const property::OfxhPropSpec * propSpec)
Definition at line 35 of file OfxhClip.cpp.
Referenced by OfxhClip(), and tuttle::host::ofx::attribute::OfxhClipImage::OfxhClipImage().
void tuttle::host::ofx::attribute::OfxhClip::notify (const std::string & name, bool isSingle, int indexOrN) [inline, virtual]
notify override properties
Implements tuttle::host::ofx::property::OfxhNotifyHook.
Definition at line 57 of file OfxhClip.hpp.
References TUTTLE_LOG_ERROR, and TUTTLE_LOG_INFOS.
bool tuttle::host::ofx::attribute::OfxhClip::operator!= (const This & other) const [inline]
Reimplemented from tuttle::host::ofx::attribute::OfxhAttribute.
Reimplemented in tuttle::host::ofx::attribute::OfxhClipImage.
Definition at line 49 of file OfxhClip.hpp.
References operator==().
virtual bool tuttle::host::ofx::attribute::OfxhClip::operator== (const This & other) const [inline, virtual]
Reimplemented from tuttle::host::ofx::attribute::OfxhAttribute.
Reimplemented in tuttle::host::ofx::attribute::OfxhClipImage.
Definition at line 42 of file OfxhClip.hpp.
Referenced by operator!=().
void tuttle::host::ofx::attribute::OfxhClip::reset (const std::string & name) [inline, virtual]
override this to handle a reset().
Reimplemented from tuttle::host::ofx::property::OfxhGetHook.
Definition at line 65 of file OfxhClip.hpp.
References TUTTLE_LOG_ERROR, and TUTTLE_LOG_INFOS.
template<class Archive > void tuttle::host::ofx::attribute::OfxhClip::serialize (Archive & ar, const unsigned int version) [inline, private]
Reimplemented from tuttle::host::ofx::attribute::OfxhAttribute.
Definition at line 76 of file OfxhClip.hpp.
Friends And Related Function Documentation
friend class boost::serialization::access [friend]
Reimplemented from tuttle::host::ofx::attribute::OfxhAttribute.
Definition at line 74 of file OfxhClip.hpp.
The documentation for this class was generated from the following files:
TuttleOFX/libraries/tuttle/src/tuttle/host/ofx/attribute/OfxhClip.hpp
TuttleOFX/libraries/tuttle/src/tuttle/host/ofx/attribute/OfxhClip.cpp