TuttleOFX: tuttle::host::NodeHashContainer Class Reference
tuttle::host::NodeHashContainer Class Reference
#include <NodeHashContainer.hpp>
Public Member Functions
NodeHashContainer ()
std::size_t getFirst () const
std::size_t getHash (const NodeAtTimeKey &k) const
std::size_t getHash (const std::string &name, const OfxTime &time) const
void addHash (const std::string &name, const OfxTime &time, const std::size_t hash)
void addHash (const NodeAtTimeKey &k, const std::size_t hash)
Private Types
typedef std::map
< NodeAtTimeKey, std::size_t > Map
Private Attributes
Map _hashes
Friends
std::ostream & operator<< (std::ostream &os, const NodeHashContainer &c)
Detailed Description
Definition at line 17 of file NodeHashContainer.hpp.
Member Typedef Documentation
typedef std::map<NodeAtTimeKey, std::size_t> tuttle::host::NodeHashContainer::Map [private]
Definition at line 55 of file NodeHashContainer.hpp.
Constructor & Destructor Documentation
tuttle::host::NodeHashContainer::NodeHashContainer () [inline]
Definition at line 20 of file NodeHashContainer.hpp.
Member Function Documentation
void tuttle::host::NodeHashContainer::addHash (const std::string & name, const OfxTime & time, const std::size_t hash) [inline]
Definition at line 41 of file NodeHashContainer.hpp.
Referenced by tuttle::host::graph::visitor::ComputeHashAtTime< TGraph >::finish_vertex().
void tuttle::host::NodeHashContainer::addHash (const NodeAtTimeKey & k, const std::size_t hash) [inline]
Definition at line 46 of file NodeHashContainer.hpp.
References _hashes.
std::size_t tuttle::host::NodeHashContainer::getFirst () const [inline]
Definition at line 23 of file NodeHashContainer.hpp.
References _hashes.
std::size_t tuttle::host::NodeHashContainer::getHash (const NodeAtTimeKey & k) const [inline]
Definition at line 27 of file NodeHashContainer.hpp.
References _hashes.
Referenced by tuttle::host::graph::visitor::ComputeHashAtTime< TGraph >::finish_vertex(), and getHash().
std::size_t tuttle::host::NodeHashContainer::getHash (const std::string & name, const OfxTime & time) const [inline]
Definition at line 36 of file NodeHashContainer.hpp.
References getHash().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const NodeHashContainer & c) [friend]
Definition at line 8 of file NodeHashContainer.cpp.
Field Documentation
Map tuttle::host::NodeHashContainer::_hashes [private]
Definition at line 56 of file NodeHashContainer.hpp.
Referenced by addHash(), getFirst(), getHash(), and tuttle::host::operator<<().
The documentation for this class was generated from the following file:
TuttleOFX/libraries/tuttle/src/tuttle/host/NodeHashContainer.hpp