TuttleOFX: tuttle::host::ofx::attribute::OfxhAttributeAccessor Class Reference
tuttle::host::ofx::attribute::OfxhAttributeAccessor Class Reference
#include <OfxhAttributeAccessor.hpp>
Public Member Functions
OfxhAttributeAccessor ()
virtual ~OfxhAttributeAccessor ()=0
virtual const property::OfxhSet & getProperties () const =0
virtual property::OfxhSet & getEditableProperties ()=0
bool isOutput () const
is the clip an output clip
void setAllNames (const std::string &name)
const std::string & getAttributeType () const
const std::string & getName () const
void setName (const std::string &name)
const std::string & getShortLabel () const
void setShortLabel (const std::string &label)
const std::string & getLabel () const
void setLabel (const std::string &label)
const std::string & getLongLabel () const
void setLongLabel (const std::string &label)
OfxPropertySetHandle getPropHandle () const
Protected Member Functions
virtual void setProperties (const property::OfxhSet &properties)=0
Detailed Description
Definition at line 16 of file OfxhAttributeAccessor.hpp.
Constructor & Destructor Documentation
tuttle::host::ofx::attribute::OfxhAttributeAccessor::OfxhAttributeAccessor ()
Definition at line 8 of file OfxhAttributeAccessor.cpp.
tuttle::host::ofx::attribute::OfxhAttributeAccessor::~OfxhAttributeAccessor () [pure virtual]
Definition at line 11 of file OfxhAttributeAccessor.cpp.
Member Function Documentation
const std::string& tuttle::host::ofx::attribute::OfxhAttributeAccessor::getAttributeType () const [inline]
Definition at line 46 of file OfxhAttributeAccessor.hpp.
References getProperties(), and tuttle::host::ofx::property::OfxhSet::getStringProperty().
Referenced by tuttle::host::ofx::attribute::OfxhAttribute::OfxhAttribute(), tuttle::host::ofx::attribute::OfxhAttributeDescriptor::setProperties(), and tuttle::host::ofx::attribute::OfxhAttribute::setProperties().
virtual property::OfxhSet& tuttle::host::ofx::attribute::OfxhAttributeAccessor::getEditableProperties () [pure virtual]
Implemented in tuttle::host::ofx::attribute::OfxhAttribute, and tuttle::host::ofx::attribute::OfxhAttributeDescriptor.
Referenced by tuttle::host::ofx::attribute::OfxhClipAccessor::setConnected(), setLabel(), setLongLabel(), setName(), and setShortLabel().
const std::string& tuttle::host::ofx::attribute::OfxhAttributeAccessor::getLabel () const [inline]
name of the clip
Definition at line 81 of file OfxhAttributeAccessor.hpp.
References getName(), getProperties(), and tuttle::host::ofx::property::OfxhSet::getStringProperty().
Referenced by getLongLabel(), and getShortLabel().
const std::string& tuttle::host::ofx::attribute::OfxhAttributeAccessor::getLongLabel () const [inline]
name of the clip
Definition at line 99 of file OfxhAttributeAccessor.hpp.
References getLabel(), getProperties(), and tuttle::host::ofx::property::OfxhSet::getStringProperty().
const std::string& tuttle::host::ofx::attribute::OfxhAttributeAccessor::getName () const [inline]
Reimplemented in tuttle::host::attribute::ClipImage, and tuttle::host::attribute::Param.
Definition at line 51 of file OfxhAttributeAccessor.hpp.
References getProperties(), and tuttle::host::ofx::property::OfxhSet::getStringProperty().
Referenced by tuttle::host::ofx::imageEffect::OfxhImageEffectNode::calcDefaultRegionOfDefinition(), tuttle::host::ofx::attribute::OfxhClipImageSet::copyClipsValues(), tuttle::host::ofx::attribute::OfxhParamSet::copyParamsValues(), tuttle::host::ofx::attribute::OfxhParamSet::declareChildParam(), tuttle::host::ofx::attribute::OfxhParamChoice::getIndexFor(), getLabel(), tuttle::host::ofx::attribute::OfxhParamSet::initMapFromList(), isOutput(), tuttle::host::ofx::imageEffect::OfxhImageEffectNode::paramChanged(), tuttle::host::ofx::imageEffect::OfxhImageEffectNode::populateParams(), and tuttle::host::ofx::attribute::OfxhParam::setValueFromExpression().
virtual const property::OfxhSet& tuttle::host::ofx::attribute::OfxhAttributeAccessor::getProperties () const [pure virtual]
Implemented in tuttle::host::ofx::attribute::OfxhAttribute, and tuttle::host::ofx::attribute::OfxhAttributeDescriptor.
Referenced by getAttributeType(), tuttle::host::ofx::attribute::OfxhParamAccessor::getCacheInvalidation(), tuttle::host::ofx::attribute::OfxhParamAccessor::getCanAnimate(), tuttle::host::ofx::attribute::OfxhParamAccessor::getCanUndo(), tuttle::host::attribute::ParamInteger::getDefault(), tuttle::host::attribute::ParamCustom::getDefault(), tuttle::host::ofx::attribute::OfxhParamAccessor::getDoubleType(), tuttle::host::ofx::attribute::OfxhParamAccessor::getEnabled(), tuttle::host::ofx::attribute::OfxhParamAccessor::getEvaluateOnChange(), tuttle::host::ofx::attribute::OfxhClipImageAccessor::getFieldExtraction(), tuttle::host::ofx::attribute::OfxhParamAccessor::getHint(), getLabel(), getLongLabel(), getName(), tuttle::host::ofx::attribute::OfxhParamAccessor::getParamType(), tuttle::host::ofx::attribute::OfxhParamAccessor::getParentName(), getPropHandle(), tuttle::host::ofx::attribute::OfxhParamAccessor::getScriptName(), tuttle::host::ofx::attribute::OfxhParamAccessor::getSecret(), getShortLabel(), tuttle::host::ofx::attribute::OfxhClipImageAccessor::getSupportedComponents(), tuttle::host::ofx::attribute::OfxhClipAccessor::isConnected(), tuttle::host::ofx::attribute::OfxhClipImageAccessor::isMask(), tuttle::host::ofx::attribute::OfxhClipAccessor::isOptional(), tuttle::host::ofx::attribute::OfxhClipImageAccessor::isSupportedComponent(), tuttle::host::ofx::attribute::OfxhClipImageAccessor::supportsTiles(), and tuttle::host::ofx::attribute::OfxhClipImageAccessor::temporalAccess().
OfxPropertySetHandle tuttle::host::ofx::attribute::OfxhAttributeAccessor::getPropHandle () const [inline]
get a handle on the properties of the clip descriptor for the C api
Definition at line 117 of file OfxhAttributeAccessor.hpp.
References tuttle::host::ofx::property::OfxhSet::getHandle(), and getProperties().
const std::string& tuttle::host::ofx::attribute::OfxhAttributeAccessor::getShortLabel () const [inline]
name of the clip
Definition at line 63 of file OfxhAttributeAccessor.hpp.
References getLabel(), getProperties(), and tuttle::host::ofx::property::OfxhSet::getStringProperty().
bool tuttle::host::ofx::attribute::OfxhAttributeAccessor::isOutput () const [inline]
is the clip an output clip
Reimplemented in tuttle::host::attribute::Param.
Definition at line 33 of file OfxhAttributeAccessor.hpp.
References getName().
Referenced by tuttle::host::ofx::imageEffect::OfxhImageEffectNode::calcDefaultRegionOfDefinition(), tuttle::host::ImageEffectNode::checkClipsConnected(), tuttle::host::ImageEffectNode::computeTimeDomain(), tuttle::host::ImageEffectNode::coutBitDepthConnections(), tuttle::host::ImageEffectNode::debugOutputImage(), tuttle::host::attribute::ClipImage::fetchRegionOfDefinition(), tuttle::host::attribute::ClipImage::getClipIdentifier(), tuttle::host::attribute::ClipImage::getConnectedClipFullName(), tuttle::host::ImageEffectNode::getDefaultTimeDomain(), tuttle::host::ofx::imageEffect::OfxhImageEffectNode::getFramesNeededAction(), tuttle::host::attribute::ClipImage::getRemappedTime(), tuttle::host::ImageEffectNode::initComponents(), tuttle::host::ImageEffectNode::initInputClipsFps(), tuttle::host::ImageEffectNode::initInputClipsPixelAspectRatio(), tuttle::host::ofx::imageEffect::OfxhImageEffectNode::isLeafNode(), tuttle::host::ImageEffectNode::maximizeBitDepthFromReadsToWrites(), tuttle::host::ImageEffectNode::maximizeBitDepthFromWritesToReads(), tuttle::host::ImageEffectNode::process(), tuttle::host::attribute::ClipImage::setConnectedClip(), tuttle::host::ofx::imageEffect::OfxhImageEffectNode::setDefaultClipPreferences(), and tuttle::host::ImageEffectNode::validInputClipsConnections().
void tuttle::host::ofx::attribute::OfxhAttributeAccessor::setAllNames (const std::string & name) [inline]
Definition at line 38 of file OfxhAttributeAccessor.hpp.
References setLabel(), setLongLabel(), setName(), and setShortLabel().
Referenced by tuttle::host::ofx::attribute::OfxhParamDescriptor::OfxhParamDescriptor().
void tuttle::host::ofx::attribute::OfxhAttributeAccessor::setLabel (const std::string & label) [inline]
Definition at line 92 of file OfxhAttributeAccessor.hpp.
References getEditableProperties(), and tuttle::host::ofx::property::OfxhSet::setStringProperty().
Referenced by setAllNames().
void tuttle::host::ofx::attribute::OfxhAttributeAccessor::setLongLabel (const std::string & label) [inline]
Definition at line 110 of file OfxhAttributeAccessor.hpp.
References getEditableProperties(), and tuttle::host::ofx::property::OfxhSet::setStringProperty().
Referenced by setAllNames().
void tuttle::host::ofx::attribute::OfxhAttributeAccessor::setName (const std::string & name) [inline]
Definition at line 56 of file OfxhAttributeAccessor.hpp.
References getEditableProperties(), and tuttle::host::ofx::property::OfxhSet::setStringProperty().
Referenced by setAllNames().
virtual void tuttle::host::ofx::attribute::OfxhAttributeAccessor::setProperties (const property::OfxhSet & properties) [protected, pure virtual]
Implemented in tuttle::host::ofx::attribute::OfxhAttribute, and tuttle::host::ofx::attribute::OfxhAttributeDescriptor.
void tuttle::host::ofx::attribute::OfxhAttributeAccessor::setShortLabel (const std::string & label) [inline]
Definition at line 74 of file OfxhAttributeAccessor.hpp.
References getEditableProperties(), and tuttle::host::ofx::property::OfxhSet::setStringProperty().
Referenced by setAllNames().
The documentation for this class was generated from the following files:
TuttleOFX/libraries/tuttle/src/tuttle/host/ofx/attribute/OfxhAttributeAccessor.hpp
TuttleOFX/libraries/tuttle/src/tuttle/host/ofx/attribute/OfxhAttributeAccessor.cpp