TuttleOFX: tuttle::host::NodeInit Class Reference
tuttle::host::NodeInit Class Reference
Node initializer class.
#include <Node.hpp>
Public Member Functions
NodeInit ()
NodeInit (const std::string &pluginName)
NodeInit (INode &node)
NodeInit (const NodeInit &other)
Non-standard copy contructor that steals the data.
NodeInit & operator= (const NodeInit &other)
INode & operator-> ()
const INode & operator-> () const
NodeInit & setParam (const std::string &paramName,...)
Set parameter values. If it's a multi-dimensional parameter, you should put all dimensions values. setParam("redColor", 1.0, 0.0, 0.0, 1.0)
NodeInit & setParamExp (const std::string &paramName, const std::string &paramValue)
Set parameter value from a string expression.
const INode & get () const
INode & get ()
void setNode (INode &node)
INode & release () const
void setBeforeRenderCallback (Callback *cb)
Private Attributes
std::auto_ptr< INode > _node
Detailed Description
Node initializer class.
Definition at line 37 of file Node.hpp.
Constructor & Destructor Documentation
tuttle::host::NodeInit::NodeInit () [inline]
Definition at line 40 of file Node.hpp.
tuttle::host::NodeInit::NodeInit (const std::string & pluginName)
Definition at line 87 of file Node.cpp.
References tuttle::host::createNode(), and setNode().
tuttle::host::NodeInit::NodeInit (INode & node)
Definition at line 92 of file Node.cpp.
References setNode().
tuttle::host::NodeInit::NodeInit (const NodeInit & other) [inline]
Non-standard copy contructor that steals the data.
Definition at line 46 of file Node.hpp.
References release(), and setNode().
Member Function Documentation
const INode& tuttle::host::NodeInit::get () const [inline]
Definition at line 72 of file Node.hpp.
References _node.
INode& tuttle::host::NodeInit::get () [inline]
Definition at line 73 of file Node.hpp.
References _node.
INode& tuttle::host::NodeInit::operator-> () [inline]
Definition at line 57 of file Node.hpp.
References _node.
const INode& tuttle::host::NodeInit::operator-> () const [inline]
Definition at line 58 of file Node.hpp.
References _node.
NodeInit& tuttle::host::NodeInit::operator= (const NodeInit & other) [inline]
Definition at line 51 of file Node.hpp.
References release(), and setNode().
INode& tuttle::host::NodeInit::release () const [inline]
Definition at line 76 of file Node.hpp.
References _node.
Referenced by tuttle::host::Graph::addNode(), NodeInit(), and operator=().
void tuttle::host::NodeInit::setBeforeRenderCallback (Callback * cb)
Definition at line 115 of file Node.cpp.
References _node.
void tuttle::host::NodeInit::setNode (INode & node) [inline]
Definition at line 75 of file Node.hpp.
References _node.
Referenced by NodeInit(), and operator=().
NodeInit & tuttle::host::NodeInit::setParam (const std::string & paramName, ...)
Set parameter values. If it's a multi-dimensional parameter, you should put all dimensions values. setParam("redColor", 1.0, 0.0, 0.0, 1.0)
Definition at line 97 of file Node.cpp.
References _node, and tuttle::host::ofx::attribute::eChangeUserEdited.
Referenced by tuttle::host::loadAndGenerateThumbnail().
NodeInit & tuttle::host::NodeInit::setParamExp (const std::string & paramName, const std::string & paramValue)
Set parameter value from a string expression.
Definition at line 108 of file Node.cpp.
References _node, and tuttle::host::ofx::attribute::eChangeUserEdited.
Field Documentation
std::auto_ptr<INode> tuttle::host::NodeInit::_node [mutable, private]
Definition at line 81 of file Node.hpp.
Referenced by get(), operator->(), release(), setBeforeRenderCallback(), setNode(), setParam(), and setParamExp().
The documentation for this class was generated from the following files:
TuttleOFX/libraries/tuttle/src/tuttle/host/Node.hpp
TuttleOFX/libraries/tuttle/src/tuttle/host/Node.cpp