TuttleOFX: TuttleOFX/libraries/tuttle/tests/asynchronous/asynchronous.cpp File Reference
TuttleOFX/libraries/tuttle/tests/asynchronous/asynchronous.cpp File Reference
#include <tuttle/test/unit_test.hpp>
#include <tuttle/host/ThreadEnv.hpp>
#include <tuttle/host/Graph.hpp>
#include <iostream>
Functions
BOOST_AUTO_TEST_CASE (computeAsynchronous)
Function Documentation
BOOST_AUTO_TEST_CASE (computeAsynchronous)
Definition at line 13 of file asynchronous.cpp.
References tuttle::host::ThreadEnv::abort(), tuttle::host::ThreadEnv::compute(), tuttle::host::Graph::connect(), tuttle::host::Graph::createNode(), tuttle::host::ThreadEnv::getComputeOptions(), tuttle::host::INode::getName(), tuttle::host::INode::getParam(), tuttle::host::ThreadEnv::getResult(), tuttle::host::ThreadEnv::join(), tuttle::host::ComputeOptions::setTimeRange(), tuttle::host::ofx::attribute::OfxhParam::setValue(), TUTTLE_LOG_INFO, TUTTLE_TLOG, and TUTTLE_TRACE.