TuttleOFX: tuttle::plugin::ReaderPlugin Class Reference
tuttle::plugin::ReaderPlugin Class Reference
#include <ReaderPlugin.hpp>
Public Member Functions
ReaderPlugin (OfxImageEffectHandle handle)
virtual ~ReaderPlugin ()=0
virtual void changedParam (const OFX::InstanceChangedArgs &args, const std::string &paramName)
virtual bool getRegionOfDefinition (const OFX::RegionOfDefinitionArguments &args, OfxRectD &rod)=0
virtual void getClipPreferences (OFX::ClipPreferencesSetter &clipPreferences)
virtual bool getTimeDomain (OfxRangeD &range)
virtual void render (const OFX::RenderArguments &args)
std::string getAbsoluteFilenameAt (const OfxTime time) const
std::string getAbsoluteFirstFilename () const
OfxTime getFirstTime () const
OfxTime getLastTime () const
EParamReaderBitDepth getExplicitBitDepthConversion () const
EParamReaderChannel getExplicitChannelConversion () const
OFX::EBitDepth getOfxExplicitConversion () const
Data Fields
OFX::Clip * _clipDst
user parameters
OFX::StringParam * _paramFilepath
File path.
OFX::ChoiceParam * _paramBitDepth
Explicit bit depth conversion.
OFX::ChoiceParam * _paramChannel
Protected Member Functions
virtual bool varyOnTime () const
Private Attributes
bool _isSequence
sequenceParser::Sequence _filePattern
Filename pattern manager.
Detailed Description
Definition at line 16 of file ReaderPlugin.hpp.
Constructor & Destructor Documentation
tuttle::plugin::ReaderPlugin::ReaderPlugin (OfxImageEffectHandle handle)
Definition at line 8 of file ReaderPlugin.cpp.
References _clipDst, _filePattern, _isSequence, _paramBitDepth, _paramChannel, _paramFilepath, tuttle::plugin::kTuttlePluginBitDepth, tuttle::plugin::kTuttlePluginChannel, and tuttle::plugin::kTuttlePluginFilename.
tuttle::plugin::ReaderPlugin::~ReaderPlugin () [pure virtual]
Definition at line 18 of file ReaderPlugin.cpp.
Member Function Documentation
void tuttle::plugin::ReaderPlugin::changedParam (const OFX::InstanceChangedArgs & args, const std::string & paramName) [virtual]
Definition at line 21 of file ReaderPlugin.cpp.
References _filePattern, _isSequence, _paramFilepath, and tuttle::plugin::kTuttlePluginFilename.
std::string tuttle::plugin::ReaderPlugin::getAbsoluteFilenameAt (const OfxTime time) const [inline]
Definition at line 31 of file ReaderPlugin.hpp.
References _filePattern, _isSequence, and _paramFilepath.
Referenced by render().
std::string tuttle::plugin::ReaderPlugin::getAbsoluteFirstFilename () const [inline]
Definition at line 46 of file ReaderPlugin.hpp.
References _filePattern, _isSequence, and _paramFilepath.
void tuttle::plugin::ReaderPlugin::getClipPreferences (OFX::ClipPreferencesSetter & clipPreferences) [virtual]
Definition at line 29 of file ReaderPlugin.cpp.
References _clipDst, tuttle::ofx::imageEffect::eBitDepthFloat, tuttle::ofx::imageEffect::eBitDepthUByte, tuttle::ofx::imageEffect::eBitDepthUShort, tuttle::plugin::eParamReaderBitDepthAuto, tuttle::plugin::eParamReaderBitDepthByte, tuttle::plugin::eParamReaderBitDepthFloat, tuttle::plugin::eParamReaderBitDepthShort, tuttle::plugin::eParamReaderChannelAuto, tuttle::plugin::eParamReaderChannelGray, tuttle::plugin::eParamReaderChannelRGB, tuttle::plugin::eParamReaderChannelRGBA, tuttle::ofx::imageEffect::ePixelComponentAlpha, tuttle::ofx::imageEffect::ePixelComponentRGB, tuttle::ofx::imageEffect::ePixelComponentRGBA, getExplicitBitDepthConversion(), getExplicitChannelConversion(), and varyOnTime().
EParamReaderBitDepth tuttle::plugin::ReaderPlugin::getExplicitBitDepthConversion () const [inline]
Definition at line 70 of file ReaderPlugin.hpp.
References _paramBitDepth.
Referenced by getClipPreferences(), and getOfxExplicitConversion().
EParamReaderChannel tuttle::plugin::ReaderPlugin::getExplicitChannelConversion () const [inline]
Definition at line 76 of file ReaderPlugin.hpp.
References _paramChannel.
Referenced by getClipPreferences().
OfxTime tuttle::plugin::ReaderPlugin::getFirstTime () const [inline]
Definition at line 54 of file ReaderPlugin.hpp.
References _filePattern, and _isSequence.
Referenced by getTimeDomain().
OfxTime tuttle::plugin::ReaderPlugin::getLastTime () const [inline]
Definition at line 62 of file ReaderPlugin.hpp.
References _filePattern, and _isSequence.
Referenced by getTimeDomain().
OFX::EBitDepth tuttle::plugin::ReaderPlugin::getOfxExplicitConversion () const [inline]
Definition at line 81 of file ReaderPlugin.hpp.
References tuttle::ofx::imageEffect::eBitDepthFloat, tuttle::ofx::imageEffect::eBitDepthNone, tuttle::ofx::imageEffect::eBitDepthUByte, tuttle::ofx::imageEffect::eBitDepthUShort, tuttle::plugin::eParamReaderBitDepthAuto, tuttle::plugin::eParamReaderBitDepthByte, tuttle::plugin::eParamReaderBitDepthFloat, tuttle::plugin::eParamReaderBitDepthShort, and getExplicitBitDepthConversion().
virtual bool tuttle::plugin::ReaderPlugin::getRegionOfDefinition (const OFX::RegionOfDefinitionArguments & args, OfxRectD & rod) [pure virtual]
bool tuttle::plugin::ReaderPlugin::getTimeDomain (OfxRangeD & range) [virtual]
Definition at line 79 of file ReaderPlugin.cpp.
References getFirstTime(), getLastTime(), TUTTLE_INFO, and TUTTLE_TLOG.
void tuttle::plugin::ReaderPlugin::render (const OFX::RenderArguments & args) [virtual]
Definition at line 87 of file ReaderPlugin.cpp.
References getAbsoluteFilenameAt(), and TUTTLE_LOG_INFO.
virtual bool tuttle::plugin::ReaderPlugin::varyOnTime () const [inline, protected, virtual]
Definition at line 98 of file ReaderPlugin.hpp.
References _isSequence.
Referenced by getClipPreferences().
Field Documentation
OFX::Clip* tuttle::plugin::ReaderPlugin::_clipDst
Destination image clip
Definition at line 101 of file ReaderPlugin.hpp.
Referenced by getClipPreferences(), and ReaderPlugin().
sequenceParser::Sequence tuttle::plugin::ReaderPlugin::_filePattern [private]
Filename pattern manager.
Definition at line 111 of file ReaderPlugin.hpp.
Referenced by changedParam(), getAbsoluteFilenameAt(), getAbsoluteFirstFilename(), getFirstTime(), getLastTime(), and ReaderPlugin().
bool tuttle::plugin::ReaderPlugin::_isSequence [private]
Definition at line 110 of file ReaderPlugin.hpp.
Referenced by changedParam(), getAbsoluteFilenameAt(), getAbsoluteFirstFilename(), getFirstTime(), getLastTime(), ReaderPlugin(), and varyOnTime().
OFX::ChoiceParam* tuttle::plugin::ReaderPlugin::_paramBitDepth
Explicit bit depth conversion.
Definition at line 105 of file ReaderPlugin.hpp.
Referenced by getExplicitBitDepthConversion(), and ReaderPlugin().
OFX::ChoiceParam* tuttle::plugin::ReaderPlugin::_paramChannel
Explicit component conversion
Definition at line 106 of file ReaderPlugin.hpp.
Referenced by getExplicitChannelConversion(), and ReaderPlugin().
OFX::StringParam* tuttle::plugin::ReaderPlugin::_paramFilepath
File path.
Definition at line 104 of file ReaderPlugin.hpp.
Referenced by changedParam(), getAbsoluteFilenameAt(), getAbsoluteFirstFilename(), and ReaderPlugin().
The documentation for this class was generated from the following files:
TuttleOFX/libraries/tuttle/src/tuttle/plugin/context/ReaderPlugin.hpp
TuttleOFX/libraries/tuttle/src/tuttle/plugin/context/ReaderPlugin.cpp