TuttleOFX: tuttle::host::ofx::attribute::OfxhParamSetDescriptor Class Reference
tuttle::host::ofx::attribute::OfxhParamSetDescriptor Class Reference
a set of parameters
#include <OfxhParamSetDescriptor.hpp>
Public Types
typedef OfxhParamSetDescriptor This
typedef std::map< std::string,
OfxhParamDescriptor * > ParamDescriptorMap
typedef boost::ptr_list
< OfxhParamDescriptor > ParamDescriptorList
Public Member Functions
OfxhParamSetDescriptor ()
default ctor
virtual ~OfxhParamSetDescriptor ()
dtor
bool operator== (const This &other) const
bool operator!= (const This &other) const
OfxParamSetHandle getParamSetHandle () const
obtain a handle on this set for passing to the C api
const ParamDescriptorMap & getParams () const
get the map of params
ParamDescriptorMap & getParams ()
const ParamDescriptorList & getParamList () const
get the list of params
virtual OfxhParamDescriptor * paramDefine (const char *paramType, const char *name)
define a param
Data Fields
ParamDescriptorMap _paramMap
ParamDescriptorList _paramList
Private Member Functions
OfxhParamSetDescriptor (const This &)
CC doesn't exist.
virtual void addParam (const std::string &name, OfxhParamDescriptor *p)
add a param in
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Friends
class boost::serialization::access
Detailed Description
a set of parameters
Definition at line 16 of file OfxhParamSetDescriptor.hpp.
Member Typedef Documentation
typedef boost::ptr_list<OfxhParamDescriptor> tuttle::host::ofx::attribute::OfxhParamSetDescriptor::ParamDescriptorList
Definition at line 21 of file OfxhParamSetDescriptor.hpp.
typedef std::map<std::string, OfxhParamDescriptor*> tuttle::host::ofx::attribute::OfxhParamSetDescriptor::ParamDescriptorMap
Definition at line 20 of file OfxhParamSetDescriptor.hpp.
typedef OfxhParamSetDescriptor tuttle::host::ofx::attribute::OfxhParamSetDescriptor::This
Reimplemented in tuttle::host::ofx::imageEffect::OfxhImageEffectNodeDescriptor.
Definition at line 19 of file OfxhParamSetDescriptor.hpp.
Constructor & Destructor Documentation
tuttle::host::ofx::attribute::OfxhParamSetDescriptor::OfxhParamSetDescriptor (const This &) [private]
CC doesn't exist.
tuttle::host::ofx::attribute::OfxhParamSetDescriptor::OfxhParamSetDescriptor ()
default ctor
obtain a handle on this set for passing to the C api
Definition at line 11 of file OfxhParamSetDescriptor.cpp.
Referenced by tuttle::host::ofx::imageEffect::OfxhImageEffectNodeDescriptor::serialize().
tuttle::host::ofx::attribute::OfxhParamSetDescriptor::~OfxhParamSetDescriptor () [virtual]
dtor
Definition at line 13 of file OfxhParamSetDescriptor.cpp.
Member Function Documentation
void tuttle::host::ofx::attribute::OfxhParamSetDescriptor::addParam (const std::string & name, OfxhParamDescriptor * p) [private, virtual]
add a param in
Definition at line 16 of file OfxhParamSetDescriptor.cpp.
References _paramList, and _paramMap.
Referenced by paramDefine().
const ParamDescriptorList& tuttle::host::ofx::attribute::OfxhParamSetDescriptor::getParamList () const [inline]
get the list of params
Definition at line 53 of file OfxhParamSetDescriptor.hpp.
References _paramList.
Referenced by tuttle::host::ofx::imageEffect::OfxhImageEffectNode::populateParams().
const ParamDescriptorMap& tuttle::host::ofx::attribute::OfxhParamSetDescriptor::getParams () const [inline]
get the map of params
Definition at line 49 of file OfxhParamSetDescriptor.hpp.
References _paramMap.
ParamDescriptorMap& tuttle::host::ofx::attribute::OfxhParamSetDescriptor::getParams () [inline]
Definition at line 50 of file OfxhParamSetDescriptor.hpp.
References _paramMap.
OfxParamSetHandle tuttle::host::ofx::attribute::OfxhParamSetDescriptor::getParamSetHandle () const [inline, virtual]
obtain a handle on this set for passing to the C api
Implements tuttle::host::ofx::attribute::OfxhParamSetAccessor.
Definition at line 46 of file OfxhParamSetDescriptor.hpp.
bool tuttle::host::ofx::attribute::OfxhParamSetDescriptor::operator!= (const This & other) const [inline]
Reimplemented in tuttle::host::ofx::imageEffect::OfxhImageEffectNodeDescriptor.
Definition at line 43 of file OfxhParamSetDescriptor.hpp.
References operator==().
bool tuttle::host::ofx::attribute::OfxhParamSetDescriptor::operator== (const This & other) const [inline]
Reimplemented in tuttle::host::ofx::imageEffect::OfxhImageEffectNodeDescriptor.
Definition at line 36 of file OfxhParamSetDescriptor.hpp.
References _paramList.
Referenced by operator!=().
OfxhParamDescriptor * tuttle::host::ofx::attribute::OfxhParamSetDescriptor::paramDefine (const char * paramType, const char * name) [virtual]
define a param
define a param on this effect
Definition at line 25 of file OfxhParamSetDescriptor.cpp.
References addParam(), tuttle::host::ofx::attribute::OfxhParamDescriptor::initStandardParamProps(), and tuttle::host::ofx::attribute::isStandardType().
template<class Archive > void tuttle::host::ofx::attribute::OfxhParamSetDescriptor::serialize (Archive & ar, const unsigned int version) [inline, private]
Reimplemented in tuttle::host::ofx::imageEffect::OfxhImageEffectNodeDescriptor.
Definition at line 66 of file OfxhParamSetDescriptor.hpp.
References _paramList.
Friends And Related Function Documentation
friend class boost::serialization::access [friend]
Reimplemented in tuttle::host::ofx::imageEffect::OfxhImageEffectNodeDescriptor.
Definition at line 64 of file OfxhParamSetDescriptor.hpp.
Field Documentation
ParamDescriptorList tuttle::host::ofx::attribute::OfxhParamSetDescriptor::_paramList
Definition at line 23 of file OfxhParamSetDescriptor.hpp.
Referenced by addParam(), getParamList(), operator==(), and serialize().
ParamDescriptorMap tuttle::host::ofx::attribute::OfxhParamSetDescriptor::_paramMap
Definition at line 22 of file OfxhParamSetDescriptor.hpp.
Referenced by addParam(), and getParams().
The documentation for this class was generated from the following files:
TuttleOFX/libraries/tuttle/src/tuttle/host/ofx/attribute/OfxhParamSetDescriptor.hpp
TuttleOFX/libraries/tuttle/src/tuttle/host/ofx/attribute/OfxhParamSetDescriptor.cpp