TuttleOFX: tuttle::host::ofx::attribute::OfxhAttributeDescriptor Class Reference
tuttle::host::ofx::attribute::OfxhAttributeDescriptor Class Reference
#include <OfxhAttributeDescriptor.hpp>
Public Types
typedef OfxhAttributeDescriptor This
Public Member Functions
OfxhAttributeDescriptor ()
OfxhAttributeDescriptor (const property::OfxhSet &properties)
virtual ~OfxhAttributeDescriptor ()=0
bool operator== (const This &other) const
bool operator!= (const This &other) const
const property::OfxhSet & getProperties () const
property::OfxhSet & getEditableProperties ()
Protected Member Functions
void setProperties (const property::OfxhSet &properties)
Protected Attributes
property::OfxhSet _properties
Private Member Functions
OfxhAttributeDescriptor (const OfxhAttributeDescriptor &other)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Friends
class boost::serialization::access
Detailed Description
Definition at line 12 of file OfxhAttributeDescriptor.hpp.
Member Typedef Documentation
typedef OfxhAttributeDescriptor tuttle::host::ofx::attribute::OfxhAttributeDescriptor::This
Reimplemented in tuttle::host::ofx::attribute::OfxhParamDescriptor, tuttle::host::ofx::attribute::OfxhClipDescriptor, and tuttle::host::ofx::attribute::OfxhClipImageDescriptor.
Definition at line 16 of file OfxhAttributeDescriptor.hpp.
Constructor & Destructor Documentation
tuttle::host::ofx::attribute::OfxhAttributeDescriptor::OfxhAttributeDescriptor (const OfxhAttributeDescriptor & other) [private]
tuttle::host::ofx::attribute::OfxhAttributeDescriptor::OfxhAttributeDescriptor ()
Definition at line 18 of file OfxhAttributeDescriptor.cpp.
References tuttle::host::ofx::property::OfxhSet::addProperties(), tuttle::host::ofx::attribute::attributeDescriptorStuffs, and getEditableProperties().
tuttle::host::ofx::attribute::OfxhAttributeDescriptor::OfxhAttributeDescriptor (const property::OfxhSet & properties)
Definition at line 24 of file OfxhAttributeDescriptor.cpp.
References tuttle::host::ofx::property::OfxhSet::addProperties(), tuttle::host::ofx::attribute::attributeDescriptorStuffs, and getEditableProperties().
tuttle::host::ofx::attribute::OfxhAttributeDescriptor::~OfxhAttributeDescriptor () [pure virtual]
Definition at line 30 of file OfxhAttributeDescriptor.cpp.
Member Function Documentation
property::OfxhSet& tuttle::host::ofx::attribute::OfxhAttributeDescriptor::getEditableProperties () [inline, virtual]
Implements tuttle::host::ofx::attribute::OfxhAttributeAccessor.
Definition at line 51 of file OfxhAttributeDescriptor.hpp.
References _properties.
Referenced by tuttle::host::ofx::attribute::OfxhParamDescriptor::initInteractParamProps(), tuttle::host::ofx::attribute::OfxhParamDescriptor::initNoValueParamProps(), tuttle::host::ofx::attribute::OfxhParamDescriptor::initNumericParamProps(), tuttle::host::ofx::attribute::OfxhParamDescriptor::initStandardParamProps(), tuttle::host::ofx::attribute::OfxhParamDescriptor::initValueParamProps(), OfxhAttributeDescriptor(), tuttle::host::ofx::attribute::OfxhClipDescriptor::OfxhClipDescriptor(), and tuttle::host::ofx::attribute::OfxhParamDescriptor::OfxhParamDescriptor().
const property::OfxhSet& tuttle::host::ofx::attribute::OfxhAttributeDescriptor::getProperties () const [inline, virtual]
Implements tuttle::host::ofx::attribute::OfxhAttributeAccessor.
Definition at line 46 of file OfxhAttributeDescriptor.hpp.
References _properties.
bool tuttle::host::ofx::attribute::OfxhAttributeDescriptor::operator!= (const This & other) const [inline]
Reimplemented in tuttle::host::ofx::attribute::OfxhParamDescriptor, tuttle::host::ofx::attribute::OfxhClipImageDescriptor, and tuttle::host::ofx::attribute::OfxhClipDescriptor.
Definition at line 44 of file OfxhAttributeDescriptor.hpp.
References operator==().
bool tuttle::host::ofx::attribute::OfxhAttributeDescriptor::operator== (const This & other) const [inline]
Reimplemented in tuttle::host::ofx::attribute::OfxhParamDescriptor, tuttle::host::ofx::attribute::OfxhClipImageDescriptor, and tuttle::host::ofx::attribute::OfxhClipDescriptor.
Definition at line 37 of file OfxhAttributeDescriptor.hpp.
References _properties.
Referenced by operator!=().
template<class Archive > void tuttle::host::ofx::attribute::OfxhAttributeDescriptor::serialize (Archive & ar, const unsigned int version) [inline, private]
Reimplemented in tuttle::host::ofx::attribute::OfxhParamDescriptor, tuttle::host::ofx::attribute::OfxhClipImageDescriptor, and tuttle::host::ofx::attribute::OfxhClipDescriptor.
Definition at line 59 of file OfxhAttributeDescriptor.hpp.
References _properties.
void tuttle::host::ofx::attribute::OfxhAttributeDescriptor::setProperties (const property::OfxhSet & properties) [inline, protected, virtual]
Implements tuttle::host::ofx::attribute::OfxhAttributeAccessor.
Definition at line 30 of file OfxhAttributeDescriptor.hpp.
References _properties, and tuttle::host::ofx::attribute::OfxhAttributeAccessor::getAttributeType().
Friends And Related Function Documentation
friend class boost::serialization::access [friend]
Reimplemented in tuttle::host::ofx::attribute::OfxhParamDescriptor, tuttle::host::ofx::attribute::OfxhClipImageDescriptor, and tuttle::host::ofx::attribute::OfxhClipDescriptor.
Definition at line 57 of file OfxhAttributeDescriptor.hpp.
Field Documentation
property::OfxhSet tuttle::host::ofx::attribute::OfxhAttributeDescriptor::_properties [protected]
Definition at line 27 of file OfxhAttributeDescriptor.hpp.
Referenced by getEditableProperties(), getProperties(), tuttle::host::ofx::attribute::OfxhClipImageDescriptor::init(), operator==(), serialize(), and setProperties().
The documentation for this class was generated from the following files:
TuttleOFX/libraries/tuttle/src/tuttle/host/ofx/attribute/OfxhAttributeDescriptor.hpp
TuttleOFX/libraries/tuttle/src/tuttle/host/ofx/attribute/OfxhAttributeDescriptor.cpp