TuttleOFX: TuttleOFX/libraries/tuttle/src/tuttle/test/io/reader.hpp File Reference
TuttleOFX/libraries/tuttle/src/tuttle/test/io/reader.hpp File Reference
#include <iostream>
#include <boost/filesystem/path.hpp>
Functions
BOOST_AUTO_TEST_CASE (process_reader)
BOOST_AUTO_TEST_CASE (process_nofile)
Function Documentation
BOOST_AUTO_TEST_CASE (process_reader)
Definition at line 9 of file reader.hpp.
References tuttle::host::Graph::compute(), tuttle::host::Graph::createNode(), tuttle::host::memory::MemoryCache::get(), tuttle::host::INode::getName(), tuttle::host::INode::getParam(), tuttle::host::ofx::attribute::OfxhParam::setValue(), TUTTLE_INFO, TUTTLE_LOG_INFO, and TUTTLE_TLOG_VAR.
BOOST_AUTO_TEST_CASE (process_nofile)
Definition at line 52 of file reader.hpp.
References tuttle::host::Graph::compute(), tuttle::host::Graph::createNode(), tuttle::host::INode::getParam(), tuttle::host::ofx::attribute::OfxhParam::setValue(), and TUTTLE_LOG_INFO.