TuttleOFX: tuttle::host::ofx::attribute::OfxhParamAccessor Class Reference
tuttle::host::ofx::attribute::OfxhParamAccessor Class Reference
base class for all params
#include <OfxhParamAccessor.hpp>
Public Member Functions
OfxhParamAccessor ()
virtual ~OfxhParamAccessor ()=0
virtual OfxParamHandle getParamHandle () const =0
grab a handle on the parameter for passing to the C API
virtual bool verifyMagic ()
const std::string & getParamType () const
std::string getParamTypeName () const
const std::string & getParentName () const
const std::string & getScriptName () const
const std::string & getHint () const
const std::string & getDoubleType () const
const std::string & getCacheInvalidation () const
bool getEnabled () const
bool getCanUndo () const
bool getSecret () const
bool getEvaluateOnChange () const
bool getCanAnimate () const
Detailed Description
base class for all params
Definition at line 16 of file OfxhParamAccessor.hpp.
Constructor & Destructor Documentation
tuttle::host::ofx::attribute::OfxhParamAccessor::OfxhParamAccessor ()
Definition at line 8 of file OfxhParamAccessor.cpp.
tuttle::host::ofx::attribute::OfxhParamAccessor::~OfxhParamAccessor () [pure virtual]
Definition at line 11 of file OfxhParamAccessor.cpp.
Member Function Documentation
const std::string & tuttle::host::ofx::attribute::OfxhParamAccessor::getCacheInvalidation () const
Definition at line 46 of file OfxhParamAccessor.cpp.
References tuttle::host::ofx::attribute::OfxhAttributeAccessor::getProperties(), and tuttle::host::ofx::property::OfxhSet::getStringProperty().
Referenced by tuttle::host::attribute::AnimatedParam< double, ofx::attribute::OfxhParamDouble >::getHashAtTime().
bool tuttle::host::ofx::attribute::OfxhParamAccessor::getCanAnimate () const
Definition at line 75 of file OfxhParamAccessor.cpp.
References tuttle::host::ofx::property::OfxhSet::getIntProperty(), and tuttle::host::ofx::attribute::OfxhAttributeAccessor::getProperties().
bool tuttle::host::ofx::attribute::OfxhParamAccessor::getCanUndo () const
Definition at line 66 of file OfxhParamAccessor.cpp.
References tuttle::host::ofx::property::OfxhSet::getIntProperty(), and tuttle::host::ofx::attribute::OfxhAttributeAccessor::getProperties().
const std::string & tuttle::host::ofx::attribute::OfxhParamAccessor::getDoubleType () const
Definition at line 41 of file OfxhParamAccessor.cpp.
References tuttle::host::ofx::attribute::OfxhAttributeAccessor::getProperties(), and tuttle::host::ofx::property::OfxhSet::getStringProperty().
bool tuttle::host::ofx::attribute::OfxhParamAccessor::getEnabled () const
Definition at line 51 of file OfxhParamAccessor.cpp.
References tuttle::host::ofx::property::OfxhSet::getIntProperty(), and tuttle::host::ofx::attribute::OfxhAttributeAccessor::getProperties().
bool tuttle::host::ofx::attribute::OfxhParamAccessor::getEvaluateOnChange () const
Definition at line 61 of file OfxhParamAccessor.cpp.
References tuttle::host::ofx::property::OfxhSet::getIntProperty(), and tuttle::host::ofx::attribute::OfxhAttributeAccessor::getProperties().
Referenced by tuttle::host::ofx::attribute::OfxhParamSet::getHashAtTime().
const std::string & tuttle::host::ofx::attribute::OfxhParamAccessor::getHint () const
Todo:
tuttle : common to all attributes
Definition at line 36 of file OfxhParamAccessor.cpp.
References tuttle::host::ofx::attribute::OfxhAttributeAccessor::getProperties(), and tuttle::host::ofx::property::OfxhSet::getStringProperty().
virtual OfxParamHandle tuttle::host::ofx::attribute::OfxhParamAccessor::getParamHandle () const [pure virtual]
grab a handle on the parameter for passing to the C API
Implemented in tuttle::host::ofx::attribute::OfxhParam, and tuttle::host::ofx::attribute::OfxhParamDescriptor.
const std::string & tuttle::host::ofx::attribute::OfxhParamAccessor::getParamType () const
Definition at line 13 of file OfxhParamAccessor.cpp.
References tuttle::host::ofx::attribute::OfxhAttributeAccessor::getProperties(), and tuttle::host::ofx::property::OfxhSet::getStringProperty().
Referenced by getParamTypeName(), and tuttle::host::ofx::attribute::OfxhParam::setValueFromExpression().
std::string tuttle::host::ofx::attribute::OfxhParamAccessor::getParamTypeName () const
Definition at line 18 of file OfxhParamAccessor.cpp.
References getParamType().
const std::string & tuttle::host::ofx::attribute::OfxhParamAccessor::getParentName () const
Definition at line 26 of file OfxhParamAccessor.cpp.
References tuttle::host::ofx::attribute::OfxhAttributeAccessor::getProperties(), and tuttle::host::ofx::property::OfxhSet::getStringProperty().
Referenced by tuttle::host::ofx::imageEffect::OfxhImageEffectNode::populateParams().
const std::string & tuttle::host::ofx::attribute::OfxhParamAccessor::getScriptName () const
Todo:
tuttle : common to all attributes
Definition at line 31 of file OfxhParamAccessor.cpp.
References tuttle::host::ofx::attribute::OfxhAttributeAccessor::getProperties(), and tuttle::host::ofx::property::OfxhSet::getStringProperty().
Referenced by tuttle::host::ofx::attribute::OfxhParamSet::initMapFromList().
bool tuttle::host::ofx::attribute::OfxhParamAccessor::getSecret () const
Definition at line 56 of file OfxhParamAccessor.cpp.
References tuttle::host::ofx::property::OfxhSet::getIntProperty(), and tuttle::host::ofx::attribute::OfxhAttributeAccessor::getProperties().
virtual bool tuttle::host::ofx::attribute::OfxhParamAccessor::verifyMagic () [inline, virtual]
Definition at line 26 of file OfxhParamAccessor.hpp.
The documentation for this class was generated from the following files:
TuttleOFX/libraries/tuttle/src/tuttle/host/ofx/attribute/OfxhParamAccessor.hpp
TuttleOFX/libraries/tuttle/src/tuttle/host/ofx/attribute/OfxhParamAccessor.cpp