TuttleOFX: tuttle::host::OutputBufferWrapper Class Reference
tuttle::host::OutputBufferWrapper Class Reference
#include <OutputBufferWrapper.hpp>
Public Types
enum EBitDepth {
eBitDepthCustom = -1, eBitDepthNone = 0, eBitDepthUByte = 1, eBitDepthUShort = 2,
eBitDepthFloat = 3
}
enum EPixelComponent {
ePixelComponentNone, ePixelComponentRGBA, ePixelComponentRGB, ePixelComponentAlpha,
ePixelComponentCustom
}
enum EField { eFieldNone, eFieldBoth, eFieldLower, eFieldUpper }
typedef void * CustomDataPtr
typedef void(* CallbackOutputImagePtr)(OfxTime time, CustomDataPtr outputCustomData, void *rawdata, int width, int height, int rowSizeBytes, EBitDepth bitDepth, EPixelComponent components, EField field)
typedef void(* CallbackDestroyCustomDataPtr)(CustomDataPtr outputCustomData)
Public Member Functions
OutputBufferWrapper (INode &node)
OutputBufferWrapper ()
~OutputBufferWrapper ()
INode & getNode ()
void setCallback (CallbackOutputImagePtr callback, CustomDataPtr customData=NULL, CallbackDestroyCustomDataPtr destroyCustomData=NULL)
Private Attributes
INode * _node
Detailed Description
Definition at line 15 of file OutputBufferWrapper.hpp.
Member Typedef Documentation
typedef void(* tuttle::host::OutputBufferWrapper::CallbackDestroyCustomDataPtr)(CustomDataPtr outputCustomData)
Definition at line 50 of file OutputBufferWrapper.hpp.
typedef void(* tuttle::host::OutputBufferWrapper::CallbackOutputImagePtr)(OfxTime time, CustomDataPtr outputCustomData, void *rawdata, int width, int height, int rowSizeBytes, EBitDepth bitDepth, EPixelComponent components, EField field)
Definition at line 49 of file OutputBufferWrapper.hpp.
typedef void* tuttle::host::OutputBufferWrapper::CustomDataPtr
Definition at line 48 of file OutputBufferWrapper.hpp.
Member Enumeration Documentation
enum tuttle::host::OutputBufferWrapper::EBitDepth
Enumerator:
eBitDepthCustom
some non standard bit depth
eBitDepthNone
bit depth that indicates no data is present
eBitDepthUByte
eBitDepthUShort
eBitDepthFloat
Definition at line 22 of file OutputBufferWrapper.hpp.
enum tuttle::host::OutputBufferWrapper::EField
Enumerator:
eFieldNone
eFieldBoth
eFieldLower
eFieldUpper
Definition at line 40 of file OutputBufferWrapper.hpp.
enum tuttle::host::OutputBufferWrapper::EPixelComponent
Enumerator:
ePixelComponentNone
ePixelComponentRGBA
ePixelComponentRGB
ePixelComponentAlpha
ePixelComponentCustom
some non standard pixel type
Definition at line 31 of file OutputBufferWrapper.hpp.
Constructor & Destructor Documentation
tuttle::host::OutputBufferWrapper::OutputBufferWrapper (INode & node) [inline]
Definition at line 52 of file OutputBufferWrapper.hpp.
tuttle::host::OutputBufferWrapper::OutputBufferWrapper () [inline]
Definition at line 55 of file OutputBufferWrapper.hpp.
tuttle::host::OutputBufferWrapper::~OutputBufferWrapper () [inline]
Definition at line 58 of file OutputBufferWrapper.hpp.
Member Function Documentation
INode& tuttle::host::OutputBufferWrapper::getNode () [inline]
Definition at line 60 of file OutputBufferWrapper.hpp.
References _node.
Referenced by setCallback().
void tuttle::host::OutputBufferWrapper::setCallback (CallbackOutputImagePtr callback, CustomDataPtr customData = NULL, CallbackDestroyCustomDataPtr destroyCustomData = NULL)
Definition at line 8 of file OutputBufferWrapper.cpp.
References getNode(), tuttle::host::INode::getParam(), and tuttle::host::ofx::attribute::OfxhParam::setValue().
Field Documentation
INode* tuttle::host::OutputBufferWrapper::_node [private]
Definition at line 18 of file OutputBufferWrapper.hpp.
Referenced by getNode().
The documentation for this class was generated from the following files:
TuttleOFX/libraries/tuttle/src/tuttle/host/OutputBufferWrapper.hpp
TuttleOFX/libraries/tuttle/src/tuttle/host/OutputBufferWrapper.cpp