TuttleOFX: tuttle::host::ofx::attribute::OfxhParamBoolean Class Reference
tuttle::host::ofx::attribute::OfxhParamBoolean Class Reference
#include <OfxhParamBoolean.hpp>
Public Types
typedef bool BaseType
Public Member Functions
OfxhParamBoolean (const OfxhParamDescriptor &descriptor, const std::string &name, OfxhParamSet &setInstance, const std::size_t index=0)
virtual void getValue (bool &) const OFX_EXCEPTION_SPEC=0
virtual void getValueAtTime (const OfxTime time, bool &) const OFX_EXCEPTION_SPEC=0
virtual void setValue (const bool &, const EChange change) OFX_EXCEPTION_SPEC=0
virtual void setValueAtTime (const OfxTime time, const bool &, const EChange change) OFX_EXCEPTION_SPEC=0
virtual void setValue (const int &v, const EChange change) OFX_EXCEPTION_SPEC
virtual void setValueAtTime (const OfxTime time, const int &v, const EChange change) OFX_EXCEPTION_SPEC
virtual void getV (va_list arg) const OFX_EXCEPTION_SPEC
implementation of var args function
virtual void getV (const OfxTime time, va_list arg) const OFX_EXCEPTION_SPEC
implementation of var args function
virtual void setV (va_list arg, const EChange change) OFX_EXCEPTION_SPEC
implementation of var args function
virtual void setV (const OfxTime time, va_list arg, const EChange change) OFX_EXCEPTION_SPEC
implementation of var args function
bool paramTypeHasData () const
std::size_t getHashAtTime (const OfxTime time) const
Protected Attributes
std::size_t _index
Detailed Description
Definition at line 14 of file OfxhParamBoolean.hpp.
Member Typedef Documentation
typedef bool tuttle::host::ofx::attribute::OfxhParamBoolean::BaseType
Definition at line 22 of file OfxhParamBoolean.hpp.
Constructor & Destructor Documentation
tuttle::host::ofx::attribute::OfxhParamBoolean::OfxhParamBoolean (const OfxhParamDescriptor & descriptor, const std::string & name, OfxhParamSet & setInstance, const std::size_t index = 0) [inline]
Definition at line 23 of file OfxhParamBoolean.hpp.
Member Function Documentation
std::size_t tuttle::host::ofx::attribute::OfxhParamBoolean::getHashAtTime (const OfxTime time) const [virtual]
Implements tuttle::host::ofx::attribute::OfxhParam.
Definition at line 56 of file OfxhParamBoolean.cpp.
References getValueAtTime(), and boost::hash_value().
void tuttle::host::ofx::attribute::OfxhParamBoolean::getV (va_list arg) const [virtual]
implementation of var args function
Reimplemented from tuttle::host::ofx::attribute::OfxhParam.
Definition at line 13 of file OfxhParamBoolean.cpp.
void tuttle::host::ofx::attribute::OfxhParamBoolean::getV (const OfxTime time, va_list arg) const [virtual]
implementation of var args function
Reimplemented from tuttle::host::ofx::attribute::OfxhParam.
Definition at line 26 of file OfxhParamBoolean.cpp.
virtual void tuttle::host::ofx::attribute::OfxhParamBoolean::getValue (bool &) const [pure virtual]
Implemented in tuttle::host::attribute::ParamBoolean.
virtual void tuttle::host::ofx::attribute::OfxhParamBoolean::getValueAtTime (const OfxTime time, bool &) const [pure virtual]
Implemented in tuttle::host::attribute::ParamBoolean.
Referenced by getHashAtTime().
bool tuttle::host::ofx::attribute::OfxhParamBoolean::paramTypeHasData () const [inline, virtual]
Implements tuttle::host::ofx::attribute::OfxhParam.
Definition at line 58 of file OfxhParamBoolean.hpp.
void tuttle::host::ofx::attribute::OfxhParamBoolean::setV (va_list arg, const EChange change) [virtual]
implementation of var args function
Reimplemented from tuttle::host::ofx::attribute::OfxhParam.
Definition at line 39 of file OfxhParamBoolean.cpp.
void tuttle::host::ofx::attribute::OfxhParamBoolean::setV (const OfxTime time, va_list arg, const EChange change) [virtual]
implementation of var args function
Reimplemented from tuttle::host::ofx::attribute::OfxhParam.
Definition at line 49 of file OfxhParamBoolean.cpp.
virtual void tuttle::host::ofx::attribute::OfxhParamBoolean::setValue (const bool & , const EChange change) [pure virtual]
Implemented in tuttle::host::attribute::ParamBoolean.
Referenced by setValue().
virtual void tuttle::host::ofx::attribute::OfxhParamBoolean::setValue (const int & v, const EChange change) [inline, virtual]
Definition at line 34 of file OfxhParamBoolean.hpp.
References setValue().
virtual void tuttle::host::ofx::attribute::OfxhParamBoolean::setValueAtTime (const OfxTime time, const bool & , const EChange change) [pure virtual]
Implemented in tuttle::host::attribute::ParamBoolean.
Referenced by setValueAtTime().
virtual void tuttle::host::ofx::attribute::OfxhParamBoolean::setValueAtTime (const OfxTime time, const int & v, const EChange change) [inline, virtual]
Definition at line 39 of file OfxhParamBoolean.hpp.
References setValueAtTime().
Field Documentation
std::size_t tuttle::host::ofx::attribute::OfxhParamBoolean::_index [protected]
Definition at line 19 of file OfxhParamBoolean.hpp.
Referenced by tuttle::host::attribute::ParamBoolean::getDefault().
The documentation for this class was generated from the following files:
TuttleOFX/libraries/tuttle/src/tuttle/host/ofx/attribute/OfxhParamBoolean.hpp
TuttleOFX/libraries/tuttle/src/tuttle/host/ofx/attribute/OfxhParamBoolean.cpp