TuttleOFX: tuttle::host::ofx::attribute Namespace Reference
tuttle::host::ofx::attribute Namespace Reference
Data Structures
class OfxhAttribute
class OfxhAttributeAccessor
class OfxhAttributeDescriptor
class OfxhClip
class OfxhClipAccessor
class OfxhClipDescriptor
class OfxhClipImage
a clip image instance
class OfxhClipImageAccessor
class OfxhClipImageDescriptor
class OfxhClipImageSet
class OfxhKeyframeParam
class OfxhMultiDimParam
class OfxhParam
plugin parameter instance
class OfxhParamAccessor
base class for all params
class OfxhParamBoolean
class OfxhParamChoice
class OfxhParamCustom
struct TypeMap
class OfxhParamDescriptor
the Descriptor of a plugin parameter
class OfxhParamDouble
class OfxhParamGroup
class OfxhParamInteger
class OfxhParamPage
class OfxhParamPushButton
class OfxhParamSet
class OfxhParamSetAccessor
base class to the param set instance and param set descriptor
class OfxhParamSetDescriptor
a set of parameters
class OfxhParamString
Enumerations
enum EChange { eChangeNone, eChangeTime, eChangeUserEdited, eChangePluginEdited }
enum EInterpolatorType { eLinearInterpolator, eSmoothInterpolator, eFastInterpolator, eSlowInterpolator }
Functions
std::string mapChangeEnumToString (const EChange change)
EChange mapChangeStringToEnum (const std::string &change)
OfxhClip * new_clone (const OfxhClip &a)
to make clonable for use in boost::ptr_container.
OfxhClipImage * new_clone (const OfxhClipImage &a)
to make ClipImageInstance clonable (for use in boost::ptr_container)
std::ostream & operator<< (std::ostream &os, const OfxhParam &v)
OfxhParam * new_clone (const OfxhParam &a)
to make ParamInstance clonable (for use in boost::ptr_container)
bool isDoubleParam (const std::string &paramType)
bool isColourParam (const std::string &paramType)
bool isIntParam (const std::string &paramType)
bool isStandardType (const std::string &type)
is this a standard type
bool findType (const std::string &paramType, property::EPropType &propType, int &propDim)
void * getParameterSuite (const int version)
fetch the param suite
Variables
static const property::OfxhPropSpec attributeDescriptorStuffs []
static TypeMap typeMap []
Enumeration Type Documentation
enum tuttle::host::ofx::attribute::EChange
Enumerator:
eChangeNone
eChangeTime
eChangeUserEdited
eChangePluginEdited
Definition at line 16 of file OfxhAttribute.hpp.
enum tuttle::host::ofx::attribute::EInterpolatorType
Enumerator:
eLinearInterpolator
eSmoothInterpolator
eFastInterpolator
eSlowInterpolator
Definition at line 106 of file OfxhParam.hpp.
Function Documentation
bool tuttle::host::ofx::attribute::findType (const std::string & paramType, property::EPropType & propType, int & propDim)
Definition at line 71 of file OfxhParamDescriptor.cpp.
References tuttle::host::ofx::attribute::TypeMap::paramType, tuttle::host::ofx::attribute::TypeMap::propDimension, tuttle::host::ofx::attribute::TypeMap::propType, and typeMap.
Referenced by tuttle::host::ofx::attribute::OfxhParamDescriptor::initStandardParamProps().
void * tuttle::host::ofx::attribute::getParameterSuite (const int version)
fetch the param suite
Definition at line 651 of file OfxhParameterSuite.cpp.
Referenced by tuttle::host::ofx::imageEffect::OfxhImageEffectHost::fetchSuite().
bool tuttle::host::ofx::attribute::isColourParam (const std::string & paramType)
Definition at line 24 of file OfxhParamDescriptor.cpp.
Referenced by tuttle::host::ofx::attribute::OfxhParamDescriptor::initNumericParamProps(), and tuttle::host::ofx::attribute::OfxhParamDescriptor::initStandardParamProps().
bool tuttle::host::ofx::attribute::isDoubleParam (const std::string & paramType)
Definition at line 17 of file OfxhParamDescriptor.cpp.
Referenced by tuttle::host::ofx::attribute::OfxhParamDescriptor::initNumericParamProps(), and tuttle::host::ofx::attribute::OfxhParamDescriptor::initStandardParamProps().
bool tuttle::host::ofx::attribute::isIntParam (const std::string & paramType)
Definition at line 31 of file OfxhParamDescriptor.cpp.
Referenced by tuttle::host::ofx::attribute::OfxhParamDescriptor::initStandardParamProps().
bool tuttle::host::ofx::attribute::isStandardType (const std::string & type)
is this a standard type
is this a standard BaseType
Definition at line 58 of file OfxhParamDescriptor.cpp.
References tuttle::host::ofx::attribute::TypeMap::paramType, and typeMap.
Referenced by tuttle::host::ofx::attribute::OfxhParamSetDescriptor::paramDefine().
std::string tuttle::host::ofx::attribute::mapChangeEnumToString (const EChange change) [inline]
Definition at line 24 of file OfxhAttribute.hpp.
References eChangeNone, eChangePluginEdited, eChangeTime, and eChangeUserEdited.
Referenced by tuttle::host::ofx::imageEffect::OfxhImageEffectNode::paramChanged(), and tuttle::host::ofx::attribute::OfxhParam::setValueFromExpression().
EChange tuttle::host::ofx::attribute::mapChangeStringToEnum (const std::string & change) [inline]
Definition at line 40 of file OfxhAttribute.hpp.
References eChangeNone, eChangePluginEdited, eChangeTime, and eChangeUserEdited.
OfxhClip* tuttle::host::ofx::attribute::new_clone (const OfxhClip & a) [inline]
to make clonable for use in boost::ptr_container.
Definition at line 87 of file OfxhClip.hpp.
References tuttle::host::ofx::attribute::OfxhClip::clone().
OfxhParam* tuttle::host::ofx::attribute::new_clone (const OfxhParam & a) [inline]
to make ParamInstance clonable (for use in boost::ptr_container)
Definition at line 295 of file OfxhParam.hpp.
References tuttle::host::ofx::attribute::OfxhParam::clone().
OfxhClipImage* tuttle::host::ofx::attribute::new_clone (const OfxhClipImage & a) [inline]
to make ClipImageInstance clonable (for use in boost::ptr_container)
Definition at line 341 of file OfxhClipImage.hpp.
References tuttle::host::ofx::attribute::OfxhClipImage::clone().
std::ostream& tuttle::host::ofx::attribute::operator<< (std::ostream & os, const OfxhParam & v)
Definition at line 156 of file OfxhParam.cpp.
References tuttle::host::ofx::attribute::OfxhAttribute::getProperties().
Variable Documentation
const property::OfxhPropSpec tuttle::host::ofx::attribute::attributeDescriptorStuffs[] [static]
Initial value:
 {
        { kOfxPropName, property::ePropTypeString, 1, true, "SET_ME_ON_CONSTRUCTION" },
        { kOfxPropLabel, property::ePropTypeString, 1, false, "" },
        { kOfxPropShortLabel, property::ePropTypeString, 1, false, "" },
        { kOfxPropLongLabel, property::ePropTypeString, 1, false, "" },
        { 0 },
}
properties common to the desciptor and instance the desc and set them, the instance cannot
Definition at line 10 of file OfxhAttributeDescriptor.cpp.
Referenced by tuttle::host::ofx::attribute::OfxhAttributeDescriptor::OfxhAttributeDescriptor().
TypeMap tuttle::host::ofx::attribute::typeMap[] [static]
Initial value:
 {
        { kOfxParamTypeInteger, property::ePropTypeInt, 1 },
        { kOfxParamTypeDouble, property::ePropTypeDouble, 1 },
        { kOfxParamTypeBoolean, property::ePropTypeInt, 1 },
        { kOfxParamTypeChoice, property::ePropTypeInt, 1 },
        { kOfxParamTypeRGBA, property::ePropTypeDouble, 4 },
        { kOfxParamTypeRGB, property::ePropTypeDouble, 3 },
        { kOfxParamTypeDouble2D, property::ePropTypeDouble, 2 },
        { kOfxParamTypeInteger2D, property::ePropTypeInt, 2 },
        { kOfxParamTypeDouble3D, property::ePropTypeDouble, 3 },
        { kOfxParamTypeInteger3D, property::ePropTypeInt, 3 },
        { kOfxParamTypeString, property::ePropTypeString, 1 },
        { kOfxParamTypeCustom, property::ePropTypeString, 1 },
        { kOfxParamTypeGroup, property::ePropTypeNone },
        { kOfxParamTypePage, property::ePropTypeNone },
        { kOfxParamTypePushButton, property::ePropTypeNone },
        { 0 }
}
Definition at line 38 of file OfxhParamDescriptor.cpp.
Referenced by findType(), and isStandardType().