TuttleOFX: TuttleOFX/libraries/tuttle/tests/memory/main.cpp File Reference
TuttleOFX/libraries/tuttle/tests/memory/main.cpp File Reference
#include <tuttle/host/memory/MemoryPool.hpp>
#include <tuttle/host/memory/MemoryCache.hpp>
#include <iostream>
#include <tuttle/test/unit_test.hpp>
Defines
#define BOOST_TEST_MODULE tuttle_memory
Functions
BOOST_AUTO_TEST_CASE (memoryPool)
BOOST_AUTO_TEST_CASE (memoryCache)
Define Documentation
#define BOOST_TEST_MODULE tuttle_memory
Definition at line 7 of file main.cpp.
Function Documentation
BOOST_AUTO_TEST_CASE (memoryPool)
Definition at line 16 of file main.cpp.
References tuttle::host::memory::MemoryPool::allocate(), tuttle::host::memory::MemoryPool::getAllocatedMemorySize(), tuttle::host::memory::MemoryPool::getMaxMemorySize(), tuttle::host::memory::MemoryPool::getUsedMemorySize(), and tuttle::host::memory::MemoryPool::getWastedMemorySize().
BOOST_AUTO_TEST_CASE (memoryCache)
Definition at line 91 of file main.cpp.
References tuttle::host::memory::MemoryCache::clearAll(), tuttle::host::memory::MemoryCache::empty(), tuttle::host::memory::MemoryCache::getPluginName(), tuttle::host::memory::MemoryCache::getTime(), tuttle::host::memory::MemoryCache::inCache(), tuttle::host::memory::MemoryCache::put(), tuttle::host::memory::MemoryCache::remove(), and tuttle::host::memory::MemoryCache::size().