TuttleOFX: tuttle::host::memory Namespace Reference
tuttle::host::memory Namespace Reference
Data Structures
struct Key
struct KeyHash
class IMemoryCache
class IUnknown
class IPoolData
class IMemoryPool
class LinkData
A link to an external buffer which can't be managed by the MemoryPool.
class MemoryCache
class PoolData
class IPool
forward declaration
class MemoryPool
Typedefs
typedef ::boost::shared_ptr
< tuttle::host::attribute::Image > CACHE_ELEMENT
configure the cache with this element CACHE_ELEMENT should be a smart_ptr of some kind pointer will be stored in a container so no auto_ptr is allowed
typedef ::boost::intrusive_ptr
< IPoolData > IPoolDataPtr
Functions
std::ostream & operator<< (std::ostream &os, const Key &v)
std::ostream & operator<< (std::ostream &os, const IMemoryCache &v)
void intrusive_ptr_add_ref (IPoolData *pData)
void intrusive_ptr_release (IPoolData *pData)
std::ostream & operator<< (std::ostream &os, const MemoryCache &v)
std::ostream & operator<< (std::ostream &os, const MemoryPool &memoryPool)
Typedef Documentation
typedef ::boost::shared_ptr<tuttle::host::attribute::Image> tuttle::host::memory::CACHE_ELEMENT
configure the cache with this element CACHE_ELEMENT should be a smart_ptr of some kind pointer will be stored in a container so no auto_ptr is allowed
Todo:
temporary solution..
Definition at line 21 of file IMemoryCache.hpp.
typedef ::boost::intrusive_ptr<IPoolData> tuttle::host::memory::IPoolDataPtr
Definition at line 36 of file IMemoryPool.hpp.
Function Documentation
void tuttle::host::memory::intrusive_ptr_add_ref (IPoolData * pData)
Definition at line 69 of file MemoryPool.cpp.
References tuttle::host::memory::IUnknown::addRef().
void tuttle::host::memory::intrusive_ptr_release (IPoolData * pData)
Definition at line 74 of file MemoryPool.cpp.
References tuttle::host::memory::IUnknown::release().
std::ostream& tuttle::host::memory::operator<< (std::ostream & os, const Key & v)
Definition at line 31 of file IMemoryCache.cpp.
References tuttle::host::memory::Key::_identifier, and tuttle::host::memory::Key::_time.
std::ostream& tuttle::host::memory::operator<< (std::ostream & os, const IMemoryCache & v)
Definition at line 40 of file IMemoryCache.cpp.
References tuttle::host::memory::IMemoryCache::outputStream().
std::ostream & tuttle::host::memory::operator<< (std::ostream & os, const MemoryCache & v)
Definition at line 206 of file MemoryCache.cpp.
References tuttle::host::memory::MemoryCache::_map, tuttle::host::ofx::imageEffect::OfxhImage::eReferenceOwnerHost, tuttle::host::ofx::imageEffect::OfxhImage::eReferenceOwnerPlugin, and tuttle::host::memory::MemoryCache::size().
std::ostream & tuttle::host::memory::operator<< (std::ostream & os, const MemoryPool & memoryPool)
Definition at line 318 of file MemoryPool.cpp.
References MemoryInfo::_totalRam, tuttle::host::memory::MemoryPool::getAllocatedMemorySize(), tuttle::host::memory::MemoryPool::getAvailableMemorySize(), tuttle::host::memory::MemoryPool::getDataUnusedSize(), tuttle::host::memory::MemoryPool::getDataUsedSize(), tuttle::host::memory::MemoryPool::getMaxMemorySize(), getMemoryInfo(), tuttle::host::memory::MemoryPool::getUsedMemorySize(), and tuttle::host::memory::MemoryPool::getWastedMemorySize().