TuttleOFX: tuttle::host::attribute::ParamString Class Reference
tuttle::host::attribute::ParamString Class Reference
#include <ParamString.hpp>
Public Member Functions
ParamString (INode &effect, const std::string &name, const ofx::attribute::OfxhParamDescriptor &descriptor)
ParamString * clone () const
clone this parameter
const std::string & getDefault () const
void getValue (std::string &) const OFX_EXCEPTION_SPEC
void getValueAtTime (const OfxTime time, std::string &) const OFX_EXCEPTION_SPEC
void setValue (const std::string &value, const ofx::attribute::EChange change) OFX_EXCEPTION_SPEC
void setValueAtTime (const OfxTime time, const std::string &value, const ofx::attribute::EChange change) OFX_EXCEPTION_SPEC
void setValueFromExpression (const std::string &value, const ofx::attribute::EChange change) OFX_EXCEPTION_SPEC
void copy (const ParamString &p) OFX_EXCEPTION_SPEC
void copy (const OfxhParam &p) OFX_EXCEPTION_SPEC
Protected Attributes
std::string _value
Detailed Description
Definition at line 13 of file ParamString.hpp.
Constructor & Destructor Documentation
tuttle::host::attribute::ParamString::ParamString (INode & effect, const std::string & name, const ofx::attribute::OfxhParamDescriptor & descriptor)
Todo:
link de parametres
Definition at line 10 of file ParamString.cpp.
References _value, and getDefault().
Referenced by clone().
Member Function Documentation
ParamString* tuttle::host::attribute::ParamString::clone () const [inline, virtual]
clone this parameter
Implements tuttle::host::ofx::attribute::OfxhParam.
Definition at line 21 of file ParamString.hpp.
References ParamString().
void tuttle::host::attribute::ParamString::copy (const ParamString & p)
Definition at line 52 of file ParamString.cpp.
References _value.
void tuttle::host::attribute::ParamString::copy (const OfxhParam & p)
Definition at line 58 of file ParamString.cpp.
const std::string & tuttle::host::attribute::ParamString::getDefault () const
Definition at line 19 of file ParamString.cpp.
References tuttle::host::ofx::attribute::OfxhAttribute::getProperties().
Referenced by ParamString().
void tuttle::host::attribute::ParamString::getValue (std::string & v) const [virtual]
Implements tuttle::host::ofx::attribute::OfxhParamString.
Definition at line 24 of file ParamString.cpp.
References _value.
void tuttle::host::attribute::ParamString::getValueAtTime (const OfxTime time, std::string & v) const [virtual]
<
Todo:
: in time !
Implements tuttle::host::ofx::attribute::OfxhParamString.
Definition at line 29 of file ParamString.cpp.
References _value.
void tuttle::host::attribute::ParamString::setValue (const std::string & value, const ofx::attribute::EChange change) [virtual]
Implements tuttle::host::ofx::attribute::OfxhParamString.
Definition at line 34 of file ParamString.cpp.
References _value.
void tuttle::host::attribute::ParamString::setValueAtTime (const OfxTime time, const std::string & value, const ofx::attribute::EChange change) [virtual]
<
Todo:
: in time !
Implements tuttle::host::ofx::attribute::OfxhParamString.
Definition at line 40 of file ParamString.cpp.
References _value.
void tuttle::host::attribute::ParamString::setValueFromExpression (const std::string & value, const ofx::attribute::EChange change) [virtual]
Reimplemented from tuttle::host::ofx::attribute::OfxhParam.
Definition at line 46 of file ParamString.cpp.
References _value.
Field Documentation
std::string tuttle::host::attribute::ParamString::_value [protected]
Definition at line 17 of file ParamString.hpp.
Referenced by ParamString().
The documentation for this class was generated from the following files:
TuttleOFX/libraries/tuttle/src/tuttle/host/attribute/ParamString.hpp
TuttleOFX/libraries/tuttle/src/tuttle/host/attribute/ParamString.cpp