TuttleOFX: tuttle::plugin::interact::PointInteract Class Reference
tuttle::plugin::interact::PointInteract Class Reference
#include <PointInteract.hpp>
Public Member Functions
PointInteract (const InteractInfos &infos)
virtual ~PointInteract ()=0
double getTime () const
virtual Point2 getPoint () const =0
virtual void setPoint (const Scalar x, const Scalar y)=0
virtual Point2 getPosition () const
virtual void setPosition (const Point2 &p)
virtual void setPositionX (const Scalar x)
virtual void setPositionY (const Scalar y)
virtual double getMarge () const
virtual bool draw (const OFX::DrawArgs &args) const
the function called to draw in the interact
virtual MotionType intersect (const OFX::PenArgs &args)
virtual bool isIn (const OfxRectD &)
Protected Attributes
const InteractInfos & _infos
Detailed Description
Definition at line 12 of file PointInteract.hpp.
Constructor & Destructor Documentation
tuttle::plugin::interact::PointInteract::PointInteract (const InteractInfos & infos)
Definition at line 16 of file PointInteract.cpp.
tuttle::plugin::interact::PointInteract::~PointInteract () [pure virtual]
Definition at line 20 of file PointInteract.cpp.
Member Function Documentation
bool tuttle::plugin::interact::PointInteract::draw (const OFX::DrawArgs & args) const [virtual]
the function called to draw in the interact
Reimplemented from tuttle::plugin::interact::InteractObject.
Reimplemented in tuttle::plugin::interact::ParamRectangleFromCenterSize< TFrame, coord >, tuttle::plugin::interact::ParamTangent< TFrame, coord >, and tuttle::plugin::interact::ParamRectangleFromTwoCorners< TFrame, coord >.
Definition at line 22 of file PointInteract.cpp.
References tuttle::plugin::overlay::displayCross(), tuttle::plugin::overlay::displayPointRect(), getMarge(), getPoint(), and tuttle::plugin::interact::InteractObject::getSelected().
Referenced by tuttle::plugin::interact::ParamRectangleFromTwoCorners< TFrame, coord >::draw().
virtual double tuttle::plugin::interact::PointInteract::getMarge () const [inline, virtual]
Definition at line 31 of file PointInteract.hpp.
References _infos, tuttle::plugin::interact::InteractInfos::_marge, and tuttle::plugin::interact::InteractInfos::_projectSize.
Referenced by draw(), and intersect().
virtual Point2 tuttle::plugin::interact::PointInteract::getPoint () const [pure virtual]
Implemented in tuttle::plugin::interact::ParamRectangleFromCenterSize< TFrame, coord >, tuttle::plugin::interact::ParamRectangleFromTwoCorners< TFrame, coord >, tuttle::plugin::interact::ParamPoint< TFrame, coord >, tuttle::plugin::interact::ParamPoint< TFrame, CoordinateSystemNotCentered< coord >::value >, and tuttle::plugin::interact::ParamPointRelativePoint< TFrame, coord >.
Referenced by draw(), tuttle::plugin::interact::ParamPointRelativePoint< TFrame, coord >::getPoint(), getPosition(), intersect(), isIn(), tuttle::plugin::interact::ParamPointRelativePoint< TFrame, coord >::setPoint(), setPositionX(), and setPositionY().
virtual Point2 tuttle::plugin::interact::PointInteract::getPosition () const [inline, virtual]
Reimplemented from tuttle::plugin::interact::InteractObject.
Definition at line 26 of file PointInteract.hpp.
References getPoint().
Referenced by tuttle::plugin::interact::ParamTangent< TFrame, coord >::translate().
double tuttle::plugin::interact::PointInteract::getTime () const [inline]
Definition at line 22 of file PointInteract.hpp.
References tuttle::plugin::interact::InteractInfos::_effect, and _infos.
Referenced by tuttle::plugin::interact::ParamPointRelativePoint< TFrame, coord >::getPoint(), tuttle::plugin::interact::ParamPoint< TFrame, CoordinateSystemNotCentered< coord >::value >::getPoint(), tuttle::plugin::interact::ParamRectangleFromTwoCorners< TFrame, coord >::getPoint(), tuttle::plugin::interact::ParamPointRelativePoint< TFrame, coord >::setPoint(), tuttle::plugin::interact::ParamPoint< TFrame, CoordinateSystemNotCentered< coord >::value >::setPoint(), tuttle::plugin::interact::ParamRectangleFromTwoCorners< TFrame, coord >::setPoint(), and tuttle::plugin::interact::ParamRectangleFromCenterSize< TFrame, coord >::setPoint().
MotionType tuttle::plugin::interact::PointInteract::intersect (const OFX::PenArgs & args) [virtual]
Reimplemented from tuttle::plugin::interact::InteractObject.
Reimplemented in tuttle::plugin::interact::ParamRectangleFromCenterSize< TFrame, coord >, tuttle::plugin::interact::ParamRectangleFromTwoCorners< TFrame, coord >, and tuttle::plugin::interact::ParamTangent< TFrame, coord >.
Definition at line 41 of file PointInteract.cpp.
References tuttle::plugin::interact::MotionType::_axis, tuttle::plugin::interact::MotionType::_mode, tuttle::plugin::interact::clicPoint(), tuttle::plugin::interact::eMotionTranslate, getMarge(), getPoint(), and tuttle::plugin::ofxToGil().
Referenced by tuttle::plugin::interact::ParamRectangleFromTwoCorners< TFrame, coord >::intersect().
bool tuttle::plugin::interact::PointInteract::isIn (const OfxRectD & rect) [virtual]
Reimplemented from tuttle::plugin::interact::InteractObject.
Reimplemented in tuttle::plugin::interact::ParamRectangleFromCenterSize< TFrame, coord >, and tuttle::plugin::interact::ParamRectangleFromTwoCorners< TFrame, coord >.
Definition at line 53 of file PointInteract.cpp.
References getPoint(), and tuttle::pointInRect().
virtual void tuttle::plugin::interact::PointInteract::setPoint (const Scalar x, const Scalar y) [pure virtual]
Implemented in tuttle::plugin::interact::ParamRectangleFromCenterSize< TFrame, coord >, tuttle::plugin::interact::ParamRectangleFromTwoCorners< TFrame, coord >, tuttle::plugin::interact::ParamPoint< TFrame, coord >, tuttle::plugin::interact::ParamPoint< TFrame, CoordinateSystemNotCentered< coord >::value >, and tuttle::plugin::interact::ParamPointRelativePoint< TFrame, coord >.
Referenced by setPosition(), setPositionX(), and setPositionY().
virtual void tuttle::plugin::interact::PointInteract::setPosition (const Point2 & p) [inline, virtual]
Reimplemented from tuttle::plugin::interact::InteractObject.
Definition at line 27 of file PointInteract.hpp.
References setPoint().
Referenced by tuttle::plugin::interact::ParamTangent< TFrame, coord >::translate().
virtual void tuttle::plugin::interact::PointInteract::setPositionX (const Scalar x) [inline, virtual]
Reimplemented from tuttle::plugin::interact::InteractObject.
Definition at line 28 of file PointInteract.hpp.
References getPoint(), and setPoint().
virtual void tuttle::plugin::interact::PointInteract::setPositionY (const Scalar y) [inline, virtual]
Reimplemented from tuttle::plugin::interact::InteractObject.
Definition at line 29 of file PointInteract.hpp.
References getPoint(), and setPoint().
Field Documentation
const InteractInfos& tuttle::plugin::interact::PointInteract::_infos [protected]
Definition at line 19 of file PointInteract.hpp.
Referenced by getMarge(), and getTime().
The documentation for this class was generated from the following files:
TuttleOFX/libraries/tuttle/src/tuttle/plugin/interact/PointInteract.hpp
TuttleOFX/libraries/tuttle/src/tuttle/plugin/interact/PointInteract.cpp