TuttleOFX: tuttle::host::ofx::attribute::OfxhParamPage Class Reference
tuttle::host::ofx::attribute::OfxhParamPage Class Reference
#include <OfxhParamPage.hpp>
Public Member Functions
OfxhParamPage (const OfxhParamDescriptor &descriptor, const std::string &name, OfxhParamSet &setInstance)
const std::map< int, OfxhParam * > & getChildren () const
Protected Member Functions
virtual void getValue (double &) const OFX_EXCEPTION_SPEC
virtual void getValueAtTime (const OfxTime time, double &) const OFX_EXCEPTION_SPEC
virtual void setValue (const double &, const EChange change) OFX_EXCEPTION_SPEC
virtual void setValueAtTime (const OfxTime time, const double &, const EChange change) OFX_EXCEPTION_SPEC
virtual void setValue (const int &v, const EChange change) OFX_EXCEPTION_SPEC
virtual void setValueAtTime (const OfxTime time, const int &v, const EChange change) OFX_EXCEPTION_SPEC
virtual void setValueFromExpression (const std::string &value, const EChange change) OFX_EXCEPTION_SPEC
void setValueFromExpression (const std::string &value) OFX_EXCEPTION_SPEC
bool paramTypeHasData () const
std::size_t getHashAtTime (const OfxTime time) const
Protected Attributes
std::map< int, OfxhParam * > _children
Detailed Description
Definition at line 15 of file OfxhParamPage.hpp.
Constructor & Destructor Documentation
tuttle::host::ofx::attribute::OfxhParamPage::OfxhParamPage (const OfxhParamDescriptor & descriptor, const std::string & name, OfxhParamSet & setInstance) [inline]
Definition at line 18 of file OfxhParamPage.hpp.
Member Function Documentation
const std::map< int, OfxhParam * > & tuttle::host::ofx::attribute::OfxhParamPage::getChildren () const
Definition at line 8 of file OfxhParamPage.cpp.
References _children, tuttle::host::ofx::attribute::OfxhParam::_paramSetInstance, tuttle::host::ofx::property::OfxhSet::getDimension(), tuttle::host::ofx::attribute::OfxhParamSet::getParam(), tuttle::host::ofx::attribute::OfxhAttribute::getProperties(), and tuttle::host::ofx::property::OfxhSet::getStringProperty().
std::size_t tuttle::host::ofx::attribute::OfxhParamPage::getHashAtTime (const OfxTime time) const [inline, protected, virtual]
Implements tuttle::host::ofx::attribute::OfxhParam.
Definition at line 36 of file OfxhParamPage.hpp.
virtual void tuttle::host::ofx::attribute::OfxhParamPage::getValue (double &) const [inline, protected, virtual]
Definition at line 25 of file OfxhParamPage.hpp.
virtual void tuttle::host::ofx::attribute::OfxhParamPage::getValueAtTime (const OfxTime time, double &) const [inline, protected, virtual]
Definition at line 26 of file OfxhParamPage.hpp.
bool tuttle::host::ofx::attribute::OfxhParamPage::paramTypeHasData () const [inline, protected, virtual]
Implements tuttle::host::ofx::attribute::OfxhParam.
Definition at line 34 of file OfxhParamPage.hpp.
virtual void tuttle::host::ofx::attribute::OfxhParamPage::setValue (const double & , const EChange change) [inline, protected, virtual]
Definition at line 27 of file OfxhParamPage.hpp.
virtual void tuttle::host::ofx::attribute::OfxhParamPage::setValue (const int & v, const EChange change) [inline, protected, virtual]
Definition at line 29 of file OfxhParamPage.hpp.
virtual void tuttle::host::ofx::attribute::OfxhParamPage::setValueAtTime (const OfxTime time, const double & , const EChange change) [inline, protected, virtual]
Definition at line 28 of file OfxhParamPage.hpp.
virtual void tuttle::host::ofx::attribute::OfxhParamPage::setValueAtTime (const OfxTime time, const int & v, const EChange change) [inline, protected, virtual]
Definition at line 30 of file OfxhParamPage.hpp.
virtual void tuttle::host::ofx::attribute::OfxhParamPage::setValueFromExpression (const std::string & value, const EChange change) [inline, protected, virtual]
Reimplemented from tuttle::host::ofx::attribute::OfxhParam.
Definition at line 31 of file OfxhParamPage.hpp.
void tuttle::host::ofx::attribute::OfxhParamPage::setValueFromExpression (const std::string & value) [inline, protected]
Reimplemented from tuttle::host::ofx::attribute::OfxhParam.
Definition at line 32 of file OfxhParamPage.hpp.
References tuttle::host::ofx::attribute::eChangeUserEdited, and setValueFromExpression().
Referenced by setValueFromExpression().
Field Documentation
std::map<int, OfxhParam*> tuttle::host::ofx::attribute::OfxhParamPage::_children [mutable, protected]
Definition at line 22 of file OfxhParamPage.hpp.
Referenced by getChildren().
The documentation for this class was generated from the following files:
TuttleOFX/libraries/tuttle/src/tuttle/host/ofx/attribute/OfxhParamPage.hpp
TuttleOFX/libraries/tuttle/src/tuttle/host/ofx/attribute/OfxhParamPage.cpp