TuttleOFX: tuttle::host::graph::ProcessVertex Class Reference
tuttle::host::graph::ProcessVertex Class Reference
#include <ProcessVertex.hpp>
Public Types
typedef std::string Key
Public Member Functions
ProcessVertex ()
ProcessVertex (const ProcessVertexData &defaultVertexData, const std::string &name="Undefined")
ProcessVertex (const ProcessVertex &v)
ProcessVertex & operator= (const ProcessVertex &v)
ProcessVertex & operator= (const UVertex &v)
Key getKey () const
void clearTimeInfo ()
void setProcessData (const ProcessVertexData &d)
ProcessVertexData & getProcessData ()
const ProcessVertexData & getProcessData () const
std::ostream & exportDotDebug (std::ostream &os) const
Data Fields
ProcessVertexData _data
Friends
std::ostream & operator<< (std::ostream &os, const ProcessVertex &v)
Detailed Description
Definition at line 12 of file ProcessVertex.hpp.
Member Typedef Documentation
typedef std::string tuttle::host::graph::ProcessVertex::Key
Definition at line 15 of file ProcessVertex.hpp.
Constructor & Destructor Documentation
tuttle::host::graph::ProcessVertex::ProcessVertex ()
Definition at line 14 of file ProcessVertex.cpp.
tuttle::host::graph::ProcessVertex::ProcessVertex (const ProcessVertexData & defaultVertexData, const std::string & name = "Undefined")
Definition at line 20 of file ProcessVertex.cpp.
tuttle::host::graph::ProcessVertex::ProcessVertex (const ProcessVertex & v)
Definition at line 26 of file ProcessVertex.cpp.
Member Function Documentation
void tuttle::host::graph::ProcessVertex::clearTimeInfo () [inline]
Definition at line 38 of file ProcessVertex.hpp.
References _data, and tuttle::host::graph::ProcessVertexData::clearTimeInfo().
std::ostream & tuttle::host::graph::ProcessVertex::exportDotDebug (std::ostream & os) const [virtual]
Todo:
remove this. Temporary solution
Reimplemented from tuttle::host::graph::IVertex.
Definition at line 32 of file ProcessVertex.cpp.
References _data, tuttle::host::graph::ProcessVertexData::_timeDomain, tuttle::host::graph::ProcessVertexData::_times, tuttle::host::graph::dotEntry(), tuttle::host::INode::eNodeTypeImageEffect, tuttle::host::ofx::attribute::OfxhClipImage::getBitDepthString(), tuttle::host::ofx::attribute::OfxhClipImage::getComponentsString(), tuttle::host::ofx::attribute::OfxhClipImage::getFrameRange(), tuttle::host::attribute::ClipImage::getFrameRate(), tuttle::host::graph::IVertex::getName(), tuttle::host::ImageEffectNode::getOutputClip(), tuttle::host::graph::IVertex::getProcessNode(), tuttle::host::graph::IVertex::isFake(), and tuttle::host::graph::subDotEntry().
Key tuttle::host::graph::ProcessVertex::getKey () const [inline]
Definition at line 36 of file ProcessVertex.hpp.
References tuttle::host::graph::IVertex::getName().
Referenced by tuttle::host::graph::ProcessGraph::updateGraph().
ProcessVertexData& tuttle::host::graph::ProcessVertex::getProcessData () [inline]
Definition at line 42 of file ProcessVertex.hpp.
References _data.
Referenced by tuttle::host::graph::ProcessGraph::computeTimeRange().
const ProcessVertexData& tuttle::host::graph::ProcessVertex::getProcessData () const [inline]
Definition at line 43 of file ProcessVertex.hpp.
References _data.
ProcessVertex& tuttle::host::graph::ProcessVertex::operator= (const ProcessVertex & v) [inline]
Definition at line 22 of file ProcessVertex.hpp.
References _data.
Referenced by operator=().
ProcessVertex& tuttle::host::graph::ProcessVertex::operator= (const UVertex & v) [inline]
Definition at line 29 of file ProcessVertex.hpp.
References tuttle::host::graph::ProcessVertexData::_apiType, _data, tuttle::host::INode::getNodeType(), tuttle::host::graph::IVertex::getProcessNode(), and operator=().
void tuttle::host::graph::ProcessVertex::setProcessData (const ProcessVertexData & d) [inline]
Definition at line 40 of file ProcessVertex.hpp.
References _data.
Referenced by tuttle::host::graph::ProcessGraph::setup().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const ProcessVertex & v) [friend]
Definition at line 81 of file ProcessVertex.cpp.
Field Documentation
ProcessVertexData tuttle::host::graph::ProcessVertex::_data
Definition at line 49 of file ProcessVertex.hpp.
Referenced by clearTimeInfo(), exportDotDebug(), getProcessData(), operator=(), setProcessData(), tuttle::host::graph::ProcessGraph::setup(), and tuttle::host::graph::ProcessGraph::setupAtTime().
The documentation for this class was generated from the following files:
TuttleOFX/libraries/tuttle/src/tuttle/host/graph/ProcessVertex.hpp
TuttleOFX/libraries/tuttle/src/tuttle/host/graph/ProcessVertex.cpp