TuttleOFX: tuttle::host::ofx::property::OfxhSet Class Reference
tuttle::host::ofx::property::OfxhSet Class Reference
#include <OfxhSet.hpp>
Public Types
typedef OfxhSet This
Public Member Functions
OfxhSet (const OfxhPropSpec spec[])
OfxhSet (const OfxhSet &)
deep copies the property set
OfxhSet ()
empty ctor
virtual ~OfxhSet ()
destructor
void clear ()
size_t getLocalSize () const
size_t getSize () const
OfxhSet & operator= (const This &)
bool operator== (const This &) const
bool operator!= (const This &other) const
void copyValues (const This &other)
OfxhProperty & localAt (const int index)
const OfxhProperty & at (const int index) const
void addProperties (const OfxhPropSpec *)
adds a bunch of properties from PropSpec
void eraseProperty (const std::string &propName)
bool hasProperty (const std::string &propName, bool followChain=true) const
bool hasLocalProperty (const std::string &propName) const
OfxhSet & operator+= (const OfxhPropSpec *p)
void createProperty (const OfxhPropSpec &s)
add one new property
void addProperty (OfxhProperty *prop)
add one new property (takes ownership)
void setChainedSet (const OfxhSet *const s)
set the chained property set
const OfxhSet & getChainedSet () const
const PropertyMap & getMap () const
grab the internal properties map
PropertyMap & getMap ()
void setGetHook (const std::string &s, OfxhGetHook *ghook)
void addNotifyHook (const std::string &name, OfxhNotifyHook *hook)
const OfxhProperty & fetchProperty (const std::string &name) const
OfxhProperty & fetchLocalProperty (const std::string &name)
const OfxhProperty & fetchLocalProperty (const std::string &name) const
template<class T >
const T & fetchTypedProperty (const std::string &name) const
template<class T >
T & fetchLocalTypedProperty (const std::string &name)
template<class T >
const T & fetchLocalTypedProperty (const std::string &name) const
const String & fetchStringProperty (const std::string &name) const
String & fetchLocalStringProperty (const std::string &name)
const String & fetchLocalStringProperty (const std::string &name) const
const Int & fetchIntProperty (const std::string &name) const
Int & fetchLocalIntProperty (const std::string &name)
const Int & fetchLocalIntProperty (const std::string &name) const
const Pointer & fetchPointerProperty (const std::string &name) const
Pointer & fetchLocalPointerProperty (const std::string &name)
const Pointer & fetchLocalPointerProperty (const std::string &name) const
const Double & fetchDoubleProperty (const std::string &name) const
Double & fetchLocalDoubleProperty (const std::string &name)
const Double & fetchLocalDoubleProperty (const std::string &name) const
int getIntPropertyRaw (const std::string &property, int index=0) const
get a particular int property without fetching via a get hook, useful for notifies
double getDoublePropertyRaw (const std::string &property, int index=0) const
get a particular double property without fetching via a get hook, useful for notifies
void * getPointerPropertyRaw (const std::string &property, int index=0) const
get a particular pointer property without fetching via a get hook, useful for notifies
const std::string & getStringPropertyRaw (const std::string &property, int index=0) const
get a particular string property
const std::string & getStringProperty (const std::string &property, int index=0) const
get the value of a particular string property
int getIntProperty (const std::string &property, int index=0) const
get the value of a particular int property
void getIntPropertyN (const std::string &property, int *v, int N) const
get the value of a particular double property
double getDoubleProperty (const std::string &property, int index=0) const
get the value of a particular double property
void getDoublePropertyN (const std::string &property, double *v, int N) const
get the value of a particular double property
void * getPointerProperty (const std::string &property, int index=0) const
get the value of a particular pointer property
void setStringProperty (const std::string &property, const std::string &value, int index=0)
set a particular string property without fetching via a get hook, useful for notifies
void setIntProperty (const std::string &property, int v, int index=0)
set a particular int property
void setIntPropertyN (const std::string &property, const int *v, int N)
set a particular double property
void setDoubleProperty (const std::string &property, double v, int index=0)
get a particular double property
void setDoublePropertyN (const std::string &property, const double *v, int N)
get a particular double property
void setPointerProperty (const std::string &property, void *v, int index=0)
get a particular double property
size_t getDimension (const std::string &property) const
get the dimension of a particular property
int findStringPropValueIndex (const std::string &propName, const std::string &propValue) const
OfxPropertySetHandle getHandle () const
get a handle on this object for passing to the C API
bool verifyMagic ()
is this a nice property set, or a dodgy pointer passed back to us
Protected Member Functions
template<class T >
void setProperty (const std::string &property, int index, const typename T::Type &value)
set a particular property
template<class T >
void setPropertyN (const std::string &property, int count, const typename T::APIType *value)
set the first N of a particular property
template<class T >
T::ReturnType getProperty (const std::string &property, int index) const
get a particular property
template<class T >
void getPropertyN (const std::string &property, int index, typename T::APIType *v) const
get the first N of a particular property
template<class T >
T::ReturnType getPropertyRaw (const std::string &property, int index) const
get a particular property without going through any getHook
template<class T >
void getPropertyRawN (const std::string &property, int count, typename T::APIType *v) const
get a particular property without going through any getHook
Protected Attributes
PropertyMap _props
Our properties.
const OfxhSet * _chainedSet
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
const int _magic
to check for handles being nice
Static Private Attributes
static const int kMagic = 0x12082007
magic number for property sets, and Connie's birthday :-)
Friends
class boost::serialization::access
std::ostream & operator<< (std::ostream &os, const This &g)
Detailed Description
Class that holds a set of properties and manipulates them The 'fetch' methods return a property object. The 'get' methods return a property value
Definition at line 61 of file OfxhSet.hpp.
Member Typedef Documentation
typedef OfxhSet tuttle::host::ofx::property::OfxhSet::This
Definition at line 64 of file OfxhSet.hpp.
Constructor & Destructor Documentation
tuttle::host::ofx::property::OfxhSet::OfxhSet (const OfxhPropSpec spec[])
take an array of of PropSpecs (which must be terminated with an entry in which ->name is null), and turn these into a Set
Definition at line 210 of file OfxhSet.cpp.
References addProperties().
tuttle::host::ofx::property::OfxhSet::OfxhSet (const OfxhSet & other)
deep copies the property set
Definition at line 217 of file OfxhSet.cpp.
References operator=().
tuttle::host::ofx::property::OfxhSet::OfxhSet ()
empty ctor
Definition at line 205 of file OfxhSet.cpp.
tuttle::host::ofx::property::OfxhSet::~OfxhSet () [virtual]
destructor
Definition at line 223 of file OfxhSet.cpp.
References clear().
Member Function Documentation
void tuttle::host::ofx::property::OfxhSet::addNotifyHook (const std::string & s, OfxhNotifyHook * hook)
add a set hook for a particular property. users may need to call particular specialised versions of this.
add a notify hook for a particular property. users may need to call particular specialised versions of this.
Definition at line 96 of file OfxhSet.cpp.
References tuttle::host::ofx::property::OfxhProperty::addNotifyHook(), and fetchLocalProperty().
Referenced by tuttle::host::ofx::attribute::OfxhParam::OfxhParam(), tuttle::host::ofx::attribute::OfxhParamDouble::OfxhParamDouble(), and tuttle::host::ofx::attribute::OfxhParamInteger::OfxhParamInteger().
void tuttle::host::ofx::property::OfxhSet::addProperties (const OfxhPropSpec *)
adds a bunch of properties from PropSpec
Definition at line 159 of file OfxhSet.cpp.
References createProperty(), and tuttle::host::ofx::property::OfxhPropSpec::name.
Referenced by tuttle::host::ofx::attribute::OfxhClipImageDescriptor::init(), tuttle::host::ofx::attribute::OfxhParamDescriptor::initInteractParamProps(), tuttle::host::ofx::attribute::OfxhParamDescriptor::initNoValueParamProps(), tuttle::host::ofx::attribute::OfxhParamDescriptor::initNumericParamProps(), tuttle::host::ofx::attribute::OfxhParamDescriptor::initStandardParamProps(), tuttle::host::ofx::attribute::OfxhParamDescriptor::initValueParamProps(), tuttle::host::ofx::attribute::OfxhAttributeDescriptor::OfxhAttributeDescriptor(), tuttle::host::ofx::attribute::OfxhClip::OfxhClip(), tuttle::host::ofx::attribute::OfxhClipDescriptor::OfxhClipDescriptor(), tuttle::host::ofx::attribute::OfxhClipImage::OfxhClipImage(), tuttle::host::ofx::imageEffect::OfxhImageEffectHost::OfxhImageEffectHost(), tuttle::host::ofx::attribute::OfxhParamDescriptor::OfxhParamDescriptor(), OfxhSet(), operator+=(), and tuttle::host::ofx::imageEffect::OfxhImageEffectNode::setupClipPreferencesArgs().
void tuttle::host::ofx::property::OfxhSet::addProperty (OfxhProperty * prop)
add one new property (takes ownership)
add one new property
Definition at line 195 of file OfxhSet.cpp.
References _props, and tuttle::host::ofx::property::OfxhProperty::getName().
const OfxhProperty & tuttle::host::ofx::property::OfxhSet::at (const int index) const
Definition at line 71 of file OfxhSet.cpp.
References _chainedSet, _props, at(), and getLocalSize().
Referenced by at().
void tuttle::host::ofx::property::OfxhSet::clear ()
Definition at line 228 of file OfxhSet.cpp.
References _props.
Referenced by ~OfxhSet().
void tuttle::host::ofx::property::OfxhSet::copyValues (const This & other)
Definition at line 261 of file OfxhSet.cpp.
References _props, tuttle::host::ofx::property::OfxhProperty::copyValues(), and tuttle::host::ofx::property::OfxhProperty::getName().
Referenced by tuttle::host::ofx::attribute::OfxhAttribute::copyValues().
void tuttle::host::ofx::property::OfxhSet::createProperty (const OfxhPropSpec & spec)
add one new property
Definition at line 131 of file OfxhSet.cpp.
References _props, tuttle::host::ofx::property::OfxhPropSpec::defaultValue, tuttle::host::ofx::property::OfxhPropSpec::dimension, tuttle::host::ofx::property::ePropTypeDouble, tuttle::host::ofx::property::ePropTypeInt, tuttle::host::ofx::property::ePropTypeNone, tuttle::host::ofx::property::ePropTypePointer, tuttle::host::ofx::property::ePropTypeString, tuttle::host::ofx::property::mapTypeEnumToString(), tuttle::host::ofx::property::OfxhPropSpec::name, tuttle::host::ofx::property::OfxhPropSpec::readonly, and tuttle::host::ofx::property::OfxhPropSpec::type.
Referenced by addProperties(), tuttle::host::ofx::imageEffect::OfxhImageEffectNode::getFramesNeededAction(), tuttle::host::ofx::imageEffect::OfxhImageEffectNode::getRegionOfInterestAction(), and tuttle::host::ofx::imageEffect::OfxhImageEffectNode::setupClipPreferencesArgs().
void tuttle::host::ofx::property::OfxhSet::eraseProperty (const std::string & propName)
Definition at line 168 of file OfxhSet.cpp.
References _props.
const Double& tuttle::host::ofx::property::OfxhSet::fetchDoubleProperty (const std::string & name) const [inline]
Definition at line 240 of file OfxhSet.hpp.
Referenced by tuttle::host::ofx::imageEffect::OfxhImageEffectNode::setupClipInstancePreferences().
const Int& tuttle::host::ofx::property::OfxhSet::fetchIntProperty (const std::string & name) const [inline]
Definition at line 216 of file OfxhSet.hpp.
Referenced by tuttle::host::ofx::imageEffect::OfxhImageEffectNode::getFramesNeeded().
Double& tuttle::host::ofx::property::OfxhSet::fetchLocalDoubleProperty (const std::string & name) [inline]
Definition at line 245 of file OfxhSet.hpp.
Referenced by tuttle::host::ofx::attribute::OfxhClipImage::setPixelAspectRatio().
const Double& tuttle::host::ofx::property::OfxhSet::fetchLocalDoubleProperty (const std::string & name) const [inline]
Definition at line 250 of file OfxhSet.hpp.
References fetchLocalDoubleProperty().
Referenced by fetchLocalDoubleProperty().
Int& tuttle::host::ofx::property::OfxhSet::fetchLocalIntProperty (const std::string & name) [inline]
Definition at line 221 of file OfxhSet.hpp.
const Int& tuttle::host::ofx::property::OfxhSet::fetchLocalIntProperty (const std::string & name) const [inline]
Definition at line 226 of file OfxhSet.hpp.
References fetchLocalIntProperty().
Referenced by fetchLocalIntProperty().
Pointer& tuttle::host::ofx::property::OfxhSet::fetchLocalPointerProperty (const std::string & name) [inline]
Definition at line 233 of file OfxhSet.hpp.
const Pointer& tuttle::host::ofx::property::OfxhSet::fetchLocalPointerProperty (const std::string & name) const [inline]
Definition at line 238 of file OfxhSet.hpp.
References fetchLocalPointerProperty().
Referenced by fetchLocalPointerProperty().
OfxhProperty & tuttle::host::ofx::property::OfxhSet::fetchLocalProperty (const std::string & name)
Definition at line 101 of file OfxhSet.cpp.
References _props.
Referenced by addNotifyHook(), fetchLocalTypedProperty(), and setGetHook().
const OfxhProperty& tuttle::host::ofx::property::OfxhSet::fetchLocalProperty (const std::string & name) const [inline]
Definition at line 179 of file OfxhSet.hpp.
References fetchLocalProperty().
Referenced by fetchLocalProperty().
String& tuttle::host::ofx::property::OfxhSet::fetchLocalStringProperty (const std::string & name) [inline]
Definition at line 209 of file OfxhSet.hpp.
Referenced by tuttle::host::ofx::attribute::OfxhClipImage::setBitDepthString(), tuttle::host::ofx::attribute::OfxhClipImage::setBitDepthStringIfUpper(), tuttle::host::ofx::attribute::OfxhClipImage::setBitDepthStringIfUpperAndNotModifiedByPlugin(), tuttle::host::ofx::attribute::OfxhClipImage::setComponentsString(), and tuttle::host::ofx::attribute::OfxhClipImage::setComponentsStringIfNotModifiedByPlugin().
const String& tuttle::host::ofx::property::OfxhSet::fetchLocalStringProperty (const std::string & name) const [inline]
Definition at line 214 of file OfxhSet.hpp.
References fetchLocalStringProperty().
Referenced by fetchLocalStringProperty().
template<class T > T& tuttle::host::ofx::property::OfxhSet::fetchLocalTypedProperty (const std::string & name) [inline]
Definition at line 192 of file OfxhSet.hpp.
References fetchLocalProperty().
template<class T > const T& tuttle::host::ofx::property::OfxhSet::fetchLocalTypedProperty (const std::string & name) const [inline]
Definition at line 198 of file OfxhSet.hpp.
const Pointer& tuttle::host::ofx::property::OfxhSet::fetchPointerProperty (const std::string & name) const [inline]
Definition at line 228 of file OfxhSet.hpp.
const OfxhProperty & tuttle::host::ofx::property::OfxhSet::fetchProperty (const std::string & name) const
Fetchs a reference to a property of the given name, following the property chain if the 'followChain' arg is not false.
Definition at line 112 of file OfxhSet.cpp.
References _chainedSet, _props, and fetchProperty().
Referenced by fetchProperty(), fetchTypedProperty(), and getDimension().
const String& tuttle::host::ofx::property::OfxhSet::fetchStringProperty (const std::string & name) const [inline]
Definition at line 204 of file OfxhSet.hpp.
Referenced by findStringPropValueIndex(), tuttle::host::ofx::attribute::OfxhParamChoice::getChoiceKeys(), tuttle::host::ofx::attribute::OfxhClipImageAccessor::getSupportedComponents(), and tuttle::host::ofx::imageEffect::OfxhImageEffectNode::setupClipInstancePreferences().
template<class T > const T& tuttle::host::ofx::property::OfxhSet::fetchTypedProperty (const std::string & name) const [inline]
get property with the particular name and type. if the property is missing or is of the wrong type, return an error status. if this is a sloppy property set and the property is missing, a new one will be created of the right type
Definition at line 186 of file OfxhSet.hpp.
References fetchProperty().
int tuttle::host::ofx::property::OfxhSet::findStringPropValueIndex (const std::string & propName, const std::string & propValue) const
is the given string one of the values of a multi-dimensional string prop this returns a non negative index if it is found, otherwise, -1
Definition at line 358 of file OfxhSet.cpp.
References fetchStringProperty(), and tuttle::host::ofx::property::OfxhPropertyTemplate< T >::getValues().
Referenced by tuttle::host::ofx::imageEffect::OfxhImageEffectNodeBase::isBitDepthSupported(), tuttle::host::ofx::imageEffect::OfxhImageEffectNodeBase::isClipPreferencesSlaveParam(), tuttle::host::ofx::imageEffect::OfxhImageEffectNodeBase::isContextSupported(), tuttle::host::ofx::imageEffect::OfxhImageEffectNode::isSupportedBitDepth(), and tuttle::host::ofx::attribute::OfxhClipImageAccessor::isSupportedComponent().
const OfxhSet& tuttle::host::ofx::property::OfxhSet::getChainedSet () const [inline]
Definition at line 161 of file OfxhSet.hpp.
References _chainedSet.
size_t tuttle::host::ofx::property::OfxhSet::getDimension (const std::string & property) const [inline]
get the dimension of a particular property
Definition at line 305 of file OfxhSet.hpp.
References fetchProperty(), and tuttle::host::ofx::property::OfxhProperty::getDimension().
Referenced by tuttle::host::ofx::attribute::OfxhParamPage::getChildren(), tuttle::host::ofx::imageEffect::OfxhImageEffectNode::getFramesNeededAction(), tuttle::host::ofx::interact::OfxhInteract::getSlaveToParam(), tuttle::host::ofx::imageEffect::OfxhImageEffectPlugin::initContexts(), tuttle::host::ofx::imageEffect::OfxhImageEffectPluginCache::loadFromPlugin(), and tuttle::host::ofx::imageEffect::OfxhImageEffectNode::upperGetDimension().
double tuttle::host::ofx::property::OfxhSet::getDoubleProperty (const std::string & property, int index = 0) const
get the value of a particular double property
get a particular double property
Definition at line 329 of file OfxhSet.cpp.
Referenced by BOOST_AUTO_TEST_CASE(), tuttle::host::ofx::attribute::OfxhClipImage::getContinuousSamples(), tuttle::host::ofx::attribute::OfxhClipImage::getFrameRange(), tuttle::host::ofx::attribute::OfxhClipImage::getFrameRate(), tuttle::host::ofx::imageEffect::OfxhImageEffectNode::getFramesNeededAction(), tuttle::host::ofx::attribute::OfxhClipImage::getPixelAspectRatio(), tuttle::host::ofx::imageEffect::OfxhImageEffectNode::getRegionOfInterestAction(), tuttle::host::ofx::imageEffect::OfxhImageEffectNode::getTimeDomainAction(), tuttle::host::ofx::attribute::OfxhClipImage::getUnmappedFrameRange(), tuttle::host::ofx::attribute::OfxhClipImage::getUnmappedFrameRate(), tuttle::host::ofx::imageEffect::OfxhImage::initClipBits(), tuttle::host::ofx::imageEffect::OfxhImageEffectNode::isIdentityAction(), and tuttle::host::ofx::imageEffect::OfxhImageEffectNode::setupClipInstancePreferences().
void tuttle::host::ofx::property::OfxhSet::getDoublePropertyN (const std::string & property, double * v, int N) const
get the value of a particular double property
Definition at line 336 of file OfxhSet.cpp.
Referenced by tuttle::host::ofx::imageEffect::OfxhImageEffectNode::getRegionOfDefinitionAction().
double tuttle::host::ofx::property::OfxhSet::getDoublePropertyRaw (const std::string & property, int index = 0) const
get a particular double property without fetching via a get hook, useful for notifies
get a particular double property
Definition at line 293 of file OfxhSet.cpp.
OfxPropertySetHandle tuttle::host::ofx::property::OfxhSet::getHandle () const [inline]
get a handle on this object for passing to the C API
Definition at line 313 of file OfxhSet.hpp.
Referenced by tuttle::host::ofx::interact::OfxhInteract::callEntry(), tuttle::host::ofx::imageEffect::OfxhImageEffectPlugin::describeInContextAction(), tuttle::host::ofx::interact::OfxhInteractDescriptor::getPropHandle(), tuttle::host::ofx::attribute::OfxhAttributeAccessor::getPropHandle(), tuttle::host::ofx::imageEffect::OfxhImage::getPropHandle(), tuttle::host::ofx::interact::OfxhInteract::getPropHandle(), tuttle::host::ofx::imageEffect::OfxhImageEffectNode::mainEntry(), and tuttle::host::ofx::OfxhHost::OfxhHost().
int tuttle::host::ofx::property::OfxhSet::getIntProperty (const std::string & property, int index = 0) const
get the value of a particular int property
get a particular int property
Definition at line 315 of file OfxhSet.cpp.
Referenced by BOOST_AUTO_TEST_CASE(), tuttle::host::ofx::imageEffect::OfxhImageEffectNode::canCurrentlyHandleMultipleClipDepths(), tuttle::host::ofx::imageEffect::OfxhImageEffectNodeBase::fieldRenderTwiceAlways(), tuttle::host::ofx::attribute::OfxhParamAccessor::getCanAnimate(), tuttle::host::ofx::attribute::OfxhParamAccessor::getCanUndo(), tuttle::host::ofx::attribute::OfxhParamAccessor::getEnabled(), tuttle::host::ofx::attribute::OfxhParamAccessor::getEvaluateOnChange(), tuttle::host::ofx::imageEffect::OfxhImageEffectNodeBase::getHostFrameThreading(), tuttle::host::ofx::imageEffect::OfxhImage::getRowBytes(), tuttle::host::ofx::attribute::OfxhParamAccessor::getSecret(), tuttle::host::ofx::attribute::OfxhClipAccessor::isConnected(), tuttle::host::ofx::attribute::OfxhClipImageAccessor::isMask(), tuttle::host::ofx::attribute::OfxhClipAccessor::isOptional(), tuttle::host::ofx::imageEffect::OfxhImageEffectNodeBase::isSingleInstance(), tuttle::host::ofx::imageEffect::OfxhImageEffectNode::OfxhImageEffectNode(), tuttle::host::ofx::imageEffect::OfxhImageEffectNode::setupClipInstancePreferences(), tuttle::host::ofx::imageEffect::OfxhImageEffectNodeBase::supportsMultipleClipDepths(), tuttle::host::ofx::imageEffect::OfxhImageEffectNodeBase::supportsMultipleClipPARs(), tuttle::host::ofx::imageEffect::OfxhImageEffectNodeBase::supportsMultiResolution(), tuttle::host::ofx::attribute::OfxhClipImageAccessor::supportsTiles(), tuttle::host::ofx::imageEffect::OfxhImageEffectNodeBase::supportsTiles(), tuttle::host::ofx::attribute::OfxhClipImageAccessor::temporalAccess(), and tuttle::host::ofx::imageEffect::OfxhImageEffectNodeBase::temporalAccess().
void tuttle::host::ofx::property::OfxhSet::getIntPropertyN (const std::string & property, int * v, int N) const
get the value of a particular double property
Definition at line 322 of file OfxhSet.cpp.
Referenced by BOOST_AUTO_TEST_CASE(), tuttle::host::ofx::imageEffect::OfxhImage::getBounds(), and tuttle::host::ofx::imageEffect::OfxhImage::getROD().
int tuttle::host::ofx::property::OfxhSet::getIntPropertyRaw (const std::string & property, int index = 0) const
get a particular int property without fetching via a get hook, useful for notifies
get a particular int property
Definition at line 286 of file OfxhSet.cpp.
size_t tuttle::host::ofx::property::OfxhSet::getLocalSize () const [inline]
Definition at line 119 of file OfxhSet.hpp.
References _props.
Referenced by at(), getSize(), and localAt().
const PropertyMap& tuttle::host::ofx::property::OfxhSet::getMap () const [inline]
grab the internal properties map
Definition at line 164 of file OfxhSet.hpp.
References _props.
PropertyMap& tuttle::host::ofx::property::OfxhSet::getMap () [inline]
Definition at line 165 of file OfxhSet.hpp.
References _props.
void * tuttle::host::ofx::property::OfxhSet::getPointerProperty (const std::string & property, int index = 0) const
get the value of a particular pointer property
get a particular double property
Definition at line 343 of file OfxhSet.cpp.
Referenced by tuttle::host::ofx::fetchSuite(), tuttle::host::ofx::imageEffect::OfxhImageEffectNodeBase::getOverlayInteractMainEntry(), and tuttle::host::ofx::interact::OfxhInteract::initArgProp().
void * tuttle::host::ofx::property::OfxhSet::getPointerPropertyRaw (const std::string & property, int index = 0) const
get a particular pointer property without fetching via a get hook, useful for notifies
get a particular double property
Definition at line 300 of file OfxhSet.cpp.
template<class T > T::ReturnType tuttle::host::ofx::property::OfxhSet::getProperty (const std::string & property, int index) const [protected]
get a particular property
Definition at line 376 of file OfxhSet.hpp.
template<class T > void tuttle::host::ofx::property::OfxhSet::getPropertyN (const std::string & property, int index, typename T::APIType * v) const [protected]
get the first N of a particular property
get a particular property
Definition at line 391 of file OfxhSet.hpp.
template<class T > T::ReturnType tuttle::host::ofx::property::OfxhSet::getPropertyRaw (const std::string & property, int index) const [protected]
get a particular property without going through any getHook
get a particular property
Definition at line 399 of file OfxhSet.hpp.
template<class T > void tuttle::host::ofx::property::OfxhSet::getPropertyRawN (const std::string & property, int count, typename T::APIType * v) const [protected]
get a particular property without going through any getHook
get a particular property
Definition at line 407 of file OfxhSet.hpp.
size_t tuttle::host::ofx::property::OfxhSet::getSize () const [inline]
Definition at line 120 of file OfxhSet.hpp.
References _chainedSet, getLocalSize(), and getSize().
Referenced by getSize(), localAt(), and operator==().
const std::string & tuttle::host::ofx::property::OfxhSet::getStringProperty (const std::string & property, int index = 0) const
get the value of a particular string property
get a particular double property
Definition at line 350 of file OfxhSet.cpp.
Referenced by BOOST_AUTO_TEST_CASE(), tuttle::host::ofx::attribute::OfxhAttributeAccessor::getAttributeType(), tuttle::host::ofx::imageEffect::OfxhImage::getBitDepth(), tuttle::host::ofx::attribute::OfxhClipImage::getBitDepthString(), tuttle::host::ofx::attribute::OfxhParamAccessor::getCacheInvalidation(), tuttle::host::ofx::attribute::OfxhParamPage::getChildren(), tuttle::host::ofx::attribute::OfxhClipImage::getComponentsString(), tuttle::host::ofx::imageEffect::OfxhImage::getComponentsType(), tuttle::host::ofx::attribute::OfxhParamAccessor::getDoubleType(), tuttle::host::ofx::attribute::OfxhClipImageAccessor::getFieldExtraction(), tuttle::host::ofx::attribute::OfxhClipImage::getFieldExtraction(), tuttle::host::ofx::attribute::OfxhClipImage::getFieldOrder(), tuttle::host::ofx::attribute::OfxhParamAccessor::getHint(), tuttle::host::ofx::imageEffect::OfxhImageEffectNodeBase::getLabel(), tuttle::host::ofx::attribute::OfxhAttributeAccessor::getLabel(), tuttle::host::ofx::imageEffect::OfxhImageEffectNodeBase::getLongLabel(), tuttle::host::ofx::attribute::OfxhAttributeAccessor::getLongLabel(), tuttle::host::ofx::attribute::OfxhAttributeAccessor::getName(), tuttle::host::ofx::imageEffect::OfxhImageEffectNodeBase::getName(), tuttle::host::ofx::attribute::OfxhParamAccessor::getParamType(), tuttle::host::ofx::attribute::OfxhParamAccessor::getParentName(), tuttle::host::ofx::imageEffect::OfxhImageEffectPluginCache::getPluginByLabel(), tuttle::host::ofx::imageEffect::OfxhImageEffectNodeBase::getPluginGrouping(), tuttle::host::ofx::attribute::OfxhClipImage::getPremult(), tuttle::host::ofx::imageEffect::OfxhImageEffectNodeBase::getRenderThreadSafety(), tuttle::host::ofx::attribute::OfxhParamAccessor::getScriptName(), tuttle::host::ofx::imageEffect::OfxhImageEffectNodeBase::getShortLabel(), tuttle::host::ofx::attribute::OfxhAttributeAccessor::getShortLabel(), tuttle::host::ofx::interact::OfxhInteract::getSlaveToParam(), tuttle::host::ofx::attribute::OfxhParamString::getStringMode(), tuttle::host::ofx::attribute::OfxhClipImage::getUnmappedBitDepth(), tuttle::host::ofx::attribute::OfxhClipImage::getUnmappedComponents(), tuttle::host::ofx::imageEffect::OfxhImage::initClipBits(), tuttle::host::ofx::imageEffect::OfxhImageEffectPlugin::initContexts(), tuttle::host::ofx::imageEffect::OfxhImageEffectNode::isIdentityAction(), tuttle::host::ofx::imageEffect::OfxhImageEffectPluginCache::loadFromPlugin(), setProperty(), setPropertyN(), and tuttle::host::ofx::imageEffect::OfxhImageEffectNode::setupClipInstancePreferences().
const std::string & tuttle::host::ofx::property::OfxhSet::getStringPropertyRaw (const std::string & property, int index = 0) const
get a particular string property
get a particular double property
Todo:
tuttle: return const no ?
Definition at line 307 of file OfxhSet.cpp.
bool tuttle::host::ofx::property::OfxhSet::hasLocalProperty (const std::string & propName) const
Definition at line 187 of file OfxhSet.cpp.
References hasProperty().
bool tuttle::host::ofx::property::OfxhSet::hasProperty (const std::string & propName, bool followChain = true) const
Definition at line 173 of file OfxhSet.cpp.
References _chainedSet, _props, and hasProperty().
Referenced by hasLocalProperty(), and hasProperty().
OfxhProperty & tuttle::host::ofx::property::OfxhSet::localAt (const int index)
Definition at line 50 of file OfxhSet.cpp.
References _props, getLocalSize(), and getSize().
bool tuttle::host::ofx::property::OfxhSet::operator!= (const This & other) const [inline]
Definition at line 131 of file OfxhSet.hpp.
References operator==().
OfxhSet& tuttle::host::ofx::property::OfxhSet::operator+= (const OfxhPropSpec * p) [inline]
Definition at line 150 of file OfxhSet.hpp.
References addProperties().
OfxhSet & tuttle::host::ofx::property::OfxhSet::operator= (const This & other)
Definition at line 233 of file OfxhSet.cpp.
References _chainedSet, and _props.
Referenced by OfxhSet().
bool tuttle::host::ofx::property::OfxhSet::operator== (const This & other) const
Definition at line 240 of file OfxhSet.cpp.
References _chainedSet, _props, and getSize().
Referenced by operator!=().
template<class Archive > void tuttle::host::ofx::property::OfxhSet::serialize (Archive & ar, const unsigned int version) [inline, private]
Definition at line 321 of file OfxhSet.hpp.
References _props.
void tuttle::host::ofx::property::OfxhSet::setChainedSet (const OfxhSet *const s) [inline]
set the chained property set
Definition at line 159 of file OfxhSet.hpp.
References _chainedSet.
Referenced by tuttle::host::ofx::imageEffect::OfxhImageEffectNode::OfxhImageEffectNode(), and tuttle::host::ofx::interact::OfxhInteract::OfxhInteract().
void tuttle::host::ofx::property::OfxhSet::setDoubleProperty (const std::string & property, double v, int index = 0) [inline]
get a particular double property
Definition at line 296 of file OfxhSet.hpp.
Referenced by tuttle::host::ofx::imageEffect::OfxhImageEffectNode::beginSequenceRenderAction(), tuttle::host::ofx::imageEffect::OfxhImageEffectNode::clipInstanceChangedAction(), tuttle::host::ofx::imageEffect::OfxhImageEffectNode::endSequenceRenderAction(), tuttle::host::ofx::imageEffect::OfxhImageEffectNode::getFramesNeededAction(), tuttle::host::ofx::imageEffect::OfxhImageEffectNode::getRegionOfDefinitionAction(), tuttle::host::ofx::imageEffect::OfxhImageEffectNode::getRegionOfInterestAction(), tuttle::host::ofx::imageEffect::OfxhImageEffectNode::getTimeDomainAction(), tuttle::host::attribute::Image::Image(), tuttle::host::ofx::interact::OfxhInteract::initArgProp(), tuttle::host::ofx::imageEffect::OfxhImage::initClipBits(), tuttle::host::ofx::imageEffect::OfxhImageEffectNode::isIdentityAction(), tuttle::host::ofx::imageEffect::OfxhImageEffectNode::paramInstanceChangedAction(), tuttle::host::ofx::imageEffect::OfxhImageEffectNode::renderAction(), tuttle::host::ofx::interact::OfxhInteract::setPenArgProps(), and tuttle::host::ofx::imageEffect::OfxhImageEffectNode::setupClipPreferencesArgs().
void tuttle::host::ofx::property::OfxhSet::setDoublePropertyN (const std::string & property, const double * v, int N) [inline]
get a particular double property
Definition at line 299 of file OfxhSet.hpp.
Referenced by tuttle::host::ofx::imageEffect::OfxhImageEffectNode::beginSequenceRenderAction(), BOOST_AUTO_TEST_CASE(), tuttle::host::ofx::imageEffect::OfxhImageEffectNode::clipInstanceChangedAction(), tuttle::host::ofx::imageEffect::OfxhImageEffectNode::endSequenceRenderAction(), tuttle::host::ofx::imageEffect::OfxhImageEffectNode::getRegionOfDefinitionAction(), tuttle::host::ofx::imageEffect::OfxhImageEffectNode::getRegionOfInterestAction(), tuttle::host::ofx::interact::OfxhInteract::initArgProp(), tuttle::host::ofx::imageEffect::OfxhImageEffectNode::isIdentityAction(), tuttle::host::ofx::imageEffect::OfxhImageEffectNode::paramInstanceChangedAction(), tuttle::host::ofx::imageEffect::OfxhImageEffectNode::renderAction(), and tuttle::host::ofx::interact::OfxhInteract::setPenArgProps().
void tuttle::host::ofx::property::OfxhSet::setGetHook (const std::string & s, OfxhGetHook * ghook)
set the get hook for a particular property. users may need to call particular specialised versions of this.
Definition at line 87 of file OfxhSet.cpp.
References fetchLocalProperty(), and tuttle::host::ofx::property::OfxhProperty::setGetHook().
Referenced by tuttle::host::ofx::imageEffect::OfxhImageEffectNode::initHook().
void tuttle::host::ofx::property::OfxhSet::setIntProperty (const std::string & property, int v, int index = 0) [inline]
set a particular int property
Definition at line 287 of file OfxhSet.hpp.
Referenced by tuttle::host::ofx::imageEffect::OfxhImageEffectNode::beginSequenceRenderAction(), BOOST_AUTO_TEST_CASE(), tuttle::host::ofx::interact::OfxhInteractDescriptor::describe(), tuttle::host::ofx::imageEffect::OfxhImageEffectNode::endSequenceRenderAction(), tuttle::host::attribute::Image::Image(), tuttle::host::ofx::imageEffect::OfxhImageEffectNode::OfxhImageEffectNode(), tuttle::host::ofx::attribute::OfxhClipAccessor::setConnected(), and tuttle::host::ofx::interact::OfxhInteract::setKeyArgProps().
void tuttle::host::ofx::property::OfxhSet::setIntPropertyN (const std::string & property, const int * v, int N) [inline]
set a particular double property
Definition at line 290 of file OfxhSet.hpp.
Referenced by tuttle::host::ofx::interact::OfxhInteract::initArgProp(), tuttle::host::ofx::imageEffect::OfxhImageEffectNode::isIdentityAction(), tuttle::host::ofx::imageEffect::OfxhImageEffectNode::renderAction(), and tuttle::host::ofx::interact::OfxhInteract::setPenArgProps().
void tuttle::host::ofx::property::OfxhSet::setPointerProperty (const std::string & property, void * v, int index = 0) [inline]
get a particular double property
Definition at line 302 of file OfxhSet.hpp.
Referenced by tuttle::host::ofx::interact::OfxhInteract::initArgProp(), tuttle::host::ofx::OfxhHost::OfxhHost(), tuttle::host::ofx::imageEffect::OfxhImageEffectNode::OfxhImageEffectNode(), tuttle::host::ofx::interact::OfxhInteract::OfxhInteract(), and tuttle::host::attribute::Image::setPoolData().
template<class T > void tuttle::host::ofx::property::OfxhSet::setProperty (const std::string & property, int index, const typename T::Type & value) [protected]
set a particular property
Definition at line 330 of file OfxhSet.hpp.
References getStringProperty(), TUTTLE_LOG_ERROR, and TUTTLE_LOG_EXCEPTION.
template<class T > void tuttle::host::ofx::property::OfxhSet::setPropertyN (const std::string & property, int count, const typename T::APIType * value) [protected]
set the first N of a particular property
set a particular property
Definition at line 354 of file OfxhSet.hpp.
References getStringProperty(), TUTTLE_LOG_ERROR, and TUTTLE_LOG_EXCEPTION.
void tuttle::host::ofx::property::OfxhSet::setStringProperty (const std::string & property, const std::string & value, int index = 0) [inline]
set a particular string property without fetching via a get hook, useful for notifies
Definition at line 284 of file OfxhSet.hpp.
Referenced by BOOST_AUTO_TEST_CASE(), tuttle::host::ofx::attribute::OfxhClipImageDescriptor::init(), tuttle::host::ofx::imageEffect::OfxhImage::initClipBits(), tuttle::host::ofx::attribute::OfxhParamDescriptor::initNumericParamProps(), tuttle::host::ofx::imageEffect::OfxhImageEffectNode::isIdentityAction(), tuttle::host::ofx::imageEffect::OfxhImageEffectNode::OfxhImageEffectNode(), tuttle::host::ofx::imageEffect::OfxhImageEffectNodeDescriptor::OfxhImageEffectNodeDescriptor(), tuttle::host::ofx::attribute::OfxhParamDescriptor::OfxhParamDescriptor(), tuttle::host::ofx::imageEffect::OfxhImageEffectNode::renderAction(), tuttle::host::ofx::interact::OfxhInteract::setKeyArgProps(), tuttle::host::ofx::attribute::OfxhAttributeAccessor::setLabel(), tuttle::host::ofx::attribute::OfxhAttributeAccessor::setLongLabel(), tuttle::host::ofx::attribute::OfxhAttributeAccessor::setName(), tuttle::host::ofx::imageEffect::OfxhImageEffectNodeBase::setName(), tuttle::host::ofx::attribute::OfxhAttributeAccessor::setShortLabel(), and tuttle::host::ofx::imageEffect::OfxhImageEffectNode::setupClipPreferencesArgs().
bool tuttle::host::ofx::property::OfxhSet::verifyMagic () [inline]
is this a nice property set, or a dodgy pointer passed back to us
Definition at line 316 of file OfxhSet.hpp.
References _magic, and kMagic.
Friends And Related Function Documentation
friend class boost::serialization::access [friend]
Definition at line 319 of file OfxhSet.hpp.
std::ostream& operator<< (std::ostream & os, const This & g) [friend]
Definition at line 372 of file OfxhSet.cpp.
Field Documentation
const OfxhSet* tuttle::host::ofx::property::OfxhSet::_chainedSet [protected]
chained property set, which is read only these are searched on a get if not found on a local search
Definition at line 76 of file OfxhSet.hpp.
Referenced by at(), fetchProperty(), getChainedSet(), getSize(), hasProperty(), operator=(), operator==(), and setChainedSet().
const int tuttle::host::ofx::property::OfxhSet::_magic [private]
to check for handles being nice
Definition at line 68 of file OfxhSet.hpp.
Referenced by verifyMagic().
PropertyMap tuttle::host::ofx::property::OfxhSet::_props [protected]
Our properties.
Definition at line 71 of file OfxhSet.hpp.
Referenced by addProperty(), at(), clear(), copyValues(), createProperty(), eraseProperty(), fetchLocalProperty(), fetchProperty(), getLocalSize(), getMap(), hasProperty(), localAt(), tuttle::host::ofx::property::operator<<(), operator=(), operator==(), and serialize().
const int tuttle::host::ofx::property::OfxhSet::kMagic = 0x12082007 [static, private]
magic number for property sets, and Connie's birthday :-)
Definition at line 67 of file OfxhSet.hpp.
Referenced by verifyMagic().
The documentation for this class was generated from the following files:
TuttleOFX/libraries/tuttle/src/tuttle/host/ofx/property/OfxhSet.hpp
TuttleOFX/libraries/tuttle/src/tuttle/host/ofx/property/OfxhSet.cpp