TuttleOFX: TuttleOFX/libraries/tuttle/src/tuttle/test/io/writer.hpp File Reference
TuttleOFX/libraries/tuttle/src/tuttle/test/io/writer.hpp File Reference
#include <iostream>
#include <boost/filesystem/path.hpp>
Functions
BOOST_AUTO_TEST_CASE (process_writer)
BOOST_AUTO_TEST_CASE (process_unconnected)
Function Documentation
BOOST_AUTO_TEST_CASE (process_writer)
Definition at line 9 of file writer.hpp.
References tuttle::host::Graph::compute(), tuttle::host::Graph::connect(), tuttle::host::Graph::createNode(), tuttle::host::memory::MemoryCache::get(), tuttle::host::INode::getName(), tuttle::host::INode::getParam(), tuttle::host::ofx::attribute::OfxhParam::setValue(), TUTTLE_INFO, TUTTLE_LOG_INFO, and TUTTLE_TLOG_VAR.
BOOST_AUTO_TEST_CASE (process_unconnected)
Definition at line 59 of file writer.hpp.
References tuttle::host::Graph::compute(), tuttle::host::Graph::createNode(), tuttle::host::INode::getParam(), tuttle::host::ofx::attribute::OfxhParam::setValue(), and TUTTLE_LOG_INFO.