TuttleOFX: tuttle::host::ofx::attribute::OfxhClipDescriptor Class Reference
tuttle::host::ofx::attribute::OfxhClipDescriptor Class Reference
#include <OfxhClipDescriptor.hpp>
Public Types
typedef OfxhClipDescriptor This
Public Member Functions
OfxhClipDescriptor ()
constructor
OfxhClipDescriptor (const property::OfxhSet &)
virtual ~OfxhClipDescriptor ()=0
bool operator== (const This &other) const
bool operator!= (const This &other) const
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Friends
class boost::serialization::access
Detailed Description
a clip descriptor
Definition at line 16 of file OfxhClipDescriptor.hpp.
Member Typedef Documentation
typedef OfxhClipDescriptor tuttle::host::ofx::attribute::OfxhClipDescriptor::This
Reimplemented from tuttle::host::ofx::attribute::OfxhAttributeDescriptor.
Reimplemented in tuttle::host::ofx::attribute::OfxhClipImageDescriptor.
Definition at line 21 of file OfxhClipDescriptor.hpp.
Constructor & Destructor Documentation
tuttle::host::ofx::attribute::OfxhClipDescriptor::OfxhClipDescriptor ()
constructor
descriptor
properties common to the desciptor and instance the desc and set them, the instance cannot
Definition at line 11 of file OfxhClipDescriptor.cpp.
References tuttle::host::ofx::property::OfxhSet::addProperties(), tuttle::host::ofx::property::ePropTypeInt, tuttle::host::ofx::property::ePropTypeString, and tuttle::host::ofx::attribute::OfxhAttributeDescriptor::getEditableProperties().
tuttle::host::ofx::attribute::OfxhClipDescriptor::OfxhClipDescriptor (const property::OfxhSet & properties)
descriptor
properties common to the desciptor and instance the desc and set them, the instance cannot
Definition at line 28 of file OfxhClipDescriptor.cpp.
References tuttle::host::ofx::property::OfxhSet::addProperties(), tuttle::host::ofx::property::ePropTypeInt, tuttle::host::ofx::property::ePropTypeString, and tuttle::host::ofx::attribute::OfxhAttributeDescriptor::getEditableProperties().
tuttle::host::ofx::attribute::OfxhClipDescriptor::~OfxhClipDescriptor () [pure virtual]
Definition at line 42 of file OfxhClipDescriptor.cpp.
Member Function Documentation
bool tuttle::host::ofx::attribute::OfxhClipDescriptor::operator!= (const This & other) const [inline]
Reimplemented from tuttle::host::ofx::attribute::OfxhAttributeDescriptor.
Reimplemented in tuttle::host::ofx::attribute::OfxhClipImageDescriptor.
Definition at line 37 of file OfxhClipDescriptor.hpp.
References operator==().
bool tuttle::host::ofx::attribute::OfxhClipDescriptor::operator== (const This & other) const [inline]
Reimplemented from tuttle::host::ofx::attribute::OfxhAttributeDescriptor.
Reimplemented in tuttle::host::ofx::attribute::OfxhClipImageDescriptor.
Definition at line 30 of file OfxhClipDescriptor.hpp.
Referenced by operator!=().
template<class Archive > void tuttle::host::ofx::attribute::OfxhClipDescriptor::serialize (Archive & ar, const unsigned int version) [inline, private]
Reimplemented from tuttle::host::ofx::attribute::OfxhAttributeDescriptor.
Reimplemented in tuttle::host::ofx::attribute::OfxhClipImageDescriptor.
Definition at line 42 of file OfxhClipDescriptor.hpp.
Friends And Related Function Documentation
friend class boost::serialization::access [friend]
Reimplemented from tuttle::host::ofx::attribute::OfxhAttributeDescriptor.
Reimplemented in tuttle::host::ofx::attribute::OfxhClipImageDescriptor.
Definition at line 40 of file OfxhClipDescriptor.hpp.
The documentation for this class was generated from the following files:
TuttleOFX/libraries/tuttle/src/tuttle/host/ofx/attribute/OfxhClipDescriptor.hpp
TuttleOFX/libraries/tuttle/src/tuttle/host/ofx/attribute/OfxhClipDescriptor.cpp