TuttleOFX: boost Namespace Reference
boost Namespace Reference
Namespaces
namespace details
namespace stack_trace
Data Structures
struct errinfo_file_name_
class backtrace
struct error_info_sstream
class error_info< Tag, error_info_sstream >
struct is_virtual_base_of< tuttle::host::ofx::attribute::OfxhAttribute, tuttle::host::ofx::attribute::OfxhClip >
struct is_virtual_base_of< tuttle::host::ofx::attribute::OfxhAttributeDescriptor, tuttle::host::ofx::attribute::OfxhClipDescriptor >
struct is_virtual_base_of< tuttle::host::ofx::attribute::OfxhClip, tuttle::host::ofx::attribute::OfxhClipImage >
struct is_virtual_base_of< tuttle::host::ofx::attribute::OfxhClipDescriptor, tuttle::host::ofx::attribute::OfxhClipImageDescriptor >
struct is_virtual_base_of< tuttle::host::ofx::attribute::OfxhAttribute, tuttle::host::ofx::attribute::OfxhParam >
struct is_virtual_base_of< tuttle::host::ofx::attribute::OfxhAttributeDescriptor, tuttle::host::ofx::attribute::OfxhParamDescriptor >
struct is_virtual_base_of< tuttle::host::ofx::property::OfxhProperty, tuttle::host::ofx::property::Int >
struct is_virtual_base_of< tuttle::host::ofx::property::OfxhProperty, tuttle::host::ofx::property::Double >
struct is_virtual_base_of< tuttle::host::ofx::property::OfxhProperty, tuttle::host::ofx::property::String >
struct is_virtual_base_of< tuttle::host::ofx::property::OfxhProperty, tuttle::host::ofx::property::Pointer >
Functions
template<typename E >
details::trace_manip trace (E const &e)
std::string to_string (const error_info_sstream &x)
std::ostream & operator<< (std::ostream &os, const error_info_sstream &x)
std::size_t hash_value (const tuttle::host::graph::ProcessVertexAtTime::Key &k)
Function Documentation
std::size_t boost::hash_value (const tuttle::host::graph::ProcessVertexAtTime::Key & k) [inline]
Definition at line 62 of file ProcessVertexAtTime.hpp.
References tuttle::host::NodeAtTimeKey::getHash().
Referenced by tuttle::host::ofx::attribute::OfxhParamString::getHashAtTime(), tuttle::host::ofx::attribute::OfxhParamBoolean::getHashAtTime(), tuttle::host::ofx::attribute::OfxhParamChoice::getHashAtTime(), and tuttle::host::attribute::AnimatedParam< double, ofx::attribute::OfxhParamDouble >::getHashAtTime().
std::ostream& boost::operator<< (std::ostream & os, const error_info_sstream & x) [inline]
Definition at line 28 of file boost_error_info_sstream.hpp.
References boost::error_info_sstream::_v.
std::string boost::to_string (const error_info_sstream & x) [inline]
Definition at line 23 of file boost_error_info_sstream.hpp.
References boost::error_info_sstream::_v.
template<typename E > details::trace_manip boost::trace (E const & e)
Definition at line 114 of file backtrace.hpp.