TuttleOFX: tuttle::common::details Namespace Reference
tuttle::common::details Namespace Reference
Functions
static const std::string kColorBlack ("")
static const std::string kColorWhite ("")
static const std::string kColorBlue ("")
static const std::string kColorGreen ("")
static const std::string kColorRed ("")
static const std::string kColorCyan ("")
static const std::string kColorMagenta ("")
static const std::string kColorYellow ("")
static const std::string kColorStd ("")
static const std::string kColorFolder ("")
static const std::string kColorFile ("")
static const std::string kColorSequence ("")
static const std::string kColorError ("")
Function Documentation
static const std::string tuttle::common::details::kColorBlack ("") [static]
static const std::string tuttle::common::details::kColorBlue ("") [static]
Referenced by tuttle::common::Color::enable().
static const std::string tuttle::common::details::kColorCyan ("") [static]
static const std::string tuttle::common::details::kColorError ("") [static]
Referenced by tuttle::common::Color::enable().
static const std::string tuttle::common::details::kColorFile ("") [static]
Referenced by tuttle::common::Color::enable().
static const std::string tuttle::common::details::kColorFolder ("") [static]
Referenced by tuttle::common::Color::enable().
static const std::string tuttle::common::details::kColorGreen ("") [static]
Referenced by tuttle::common::Color::enable().
static const std::string tuttle::common::details::kColorMagenta ("") [static]
static const std::string tuttle::common::details::kColorRed ("") [static]
Referenced by tuttle::common::Color::enable().
static const std::string tuttle::common::details::kColorSequence ("") [static]
static const std::string tuttle::common::details::kColorStd ("") [static]
Referenced by tuttle::common::Color::enable().
static const std::string tuttle::common::details::kColorWhite ("") [static]
static const std::string tuttle::common::details::kColorYellow ("") [static]
Referenced by tuttle::common::Color::enable().