TuttleOFX: tuttle::plugin::OfxAllocator< T > Class Template Reference
tuttle::plugin::OfxAllocator< T > Class Template Reference
#include <OfxAllocator.hpp>
Data Structures
struct rebind
Public Types
typedef T Type
typedef size_t size_type
typedef ptrdiff_t difference_type
typedef T * pointer
typedef const T * const_pointer
typedef T & reference
typedef const T & const_reference
typedef T value_type
Public Member Functions
OfxAllocator ()
OfxAllocator (const OfxAllocator &)
template<class U >
OfxAllocator (const OfxAllocator< U > &)
pointer allocate (const size_type n, const void *=0)
void deallocate (void *ptr, size_type)
void construct (pointer p, const T &val)
void destroy (pointer p)
OfxAllocator< T > & operator= (const OfxAllocator< T > &)
template<class U >
OfxAllocator< T > & operator= (const OfxAllocator< U > &)
pointer address (reference x) const
const_pointer address (const_reference x) const
size_type max_size () const
bool operator== (OfxAllocator< T > const &)
bool operator!= (OfxAllocator< T > const &a)
Static Private Attributes
static int size_all = 0
Detailed Description
template<typename T>
class tuttle::plugin::OfxAllocator< T >
Definition at line 18 of file OfxAllocator.hpp.
Member Typedef Documentation
template<typename T> typedef const T* tuttle::plugin::OfxAllocator< T >::const_pointer
Definition at line 27 of file OfxAllocator.hpp.
template<typename T> typedef const T& tuttle::plugin::OfxAllocator< T >::const_reference
Definition at line 29 of file OfxAllocator.hpp.
template<typename T> typedef ptrdiff_t tuttle::plugin::OfxAllocator< T >::difference_type
Definition at line 25 of file OfxAllocator.hpp.
template<typename T> typedef T* tuttle::plugin::OfxAllocator< T >::pointer
Definition at line 26 of file OfxAllocator.hpp.
template<typename T> typedef T& tuttle::plugin::OfxAllocator< T >::reference
Definition at line 28 of file OfxAllocator.hpp.
template<typename T> typedef size_t tuttle::plugin::OfxAllocator< T >::size_type
Definition at line 24 of file OfxAllocator.hpp.
template<typename T> typedef T tuttle::plugin::OfxAllocator< T >::Type
Definition at line 23 of file OfxAllocator.hpp.
template<typename T> typedef T tuttle::plugin::OfxAllocator< T >::value_type
Definition at line 30 of file OfxAllocator.hpp.
Constructor & Destructor Documentation
template<typename T> tuttle::plugin::OfxAllocator< T >::OfxAllocator () [inline]
Definition at line 33 of file OfxAllocator.hpp.
template<typename T> tuttle::plugin::OfxAllocator< T >::OfxAllocator (const OfxAllocator< T > &) [inline]
Definition at line 34 of file OfxAllocator.hpp.
template<typename T> template<class U > tuttle::plugin::OfxAllocator< T >::OfxAllocator (const OfxAllocator< U > &) [inline]
Definition at line 36 of file OfxAllocator.hpp.
Member Function Documentation
template<typename T> pointer tuttle::plugin::OfxAllocator< T >::address (reference x) const [inline]
Definition at line 73 of file OfxAllocator.hpp.
template<typename T> const_pointer tuttle::plugin::OfxAllocator< T >::address (const_reference x) const [inline]
Definition at line 74 of file OfxAllocator.hpp.
template<typename T> pointer tuttle::plugin::OfxAllocator< T >::allocate (const size_type n, const void * = 0) [inline]
Definition at line 39 of file OfxAllocator.hpp.
References tuttle::plugin::OfxAllocator< T >::size_all.
template<typename T> void tuttle::plugin::OfxAllocator< T >::construct (pointer p, const T & val) [inline]
Definition at line 58 of file OfxAllocator.hpp.
template<typename T> void tuttle::plugin::OfxAllocator< T >::deallocate (void * ptr, size_type) [inline]
Definition at line 49 of file OfxAllocator.hpp.
References tuttle::plugin::OfxAllocator< T >::size_all.
template<typename T> void tuttle::plugin::OfxAllocator< T >::destroy (pointer p) [inline]
Definition at line 60 of file OfxAllocator.hpp.
template<typename T> size_type tuttle::plugin::OfxAllocator< T >::max_size () const [inline]
Definition at line 76 of file OfxAllocator.hpp.
References tuttle::max().
template<typename T> bool tuttle::plugin::OfxAllocator< T >::operator!= (OfxAllocator< T > const & a) [inline]
Definition at line 79 of file OfxAllocator.hpp.
References tuttle::plugin::OfxAllocator< T >::operator==().
template<typename T> OfxAllocator<T>& tuttle::plugin::OfxAllocator< T >::operator= (const OfxAllocator< T > &) [inline]
Definition at line 68 of file OfxAllocator.hpp.
template<typename T> template<class U > OfxAllocator<T>& tuttle::plugin::OfxAllocator< T >::operator= (const OfxAllocator< U > &) [inline]
Definition at line 71 of file OfxAllocator.hpp.
template<typename T> bool tuttle::host::ofx::imageEffect::OfxhImageEffectNode::operator== (OfxAllocator< T > const &) [inline]
Todo:
tuttle check clip ? check hash ? etc.
Definition at line 78 of file OfxAllocator.hpp.
Referenced by tuttle::plugin::OfxAllocator< T >::operator!=().
Field Documentation
template<typename T> int tuttle::plugin::OfxAllocator< T >::size_all = 0 [static, private]
Definition at line 20 of file OfxAllocator.hpp.
Referenced by tuttle::plugin::OfxAllocator< T >::allocate(), and tuttle::plugin::OfxAllocator< T >::deallocate().
The documentation for this class was generated from the following files:
TuttleOFX/libraries/tuttle/src/tuttle/plugin/memory/OfxAllocator.hpp
TuttleOFX/libraries/tuttle/src/tuttle/host/ofx/OfxhImageEffectNode.cpp