TuttleOFX: tuttle::host::ofx::imageEffect::OfxhImageEffectNodeDescriptor Class Reference
tuttle::host::ofx::imageEffect::OfxhImageEffectNodeDescriptor Class Reference
#include <OfxhImageEffectNodeDescriptor.hpp>
Public Types
typedef
OfxhImageEffectNodeDescriptor This
typedef std::map< std::string,
attribute::OfxhClipImageDescriptor * > ClipImageDescriptorMap
typedef boost::ptr_vector
< attribute::OfxhClipImageDescriptor > ClipImageDescriptorVector
Public Member Functions
OfxhImageEffectNodeDescriptor (OfxhPlugin &plug)
used to construct the global description
OfxhImageEffectNodeDescriptor (const OfxhImageEffectNodeDescriptor &rootContext, OfxhPlugin &plug)
used to construct a context description, 'other' is the main context
OfxhImageEffectNodeDescriptor (const std::string &bundlePath, OfxhPlugin &plug)
used to construct populate the cache
virtual ~OfxhImageEffectNodeDescriptor ()
dtor
bool operator== (const This &other) const
bool operator!= (const This &other) const
property::OfxhSet & getParamSetProps ()
implemented for ParamDescriptorSet
OfxhPlugin & getPlugin () const
get the plugin I belong to
virtual
attribute::OfxhClipImageDescriptor * defineClip (const std::string &name)
create a new clip and add this to the clip map
const ClipImageDescriptorMap & getClips () const
get the clips
void addClip (const std::string &name, attribute::OfxhClipImageDescriptor *clip)
add a new clip
const ClipImageDescriptorVector & getClipsByOrder () const
get the clips in order of construction
ClipImageDescriptorVector & getClipsByOrder ()
get the clips in order of construction
const
interact::OfxhInteractDescriptor & getOverlayDescriptor () const
void initOverlayDescriptor (int bitDepthPerComponent=8, bool hasAlpha=false)
Protected Attributes
OfxhPlugin * _plugin
the plugin I belong to
ClipImageDescriptorMap _clips
clips descriptors by name
ClipImageDescriptorVector _clipsByOrder
clip descriptors in order of declaration
interact::OfxhInteractDescriptor _overlayDescriptor
descriptor to use for overlays, it has delayed description
Private Member Functions
OfxhImageEffectNodeDescriptor (const OfxhImageEffectNodeDescriptor &other)
OfxhImageEffectNodeDescriptor ()
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Friends
class boost::serialization::access
Detailed Description
an image effect plugin descriptor
Definition at line 20 of file OfxhImageEffectNodeDescriptor.hpp.
Member Typedef Documentation
typedef std::map<std::string, attribute::OfxhClipImageDescriptor*> tuttle::host::ofx::imageEffect::OfxhImageEffectNodeDescriptor::ClipImageDescriptorMap
Definition at line 27 of file OfxhImageEffectNodeDescriptor.hpp.
typedef boost::ptr_vector<attribute::OfxhClipImageDescriptor> tuttle::host::ofx::imageEffect::OfxhImageEffectNodeDescriptor::ClipImageDescriptorVector
Definition at line 28 of file OfxhImageEffectNodeDescriptor.hpp.
typedef OfxhImageEffectNodeDescriptor tuttle::host::ofx::imageEffect::OfxhImageEffectNodeDescriptor::This
Reimplemented from tuttle::host::ofx::attribute::OfxhParamSetDescriptor.
Definition at line 26 of file OfxhImageEffectNodeDescriptor.hpp.
Constructor & Destructor Documentation
tuttle::host::ofx::imageEffect::OfxhImageEffectNodeDescriptor::OfxhImageEffectNodeDescriptor (const OfxhImageEffectNodeDescriptor & other) [inline, private]
Definition at line 38 of file OfxhImageEffectNodeDescriptor.hpp.
tuttle::host::ofx::imageEffect::OfxhImageEffectNodeDescriptor::OfxhImageEffectNodeDescriptor () [private]
Todo:
tuttle...
Definition at line 45 of file OfxhImageEffectNodeDescriptor.cpp.
tuttle::host::ofx::imageEffect::OfxhImageEffectNodeDescriptor::OfxhImageEffectNodeDescriptor (OfxhPlugin & plug)
used to construct the global description
Definition at line 52 of file OfxhImageEffectNodeDescriptor.cpp.
References tuttle::host::ofx::imageEffect::OfxhImageEffectNodeBase::_properties, tuttle::host::core(), tuttle::host::ofx::OfxhPlugin::getBinary(), tuttle::host::ofx::OfxhPluginBinary::getBundlePath(), tuttle::host::Core::getHost(), tuttle::host::ofx::imageEffect::OfxhImageEffectHost::initDescriptor(), and tuttle::host::ofx::property::OfxhSet::setStringProperty().
tuttle::host::ofx::imageEffect::OfxhImageEffectNodeDescriptor::OfxhImageEffectNodeDescriptor (const OfxhImageEffectNodeDescriptor & rootContext, OfxhPlugin & plug)
used to construct a context description, 'other' is the main context
Definition at line 60 of file OfxhImageEffectNodeDescriptor.cpp.
References tuttle::host::ofx::imageEffect::OfxhImageEffectNodeBase::_properties, tuttle::host::core(), tuttle::host::ofx::OfxhPlugin::getBinary(), tuttle::host::ofx::OfxhPluginBinary::getBundlePath(), tuttle::host::Core::getHost(), tuttle::host::ofx::imageEffect::OfxhImageEffectHost::initDescriptor(), and tuttle::host::ofx::property::OfxhSet::setStringProperty().
tuttle::host::ofx::imageEffect::OfxhImageEffectNodeDescriptor::OfxhImageEffectNodeDescriptor (const std::string & bundlePath, OfxhPlugin & plug)
used to construct populate the cache
Definition at line 68 of file OfxhImageEffectNodeDescriptor.cpp.
References tuttle::host::ofx::imageEffect::OfxhImageEffectNodeBase::_properties, tuttle::host::core(), tuttle::host::Core::getHost(), tuttle::host::ofx::imageEffect::OfxhImageEffectHost::initDescriptor(), and tuttle::host::ofx::property::OfxhSet::setStringProperty().
tuttle::host::ofx::imageEffect::OfxhImageEffectNodeDescriptor::~OfxhImageEffectNodeDescriptor () [virtual]
dtor
Definition at line 76 of file OfxhImageEffectNodeDescriptor.cpp.
Member Function Documentation
void tuttle::host::ofx::imageEffect::OfxhImageEffectNodeDescriptor::addClip (const std::string & name, attribute::OfxhClipImageDescriptor * clip)
add a new clip
Definition at line 113 of file OfxhImageEffectNodeDescriptor.cpp.
References _clips, and _clipsByOrder.
attribute::OfxhClipImageDescriptor * tuttle::host::ofx::imageEffect::OfxhImageEffectNodeDescriptor::defineClip (const std::string & name) [virtual]
create a new clip and add this to the clip map
Definition at line 91 of file OfxhImageEffectNodeDescriptor.cpp.
References _clips, and _clipsByOrder.
const ClipImageDescriptorMap& tuttle::host::ofx::imageEffect::OfxhImageEffectNodeDescriptor::getClips () const [inline]
get the clips
Definition at line 74 of file OfxhImageEffectNodeDescriptor.hpp.
References _clips.
Referenced by tuttle::host::ofx::imageEffect::operator<<().
const ClipImageDescriptorVector& tuttle::host::ofx::imageEffect::OfxhImageEffectNodeDescriptor::getClipsByOrder () const [inline]
get the clips in order of construction
Definition at line 80 of file OfxhImageEffectNodeDescriptor.hpp.
References _clipsByOrder.
ClipImageDescriptorVector& tuttle::host::ofx::imageEffect::OfxhImageEffectNodeDescriptor::getClipsByOrder () [inline]
get the clips in order of construction
Definition at line 83 of file OfxhImageEffectNodeDescriptor.hpp.
References _clipsByOrder.
const interact::OfxhInteractDescriptor& tuttle::host::ofx::imageEffect::OfxhImageEffectNodeDescriptor::getOverlayDescriptor () const [inline]
Todo:
tuttle some modifs here... doc needs updates... Get the interact description, this will also call describe on the interact This will return NULL if there is not main entry point or if the description failed otherwise it will return the described overlay
Definition at line 91 of file OfxhImageEffectNodeDescriptor.hpp.
References _overlayDescriptor.
Referenced by tuttle::host::ofx::imageEffect::OfxhImageEffectNode::getOverlayDescriptor().
property::OfxhSet& tuttle::host::ofx::imageEffect::OfxhImageEffectNodeDescriptor::getParamSetProps () [inline, virtual]
implemented for ParamDescriptorSet
Implements tuttle::host::ofx::attribute::OfxhParamSetAccessor.
Definition at line 62 of file OfxhImageEffectNodeDescriptor.hpp.
References tuttle::host::ofx::imageEffect::OfxhImageEffectNodeBase::_properties.
OfxhPlugin& tuttle::host::ofx::imageEffect::OfxhImageEffectNodeDescriptor::getPlugin () const [inline]
get the plugin I belong to
Definition at line 68 of file OfxhImageEffectNodeDescriptor.hpp.
References _plugin.
void tuttle::host::ofx::imageEffect::OfxhImageEffectNodeDescriptor::initOverlayDescriptor (int bitDepthPerComponent = 8, bool hasAlpha = false)
Warning:
tuttle some modifs here, doc needs update get the interact description, this will also call describe on the interact
Definition at line 102 of file OfxhImageEffectNodeDescriptor.cpp.
References _overlayDescriptor, tuttle::host::ofx::interact::OfxhInteractDescriptor::describe(), tuttle::host::ofx::interact::eUninitialised, tuttle::host::ofx::imageEffect::OfxhImageEffectNodeBase::getOverlayInteractMainEntry(), tuttle::host::ofx::interact::OfxhInteractDescriptor::getState(), and tuttle::host::ofx::interact::OfxhInteractDescriptor::setEntryPoint().
bool tuttle::host::ofx::imageEffect::OfxhImageEffectNodeDescriptor::operator!= (const This & other) const [inline]
Reimplemented from tuttle::host::ofx::attribute::OfxhParamSetDescriptor.
Definition at line 59 of file OfxhImageEffectNodeDescriptor.hpp.
References operator==().
bool tuttle::host::ofx::imageEffect::OfxhImageEffectNodeDescriptor::operator== (const This & other) const
Reimplemented from tuttle::host::ofx::attribute::OfxhParamSetDescriptor.
Definition at line 79 of file OfxhImageEffectNodeDescriptor.cpp.
References _clipsByOrder.
Referenced by operator!=().
template<class Archive > void tuttle::host::ofx::imageEffect::OfxhImageEffectNodeDescriptor::serialize (Archive & ar, const unsigned int version) [inline, private]
Reimplemented from tuttle::host::ofx::attribute::OfxhParamSetDescriptor.
Definition at line 98 of file OfxhImageEffectNodeDescriptor.hpp.
References _clipsByOrder, and tuttle::host::ofx::attribute::OfxhParamSetDescriptor::OfxhParamSetDescriptor().
Friends And Related Function Documentation
friend class boost::serialization::access [friend]
Reimplemented from tuttle::host::ofx::attribute::OfxhParamSetDescriptor.
Definition at line 96 of file OfxhImageEffectNodeDescriptor.hpp.
Field Documentation
ClipImageDescriptorMap tuttle::host::ofx::imageEffect::OfxhImageEffectNodeDescriptor::_clips [protected]
clips descriptors by name
Definition at line 32 of file OfxhImageEffectNodeDescriptor.hpp.
Referenced by addClip(), defineClip(), and getClips().
ClipImageDescriptorVector tuttle::host::ofx::imageEffect::OfxhImageEffectNodeDescriptor::_clipsByOrder [protected]
clip descriptors in order of declaration
Definition at line 33 of file OfxhImageEffectNodeDescriptor.hpp.
Referenced by addClip(), defineClip(), getClipsByOrder(), operator==(), and serialize().
interact::OfxhInteractDescriptor tuttle::host::ofx::imageEffect::OfxhImageEffectNodeDescriptor::_overlayDescriptor [mutable, protected]
descriptor to use for overlays, it has delayed description
Todo:
tuttle: remove mutable
Definition at line 34 of file OfxhImageEffectNodeDescriptor.hpp.
Referenced by getOverlayDescriptor(), and initOverlayDescriptor().
OfxhPlugin* tuttle::host::ofx::imageEffect::OfxhImageEffectNodeDescriptor::_plugin [protected]
the plugin I belong to
Definition at line 31 of file OfxhImageEffectNodeDescriptor.hpp.
Referenced by getPlugin().
The documentation for this class was generated from the following files:
TuttleOFX/libraries/tuttle/src/tuttle/host/ofx/OfxhImageEffectNodeDescriptor.hpp
TuttleOFX/libraries/tuttle/src/tuttle/host/ofx/OfxhImageEffectNodeDescriptor.cpp