TuttleOFX: tuttle::plugin::interact::SelectionManipulator Class Reference
tuttle::plugin::interact::SelectionManipulator Class Reference
#include <SelectionManipulator.hpp>
Public Member Functions
SelectionManipulator (const InteractInfos &infos)
virtual ~SelectionManipulator ()
MotionType intersect (const OFX::PenArgs &args)
double getMarge () const
Point2 getDistance (const Point2 &p) const
void setPosition (const Point2 &p)
void setPositionX (const Scalar x)
void setPositionY (const Scalar y)
void beginMove (const Point2 &penPosition)
void endMove (const Point2 &penPosition)
Protected Attributes
const InteractInfos & _infos
Private Attributes
Point2 _selectionPos
Detailed Description
Definition at line 11 of file SelectionManipulator.hpp.
Constructor & Destructor Documentation
tuttle::plugin::interact::SelectionManipulator::SelectionManipulator (const InteractInfos & infos)
Definition at line 7 of file SelectionManipulator.cpp.
tuttle::plugin::interact::SelectionManipulator::~SelectionManipulator () [virtual]
Definition at line 14 of file SelectionManipulator.cpp.
Member Function Documentation
void tuttle::plugin::interact::SelectionManipulator::beginMove (const Point2 & penPosition) [inline, virtual]
Reimplemented from tuttle::plugin::interact::InteractObject.
Definition at line 48 of file SelectionManipulator.hpp.
void tuttle::plugin::interact::SelectionManipulator::endMove (const Point2 & penPosition) [inline, virtual]
Reimplemented from tuttle::plugin::interact::InteractObject.
Definition at line 51 of file SelectionManipulator.hpp.
Point2 tuttle::plugin::interact::SelectionManipulator::getDistance (const Point2 & p) const [inline]
Definition at line 31 of file SelectionManipulator.hpp.
double tuttle::plugin::interact::SelectionManipulator::getMarge () const [inline]
Definition at line 29 of file SelectionManipulator.hpp.
References _infos, tuttle::plugin::interact::InteractInfos::_marge, and tuttle::plugin::interact::InteractInfos::_projectSize.
Referenced by intersect().
MotionType tuttle::plugin::interact::SelectionManipulator::intersect (const OFX::PenArgs & args) [inline, virtual]
Reimplemented from tuttle::plugin::interact::InteractObject.
Definition at line 17 of file SelectionManipulator.hpp.
References tuttle::plugin::interact::MotionType::_axis, tuttle::plugin::interact::MotionType::_mode, _selectionPos, tuttle::plugin::interact::clicPoint(), tuttle::plugin::interact::eMotionTranslate, getMarge(), and tuttle::plugin::ofxToGil().
void tuttle::plugin::interact::SelectionManipulator::setPosition (const Point2 & p) [inline, virtual]
Reimplemented from tuttle::plugin::interact::InteractObject.
Definition at line 33 of file SelectionManipulator.hpp.
References _selectionPos.
void tuttle::plugin::interact::SelectionManipulator::setPositionX (const Scalar x) [inline, virtual]
Reimplemented from tuttle::plugin::interact::InteractObject.
Definition at line 37 of file SelectionManipulator.hpp.
References _selectionPos, and tuttle::plugin::interact::InteractObject::getPosition().
void tuttle::plugin::interact::SelectionManipulator::setPositionY (const Scalar y) [inline, virtual]
Reimplemented from tuttle::plugin::interact::InteractObject.
Definition at line 42 of file SelectionManipulator.hpp.
References _selectionPos, and tuttle::plugin::interact::InteractObject::getPosition().
Field Documentation
const InteractInfos& tuttle::plugin::interact::SelectionManipulator::_infos [protected]
Definition at line 56 of file SelectionManipulator.hpp.
Referenced by getMarge().
Point2 tuttle::plugin::interact::SelectionManipulator::_selectionPos [private]
Definition at line 58 of file SelectionManipulator.hpp.
Referenced by intersect(), setPosition(), setPositionX(), and setPositionY().
The documentation for this class was generated from the following files:
TuttleOFX/libraries/tuttle/src/tuttle/plugin/interact/SelectionManipulator.hpp
TuttleOFX/libraries/tuttle/src/tuttle/plugin/interact/SelectionManipulator.cpp