TuttleOFX: tuttle::host::ofx::imageEffect::OfxhImageEffectHost Class Reference
tuttle::host::ofx::imageEffect::OfxhImageEffectHost Class Reference
#include <OfxhImageEffectHost.hpp>
Public Member Functions
OfxhImageEffectHost ()
ctor
virtual ~OfxhImageEffectHost ()=0
virtual void * fetchSuite (const char *suiteName, const int suiteVersion)
fetch a suite
virtual OfxhImageEffectNode * newInstance (OfxhImageEffectPlugin &plugin, OfxhImageEffectNodeDescriptor &desc, const std::string &context) const =0
virtual void loadingStatus (const std::string &)
virtual bool pluginSupported (const OfxhImageEffectPlugin &plugin, std::string &reason) const
virtual
OfxhImageEffectNodeDescriptor * makeDescriptor (OfxhImageEffectPlugin &plugin) const =0
Override this to create a descriptor, this makes the 'root' descriptor.
virtual
OfxhImageEffectNodeDescriptor * makeDescriptor (const OfxhImageEffectNodeDescriptor &rootContext, OfxhImageEffectPlugin &plug) const =0
used to construct a context description, rootContext is the main context
virtual
OfxhImageEffectNodeDescriptor * makeDescriptor (const std::string &bundlePath, OfxhImageEffectPlugin &plug) const =0
used to construct populate the cache
virtual void initDescriptor (OfxhImageEffectNodeDescriptor &desc) const
Detailed Description
An image effect host, passed to the setHost function of all image effect plugins
Definition at line 41 of file OfxhImageEffectHost.hpp.
Constructor & Destructor Documentation
tuttle::host::ofx::imageEffect::OfxhImageEffectHost::OfxhImageEffectHost ()
ctor
add the properties for an image effect host, derived classs to set most of them
Definition at line 52 of file OfxhImageEffectHost.cpp.
References tuttle::host::ofx::OfxhHost::_properties, tuttle::host::ofx::property::OfxhSet::addProperties(), and tuttle::host::ofx::imageEffect::hostStuffs.
tuttle::host::ofx::imageEffect::OfxhImageEffectHost::~OfxhImageEffectHost () [pure virtual]
Definition at line 58 of file OfxhImageEffectHost.cpp.
Member Function Documentation
void * tuttle::host::ofx::imageEffect::OfxhImageEffectHost::fetchSuite (const char * suiteName, const int suiteVersion) [virtual]
fetch a suite
our suite fetcher
otherwise just grab the base class one, which is props and memory
Reimplemented from tuttle::host::ofx::OfxhHost.
Definition at line 79 of file OfxhImageEffectHost.cpp.
References tuttle::host::ofx::imageEffect::getImageEffectSuite(), tuttle::host::ofx::interact::getInteractSuite(), tuttle::host::ofx::getMessageSuite(), tuttle::host::ofx::getMultithreadSuite(), tuttle::host::ofx::attribute::getParameterSuite(), tuttle::host::ofx::getProgressSuite(), and tuttle::host::ofx::getTimelineSuite().
void tuttle::host::ofx::imageEffect::OfxhImageEffectHost::initDescriptor (OfxhImageEffectNodeDescriptor & desc) const [virtual]
Override this to initialise an image effect descriptor after it has been created.
optionally over-ridden function to register the creation of a new descriptor in the host app
Definition at line 64 of file OfxhImageEffectHost.cpp.
Referenced by tuttle::host::ofx::imageEffect::OfxhImageEffectNodeDescriptor::OfxhImageEffectNodeDescriptor().
void tuttle::host::ofx::imageEffect::OfxhImageEffectHost::loadingStatus (const std::string &) [virtual]
Function called as each plugin binary is found and loaded from disk
Use this in any dialogue etc... showing progress
Use this in any dialogue etc... showing progress
Definition at line 69 of file OfxhImageEffectHost.cpp.
Referenced by tuttle::host::ofx::imageEffect::OfxhImageEffectPluginCache::loadFromPlugin().
virtual OfxhImageEffectNodeDescriptor* tuttle::host::ofx::imageEffect::OfxhImageEffectHost::makeDescriptor (OfxhImageEffectPlugin & plugin) const [pure virtual]
Override this to create a descriptor, this makes the 'root' descriptor.
Implemented in tuttle::host::Host.
virtual OfxhImageEffectNodeDescriptor* tuttle::host::ofx::imageEffect::OfxhImageEffectHost::makeDescriptor (const OfxhImageEffectNodeDescriptor & rootContext, OfxhImageEffectPlugin & plug) const [pure virtual]
used to construct a context description, rootContext is the main context
Implemented in tuttle::host::Host.
virtual OfxhImageEffectNodeDescriptor* tuttle::host::ofx::imageEffect::OfxhImageEffectHost::makeDescriptor (const std::string & bundlePath, OfxhImageEffectPlugin & plug) const [pure virtual]
used to construct populate the cache
Implemented in tuttle::host::Host.
virtual OfxhImageEffectNode* tuttle::host::ofx::imageEffect::OfxhImageEffectHost::newInstance (OfxhImageEffectPlugin & plugin, OfxhImageEffectNodeDescriptor & desc, const std::string & context) const [pure virtual]
Create a new instance of an image effect plug-in.
It is called by ImageEffectPlugin::createInstance which the client code calls when it wants to make a new instance.
param: clientData - the clientData passed into the ImageEffectPlugin::createInstance (tuttle remove this parameter)
Parameters:
plugin - the plugin being created
desc - the descriptor for that plugin
context - the context to be created in
Implemented in tuttle::host::Host.
bool tuttle::host::ofx::imageEffect::OfxhImageEffectHost::pluginSupported (const OfxhImageEffectPlugin & plugin, std::string & reason) const [virtual]
Override this to filter out plugins which the host can't support for whatever reason
Parameters:
plugin - the plugin to examine
reason - set this to report the reason the plugin was not loaded
Definition at line 71 of file OfxhImageEffectHost.cpp.
Referenced by tuttle::host::ofx::imageEffect::OfxhImageEffectPluginCache::pluginSupported().
The documentation for this class was generated from the following files:
TuttleOFX/libraries/tuttle/src/tuttle/host/ofx/OfxhImageEffectHost.hpp
TuttleOFX/libraries/tuttle/src/tuttle/host/ofx/OfxhImageEffectHost.cpp