TuttleOFX: tuttle::host::attribute::AnimatedParamDouble Class Reference
tuttle::host::attribute::AnimatedParamDouble Class Reference
This class is just a re-implementation dedicated to Double Param. It allows implicit conversion from Int to Double.
#include <AnimatedParamType.hpp>
Public Member Functions
AnimatedParamDouble (INode &effect, const std::string &name, const ofx::attribute::OfxhParamDescriptor &descriptor, const std::size_t index, const double value)
void setValue (const double &v, const ofx::attribute::EChange change) OFX_EXCEPTION_SPEC
void setValueAtTime (const OfxTime time, const double &v, const ofx::attribute::EChange change) OFX_EXCEPTION_SPEC
void setValue (const int &v, const ofx::attribute::EChange change) OFX_EXCEPTION_SPEC
void setValueAtTime (const OfxTime time, const int &v, const ofx::attribute::EChange change) OFX_EXCEPTION_SPEC
Private Types
typedef AnimatedParam< double,
ofx::attribute::OfxhParamDouble > Parent
Detailed Description
This class is just a re-implementation dedicated to Double Param. It allows implicit conversion from Int to Double.
Definition at line 19 of file AnimatedParamType.hpp.
Member Typedef Documentation
typedef AnimatedParam<double, ofx::attribute::OfxhParamDouble> tuttle::host::attribute::AnimatedParamDouble::Parent [private]
Definition at line 21 of file AnimatedParamType.hpp.
Constructor & Destructor Documentation
tuttle::host::attribute::AnimatedParamDouble::AnimatedParamDouble (INode & effect, const std::string & name, const ofx::attribute::OfxhParamDescriptor & descriptor, const std::size_t index, const double value) [inline]
Definition at line 25 of file AnimatedParamType.hpp.
Member Function Documentation
void tuttle::host::attribute::AnimatedParamDouble::setValue (const double & v, const ofx::attribute::EChange change) [inline, virtual]
Reimplemented from tuttle::host::attribute::AnimatedParam< double, ofx::attribute::OfxhParamDouble >.
Reimplemented in tuttle::host::attribute::ParamDouble.
Definition at line 34 of file AnimatedParamType.hpp.
References tuttle::host::attribute::AnimatedParam< double, ofx::attribute::OfxhParamDouble >::setValue().
void tuttle::host::attribute::AnimatedParamDouble::setValue (const int & v, const ofx::attribute::EChange change) [inline, virtual]
Reimplemented from tuttle::host::ofx::attribute::OfxhParamDouble.
Reimplemented in tuttle::host::attribute::ParamDouble.
Definition at line 44 of file AnimatedParamType.hpp.
References tuttle::host::attribute::AnimatedParam< double, ofx::attribute::OfxhParamDouble >::setValue().
void tuttle::host::attribute::AnimatedParamDouble::setValueAtTime (const OfxTime time, const double & v, const ofx::attribute::EChange change) [inline, virtual]
Reimplemented from tuttle::host::attribute::AnimatedParam< double, ofx::attribute::OfxhParamDouble >.
Reimplemented in tuttle::host::attribute::ParamDouble.
Definition at line 39 of file AnimatedParamType.hpp.
References tuttle::host::attribute::AnimatedParam< double, ofx::attribute::OfxhParamDouble >::setValueAtTime().
void tuttle::host::attribute::AnimatedParamDouble::setValueAtTime (const OfxTime time, const int & v, const ofx::attribute::EChange change) [inline, virtual]
Reimplemented from tuttle::host::ofx::attribute::OfxhParamDouble.
Reimplemented in tuttle::host::attribute::ParamDouble.
Definition at line 49 of file AnimatedParamType.hpp.
References tuttle::host::attribute::AnimatedParam< double, ofx::attribute::OfxhParamDouble >::setValueAtTime().
The documentation for this class was generated from the following file:
TuttleOFX/libraries/tuttle/src/tuttle/host/attribute/AnimatedParamType.hpp