TuttleOFX: tuttle::host::ofx::attribute::OfxhParamString Class Reference
tuttle::host::ofx::attribute::OfxhParamString Class Reference
#include <OfxhParamString.hpp>
Public Types
typedef std::string BaseType
Public Member Functions
OfxhParamString (const OfxhParamDescriptor &descriptor, const std::string &name, OfxhParamSet &setInstance)
const std::string & getStringMode () const
virtual void getValue (std::string &) const OFX_EXCEPTION_SPEC=0
virtual void getValueAtTime (const OfxTime time, std::string &) const OFX_EXCEPTION_SPEC=0
virtual void setValue (const std::string &, const EChange change) OFX_EXCEPTION_SPEC=0
virtual void setValueAtTime (const OfxTime time, const std::string &, const EChange change) OFX_EXCEPTION_SPEC=0
virtual void getV (va_list arg) const OFX_EXCEPTION_SPEC
implementation of var args function
virtual void getV (const OfxTime time, va_list arg) const OFX_EXCEPTION_SPEC
implementation of var args function
virtual void setV (va_list arg, const EChange change) OFX_EXCEPTION_SPEC
implementation of var args function
virtual void setV (const OfxTime time, va_list arg, const EChange change) OFX_EXCEPTION_SPEC
implementation of var args function
bool paramTypeHasData () const
std::size_t getHashAtTime (const OfxTime time) const
std::ostream & displayValues (std::ostream &os) const
Private Attributes
std::string _returnValue
location to hold temporary return value. Should delegate this to implementation!!!
Detailed Description
Definition at line 14 of file OfxhParamString.hpp.
Member Typedef Documentation
typedef std::string tuttle::host::ofx::attribute::OfxhParamString::BaseType
Definition at line 21 of file OfxhParamString.hpp.
Constructor & Destructor Documentation
tuttle::host::ofx::attribute::OfxhParamString::OfxhParamString (const OfxhParamDescriptor & descriptor, const std::string & name, OfxhParamSet & setInstance) [inline]
Definition at line 22 of file OfxhParamString.hpp.
Member Function Documentation
std::ostream& tuttle::host::ofx::attribute::OfxhParamString::displayValues (std::ostream & os) const [inline, virtual]
Reimplemented from tuttle::host::ofx::attribute::OfxhParam.
Definition at line 49 of file OfxhParamString.hpp.
std::size_t tuttle::host::ofx::attribute::OfxhParamString::getHashAtTime (const OfxTime time) const [virtual]
Implements tuttle::host::ofx::attribute::OfxhParam.
Definition at line 57 of file OfxhParamString.cpp.
References getStringMode(), getValueAtTime(), and boost::hash_value().
const std::string & tuttle::host::ofx::attribute::OfxhParamString::getStringMode () const
Definition at line 11 of file OfxhParamString.cpp.
References tuttle::host::ofx::attribute::OfxhAttribute::getProperties(), and tuttle::host::ofx::property::OfxhSet::getStringProperty().
Referenced by getHashAtTime().
void tuttle::host::ofx::attribute::OfxhParamString::getV (va_list arg) const [virtual]
implementation of var args function
Todo:
tuttle: "I so don't like this, temp storage should be delegated to the implementation"
Reimplemented from tuttle::host::ofx::attribute::OfxhParam.
Definition at line 16 of file OfxhParamString.cpp.
void tuttle::host::ofx::attribute::OfxhParamString::getV (const OfxTime time, va_list arg) const [virtual]
implementation of var args function
Reimplemented from tuttle::host::ofx::attribute::OfxhParam.
Definition at line 28 of file OfxhParamString.cpp.
virtual void tuttle::host::ofx::attribute::OfxhParamString::getValue (std::string &) const [pure virtual]
Implemented in tuttle::host::attribute::ParamCustom, and tuttle::host::attribute::ParamString.
virtual void tuttle::host::ofx::attribute::OfxhParamString::getValueAtTime (const OfxTime time, std::string &) const [pure virtual]
Implemented in tuttle::host::attribute::ParamCustom, and tuttle::host::attribute::ParamString.
Referenced by getHashAtTime().
bool tuttle::host::ofx::attribute::OfxhParamString::paramTypeHasData () const [inline, virtual]
Implements tuttle::host::ofx::attribute::OfxhParam.
Definition at line 45 of file OfxhParamString.hpp.
void tuttle::host::ofx::attribute::OfxhParamString::setV (va_list arg, const EChange change) [virtual]
implementation of var args function
Reimplemented from tuttle::host::ofx::attribute::OfxhParam.
Definition at line 40 of file OfxhParamString.cpp.
void tuttle::host::ofx::attribute::OfxhParamString::setV (const OfxTime time, va_list arg, const EChange change) [virtual]
implementation of var args function
Reimplemented from tuttle::host::ofx::attribute::OfxhParam.
Definition at line 50 of file OfxhParamString.cpp.
virtual void tuttle::host::ofx::attribute::OfxhParamString::setValue (const std::string & , const EChange change) [pure virtual]
Implemented in tuttle::host::attribute::ParamCustom, and tuttle::host::attribute::ParamString.
virtual void tuttle::host::ofx::attribute::OfxhParamString::setValueAtTime (const OfxTime time, const std::string & , const EChange change) [pure virtual]
Implemented in tuttle::host::attribute::ParamCustom, and tuttle::host::attribute::ParamString.
Field Documentation
std::string tuttle::host::ofx::attribute::OfxhParamString::_returnValue [mutable, private]
location to hold temporary return value. Should delegate this to implementation!!!
Definition at line 18 of file OfxhParamString.hpp.
The documentation for this class was generated from the following files:
TuttleOFX/libraries/tuttle/src/tuttle/host/ofx/attribute/OfxhParamString.hpp
TuttleOFX/libraries/tuttle/src/tuttle/host/ofx/attribute/OfxhParamString.cpp