TuttleOFX: tuttle::host::graph Namespace Reference
tuttle::host::graph Namespace Reference
graph work
Namespaces
namespace detail
namespace visitor
Data Structures
class IEdge
class InternalGraph
class IVertex
class ProcessEdge
class ProcessEdgeAtTime
class ProcessGraph
Created from a user Graph, this class allows you to launch the process.
class ProcessVertex
class ProcessVertexAtTime
class ProcessVertexAtTimeInfo
class ProcessVertexAtTimeData
class ProcessVertexData
class UEdge
Edge of the user graph.
class UVertex
Vertex of the user graph.
class TestVertex
class TestEdge
struct vertex_label_writer
struct edge_label_writer
Functions
template<class T >
detail::DotEntry< T > dotEntry (const std::string &key, const T &value)
Use this function to force the correct syntax. os << dotEntry("label", "fooNode"); output: [label="fooNode"].
template<class T >
detail::SubDotEntry< T > subDotEntry (const std::string &key, const T &value)
template<typename Vertex , typename ProcessEdge , typename OutEdgeList , typename VertexList , typename EdgeList >
void exportSimple (std::ostream &os, const InternalGraph< Vertex, ProcessEdge, OutEdgeList, VertexList, EdgeList > &g)
template<typename Vertex , typename ProcessEdge , typename OutEdgeList , typename VertexList , typename EdgeList >
void exportAsDOT (std::ostream &os, const InternalGraph< Vertex, ProcessEdge, OutEdgeList, VertexList, EdgeList > &g)
template<typename Vertex , typename ProcessEdge , typename OutEdgeList , typename VertexList , typename EdgeList >
void exportAsDOT (const std::string &filename, const InternalGraph< Vertex, ProcessEdge, OutEdgeList, VertexList, EdgeList > &g)
template<typename Vertex , typename ProcessEdge , typename OutEdgeList , typename VertexList , typename EdgeList >
void exportDebugAsDOT (std::ostream &os, const InternalGraph< Vertex, ProcessEdge, OutEdgeList, VertexList, EdgeList > &g)
template<typename Vertex , typename ProcessEdge , typename OutEdgeList , typename VertexList , typename EdgeList >
void exportDebugAsDOT (const std::string &filename, const InternalGraph< Vertex, ProcessEdge, OutEdgeList, VertexList, EdgeList > &g)
template<class Name >
detail::simple_node_writer< Name > make_simple_node_writer (Name n)
For simple export, don't use the real .dot syntax, just put the name. like: [ fooNode ] instead of: [label="fooNode"].
template<class Graph >
detail::debug_node_writer< Graph > make_debug_node_writer (const Graph g)
std::ostream & operator<< (std::ostream &os, const IEdge &v)
template<typename Vertex , typename Edge >
std::ostream & operator<< (std::ostream &os, const InternalGraph< Vertex, Edge > &g)
std::ostream & operator<< (std::ostream &os, const IVertex &v)
std::ostream & operator<< (std::ostream &os, const ProcessVertex &v)
std::ostream & operator<< (std::ostream &os, const ProcessVertexAtTime &v)
std::ostream & operator<< (std::ostream &os, const ProcessVertexAtTimeInfo &infos)
std::ostream & operator<< (std::ostream &os, const ProcessVertexAtTimeData &vData)
std::ostream & operator<< (std::ostream &os, const ProcessVertexData &vData)
template<class TGraph >
void connectClips (TGraph &graph)
std::ostream & operator<< (std::ostream &os, const UEdge &v)
std::ostream & operator<< (std::ostream &os, const UVertex &v)
std::ostream & operator<< (std::ostream &os, const TestVertex &v)
std::ostream & operator<< (std::ostream &os, const TestEdge &e)
template<template< typename > class T, class G >
T< G > make (const G &g)
template<>
void exportAsDOT< TestVertex, TestEdge > (std::ostream &os, const InternalGraph< TestVertex, TestEdge > &g)
Detailed Description
graph work
Function Documentation
template<class TGraph > void tuttle::host::graph::connectClips (TGraph & graph) [inline]
Definition at line 25 of file ProcessVisitors.hpp.
References tuttle::host::INode::connect(), tuttle::host::INode::getAttribute(), TUTTLE_TLOG, and TUTTLE_TRACE.
template<class T > detail::DotEntry< T > tuttle::host::graph::dotEntry (const std::string & key, const T & value)
Use this function to force the correct syntax. os << dotEntry("label", "fooNode"); output: [label="fooNode"].
Definition at line 34 of file GraphExporter.tcc.
Referenced by tuttle::host::graph::ProcessEdgeAtTime::exportDotDebug(), tuttle::host::graph::ProcessEdge::exportDotDebug(), tuttle::host::graph::IEdge::exportDotDebug(), tuttle::host::graph::ProcessVertex::exportDotDebug(), tuttle::host::graph::ProcessVertexAtTime::exportDotDebug(), tuttle::host::graph::IVertex::exportDotDebug(), tuttle::host::graph::vertex_label_writer< G >::operator()(), and tuttle::host::graph::edge_label_writer< G >::operator()().
template<typename Vertex , typename ProcessEdge , typename OutEdgeList , typename VertexList , typename EdgeList > void tuttle::host::graph::exportAsDOT (std::ostream & os, const InternalGraph< Vertex, ProcessEdge, OutEdgeList, VertexList, EdgeList > & g) [inline]
Definition at line 82 of file GraphExporter.tcc.
References tuttle::host::graph::IEdge::_name, tuttle::host::graph::IVertex::_name, and tuttle::host::graph::InternalGraph< VERTEX, EDGE, OutEdgeList, VertexList, EdgeList >::getGraph().
Referenced by tuttle::host::Graph::compute(), exportAsDOT(), tuttle::host::Graph::exportDot(), and tuttle::host::graph::ProcessGraph::process().
template<typename Vertex , typename ProcessEdge , typename OutEdgeList , typename VertexList , typename EdgeList > void tuttle::host::graph::exportAsDOT (const std::string & filename, const InternalGraph< Vertex, ProcessEdge, OutEdgeList, VertexList, EdgeList > & g) [inline]
Definition at line 106 of file GraphExporter.tcc.
References exportAsDOT().
template<> void tuttle::host::graph::exportAsDOT< TestVertex, TestEdge > (std::ostream & os, const InternalGraph< TestVertex, TestEdge > & g)
Definition at line 97 of file main.cpp.
template<typename Vertex , typename ProcessEdge , typename OutEdgeList , typename VertexList , typename EdgeList > void tuttle::host::graph::exportDebugAsDOT (std::ostream & os, const InternalGraph< Vertex, ProcessEdge, OutEdgeList, VertexList, EdgeList > & g) [inline]
Definition at line 134 of file GraphExporter.tcc.
References tuttle::host::graph::InternalGraph< VERTEX, EDGE, OutEdgeList, VertexList, EdgeList >::getGraph(), and make_debug_node_writer().
Referenced by exportDebugAsDOT(), tuttle::host::graph::ProcessGraph::process(), and tuttle::host::graph::ProcessGraph::setupAtTime().
template<typename Vertex , typename ProcessEdge , typename OutEdgeList , typename VertexList , typename EdgeList > void tuttle::host::graph::exportDebugAsDOT (const std::string & filename, const InternalGraph< Vertex, ProcessEdge, OutEdgeList, VertexList, EdgeList > & g) [inline]
Definition at line 158 of file GraphExporter.tcc.
References exportDebugAsDOT().
template<typename Vertex , typename ProcessEdge , typename OutEdgeList , typename VertexList , typename EdgeList > void tuttle::host::graph::exportSimple (std::ostream & os, const InternalGraph< Vertex, ProcessEdge, OutEdgeList, VertexList, EdgeList > & g) [inline]
Definition at line 73 of file GraphExporter.tcc.
References tuttle::host::graph::IEdge::_name, tuttle::host::graph::InternalGraph< VERTEX, EDGE, OutEdgeList, VertexList, EdgeList >::getGraph(), and make_simple_node_writer().
template<template< typename > class T, class G > T<G> tuttle::host::graph::make (const G & g)
Definition at line 91 of file main.cpp.
template<class Graph > detail::debug_node_writer<Graph> tuttle::host::graph::make_debug_node_writer (const Graph g) [inline]
Definition at line 128 of file GraphExporter.tcc.
Referenced by exportDebugAsDOT().
template<class Name > detail::simple_node_writer<Name> tuttle::host::graph::make_simple_node_writer (Name n) [inline]
For simple export, don't use the real .dot syntax, just put the name. like: [ fooNode ] instead of: [label="fooNode"].
Definition at line 67 of file GraphExporter.tcc.
Referenced by exportSimple().
std::ostream& tuttle::host::graph::operator<< (std::ostream & os, const ProcessVertexData & vData)
Definition at line 12 of file ProcessVertexData.cpp.
References tuttle::host::graph::ProcessVertexData::_inDegree, tuttle::host::graph::ProcessVertexData::_interactive, tuttle::host::graph::ProcessVertexData::_outDegree, tuttle::host::graph::ProcessVertexData::_renderTimeRange, and tuttle::host::graph::ProcessVertexData::_step.
std::ostream& tuttle::host::graph::operator<< (std::ostream & os, const UEdge & v)
Definition at line 12 of file UEdge.cpp.
std::ostream& tuttle::host::graph::operator<< (std::ostream & os, const UVertex & v)
Definition at line 13 of file UVertex.cpp.
std::ostream& tuttle::host::graph::operator<< (std::ostream & os, const ProcessVertexAtTimeInfo & infos)
Definition at line 13 of file ProcessVertexAtTimeData.cpp.
References tuttle::host::graph::ProcessVertexAtTimeInfo::_memory, and tuttle::host::graph::ProcessVertexAtTimeInfo::_nodes.
std::ostream& tuttle::host::graph::operator<< (std::ostream & os, const ProcessVertexAtTimeData & vData)
Definition at line 22 of file ProcessVertexAtTimeData.cpp.
References tuttle::host::graph::ProcessVertexAtTimeData::_apiImageEffect, tuttle::host::graph::ProcessVertexData::_apiType, tuttle::host::graph::ProcessVertexAtTimeData::ImageEffect::_field, tuttle::host::graph::ProcessVertexAtTimeData::_globalInfos, tuttle::host::graph::ProcessVertexAtTimeData::_inDegree, tuttle::host::graph::ProcessVertexAtTimeData::_inputsInfos, tuttle::host::graph::ProcessVertexAtTimeData::ImageEffect::_inputsRoI, tuttle::host::graph::ProcessVertexAtTimeData::_localInfos, tuttle::host::graph::ProcessVertexAtTimeData::_nodeData, tuttle::host::graph::ProcessVertexAtTimeData::_outDegree, tuttle::host::graph::ProcessVertexAtTimeData::ImageEffect::_renderRoI, tuttle::host::graph::ProcessVertexData::_renderScale, tuttle::host::graph::ProcessVertexAtTimeData::_time, tuttle::host::INode::eNodeTypeBuffer, tuttle::host::INode::eNodeTypeGraph, tuttle::host::INode::eNodeTypeImageEffect, tuttle::host::INode::eNodeTypeParam, and tuttle::host::INode::eNodeTypeUnknown.
std::ostream& tuttle::host::graph::operator<< (std::ostream & os, const TestVertex & v) [inline]
Definition at line 30 of file main.cpp.
References tuttle::host::graph::TestVertex::_name.
std::ostream& tuttle::host::graph::operator<< (std::ostream & os, const IEdge & v)
Definition at line 46 of file IEdge.cpp.
References tuttle::host::graph::IEdge::getName().
std::ostream& tuttle::host::graph::operator<< (std::ostream & os, const TestEdge & e) [inline]
Definition at line 54 of file main.cpp.
References tuttle::host::graph::TestEdge::_name.
std::ostream& tuttle::host::graph::operator<< (std::ostream & os, const IVertex & v)
Definition at line 56 of file IVertex.cpp.
References tuttle::host::graph::IVertex::getName().
std::ostream & tuttle::host::graph::operator<< (std::ostream & os, const ProcessVertexAtTime & v)
Definition at line 79 of file ProcessVertexAtTime.cpp.
References tuttle::host::graph::ProcessVertexAtTime::getKey().
std::ostream& tuttle::host::graph::operator<< (std::ostream & os, const ProcessVertex & v)
Definition at line 81 of file ProcessVertex.cpp.
template<typename Vertex , typename Edge > std::ostream& tuttle::host::graph::operator<< (std::ostream & os, const InternalGraph< Vertex, Edge > & g)
Definition at line 157 of file InternalGraph.tcc.
template<class T > detail::SubDotEntry< T > tuttle::host::graph::subDotEntry (const std::string & key, const T & value)
Definition at line 39 of file GraphExporter.tcc.
Referenced by tuttle::host::graph::ProcessEdgeAtTime::exportDotDebug(), tuttle::host::graph::ProcessEdge::exportDotDebug(), tuttle::host::graph::IEdge::exportDotDebug(), tuttle::host::graph::ProcessVertexAtTime::exportDotDebug(), tuttle::host::graph::ProcessVertex::exportDotDebug(), and tuttle::host::graph::IVertex::exportDotDebug().