TuttleOFX: tuttle::plugin::interact::InteractInfos Class Reference
tuttle::plugin::interact::InteractInfos Class Reference
#include <InteractInfos.hpp>
Public Member Functions
InteractInfos (OFX::ImageEffect *effect)
template<typename Value >
Value canonicalXXToNormalizedXX (const Value &point) const
template<typename Value >
Value normalizedXXToCanonicalXX (const Value &point) const
template<typename Value >
Value pointCanonicalXYToNormalizedXY (const Value &point) const
template<typename Point >
Point pointNormalizedXYToCanonicalXY (const Point &point) const
template<typename Point >
Point pointCanonicalXYToNormalizedXXc (const Point &point) const
template<typename Point >
Point pointNormalizedXXcnToCanonicalXY (const Point &point) const
Data Fields
OFX::ImageEffect * _effect
bool _focus
Point2 _lastPenPos
bool _penDown
Point2 _projectSize
ideally must be the RoW and not a project size...
double _marge
Private Types
typedef boost::gil::point2
< double > Point2
Detailed Description
Definition at line 19 of file InteractInfos.hpp.
Member Typedef Documentation
typedef boost::gil::point2<double> tuttle::plugin::interact::InteractInfos::Point2 [private]
Definition at line 21 of file InteractInfos.hpp.
Constructor & Destructor Documentation
tuttle::plugin::interact::InteractInfos::InteractInfos (OFX::ImageEffect * effect) [inline]
Definition at line 24 of file InteractInfos.hpp.
Member Function Documentation
template<typename Value > Value tuttle::plugin::interact::InteractInfos::canonicalXXToNormalizedXX (const Value & point) const [inline]
Definition at line 41 of file InteractInfos.hpp.
References _projectSize, and canonicalXXToNormalizedXX().
Referenced by canonicalXXToNormalizedXX().
template<typename Value > Value tuttle::plugin::interact::InteractInfos::normalizedXXToCanonicalXX (const Value & point) const [inline]
Definition at line 43 of file InteractInfos.hpp.
References _projectSize, and normalizedXXToCanonicalXX().
Referenced by normalizedXXToCanonicalXX().
template<typename Point > Point tuttle::plugin::interact::InteractInfos::pointCanonicalXYToNormalizedXXc (const Point & point) const [inline]
Definition at line 56 of file InteractInfos.hpp.
References _projectSize.
template<typename Value > Value tuttle::plugin::interact::InteractInfos::pointCanonicalXYToNormalizedXY (const Value & point) const [inline]
Definition at line 46 of file InteractInfos.hpp.
References _projectSize, and pointCanonicalXYToNormalizedXY().
Referenced by pointCanonicalXYToNormalizedXY().
template<typename Point > Point tuttle::plugin::interact::InteractInfos::pointNormalizedXXcnToCanonicalXY (const Point & point) const [inline]
Definition at line 67 of file InteractInfos.hpp.
References _projectSize, and tuttle::plugin::pointNormalizedXXcToCanonicalXY().
template<typename Point > Point tuttle::plugin::interact::InteractInfos::pointNormalizedXYToCanonicalXY (const Point & point) const [inline]
Definition at line 48 of file InteractInfos.hpp.
References _projectSize, and pointNormalizedXYToCanonicalXY().
Referenced by pointNormalizedXYToCanonicalXY().
Field Documentation
OFX::ImageEffect* tuttle::plugin::interact::InteractInfos::_effect
Definition at line 33 of file InteractInfos.hpp.
Referenced by tuttle::plugin::interact::PointInteract::getTime().
bool tuttle::plugin::interact::InteractInfos::_focus
Definition at line 34 of file InteractInfos.hpp.
Point2 tuttle::plugin::interact::InteractInfos::_lastPenPos
Definition at line 35 of file InteractInfos.hpp.
double tuttle::plugin::interact::InteractInfos::_marge
Definition at line 38 of file InteractInfos.hpp.
Referenced by tuttle::plugin::interact::SelectionManipulator::getMarge(), and tuttle::plugin::interact::PointInteract::getMarge().
bool tuttle::plugin::interact::InteractInfos::_penDown
Definition at line 36 of file InteractInfos.hpp.
Point2 tuttle::plugin::interact::InteractInfos::_projectSize
ideally must be the RoW and not a project size...
Definition at line 37 of file InteractInfos.hpp.
Referenced by canonicalXXToNormalizedXX(), tuttle::plugin::interact::SelectionManipulator::getMarge(), tuttle::plugin::interact::PointInteract::getMarge(), normalizedXXToCanonicalXX(), pointCanonicalXYToNormalizedXXc(), pointCanonicalXYToNormalizedXY(), pointNormalizedXXcnToCanonicalXY(), and pointNormalizedXYToCanonicalXY().
The documentation for this class was generated from the following file:
TuttleOFX/libraries/tuttle/src/tuttle/plugin/interact/InteractInfos.hpp