TuttleOFX: tuttle::host::ofx::OfxhPluginLoadGuard Class Reference
tuttle::host::ofx::OfxhPluginLoadGuard Class Reference
#include <OfxhPluginLoadGuard.hpp>
Public Member Functions
OfxhPluginLoadGuard (OfxhPlugin &p, OfxhHost &_host)
virtual ~OfxhPluginLoadGuard ()
OfxPlugin * getOfxPlugin ()
const OfxPlugin * getOfxPlugin () const
OfxPlugin * operator-> ()
Private Attributes
OfxhPlugin * _plugin
OfxhPluginBinary * _pluginBinary
OfxPlugin * _rawOfxPlugin
Detailed Description
Wrapper class for Plugin/PluginBinary. Use in a RAII fashion to make sure the binary gets unloaded when needed.
Definition at line 17 of file OfxhPluginLoadGuard.hpp.
Constructor & Destructor Documentation
tuttle::host::ofx::OfxhPluginLoadGuard::OfxhPluginLoadGuard (OfxhPlugin & p, OfxhHost & _host)
Definition at line 13 of file OfxhPluginLoadGuard.cpp.
References tuttle::host::ofx::OfxhPluginBinary::_binary, _plugin, _pluginBinary, _rawOfxPlugin, tuttle::host::ofx::OfxhBinary::findSymbol(), tuttle::host::ofx::OfxhPluginBinary::getBundlePath(), tuttle::host::ofx::OfxhHost::getHandle(), tuttle::host::ofx::OfxhPlugin::getIndex(), tuttle::host::ofx::OfxhBinary::ref(), and tuttle::host::ofx::OfxhBinary::unref().
tuttle::host::ofx::OfxhPluginLoadGuard::~OfxhPluginLoadGuard () [virtual]
Definition at line 35 of file OfxhPluginLoadGuard.cpp.
References tuttle::host::ofx::OfxhPluginBinary::_binary, _pluginBinary, and tuttle::host::ofx::OfxhBinary::unref().
Member Function Documentation
OfxPlugin* tuttle::host::ofx::OfxhPluginLoadGuard::getOfxPlugin () [inline]
Definition at line 28 of file OfxhPluginLoadGuard.hpp.
References _rawOfxPlugin.
Referenced by tuttle::host::ofx::imageEffect::OfxhImageEffectNode::mainEntry(), and tuttle::host::ofx::imageEffect::OfxhImageEffectNode::OfxhImageEffectNode().
const OfxPlugin* tuttle::host::ofx::OfxhPluginLoadGuard::getOfxPlugin () const [inline]
Definition at line 29 of file OfxhPluginLoadGuard.hpp.
References _rawOfxPlugin.
OfxPlugin* tuttle::host::ofx::OfxhPluginLoadGuard::operator-> () [inline]
Definition at line 31 of file OfxhPluginLoadGuard.hpp.
References _rawOfxPlugin.
Field Documentation
OfxhPlugin* tuttle::host::ofx::OfxhPluginLoadGuard::_plugin [private]
Definition at line 19 of file OfxhPluginLoadGuard.hpp.
Referenced by OfxhPluginLoadGuard().
OfxhPluginBinary* tuttle::host::ofx::OfxhPluginLoadGuard::_pluginBinary [private]
Definition at line 20 of file OfxhPluginLoadGuard.hpp.
Referenced by OfxhPluginLoadGuard(), and ~OfxhPluginLoadGuard().
OfxPlugin* tuttle::host::ofx::OfxhPluginLoadGuard::_rawOfxPlugin [private]
Definition at line 22 of file OfxhPluginLoadGuard.hpp.
Referenced by getOfxPlugin(), OfxhPluginLoadGuard(), and operator->().
The documentation for this class was generated from the following files:
TuttleOFX/libraries/tuttle/src/tuttle/host/ofx/OfxhPluginLoadGuard.hpp
TuttleOFX/libraries/tuttle/src/tuttle/host/ofx/OfxhPluginLoadGuard.cpp