TuttleOFX: tuttle::host::Preferences Class Reference
tuttle::host::Preferences Class Reference
#include <Preferences.hpp>
Public Member Functions
Preferences ()
void setTuttleHomePath (const boost::filesystem::path &home)
boost::filesystem::path getTuttleHomePath () const
std::string getTuttleHomeStr () const
boost::filesystem::path getTuttleTempPath () const
boost::filesystem::path buildTuttleTestPath () const
Private Member Functions
boost::filesystem::path buildTuttleHome () const
boost::filesystem::path buildTuttleTemp () const
Private Attributes
boost::filesystem::path _home
boost::filesystem::path _temp
Detailed Description
Definition at line 11 of file Preferences.hpp.
Constructor & Destructor Documentation
tuttle::host::Preferences::Preferences ()
Definition at line 20 of file Preferences.cpp.
Member Function Documentation
boost::filesystem::path tuttle::host::Preferences::buildTuttleHome () const [private]
Definition at line 25 of file Preferences.cpp.
boost::filesystem::path tuttle::host::Preferences::buildTuttleTemp () const [private]
Definition at line 94 of file Preferences.cpp.
boost::filesystem::path tuttle::host::Preferences::buildTuttleTestPath () const
Definition at line 105 of file Preferences.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
boost::filesystem::path tuttle::host::Preferences::getTuttleHomePath () const [inline]
Definition at line 21 of file Preferences.hpp.
References _home.
Referenced by getTuttleHomeStr(), and tuttle::host::Core::preload().
std::string tuttle::host::Preferences::getTuttleHomeStr () const [inline]
Definition at line 22 of file Preferences.hpp.
References getTuttleHomePath().
boost::filesystem::path tuttle::host::Preferences::getTuttleTempPath () const [inline]
Definition at line 24 of file Preferences.hpp.
References _temp.
void tuttle::host::Preferences::setTuttleHomePath (const boost::filesystem::path & home) [inline]
Definition at line 20 of file Preferences.hpp.
References _home.
Field Documentation
boost::filesystem::path tuttle::host::Preferences::_home [private]
Definition at line 14 of file Preferences.hpp.
Referenced by getTuttleHomePath(), and setTuttleHomePath().
boost::filesystem::path tuttle::host::Preferences::_temp [private]
Definition at line 15 of file Preferences.hpp.
Referenced by getTuttleTempPath().
The documentation for this class was generated from the following files:
TuttleOFX/libraries/tuttle/src/tuttle/host/Preferences.hpp
TuttleOFX/libraries/tuttle/src/tuttle/host/Preferences.cpp