TuttleOFX: tuttle::host::attribute::ParamBoolean Class Reference
tuttle::host::attribute::ParamBoolean Class Reference
#include <ParamBoolean.hpp>
Public Member Functions
ParamBoolean (INode &effect, const std::string &name, const ofx::attribute::OfxhParamDescriptor &descriptor, const std::size_t index=0)
virtual ParamBoolean * clone () const
clone this parameter
bool getDefault () const
void getValue (bool &) const OFX_EXCEPTION_SPEC
void getValueAtTime (const OfxTime time, bool &) const OFX_EXCEPTION_SPEC
void setValue (const bool &, const ofx::attribute::EChange change) OFX_EXCEPTION_SPEC
void setValueAtTime (const OfxTime time, const bool &, const ofx::attribute::EChange change) OFX_EXCEPTION_SPEC
void setValueFromExpression (const std::string &value, const ofx::attribute::EChange change) OFX_EXCEPTION_SPEC
void copy (const ParamBoolean &p) OFX_EXCEPTION_SPEC
void copy (const OfxhParam &p) OFX_EXCEPTION_SPEC
Protected Attributes
bool _value
Detailed Description
Definition at line 13 of file ParamBoolean.hpp.
Constructor & Destructor Documentation
tuttle::host::attribute::ParamBoolean::ParamBoolean (INode & effect, const std::string & name, const ofx::attribute::OfxhParamDescriptor & descriptor, const std::size_t index = 0)
Definition at line 10 of file ParamBoolean.cpp.
References _value, and getDefault().
Referenced by clone().
Member Function Documentation
virtual ParamBoolean* tuttle::host::attribute::ParamBoolean::clone () const [inline, virtual]
clone this parameter
Implements tuttle::host::ofx::attribute::OfxhParam.
Definition at line 21 of file ParamBoolean.hpp.
References ParamBoolean().
void tuttle::host::attribute::ParamBoolean::copy (const ParamBoolean & p)
Definition at line 53 of file ParamBoolean.cpp.
References _value.
void tuttle::host::attribute::ParamBoolean::copy (const OfxhParam & p)
Definition at line 59 of file ParamBoolean.cpp.
bool tuttle::host::attribute::ParamBoolean::getDefault () const
Definition at line 20 of file ParamBoolean.cpp.
References tuttle::host::ofx::attribute::OfxhParamBoolean::_index, and tuttle::host::ofx::attribute::OfxhAttribute::getProperties().
Referenced by ParamBoolean().
void tuttle::host::attribute::ParamBoolean::getValue (bool & v) const [virtual]
Implements tuttle::host::ofx::attribute::OfxhParamBoolean.
Definition at line 25 of file ParamBoolean.cpp.
References _value.
void tuttle::host::attribute::ParamBoolean::getValueAtTime (const OfxTime time, bool & v) const [virtual]
<
Todo:
: in time !
Implements tuttle::host::ofx::attribute::OfxhParamBoolean.
Definition at line 30 of file ParamBoolean.cpp.
References _value.
void tuttle::host::attribute::ParamBoolean::setValue (const bool & v, const ofx::attribute::EChange change) [virtual]
Implements tuttle::host::ofx::attribute::OfxhParamBoolean.
Definition at line 35 of file ParamBoolean.cpp.
References _value.
void tuttle::host::attribute::ParamBoolean::setValueAtTime (const OfxTime time, const bool & v, const ofx::attribute::EChange change) [virtual]
<
Todo:
: in time !
Implements tuttle::host::ofx::attribute::OfxhParamBoolean.
Definition at line 41 of file ParamBoolean.cpp.
References _value.
void tuttle::host::attribute::ParamBoolean::setValueFromExpression (const std::string & value, const ofx::attribute::EChange change) [virtual]
Reimplemented from tuttle::host::ofx::attribute::OfxhParam.
Definition at line 47 of file ParamBoolean.cpp.
References _value.
Field Documentation
bool tuttle::host::attribute::ParamBoolean::_value [protected]
Definition at line 17 of file ParamBoolean.hpp.
Referenced by ParamBoolean().
The documentation for this class was generated from the following files:
TuttleOFX/libraries/tuttle/src/tuttle/host/attribute/ParamBoolean.hpp
TuttleOFX/libraries/tuttle/src/tuttle/host/attribute/ParamBoolean.cpp