TuttleOFX: tuttle::host::graph::IVertex Class Reference
tuttle::host::graph::IVertex Class Reference
#include <IVertex.hpp>
Public Member Functions
IVertex (const std::string &name="Undefined")
IVertex (const std::string &name, INode &processNode)
IVertex (const IVertex &v)
virtual ~IVertex ()=0
IVertex & operator= (const IVertex &v)
bool isFake () const
void setUsed (const bool used=true)
bool isUsed () const
const std::string & getName () const
INode & getProcessNode ()
const INode & getProcessNode () const
void setProcessNode (INode *p)
virtual std::ostream & exportDotDebug (std::ostream &os) const
Data Fields
std::string _name
int _id
Private Attributes
INode * _processNode
bool _fake
bool _used
Static Private Attributes
static int _count = 0
Friends
std::ostream & operator<< (std::ostream &os, const IVertex &v)
Detailed Description
Definition at line 15 of file IVertex.hpp.
Constructor & Destructor Documentation
tuttle::host::graph::IVertex::IVertex (const std::string & name = "Undefined")
Definition at line 12 of file IVertex.cpp.
tuttle::host::graph::IVertex::IVertex (const std::string & name, INode & processNode)
Definition at line 20 of file IVertex.cpp.
tuttle::host::graph::IVertex::IVertex (const IVertex & v)
Definition at line 28 of file IVertex.cpp.
References _count, _id, and operator=().
tuttle::host::graph::IVertex::~IVertex () [pure virtual]
Definition at line 34 of file IVertex.cpp.
Member Function Documentation
std::ostream & tuttle::host::graph::IVertex::exportDotDebug (std::ostream & os) const [virtual]
Todo:
remove this. Temporary solution
Reimplemented in tuttle::host::graph::ProcessVertex, and tuttle::host::graph::ProcessVertexAtTime.
Definition at line 39 of file IVertex.cpp.
References tuttle::host::graph::dotEntry(), getName(), getProcessNode(), isFake(), and tuttle::host::graph::subDotEntry().
const std::string& tuttle::host::graph::IVertex::getName () const [inline]
Definition at line 38 of file IVertex.hpp.
References _name.
Referenced by tuttle::host::graph::ProcessGraph::bakeGraphInformationToNodes(), tuttle::host::graph::ProcessGraph::computeTimeRange(), tuttle::host::graph::ProcessVertexAtTime::exportDotDebug(), tuttle::host::graph::ProcessVertex::exportDotDebug(), exportDotDebug(), tuttle::host::graph::UVertex::getKey(), tuttle::host::graph::ProcessVertex::getKey(), getProcessNode(), tuttle::host::graph::operator<<(), and tuttle::host::graph::ProcessGraph::processAtTime().
INode& tuttle::host::graph::IVertex::getProcessNode () [inline]
Definition at line 39 of file IVertex.hpp.
References _processNode, and getName().
Referenced by tuttle::host::Graph::deleteUnconnectedNodes(), tuttle::host::graph::ProcessVertex::exportDotDebug(), tuttle::host::graph::ProcessVertexAtTime::exportDotDebug(), exportDotDebug(), tuttle::host::Graph::getConnectedNodes(), tuttle::host::Graph::getUnconnectedNodes(), tuttle::host::graph::ProcessVertex::operator=(), tuttle::host::graph::ProcessGraph::processAtTime(), tuttle::host::graph::ProcessGraph::relink(), tuttle::host::Graph::replaceNodeConnections(), tuttle::host::graph::ProcessGraph::setup(), and tuttle::host::graph::ProcessGraph::setupAtTime().
const INode& tuttle::host::graph::IVertex::getProcessNode () const [inline]
Definition at line 48 of file IVertex.hpp.
References _processNode, and getName().
bool tuttle::host::graph::IVertex::isFake () const [inline]
Definition at line 35 of file IVertex.hpp.
References _fake.
Referenced by tuttle::host::graph::ProcessVertex::exportDotDebug(), tuttle::host::graph::ProcessVertexAtTime::exportDotDebug(), exportDotDebug(), tuttle::host::graph::ProcessGraph::processAtTime(), tuttle::host::graph::ProcessGraph::relink(), tuttle::host::graph::ProcessGraph::setup(), and tuttle::host::graph::ProcessGraph::setupAtTime().
bool tuttle::host::graph::IVertex::isUsed () const [inline]
Definition at line 37 of file IVertex.hpp.
References _used.
IVertex& tuttle::host::graph::IVertex::operator= (const IVertex & v) [inline]
Definition at line 26 of file IVertex.hpp.
References _fake, _name, _processNode, and _used.
Referenced by IVertex().
void tuttle::host::graph::IVertex::setProcessNode (INode * p) [inline]
Definition at line 57 of file IVertex.hpp.
References _processNode.
Referenced by tuttle::host::graph::ProcessGraph::relink().
void tuttle::host::graph::IVertex::setUsed (const bool used = true) [inline]
Definition at line 36 of file IVertex.hpp.
References _used.
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const IVertex & v) [friend]
Definition at line 56 of file IVertex.cpp.
Field Documentation
int tuttle::host::graph::IVertex::_count = 0 [static, private]
Definition at line 72 of file IVertex.hpp.
Referenced by IVertex().
bool tuttle::host::graph::IVertex::_fake [private]
Definition at line 70 of file IVertex.hpp.
Referenced by isFake(), and operator=().
int tuttle::host::graph::IVertex::_id
Definition at line 75 of file IVertex.hpp.
Referenced by IVertex().
std::string tuttle::host::graph::IVertex::_name
Definition at line 66 of file IVertex.hpp.
Referenced by tuttle::host::graph::exportAsDOT(), getName(), operator=(), and tuttle::host::graph::ProcessVertexAtTime::ProcessVertexAtTime().
INode* tuttle::host::graph::IVertex::_processNode [private]
Definition at line 69 of file IVertex.hpp.
Referenced by getProcessNode(), operator=(), and setProcessNode().
bool tuttle::host::graph::IVertex::_used [private]
Definition at line 71 of file IVertex.hpp.
Referenced by isUsed(), operator=(), and setUsed().
The documentation for this class was generated from the following files:
TuttleOFX/libraries/tuttle/src/tuttle/host/graph/IVertex.hpp
TuttleOFX/libraries/tuttle/src/tuttle/host/graph/IVertex.cpp