TuttleOFX: tuttle::plugin::interact::InteractObject Class Reference
tuttle::plugin::interact::InteractObject Class Reference
A base class for all object to use in interact or overlay. All sub classes needs to implement virtual functions from OFX::InteractI.
#include <InteractObject.hpp>
Public Member Functions
InteractObject ()
virtual ~InteractObject ()=0
virtual bool draw (const OFX::DrawArgs &args) const
the function called to draw in the interact
virtual MotionType intersect (const OFX::PenArgs &args)
virtual bool isIn (const OfxRectD &)
virtual Point2 getPosition () const
virtual void setPosition (const Point2 &)
virtual void setPositionX (const Scalar x)
virtual void setPositionY (const Scalar y)
virtual void translate (const Point2 &previous, const Point2 &vec)
virtual void rotate (const Point2 &previous, const Point2 &center, const Point2 &from, const Point2 &vec)
virtual void scale (const Point2 &previous, const Point2 &center, const Point2 &factor)
virtual void beginMove (const Point2 &penPosition)
virtual void endMove (const Point2 &penPosition)
bool getSelected () const
void setSelected (const bool s)
Private Attributes
bool _selected
Detailed Description
A base class for all object to use in interact or overlay. All sub classes needs to implement virtual functions from OFX::InteractI.
Definition at line 21 of file InteractObject.hpp.
Constructor & Destructor Documentation
tuttle::plugin::interact::InteractObject::InteractObject ()
Definition at line 7 of file InteractObject.cpp.
tuttle::plugin::interact::InteractObject::~InteractObject () [pure virtual]
Definition at line 11 of file InteractObject.cpp.
Member Function Documentation
virtual void tuttle::plugin::interact::InteractObject::beginMove (const Point2 & penPosition) [inline, virtual]
Reimplemented in tuttle::plugin::interact::SelectionManipulator.
Definition at line 63 of file InteractObject.hpp.
virtual bool tuttle::plugin::interact::InteractObject::draw (const OFX::DrawArgs & args) const [inline, virtual]
the function called to draw in the interact
Reimplemented in tuttle::plugin::interact::ParamRectangleFromCenterSize< TFrame, coord >, tuttle::plugin::interact::InteractScene, tuttle::plugin::interact::ParamTangent< TFrame, coord >, tuttle::plugin::interact::ParamRectangleFromTwoCorners< TFrame, coord >, and tuttle::plugin::interact::PointInteract.
Definition at line 28 of file InteractObject.hpp.
Referenced by tuttle::plugin::interact::InteractScene::drawSelection().
virtual void tuttle::plugin::interact::InteractObject::endMove (const Point2 & penPosition) [inline, virtual]
Reimplemented in tuttle::plugin::interact::SelectionManipulator.
Definition at line 64 of file InteractObject.hpp.
virtual Point2 tuttle::plugin::interact::InteractObject::getPosition () const [inline, virtual]
Reimplemented in tuttle::plugin::interact::PointInteract.
Definition at line 39 of file InteractObject.hpp.
Referenced by tuttle::plugin::interact::InteractScene::penMotion(), tuttle::plugin::interact::SelectionManipulator::setPositionX(), and tuttle::plugin::interact::SelectionManipulator::setPositionY().
bool tuttle::plugin::interact::InteractObject::getSelected () const [inline]
Definition at line 66 of file InteractObject.hpp.
References _selected.
Referenced by tuttle::plugin::interact::PointInteract::draw(), and tuttle::plugin::interact::ParamPointRelativePoint< TFrame, coord >::setPoint().
virtual MotionType tuttle::plugin::interact::InteractObject::intersect (const OFX::PenArgs & args) [inline, virtual]
Reimplemented in tuttle::plugin::interact::ParamRectangleFromCenterSize< TFrame, coord >, tuttle::plugin::interact::ParamRectangleFromTwoCorners< TFrame, coord >, tuttle::plugin::interact::ParamTangent< TFrame, coord >, tuttle::plugin::interact::PointInteract, and tuttle::plugin::interact::SelectionManipulator.
Definition at line 30 of file InteractObject.hpp.
References tuttle::plugin::interact::MotionType::_axis, tuttle::plugin::interact::MotionType::_mode, tuttle::plugin::interact::eAxisNone, and tuttle::plugin::interact::eMotionNone.
Referenced by tuttle::plugin::interact::InteractScene::penDown().
virtual bool tuttle::plugin::interact::InteractObject::isIn (const OfxRectD &) [inline, virtual]
Reimplemented in tuttle::plugin::interact::ParamRectangleFromCenterSize< TFrame, coord >, tuttle::plugin::interact::ParamRectangleFromTwoCorners< TFrame, coord >, and tuttle::plugin::interact::PointInteract.
Definition at line 37 of file InteractObject.hpp.
virtual void tuttle::plugin::interact::InteractObject::rotate (const Point2 & previous, const Point2 & center, const Point2 & from, const Point2 & vec) [inline, virtual]
Definition at line 48 of file InteractObject.hpp.
virtual void tuttle::plugin::interact::InteractObject::scale (const Point2 & previous, const Point2 & center, const Point2 & factor) [inline, virtual]
Definition at line 59 of file InteractObject.hpp.
virtual void tuttle::plugin::interact::InteractObject::setPosition (const Point2 &) [inline, virtual]
Reimplemented in tuttle::plugin::interact::SelectionManipulator, and tuttle::plugin::interact::PointInteract.
Definition at line 40 of file InteractObject.hpp.
Referenced by translate().
virtual void tuttle::plugin::interact::InteractObject::setPositionX (const Scalar x) [inline, virtual]
Reimplemented in tuttle::plugin::interact::SelectionManipulator, and tuttle::plugin::interact::PointInteract.
Definition at line 41 of file InteractObject.hpp.
virtual void tuttle::plugin::interact::InteractObject::setPositionY (const Scalar y) [inline, virtual]
Reimplemented in tuttle::plugin::interact::SelectionManipulator, and tuttle::plugin::interact::PointInteract.
Definition at line 42 of file InteractObject.hpp.
void tuttle::plugin::interact::InteractObject::setSelected (const bool s) [inline]
Definition at line 67 of file InteractObject.hpp.
References _selected.
virtual void tuttle::plugin::interact::InteractObject::translate (const Point2 & previous, const Point2 & vec) [inline, virtual]
Reimplemented in tuttle::plugin::interact::ParamTangent< TFrame, coord >.
Definition at line 44 of file InteractObject.hpp.
References setPosition().
Field Documentation
bool tuttle::plugin::interact::InteractObject::_selected [private]
Reimplemented in tuttle::plugin::interact::InteractScene.
Definition at line 70 of file InteractObject.hpp.
Referenced by getSelected(), and setSelected().
The documentation for this class was generated from the following files:
TuttleOFX/libraries/tuttle/src/tuttle/plugin/interact/InteractObject.hpp
TuttleOFX/libraries/tuttle/src/tuttle/plugin/interact/InteractObject.cpp