TuttleOFX: tuttle::host::ofx::attribute::OfxhParam Class Reference
tuttle::host::ofx::attribute::OfxhParam Class Reference
plugin parameter instance
#include <OfxhParam.hpp>
Public Types
typedef OfxhParam This
Public Member Functions
OfxhParam (const OfxhParamDescriptor &descriptor, const std::string &name, OfxhParamSet &setInstance)
make a parameter, with the given type and name
virtual ~OfxhParam ()=0
virtual This * clone () const =0
clone this parameter
virtual bool paramTypeHasData () const =0
virtual std::size_t getHashAtTime (const OfxTime time) const =0
bool operator== (const This &p) const
OfxParamHandle getParamHandle () const
grab a handle on the parameter for passing to the C API
virtual std::ostream & displayValues (std::ostream &os) const
void paramChanged (const EChange change)
void changedActionBegin ()
void changedActionEnd ()
bool changedActionInProgress () const
OfxhParamSet * getParamSetInstance ()
void setParamSetInstance (OfxhParamSet *instance)
void setParentInstance (OfxhParam *instance)
OfxhParam * getParentInstance ()
virtual void copy (const OfxhParam &instance) OFX_EXCEPTION_SPEC=0
virtual void copy (const OfxhParam &instance, OfxTime offset) OFX_EXCEPTION_SPEC
virtual void copy (const OfxhParam &instance, OfxTime offset, OfxRangeD range) OFX_EXCEPTION_SPEC
virtual void setEnabled ()
virtual void setSecret ()
virtual void setLabel ()
callback which should update label
virtual void setDisplayRange ()
callback which should set
virtual std::size_t getSize () const
TUTTLE_DEFINE_OFXHPARAM_ACCESSORS (String, std::string)
TUTTLE_DEFINE_OFXHPARAM_ACCESSORS (Double, double)
TUTTLE_DEFINE_OFXHPARAM_ACCESSORS (Int, int)
TUTTLE_DEFINE_OFXHPARAM_ACCESSORS (Bool, bool)
TUTTLE_DEFINE_OFXHPARAM_MULTIDIM_ACCESSORS (String, std::string)
TUTTLE_DEFINE_OFXHPARAM_MULTIDIM_ACCESSORS (Double, double)
TUTTLE_DEFINE_OFXHPARAM_MULTIDIM_ACCESSORS (Int, int)
TUTTLE_DEFINE_OFXHPARAM_MULTIDIM_ACCESSORS (Bool, bool)
virtual void setValueFromExpression (const std::string &value, const EChange change) OFX_EXCEPTION_SPEC
void setValueFromExpression (const std::string &value) OFX_EXCEPTION_SPEC
void setValue (const char *value, const EChange change) OFX_EXCEPTION_SPEC
void setValue (const char *value) OFX_EXCEPTION_SPEC
void setValueAtTime (const OfxTime time, const char *value, const attribute::EChange change) OFX_EXCEPTION_SPEC
void setValueAtTime (const OfxTime time, const char *value) OFX_EXCEPTION_SPEC
virtual void setInterpolator (const enum EInterpolatorType etype) OFX_EXCEPTION_SPEC
virtual void getV (va_list arg) const OFX_EXCEPTION_SPEC
get a value, implemented by instances to deconstruct var args
virtual void getV (const OfxTime time, va_list arg) const OFX_EXCEPTION_SPEC
get a value, implemented by instances to deconstruct var args
virtual void setV (va_list arg, const EChange change) OFX_EXCEPTION_SPEC
set a value, implemented by instances to deconstruct var args
virtual void setV (const OfxTime time, va_list arg, const EChange change) OFX_EXCEPTION_SPEC
key a value, implemented by instances to deconstruct var args
virtual void deriveV (const OfxTime time, va_list arg) const OFX_EXCEPTION_SPEC
derive a value, implemented by instances to deconstruct var args
virtual void integrateV (const OfxTime time1, const OfxTime time2, va_list arg) const OFX_EXCEPTION_SPEC
integrate a value, implemented by instances to deconstruct var args
virtual void notify (const std::string &name, bool single, int num) OFX_EXCEPTION_SPEC
overridden from Property::NotifyHook
Protected Member Functions
OfxhParam (const OfxhParam &other)
Protected Attributes
OfxhParamSet * _paramSetInstance
OfxhParam * _parentInstance
bool _avoidRecursion
Avoid recursion when updating with paramChangedAction.
Private Member Functions
OfxhParam ()
Friends
std::ostream & operator<< (std::ostream &os, const This &g)
Detailed Description
plugin parameter instance
Definition at line 118 of file OfxhParam.hpp.
Member Typedef Documentation
typedef OfxhParam tuttle::host::ofx::attribute::OfxhParam::This
Reimplemented from tuttle::host::ofx::attribute::OfxhAttribute.
Reimplemented in tuttle::host::attribute::AnimatedParam< double, ofx::attribute::OfxhParamDouble >.
Definition at line 127 of file OfxhParam.hpp.
Constructor & Destructor Documentation
tuttle::host::ofx::attribute::OfxhParam::OfxhParam () [private]
tuttle::host::ofx::attribute::OfxhParam::OfxhParam (const OfxhParam & other) [inline, protected]
Todo:
tuttle : copy content, not pointer ?
Definition at line 135 of file OfxhParam.hpp.
tuttle::host::ofx::attribute::OfxhParam::OfxhParam (const OfxhParamDescriptor & descriptor, const std::string & name, attribute::OfxhParamSet & setInstance) [explicit]
make a parameter, with the given type and name
Definition at line 15 of file OfxhParam.cpp.
References tuttle::host::ofx::property::OfxhSet::addNotifyHook(), and tuttle::host::ofx::attribute::OfxhAttribute::getEditableProperties().
tuttle::host::ofx::attribute::OfxhParam::~OfxhParam () [pure virtual]
the description of a plugin parameter
Definition at line 32 of file OfxhParam.cpp.
Member Function Documentation
void tuttle::host::ofx::attribute::OfxhParam::changedActionBegin () [inline]
Definition at line 195 of file OfxhParam.hpp.
References _avoidRecursion.
void tuttle::host::ofx::attribute::OfxhParam::changedActionEnd () [inline]
Definition at line 196 of file OfxhParam.hpp.
References _avoidRecursion.
bool tuttle::host::ofx::attribute::OfxhParam::changedActionInProgress () const [inline]
Definition at line 197 of file OfxhParam.hpp.
References _avoidRecursion.
virtual This* tuttle::host::ofx::attribute::OfxhParam::clone () const [pure virtual]
clone this parameter
Implemented in tuttle::host::attribute::AnimatedParam< double, ofx::attribute::OfxhParamDouble >, tuttle::host::attribute::ParamBoolean, tuttle::host::attribute::ParamCustom, tuttle::host::attribute::ParamString, tuttle::host::attribute::ParamChoice, tuttle::host::attribute::ParamRGB, tuttle::host::attribute::ParamRGBA, tuttle::host::attribute::ParamInteger2D, tuttle::host::attribute::ParamInteger3D, tuttle::host::attribute::ParamGroup, tuttle::host::attribute::ParamPage, tuttle::host::attribute::ParamPushButton, tuttle::host::attribute::ParamDouble2D, and tuttle::host::attribute::ParamDouble3D.
Referenced by tuttle::host::ofx::attribute::new_clone().
virtual void tuttle::host::ofx::attribute::OfxhParam::copy (const OfxhParam & instance) [pure virtual]
Implemented in tuttle::host::attribute::AnimatedParam< double, ofx::attribute::OfxhParamDouble >, tuttle::host::ofx::attribute::OfxhMultiDimParam< T, DIM >, tuttle::host::ofx::attribute::OfxhMultiDimParam< ParamInteger, 3 >, tuttle::host::ofx::attribute::OfxhMultiDimParam< ParamInteger, 2 >, and tuttle::host::ofx::attribute::OfxhMultiDimParam< ParamDouble, DIM >.
Referenced by tuttle::host::ofx::attribute::OfxhParamSet::copyParamsValues().
void tuttle::host::ofx::attribute::OfxhParam::copy (const OfxhParam & instance, OfxTime offset) [virtual]
copy one parameter to another
Definition at line 133 of file OfxhParam.cpp.
void tuttle::host::ofx::attribute::OfxhParam::copy (const OfxhParam & instance, OfxTime offset, OfxRangeD range) [virtual]
copy one parameter to another, with a range
Definition at line 141 of file OfxhParam.cpp.
void tuttle::host::ofx::attribute::OfxhParam::deriveV (const OfxTime time, va_list arg) const [virtual]
derive a value, implemented by instances to deconstruct var args
Reimplemented in tuttle::host::ofx::attribute::OfxhMultiDimParam< T, DIM >, tuttle::host::ofx::attribute::OfxhMultiDimParam< ParamInteger, 3 >, tuttle::host::ofx::attribute::OfxhMultiDimParam< ParamInteger, 2 >, tuttle::host::ofx::attribute::OfxhMultiDimParam< ParamDouble, DIM >, tuttle::host::ofx::attribute::OfxhParamInteger, and tuttle::host::ofx::attribute::OfxhParamDouble.
Definition at line 94 of file OfxhParam.cpp.
virtual std::ostream& tuttle::host::ofx::attribute::OfxhParam::displayValues (std::ostream & os) const [inline, virtual]
Reimplemented in tuttle::host::ofx::attribute::OfxhMultiDimParam< T, DIM >, tuttle::host::ofx::attribute::OfxhMultiDimParam< ParamInteger, 3 >, tuttle::host::ofx::attribute::OfxhMultiDimParam< ParamInteger, 2 >, tuttle::host::ofx::attribute::OfxhMultiDimParam< ParamDouble, DIM >, tuttle::host::ofx::attribute::OfxhParamInteger, tuttle::host::ofx::attribute::OfxhParamDouble, and tuttle::host::ofx::attribute::OfxhParamString.
Definition at line 171 of file OfxhParam.hpp.
virtual std::size_t tuttle::host::ofx::attribute::OfxhParam::getHashAtTime (const OfxTime time) const [pure virtual]
Implemented in tuttle::host::attribute::AnimatedParam< double, ofx::attribute::OfxhParamDouble >, tuttle::host::ofx::attribute::OfxhMultiDimParam< T, DIM >, tuttle::host::ofx::attribute::OfxhMultiDimParam< ParamInteger, 3 >, tuttle::host::ofx::attribute::OfxhMultiDimParam< ParamInteger, 2 >, tuttle::host::ofx::attribute::OfxhMultiDimParam< ParamDouble, DIM >, tuttle::host::ofx::attribute::OfxhParamChoice, tuttle::host::ofx::attribute::OfxhParamBoolean, tuttle::host::ofx::attribute::OfxhParamGroup, tuttle::host::ofx::attribute::OfxhParamString, tuttle::host::ofx::attribute::OfxhParamPage, and tuttle::host::ofx::attribute::OfxhParamPushButton.
Referenced by tuttle::host::ofx::attribute::OfxhParamSet::getHashAtTime().
OfxParamHandle tuttle::host::ofx::attribute::OfxhParam::getParamHandle () const [inline, virtual]
grab a handle on the parameter for passing to the C API
Implements tuttle::host::ofx::attribute::OfxhParamAccessor.
Definition at line 165 of file OfxhParam.hpp.
OfxhParamSet* tuttle::host::ofx::attribute::OfxhParam::getParamSetInstance () [inline]
Definition at line 200 of file OfxhParam.hpp.
References _paramSetInstance.
OfxhParam * tuttle::host::ofx::attribute::OfxhParam::getParentInstance ()
Definition at line 151 of file OfxhParam.cpp.
References _parentInstance.
virtual std::size_t tuttle::host::ofx::attribute::OfxhParam::getSize () const [inline, virtual]
Reimplemented in tuttle::host::ofx::attribute::OfxhMultiDimParam< T, DIM >, tuttle::host::ofx::attribute::OfxhMultiDimParam< ParamInteger, 3 >, tuttle::host::ofx::attribute::OfxhMultiDimParam< ParamInteger, 2 >, and tuttle::host::ofx::attribute::OfxhMultiDimParam< ParamDouble, DIM >.
Definition at line 235 of file OfxhParam.hpp.
void tuttle::host::ofx::attribute::OfxhParam::getV (va_list arg) const [virtual]
get a value, implemented by instances to deconstruct var args
Reimplemented in tuttle::host::ofx::attribute::OfxhMultiDimParam< T, DIM >, tuttle::host::ofx::attribute::OfxhMultiDimParam< ParamInteger, 3 >, tuttle::host::ofx::attribute::OfxhMultiDimParam< ParamInteger, 2 >, tuttle::host::ofx::attribute::OfxhMultiDimParam< ParamDouble, DIM >, tuttle::host::ofx::attribute::OfxhParamInteger, tuttle::host::ofx::attribute::OfxhParamDouble, tuttle::host::ofx::attribute::OfxhParamChoice, tuttle::host::ofx::attribute::OfxhParamBoolean, and tuttle::host::ofx::attribute::OfxhParamString.
Definition at line 62 of file OfxhParam.cpp.
void tuttle::host::ofx::attribute::OfxhParam::getV (const OfxTime time, va_list arg) const [virtual]
get a value, implemented by instances to deconstruct var args
Reimplemented in tuttle::host::ofx::attribute::OfxhMultiDimParam< T, DIM >, tuttle::host::ofx::attribute::OfxhMultiDimParam< ParamInteger, 3 >, tuttle::host::ofx::attribute::OfxhMultiDimParam< ParamInteger, 2 >, tuttle::host::ofx::attribute::OfxhMultiDimParam< ParamDouble, DIM >, tuttle::host::ofx::attribute::OfxhParamInteger, tuttle::host::ofx::attribute::OfxhParamDouble, tuttle::host::ofx::attribute::OfxhParamChoice, tuttle::host::ofx::attribute::OfxhParamBoolean, and tuttle::host::ofx::attribute::OfxhParamString.
Definition at line 70 of file OfxhParam.cpp.
void tuttle::host::ofx::attribute::OfxhParam::integrateV (const OfxTime time1, const OfxTime time2, va_list arg) const [virtual]
integrate a value, implemented by instances to deconstruct var args
Reimplemented in tuttle::host::ofx::attribute::OfxhMultiDimParam< T, DIM >, tuttle::host::ofx::attribute::OfxhMultiDimParam< ParamInteger, 3 >, tuttle::host::ofx::attribute::OfxhMultiDimParam< ParamInteger, 2 >, tuttle::host::ofx::attribute::OfxhMultiDimParam< ParamDouble, DIM >, tuttle::host::ofx::attribute::OfxhParamInteger, and tuttle::host::ofx::attribute::OfxhParamDouble.
Definition at line 102 of file OfxhParam.cpp.
void tuttle::host::ofx::attribute::OfxhParam::notify (const std::string & name, bool single, int num) [virtual]
overridden from Property::NotifyHook
Implements tuttle::host::ofx::property::OfxhNotifyHook.
Definition at line 110 of file OfxhParam.cpp.
bool tuttle::host::ofx::attribute::OfxhParam::operator== (const This & p) const [inline]
Todo:
tuttle: check values !!!
Definition at line 162 of file OfxhParam.hpp.
void tuttle::host::ofx::attribute::OfxhParam::paramChanged (const EChange change)
Definition at line 34 of file OfxhParam.cpp.
References _paramSetInstance, and tuttle::host::ofx::attribute::OfxhParamSet::paramChanged().
Referenced by tuttle::host::ofx::attribute::OfxhMultiDimParam< ParamDouble, DIM >::setV(), tuttle::host::ofx::attribute::OfxhMultiDimParam< ParamDouble, DIM >::setValue(), tuttle::host::ofx::attribute::OfxhMultiDimParam< ParamDouble, DIM >::setValueAtIndex(), tuttle::host::ofx::attribute::OfxhMultiDimParam< ParamDouble, DIM >::setValueAtTime(), tuttle::host::ofx::attribute::OfxhMultiDimParam< ParamDouble, DIM >::setValueAtTimeAndIndex(), and tuttle::host::ofx::attribute::OfxhMultiDimParam< ParamDouble, DIM >::setValueFromExpression().
virtual bool tuttle::host::ofx::attribute::OfxhParam::paramTypeHasData () const [pure virtual]
Implemented in tuttle::host::attribute::AnimatedParam< double, ofx::attribute::OfxhParamDouble >, tuttle::host::ofx::attribute::OfxhMultiDimParam< T, DIM >, tuttle::host::ofx::attribute::OfxhMultiDimParam< ParamInteger, 3 >, tuttle::host::ofx::attribute::OfxhMultiDimParam< ParamInteger, 2 >, tuttle::host::ofx::attribute::OfxhMultiDimParam< ParamDouble, DIM >, tuttle::host::ofx::attribute::OfxhParamChoice, tuttle::host::ofx::attribute::OfxhParamBoolean, tuttle::host::ofx::attribute::OfxhParamGroup, tuttle::host::ofx::attribute::OfxhParamString, tuttle::host::ofx::attribute::OfxhParamPage, and tuttle::host::ofx::attribute::OfxhParamPushButton.
Referenced by tuttle::host::ofx::attribute::OfxhParamSet::getHashAtTime().
void tuttle::host::ofx::attribute::OfxhParam::setDisplayRange () [virtual]
callback which should set
Definition at line 57 of file OfxhParam.cpp.
void tuttle::host::ofx::attribute::OfxhParam::setEnabled () [virtual]
callback which should set enabled state as appropriate
Definition at line 42 of file OfxhParam.cpp.
virtual void tuttle::host::ofx::attribute::OfxhParam::setInterpolator (const enum EInterpolatorType etype) [inline, virtual]
Reimplemented in tuttle::host::attribute::AnimatedParam< double, ofx::attribute::OfxhParamDouble >.
Definition at line 263 of file OfxhParam.hpp.
void tuttle::host::ofx::attribute::OfxhParam::setLabel () [virtual]
callback which should update label
Definition at line 52 of file OfxhParam.cpp.
void tuttle::host::ofx::attribute::OfxhParam::setParamSetInstance (OfxhParamSet * instance) [inline]
Definition at line 201 of file OfxhParam.hpp.
References _paramSetInstance.
Referenced by tuttle::host::ofx::attribute::OfxhParamSet::declareChildParam().
void tuttle::host::ofx::attribute::OfxhParam::setParentInstance (OfxhParam * instance)
Definition at line 146 of file OfxhParam.cpp.
References _parentInstance.
void tuttle::host::ofx::attribute::OfxhParam::setSecret () [virtual]
callback which should set secret state as appropriate
Definition at line 47 of file OfxhParam.cpp.
void tuttle::host::ofx::attribute::OfxhParam::setV (va_list arg, const EChange change) [virtual]
set a value, implemented by instances to deconstruct var args
Reimplemented in tuttle::host::ofx::attribute::OfxhMultiDimParam< T, DIM >, tuttle::host::ofx::attribute::OfxhMultiDimParam< ParamInteger, 3 >, tuttle::host::ofx::attribute::OfxhMultiDimParam< ParamInteger, 2 >, tuttle::host::ofx::attribute::OfxhMultiDimParam< ParamDouble, DIM >, tuttle::host::ofx::attribute::OfxhParamInteger, tuttle::host::ofx::attribute::OfxhParamDouble, tuttle::host::ofx::attribute::OfxhParamChoice, tuttle::host::ofx::attribute::OfxhParamBoolean, and tuttle::host::ofx::attribute::OfxhParamString.
Definition at line 78 of file OfxhParam.cpp.
void tuttle::host::ofx::attribute::OfxhParam::setV (const OfxTime time, va_list arg, const EChange change) [virtual]
key a value, implemented by instances to deconstruct var args
Reimplemented in tuttle::host::ofx::attribute::OfxhMultiDimParam< T, DIM >, tuttle::host::ofx::attribute::OfxhMultiDimParam< ParamInteger, 3 >, tuttle::host::ofx::attribute::OfxhMultiDimParam< ParamInteger, 2 >, tuttle::host::ofx::attribute::OfxhMultiDimParam< ParamDouble, DIM >, tuttle::host::ofx::attribute::OfxhParamInteger, tuttle::host::ofx::attribute::OfxhParamDouble, tuttle::host::ofx::attribute::OfxhParamChoice, tuttle::host::ofx::attribute::OfxhParamBoolean, and tuttle::host::ofx::attribute::OfxhParamString.
Definition at line 86 of file OfxhParam.cpp.
void tuttle::host::ofx::attribute::OfxhParam::setValue (const char * value, const EChange change) [inline]
Definition at line 255 of file OfxhParam.hpp.
References setValue().
Referenced by BOOST_AUTO_TEST_CASE(), tuttle::host::io::getBestReader(), tuttle::host::OutputBufferWrapper::setCallback(), and setValue().
void tuttle::host::ofx::attribute::OfxhParam::setValue (const char * value) [inline]
Definition at line 256 of file OfxhParam.hpp.
References tuttle::host::ofx::attribute::eChangeUserEdited, and setValue().
Referenced by setValue().
void tuttle::host::ofx::attribute::OfxhParam::setValueAtTime (const OfxTime time, const char * value, const attribute::EChange change) [inline]
Definition at line 257 of file OfxhParam.hpp.
References setValueAtTime().
Referenced by setValueAtTime().
void tuttle::host::ofx::attribute::OfxhParam::setValueAtTime (const OfxTime time, const char * value) [inline]
Definition at line 258 of file OfxhParam.hpp.
References tuttle::host::ofx::attribute::eChangeUserEdited, and setValueAtTime().
Referenced by setValueAtTime().
virtual void tuttle::host::ofx::attribute::OfxhParam::setValueFromExpression (const std::string & value, const EChange change) [inline, virtual]
Reimplemented in tuttle::host::attribute::AnimatedParam< double, ofx::attribute::OfxhParamDouble >, tuttle::host::ofx::attribute::OfxhMultiDimParam< T, DIM >, tuttle::host::ofx::attribute::OfxhMultiDimParam< ParamInteger, 3 >, tuttle::host::ofx::attribute::OfxhMultiDimParam< ParamInteger, 2 >, tuttle::host::ofx::attribute::OfxhMultiDimParam< ParamDouble, DIM >, tuttle::host::ofx::attribute::OfxhParamPage, tuttle::host::attribute::ParamBoolean, tuttle::host::attribute::ParamCustom, tuttle::host::attribute::ParamString, tuttle::host::attribute::ParamChoice, and tuttle::host::ofx::attribute::OfxhParamPushButton.
Definition at line 252 of file OfxhParam.hpp.
References tuttle::host::ofx::attribute::OfxhAttributeAccessor::getName(), tuttle::host::ofx::attribute::OfxhParamAccessor::getParamType(), and tuttle::host::ofx::attribute::mapChangeEnumToString().
void tuttle::host::ofx::attribute::OfxhParam::setValueFromExpression (const std::string & value) [inline]
Reimplemented in tuttle::host::ofx::attribute::OfxhParamPage, and tuttle::host::ofx::attribute::OfxhParamPushButton.
Definition at line 253 of file OfxhParam.hpp.
References tuttle::host::ofx::attribute::eChangeUserEdited, and setValueFromExpression().
Referenced by setValueFromExpression().
tuttle::host::ofx::attribute::OfxhParam::TUTTLE_DEFINE_OFXHPARAM_ACCESSORS (String , std::string)
tuttle::host::ofx::attribute::OfxhParam::TUTTLE_DEFINE_OFXHPARAM_ACCESSORS (Double , double)
tuttle::host::ofx::attribute::OfxhParam::TUTTLE_DEFINE_OFXHPARAM_ACCESSORS (Int , int)
tuttle::host::ofx::attribute::OfxhParam::TUTTLE_DEFINE_OFXHPARAM_ACCESSORS (Bool , bool)
tuttle::host::ofx::attribute::OfxhParam::TUTTLE_DEFINE_OFXHPARAM_MULTIDIM_ACCESSORS (String , std::string)
tuttle::host::ofx::attribute::OfxhParam::TUTTLE_DEFINE_OFXHPARAM_MULTIDIM_ACCESSORS (Double , double)
tuttle::host::ofx::attribute::OfxhParam::TUTTLE_DEFINE_OFXHPARAM_MULTIDIM_ACCESSORS (Int , int)
tuttle::host::ofx::attribute::OfxhParam::TUTTLE_DEFINE_OFXHPARAM_MULTIDIM_ACCESSORS (Bool , bool)
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const This & g) [friend]
Definition at line 156 of file OfxhParam.cpp.
Field Documentation
bool tuttle::host::ofx::attribute::OfxhParam::_avoidRecursion [protected]
Avoid recursion when updating with paramChangedAction.
Definition at line 132 of file OfxhParam.hpp.
Referenced by changedActionBegin(), changedActionEnd(), and changedActionInProgress().
OfxhParamSet* tuttle::host::ofx::attribute::OfxhParam::_paramSetInstance [protected]
Definition at line 130 of file OfxhParam.hpp.
Referenced by tuttle::host::ofx::attribute::OfxhParamGroup::editBegin(), tuttle::host::ofx::attribute::OfxhParamGroup::editEnd(), tuttle::host::ofx::attribute::OfxhParamPage::getChildren(), getParamSetInstance(), tuttle::host::ofx::attribute::OfxhParamGroup::getParamSetProps(), tuttle::host::ofx::attribute::OfxhParamGroup::paramChanged(), paramChanged(), and setParamSetInstance().
OfxhParam* tuttle::host::ofx::attribute::OfxhParam::_parentInstance [protected]
Definition at line 131 of file OfxhParam.hpp.
Referenced by getParentInstance(), and setParentInstance().
The documentation for this class was generated from the following files:
TuttleOFX/libraries/tuttle/src/tuttle/host/ofx/attribute/OfxhParam.hpp
TuttleOFX/libraries/tuttle/src/tuttle/host/ofx/attribute/OfxhParam.cpp