TuttleOFX: TuttleOFX/libraries/tuttle/src/tuttle/common/system/memoryInfo.hpp File Reference
TuttleOFX/libraries/tuttle/src/tuttle/common/system/memoryInfo.hpp File Reference
#include <cstddef>
#include <ostream>
Data Structures
struct MemoryInfo
Functions
MemoryInfo getMemoryInfo ()
std::ostream & operator<< (std::ostream &os, const MemoryInfo &infos)
Function Documentation
MemoryInfo getMemoryInfo ()
Definition at line 21 of file memoryInfo.cpp.
References MemoryInfo::_freeRam, MemoryInfo::_freeSwap, MemoryInfo::_totalRam, MemoryInfo::_totalSwap, tuttle::max(), TUTTLE_INFO, and TUTTLE_LOG_DEBUG.
Referenced by tuttle::host::memory::operator<<(), and tuttle::host::memory::MemoryPool::updateMemoryAuthorizedWithRAM().
std::ostream& operator<< (std::ostream & os, const MemoryInfo & infos)
Definition at line 93 of file memoryInfo.cpp.
References MemoryInfo::_freeRam, MemoryInfo::_freeSwap, MemoryInfo::_totalRam, and MemoryInfo::_totalSwap.