TuttleOFX: tuttle::host::graph::ProcessVertexAtTime Class Reference
tuttle::host::graph::ProcessVertexAtTime Class Reference
#include <ProcessVertexAtTime.hpp>
Public Types
typedef NodeAtTimeKey Key
Public Member Functions
ProcessVertexAtTime ()
ProcessVertexAtTime (const ProcessVertex &v, const OfxTime t)
ProcessVertexAtTime (const ProcessVertexAtTime &other)
virtual ~ProcessVertexAtTime ()
ProcessVertexAtTime & operator= (const ProcessVertexAtTime &v)
Key getKey () const
const ProcessVertexData & getProcessData () const
ProcessVertexAtTimeData & getProcessDataAtTime ()
const ProcessVertexAtTimeData & getProcessDataAtTime () const
std::ostream & exportDotDebug (std::ostream &os) const
Data Fields
std::string _clipName
ProcessVertexAtTimeData _data
Friends
std::ostream & operator<< (std::ostream &os, const ProcessVertexAtTime &v)
std::ostream & operator<< (std::ostream &os, const Key &v)
Detailed Description
Definition at line 18 of file ProcessVertexAtTime.hpp.
Member Typedef Documentation
typedef NodeAtTimeKey tuttle::host::graph::ProcessVertexAtTime::Key
Definition at line 21 of file ProcessVertexAtTime.hpp.
Constructor & Destructor Documentation
tuttle::host::graph::ProcessVertexAtTime::ProcessVertexAtTime ()
Definition at line 15 of file ProcessVertexAtTime.cpp.
tuttle::host::graph::ProcessVertexAtTime::ProcessVertexAtTime (const ProcessVertex & v, const OfxTime t)
Definition at line 18 of file ProcessVertexAtTime.cpp.
References tuttle::host::graph::IVertex::_name.
tuttle::host::graph::ProcessVertexAtTime::ProcessVertexAtTime (const ProcessVertexAtTime & other)
Definition at line 26 of file ProcessVertexAtTime.cpp.
tuttle::host::graph::ProcessVertexAtTime::~ProcessVertexAtTime () [virtual]
Definition at line 33 of file ProcessVertexAtTime.cpp.
Member Function Documentation
std::ostream & tuttle::host::graph::ProcessVertexAtTime::exportDotDebug (std::ostream & os) const [virtual]
Todo:
remove this. Temporary solution
Reimplemented from tuttle::host::graph::IVertex.
Definition at line 37 of file ProcessVertexAtTime.cpp.
References _data, tuttle::host::graph::ProcessVertexAtTimeData::_globalInfos, tuttle::host::graph::ProcessVertexAtTimeData::_localInfos, tuttle::host::graph::ProcessVertexAtTimeInfo::_memory, tuttle::host::graph::ProcessVertexAtTimeData::_nodeData, tuttle::host::graph::ProcessVertexAtTimeData::_time, tuttle::host::graph::ProcessVertexData::_timeDomain, tuttle::host::graph::dotEntry(), tuttle::host::INode::eNodeTypeImageEffect, tuttle::host::attribute::ClipImage::fetchRegionOfDefinition(), tuttle::host::ofx::attribute::OfxhClipImage::getBitDepthString(), tuttle::host::ofx::attribute::OfxhClipImage::getComponentsString(), tuttle::host::ofx::attribute::OfxhClipImage::getFrameRange(), tuttle::host::attribute::ClipImage::getFrameRate(), tuttle::host::graph::IVertex::getName(), tuttle::host::ImageEffectNode::getOutputClip(), tuttle::host::ofx::attribute::OfxhClipImage::getPixelAspectRatio(), tuttle::host::graph::IVertex::getProcessNode(), tuttle::host::graph::IVertex::isFake(), and tuttle::host::graph::subDotEntry().
Key tuttle::host::graph::ProcessVertexAtTime::getKey () const [inline]
Definition at line 36 of file ProcessVertexAtTime.hpp.
References _clipName, _data, and tuttle::host::graph::ProcessVertexAtTimeData::_time.
Referenced by tuttle::host::graph::ProcessGraph::getOutputKeyAtTime(), tuttle::host::graph::operator<<(), and tuttle::host::graph::ProcessGraph::setupAtTime().
const ProcessVertexData& tuttle::host::graph::ProcessVertexAtTime::getProcessData () const [inline]
Definition at line 41 of file ProcessVertexAtTime.hpp.
References _data, and tuttle::host::graph::ProcessVertexAtTimeData::_nodeData.
ProcessVertexAtTimeData& tuttle::host::graph::ProcessVertexAtTime::getProcessDataAtTime () [inline]
Definition at line 42 of file ProcessVertexAtTime.hpp.
References _data.
Referenced by tuttle::host::graph::ProcessGraph::bakeGraphInformationToNodes(), and tuttle::host::graph::ProcessGraph::setupAtTime().
const ProcessVertexAtTimeData& tuttle::host::graph::ProcessVertexAtTime::getProcessDataAtTime () const [inline]
Definition at line 43 of file ProcessVertexAtTime.hpp.
References _data.
ProcessVertexAtTime& tuttle::host::graph::ProcessVertexAtTime::operator= (const ProcessVertexAtTime & v) [inline]
Definition at line 29 of file ProcessVertexAtTime.hpp.
References _data.
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const ProcessVertexAtTime & v) [friend]
Definition at line 79 of file ProcessVertexAtTime.cpp.
std::ostream& operator<< (std::ostream & os, const Key & v) [friend]
Definition at line 32 of file NodeAtTimeKey.cpp.
Field Documentation
std::string tuttle::host::graph::ProcessVertexAtTime::_clipName
Definition at line 50 of file ProcessVertexAtTime.hpp.
Referenced by getKey().
ProcessVertexAtTimeData tuttle::host::graph::ProcessVertexAtTime::_data
Definition at line 51 of file ProcessVertexAtTime.hpp.
Referenced by exportDotDebug(), getKey(), getProcessData(), getProcessDataAtTime(), operator=(), and tuttle::host::graph::ProcessGraph::setupAtTime().
The documentation for this class was generated from the following files:
TuttleOFX/libraries/tuttle/src/tuttle/host/graph/ProcessVertexAtTime.hpp
TuttleOFX/libraries/tuttle/src/tuttle/host/graph/ProcessVertexAtTime.cpp